<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/officedefault/index/deleteoffice/id/<?php echo $this->memberid; ?>/modId/<?php echo $this->mod_id; ?>/subId/<?php echo $this->sub_id; ?>" method="POST">
    <table id="hor-minimalist-b">
                <tr><th><?php echo $this->translate("Member Information"); ?></th><th></th></tr>
            	<tr><td align='right' valign='center'><font color="green">* </font>Remarks</td><td><?php echo $this->delete; ?></td></tr>
		<tr><td colspan=2'><font color="red"><?php echo $this->translate("Are you sure you want to delete Office ?"); ?></font> <br /><br />
		<input type="submit" value="Delete" id="Delete" name="Submit">
            <a href="<?php echo $this->baseUrl();?>/officecommonview/index/commonview/id/<?php echo $this->memberid ?>">
		<input type="button" name="no" value="<?php echo $this->translate('Cancel'); ?>"></a></td></tr>
            
    </table>
</form>
