<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script type="text/javascript">
function gettaluk(district_id,path) {
	if(district_id) {
		targeturl=path+"/officedefault/index/gettaluk?districtid="+district_id;
		$.ajax({ url: targeturl, success: function(data){ $("#talukdiv").html(data) }});
	}
}

function gethobli(taluk_id,path){
	if(taluk_id) {
		targeturl=path+"/officedefault/index/gethobli?taluk_id="+taluk_id;
		$.ajax({ url: targeturl, success: function(data){ $("#hoblidiv").html(data) }});
	}
}

function getpanchayath(hobli_id,path){
	if(hobli_id) {
		targeturl=path+"/officedefault/index/getpanchayath?hobli_id="+hobli_id;
		$.ajax({ url: targeturl, success: function(data){ $("#panchayathdiv").html(data) }});
	}
}
</script>

        <div class="register">
            <div class="profile_tab">
                <form action="<?php  echo $this->baseUrl();?>/officedefault/index/officeedit/id/<?php echo $this->id ?>" method="POST" name="joe" id="signupForm" class="cmxform">



                    <table id="hor-minimalist-b">  

			<tr bgcolor="Gray"> <td class="label"><?php echo $this->translate('New Office'); ?></td>
				<td align="right"><a href="<?php echo $this->baseUrl();?>/officedefault/index/deleteoffice/id/<?php echo $this->id; ?>/sub_id/<?php echo $this->sub_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
			</tr>
                        <tr>
                            <td width="50%"><?php echo $this->translate('Office type'); ?></td><td width="50%"><?php  echo $this->form->officetypename;?></td>    
                        </tr>
                        <tr>
                           <td><?php echo $this->translate('Parent office'); ?></td> <td><div id="statediv"><?php echo $this->form->parentoffice_id; ?></div></td>    
                        </tr>
		        <tr><td><?php echo $this->translate('Office name'); ?></td>
			<td><?php  echo $this->form->name;?></td>
		        </tr>
		        <tr><td><?php echo $this->translate('Office short name'); ?></td>
			<td><?php  echo $this->form->short_name; echo $this->form->createdby; echo $this->form->createddate; ?></td>
		        </tr>
                        <?php if($this->villagelastid){ ?>

                        <tr><td><?php echo $this->translate('District'); ?></td><td><?php  echo $this->form->district;?></td></tr>
                        <tr ><td><?php echo $this->translate('Talue'); ?></td><td id="talukdiv"><?php  echo $this->form->taluque;?></td> </tr>
                        <tr><td><?php echo $this->translate('Hobli'); ?></td><td id="hoblidiv"><?php  echo $this->form->hobli;?></td> </tr>
                        <tr><td><?php echo $this->translate('Gilla panchayath'); ?></td><td id="panchayathdiv"><?php  echo $this->form->panchayath;?></td> </tr>

                        <?php } else { ?><tr id="addressdiv"></tr> <?php } ?>
                        <tr>
                  <!--         <td id="addressdiv" colspan="2"> </td>-->
                        </tr>
        		<tr>
			<td><input name="Submit" id="Submit" type="submit" class="officebutton" value="<?php echo $this->translate('Update'); ?>"></td>
		        <td><a href=<?php echo $this->baseUrl();?>/office/index>
                        <input name="submit" type="submit" class="officebutton" value="<?php echo $this->translate('back'); ?>"></a></td>
	           	</tr>
                        <tr>
			<td></td>
			<td><B style='color:red'><?php echo $this->error; ?></B></td>
		        </tr>
	         </table>
	   </form>
	</div>
    </div>

