 
<head>
<script src="<? echo $this->baseUrl();?>/js/jquery-latest.js"></script>
<!-- <link rel="stylesheet" href="<? echo $this->baseUrl();?>/css/screen.css" type="text/css"/> -->
<link rel="stylesheet" href="<? echo $this->baseUrl();?>/css/jquery.treeview.css" type="text/css"/>
<script type="text/javascript" src="<? echo $this->baseUrl();?>/js/jquery.treeview.js"></script>
<script>
$(document).ready(function() {
    $("#example").treeview();
});
</script>
</head>

<?php
function tree_set($index,$branchId)
{
//     $con = mysql_connect("localhost","root","root");
//     mysql_select_db("idf", $con);
//     $result = mysql_query("SELECT a.id,a.name,a.officetype_id,a.parentoffice_id,a.short_name FROM ourbank_office a,ourbank_officehierarchy b where a.parentoffice_id='".$index."' and a.officetype_id = b.id");
   $treeobj = new Officedefault_Model_officedefault();
   $result = $treeobj->get($index);
    $id= array();
    $name= array();
    $sort= array();
    foreach($result as $row)
    {
        $id[] = $row['id'];
        $name[] = $row['name'];
        $officetypeID[] = $row['officetype_id'];
        $sort[] = $row['short_name'];
    }


    if(count($id) === 0)
    {
        return;
    }

    // User $tree instead of the $menu global as this way there shouldn't be any data duplication
    $tree = $index > 0 ? '<ul>' : ''; // If we are on index 0 then we don't need the enclosing ul
    for($i=0; $i<count($id); $i++)
    {
        $treeobj = new Officedefault_Model_officedefault();
        $result = $treeobj->get($id[$i]);
        /*$result = mysql_query("SELECT a.id,a.name,a.officetype_id,a.parentoffice_id,a.short_name FROM ourbank_office a,ourbank_officehierarchy b where a.parentoffice_id='".$id[$i]."' and a.officetype_id = b.id");*/
        if($officetypeID[$i] != $branchId) {
            $class="folder";
        } else { 
            $class="file";
        }

        $tree .= '<li>';
        $tree .= '<span class="'.$class.'">'.$name[$i].'('.$sort[$i].')</span>';
        $tree .=tree_set($id[$i],$branchId);
        $tree .= '</li>'."\n";
    }
    // If we are on index 0 then we don't need the enclosing ul
    $tree .= $index > 0 ? '</ul>' : ''; 
    return $tree;
}
//assign branchID from office_hierarchy table
$branchId = $this->branchId;
//variable $menu must be defined before the function call
$menu = '<ul id="example" class="filetree">'."\n";
$menu .= '<li><span class="folder">'.$this->rootname.'</span>';
$menu .= tree_set(1,$branchId);
$menu .='</li>';
$menu .= '</ul>';
if($this->rootname) {
    echo $menu;
} else {
    echo "No office exists in system";
}
?>
