<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id = "searchDiv">
        <TABLE id="hor-minimalist-b">
	<Th colspan="5">Delete category</th>
           <?php foreach($this->categorydetails as $category) {  ?>
            <TR>
                <TD>Category Name</TD>
                <TD></TD>
                <TD></TD>
                <TD><?php echo $category['name'];?></TD>
                <TD></TD>
            </TR>
            <TR>
                <TD>Category Description</TD>
                <TD></TD>
                <TD></TD>
                <TD><?php echo $category['description'];?></TD>
                <TD></TD>
            </TR>
        </TABLE>
        <?php } ?>

        <form action="<?php echo $this->baseUrl();?>/category/index/categorydelete/id/<?php echo $this->id; ?>" method="POST" name="joe" id="signupForm" class="cmxform">
        <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                <TR>
                        <TD  width="35%" align="right" ><font color="green" size="+1">*</font><label>Remarks</label></TD>
                        <TD  width="65%"  align="left" ><?php echo $this->deleteform->remarks;?></TD>
                </tr>
                <tr>
                        <TD><input type="submit" name="Delete" id="Submit" value="Delete"></td>			
                        <td align="right"><a href="<?php echo $this->baseUrl();?>/category/index"><input name="submit" type="submit"  value="Cancel" ></a></td>
                </TR>
        </table>
        </form>

</div>
