<?php if(!$this->result) { ?>
<div id="searchDiv">
<fieldset>
	<legend><?php echo $this->translate("Search member"); ?></legend>
		<form action="<?php echo $this->baseUrl();?>/internalloan/index" method="POST">
			<table class="fieldsets">
                            <TR>
                                <TD><label class="mand"><?php echo $this->translate("Group code:"); ?></label></TD>
                                <TD><? echo $this->form->membercode;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <input type="Submit" name="Submit" value="Search"><br><br>
                                <table><TR><TD><?php echo "<font color='red' size='2'>".$this->error."</font>";?></TD></TR></table>
                            </div>
                        </div>
	 </form>

</fieldset>
</div>

<?php } $dateconvert= new App_Model_dateConvertor(); ?>
<?php if($this->result) { $count = 0;
foreach ($this->result as $result) {
if ($count == 0) {
?>
<fieldset>
	<legend><?php echo $this->translate("Individual loan sanction"); ?></legend>
        <div align="center"><h3><b><u>Member loan application - sanction</u></b></h3></div>
        <br>
        <div align="left">
            <p> Member name .....................................................</p>
            <p> No: .............................................................</p>
        </div>
        <hr>
        <br>
        <div align="center"><h4><b>(a) Loan application</b></h4></div>
        <div align="left">
            <p align="right">Date: <?php echo date('d-m-Y');?></p>
            <p> To,</p>
            <p> Group representatives,</p>
            <p><?php echo "<font color='green'>".$result->groupname."</font>";?>&nbsp; Self help group</p>
            <p>I here by declare that asdfgf ;lkjhgh asdff dsfksdh hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
               I here by declare that asdfgf ;lkjhgh asdff dsfksdh hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
               I here by declare that asdfgf ;lkjhgh asdff dsfksdh hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
            </p>
        </div><br>
        <div align="right">
            <p>Member signature</p>
        </div>
        <hr>
        <div align="center"><h4><b>(b) Loan sanctioned</b></h4></div>
        <div align="left">
        <br>
            <p>I here by declare that asdfgf ;...................  hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
               I here by declare that asdfgf ;lkjhgh asdff dsfksdh hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
               I here by declare that asdfgf ;lkjhgh asdff dsfksdh hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
            </p>

 <?php   $repmembers = $this->repmemberslist; ?>
				<p>
                <?php  $i=1;foreach($repmembers as $representative) { ?>
				<?php 	 echo $i++.") "; ?>
				<?php echo "<font color='green'>".$representative['membername']."<br>","</font>"; } ?>
                </p>
        </div>
        <hr>
                <div align="center"><h4><b>(c) Loan received receipt</b></h4></div>
    <div align="left">
        <br>
            <p>I here by declare that asdfgf ;(...........................) hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
               I here by declare that asdfgf ;lkjhgh asdff dsfksdh hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
               I here by declare that asdfgf ;lkjhgh asdff dsfksdh hdfjshdf hfjshf dhkfshdf dhdhf dhfsjdhf  jhjfsdhf jhfsdhf
            </p><br><br>
<P>Borrower signature&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   Insurer signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Witness signature</P>
    </div>
</fieldset>
<?php } $count = $count + 1; } } ?>



