<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<?php if($this->search == 0) { ?>
<div>
<form action="<?php echo $this->baseUrl();?>/generalledger/index" method="POST">  

<fieldset>
    <legend>Search</legend>
        <TABLE width="100%">
            <tr><br>
                <td align = "center" class="label">Begin Date :</td>
                <td align = "center"><?php  echo $this->form->datefrom;?></td>
                <td class="label">Close Date :</td>
                <td align = "right"><?php  echo $this->form->dateto;?></td>
            </tr>
			<tr><TD align = "center" class="label"><br>Ledger:</TD>
                <td align = "center"><br><?php  echo $this->form->ledger;?></td>


</tr>
            <tr>
                <TD align="center"><br><input type="submit" name="Search" value="Search"></TD>
            </tr>
        </table>
</fieldset>
</form>
</div>
<?php } ?>

<?php if (count($this->ledegerList)) { ?>
	<h3 align="right">From <?php echo "<font color='#045'>".$this->datefrom."</font>"; ?> </h3>
	<h3 align="right"> To <?php echo "<font color='#045'>".$this->dateto."</font>"; ?></h3> 
	<h3 style="text-align:right">* Amount in <font color="red">Rs</font></h3>
	<div style="float:left;width:800px">
    <legend>Liabilities</legend>

    <TABLE id="hor-minimalist-b" width="80%">
     <tr>
        <TH allign = "right">Particular</TH>
        <TH allign = "right">Dr</TH>
        <TH allign = "right">Cr</TH>
        <TH allign = "right">Balance</TH>
     </tr>
     <?php foreach($this->ledegerList as $ledegerList) { 
     $liabilityCash = 0.00; ?>
             <tr>
            <TD allign = "right">Opening Balance</TD>
            <TD allign = "right"></TD>
            <TD allign = "right"></TD>
          <?php  if(count($this->openingCash)) {
            foreach($this->openingCash as $openingCash) {
        if ($openingCash["glsubcode_id"] == $ledegerList["glsubcode_id"]) {
           $liabilityCash = $openingCash["openingCash"];
             }
           } 
           }  ?>

            <TD align = "rgiht"><?php echo $liabilityCash;?></TD>
        </tr>

     <TR>
        <TD allign = "right"><?php echo $ledegerList["glsubcode"];?> - <?php echo $ledegerList["subheader"];?></TD>
        <?php if ($ledegerList["credit"]) { ?>
		<TD></TD>
        <TD allign = "right"><?php echo $ledegerList["credit"];?></TD>
        <TD ><?php echo sprintf("%4.2f",  $liabilityCash + $ledegerList["credit"]);?></TD>

        <?php } ?>

     </tr>
     <TR>
        <TD allign = "right"></TD>
        <?php if ($ledegerList["debit"]) { ?>
        <TD allign = "right"><?php echo $ledegerList["debit"];?></TD>
        <TD allign = "right"></TD>
        <TD ><?php echo sprintf("%4.2f", $ledegerList["credit"] + $liabilityCash - $ledegerList["debit"]); ?></TD>
        <?php } ?>
     </tr>
     <tr>
            <TH allign = "right">Closing Balance</TH>
            <TH allign = "right"></TH>
            <TH allign = "right"></TH>
            <TH align = "right"><?php echo sprintf("%4.2f", $ledegerList["credit"] + $liabilityCash - $ledegerList["debit"]);?></TH>
     </tr>
     <?php }  ?>
    </TABLE>
</div>
<?php } ?>

<div style="float:left;width:800px">
<?php if (count($this->ledegerListAssets)) { ?>
	
    <legend>Assets</legend>
    <TABLE id="hor-minimalist-b" width="80%">
     <tr>
        <TH allign = "right">Particular</TH>
        <TH allign = "right">Dr</TH>
        <TH allign = "right">Cr</TH>
        <TH allign = "right">Balance</TH>
     </tr>

     <?php foreach($this->ledegerListAssets as $ledegerListAssets) {
         $assetsCash = 0.00; ?>
       <tr>
            <TD allign = "right">Opening Balance</TD>
            <TD allign = "right"></TD>
          <?php   if (count($this->openingCashAssets)) { 
            foreach($this->openingCashAssets as $openingCashAssets) {
        if ($openingCashAssets["glsubcode_id"] == $ledegerListAssets["glsubcode_id"]) { 

           $assetsCash = $openingCashAssets["openingCash"];?>


     <?php } } } ?>
            <TD allign = "right"></TD>

                 <TD><?php echo $assetsCash ;?></TD>

             </tr>
     <TR>
        <TD allign = "right"><?php echo $ledegerListAssets["glsubcode"];?> - <?php echo $ledegerListAssets["subheader"];?></TD>
        <?php if ($ledegerListAssets["credit"]) { ?>
        <TD allign = "right"></TD>
        <TD allign = "right"><?php echo $ledegerListAssets["credit"];?></TD>
        <TD ><?php echo sprintf("%4.2f",  $assetsCash + $ledegerListAssets["credit"]);?></TD>
        <?php } ?>

     </tr>
     <TR>
        <TD allign = "right"></TD>
        <?php if ($ledegerListAssets["debit"]) { ?>
        <TD allign = "right"><?php echo $ledegerListAssets["debit"];?></TD>
        <TD allign = "right"></TD>
        <TD ><?php echo sprintf("%4.2f", $ledegerListAssets["debit"] + $assetsCash - $ledegerListAssets["credit"]); ?></TD>
        <?php } ?>
     </tr>
     <tr>
           <TH allign = "right">Closing Balance</TH>
           <TH allign = "right"></TH>
           <TH allign = "right"></TH>
   <TH align = "right"><?php echo sprintf("%4.2f", $ledegerListAssets["debit"] + $assetsCash - $ledegerListAssets["credit"]);?></TH>
     </tr>
 </TABLE>

 <form action="<?php echo $this->baseUrl();?>/generalledger/index/pdfdisplay" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/generalledger/index/reportdisplay/file/GL.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <br><input type="submit" value="PDF" id="submit">
     		<input type="hidden" name="field1" value="<?php echo $this->ledegerList; ?>">
			<input type="hidden" name="field2" value="<?php echo $this->openingCash; ?>">
			<input type="hidden" name="field3" value="<?php echo $this->ledegerListAssets; ?>">
			<input type="hidden" name="field4" value="<?php echo $this->openingCashAssets; ?>">
			<input type="hidden" name="datefrom" value="<?php echo $this->datefrom; ?>"/>
			<input type="hidden" name="dateto" value="<?php echo $this->dateto; ?>"/>


</form>
    <?php } }?>
</div>