<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}

$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});
</script>
<?php
if($this->search == 0) { ?>   
<fieldset>
  <legend>Search</legend>
	<form action="<?php echo $this->baseUrl();?>/generalledger/index" method="POST">  
      <TABLE width="100%">
  						<tr>
							<td><?php echo $this->translate('Hierarchy'); ?></td>
                            <td id="show"><?php echo $this->form->hierarchy;?></td>
                			<td align = "center" class="label">Begin Date :</td>
                			<td align = "left"><?php  echo $this->form->datefrom;?></td>
						</tr>
						<tr>
                            <td><br><?php echo $this->translate('Branch'); ?></td>
                            <td><br><div id="statediv"><?php echo $this->form->branch;?></div></td>
			                <td align = "center"><br>Close Date :</td>
            			    <td ><br><?php  echo $this->form->dateto;?></td>
						</tr>
<!--						<tr id="hide">
							<TD><?php //echo $this->translate('Group'); ?></TD>
                            <TD><div id="groupdiv"><?php //echo $this->form->group;?></TD>
						</tr>-->
            <tr><TD align="center"><br><input type="submit" name="Search" value="Search"></TD></tr>
        </table>
	</form>
</fieldset>

<?php } ?>
<?php if (count($this->ledegerList)) { ?>
	<h3 align="left">From <?php echo "<font color='#039'>".$this->from."</font>"; ?> </h3> 
	<h3 align="left"> To <?php echo "<font color='#039'>".$this->to."</font>"; ?></h3> 
	<?php foreach($this->ledegerList as $ledegerList) { $type = $ledegerList["subheader"]; }?>
	<div style="float:left;width:200px">
    <TABLE id="hor-minimalist-s" >
	<tr><TD align="center"><b>Liabilities</b></TD></tr>
     <tr>
        <TH allign = "right">Particular</TH>
        <TH allign = "right">Dr</TH>
        <TH allign = "right">Cr</TH>
        <TH allign = "right">Balance</TH>
     </tr>
     <?php foreach($this->ledegerList as $ledegerList) {
     $liabilityCash = 0.00; ?>
             <tr>
            <TD allign = "right">Opening Balance</TD>
            <TD allign = "right"></TD>
            <TD allign = "right"></TD>
          <?php  if(count($this->openingCash)) {
            foreach($this->openingCash as $openingCash) {
        if ($openingCash["glsubcode_id"] == $ledegerList["glsubcode_id"]) {
           $liabilityCash = $openingCash["openingCash"];
             	}
           	  }
           }  ?>

            <TD align = "rgiht"><?php echo $liabilityCash;?></TD>
        </tr>

     <TR>
        <TD allign = "right"><?php echo $ledegerList["glsubcode"];?> - <?php echo $ledegerList["subheader"];?></TD>
        <?php if ($ledegerList["credit"]) { ?>
        <TD allign = "right"></TD>
        <TD allign = "right"><?php echo $ledegerList["credit"];?></TD>
        <TD align = "right"><?php echo sprintf("%4.2f",  $liabilityCash + $ledegerList["credit"]);?></TD>
        <?php } ?>

     </tr>
     <TR>
        <TD allign = "right"></TD>
        <?php if ($ledegerList["debit"]) { ?>
        <TD allign = "right"><?php echo $ledegerList["debit"];?></TD>
        <TD allign = "right"></TD>
        <TD align = "right"><?php echo sprintf("%4.2f", $ledegerList["credit"] + $liabilityCash - $ledegerList["debit"]); ?></TD>
        <?php } ?>
     </tr>
     <tr>
            <TH allign = "right">Closing Balance</TH>
            <TH allign = "right"></TH>
            <TH allign = "right"></TH>
            <TH align = "right"><?php echo sprintf("%4.2f", $ledegerList["credit"] + $liabilityCash - $ledegerList["debit"]);?></TH>
     </tr>
     <?php }  ?>
    </TABLE>
</div>
<?php } ?>
<div style="float:right;width:340px">

<?php if (count($this->ledegerListAssets)) { ?>

	<?php foreach($this->ledegerListAssets as $ledegerListAssets) { $type = $ledegerListAssets["subheader"]; }?>
    <TABLE id="hor-minimalist-s">
	<tr><TD align="center"><b>Assets</b></TD></tr>
     <tr>
        <TH allign = "right">Particular</TH>
        <TH allign = "right">Dr</TH>
        <TH allign = "right">Cr</TH>
        <TH allign = "right">Balance</TH>
     </tr>

     <?php foreach($this->ledegerListAssets as $ledegerListAssets) {
         $assetsCash = 0.00; ?>
       <tr>
            <TD allign = "right">Opening Balance</TD>
            <TD allign = "right"></TD>
            <TD allign = "right"></TD>
          <?php   if (count($this->openingCashAssets)) { 
            foreach($this->openingCashAssets as $openingCashAssets) {
        if ($openingCashAssets["glsubcode"] == $ledegerListAssets["glsubcode"]) { 

           $assetsCash = $openingCashAssets["openingCash"];?>


     <?php } } } ?>
                 <TD align = "right"><?php echo $assetsCash ;?></TD>

             </tr>
     <TR>
        <TD allign = "right"><?php echo $ledegerListAssets["glsubcode"];?> - <?php echo $ledegerListAssets["subheader"];?></TD>
        <?php if ($ledegerListAssets["credit"]) { ?>
        <TD allign = "right"></TD>
        <TD allign = "right"><?php echo $ledegerListAssets["credit"];?></TD>
        <TD align = "right"><?php echo sprintf("%4.2f",  $assetsCash + $ledegerListAssets["credit"]);?></TD>
        <?php } ?>

     </tr>
     <TR>
        <TD allign = "right"></TD>
        <?php if ($ledegerListAssets["debit"]) { ?>
        <TD allign = "right"><?php echo $ledegerListAssets["debit"];?></TD>
        <TD allign = "right"></TD>
        <TD align = "right"><?php echo sprintf("%4.2f", $ledegerListAssets["credit"] + $assetsCash - $ledegerListAssets["debit"]); ?></TD>
        <?php } ?>
     </tr>
     <tr>
            <TH allign = "right">Closing Balance</TH>
            <TH allign = "right"></TH>
            <TH allign = "right"></TH>
            <TH align = "right"><?php echo sprintf("%4.2f", $ledegerListAssets["credit"] + $assetsCash - $ledegerListAssets["debit"]);?></TH>
     </tr>

       <?php } ?>
    </TABLE>



 <?php } ?>

</div>