
<?php if (count($this->details)) { ?>
 <div style="float:left;width:350px"> 
    <?php foreach($this->details as $details) { ?>
        <table id="hor-minimalist-s">
            <TR>
                <TH><?php echo $this->translate("Member details"); ?></TH>
                <TH></TH>
            </TR>
            <TR>
                <td><?php echo $this->translate("Name"); ?> </td>
                <TD><?php echo $details->name ?></TD>
            </TR>

            <TR>
                <td><?php echo $this->translate("Branch"); ?></td>
                <TD><?php echo $details->officename ?></TD>
            </TR>
            <TR>
                <td><?php echo $this->translate("Code"); ?></td>
                <TD><?php echo $details->code ?></TD>

            </TR>
            <TR>
                <td><?php echo $this->translate("Account code"); ?></td>
                <td><?php echo $details->number ?></TD>
            </TR>
            <TR>
                <TH><?php echo $this->translate("Loan Details"); ?></TH>
                <TH></TH>
            </TR>
            <TR>
                <td><?php echo $this->translate("Loan name"); ?></b></td>
                <td><?php echo $details->loanname ?></TD>
            </TR>
            <TR>
                <td><?php echo $this->translate("Loan amount R$"); ?></b></td>
                <td><?php echo $details->amount ?></TD>
            </TR>

            <TR>
                <td><?php echo $this->translate("Interest rate %"); ?></td>
                <TD><?php echo $details->interest ?></TD>
            </TR>

            <TR>
            <td><?php echo $this->translate("Installments"); ?></td>
                <TD><?php echo $details->installments ?></TD>
            </TR>
            <TR>
                <td><?php echo $this->translate("Sanctioned date"); ?></b></td>
                <td><?php echo $details->sanctioned ?></TD>
            </TR>
            <TR>
                <td><?php echo $this->translate("Fee"); ?></b></td>
                <td></TD>
            </TR> 
        </table> 
    <?php } ?>
    <br/>
</div>
<div style="float:right;width:350px"> 
        <table id="hor-minimalist-s" border="1">
            <TR>
                <TH colspan="9"><?php echo $this->translate("Installment status"); ?></TH>
                <TH>No.</TD>
                <TH colspan="9"><?php echo $this->translate("Amount"); ?></TH>
            </TR>
            <TR>
                <TD colspan="9"><?php echo $this->translate("Paid"); ?></TD>
                <?php foreach ($this->paid as $paid) { ?>
                <TD><?php echo $paid->paidCount ; ?></TD>
                <TD colspan="9" align="right"><?php echo $paid->paidAmt ; ?></TD>
                <?php } ?>
            </TR>
            <TR>
                <TD colspan="9"><?php echo $this->translate("Due"); ?></TD>
                <?php foreach ($this->unpaid as $unpaid) { ?>
                <TD><?php echo $unpaid->unpaidCount ; ?></TD>
                <TD colspan="9" align="right"><?php echo $unpaid->unpaidAmt ; ?></TD>
                <?php } ?>
            </TR>
        </table>
        <br>
        <table id="hor-minimalist-s" border="1">
            <TR>
                <TH><?php echo $this->translate("Sl no."); ?></TH>
                <TH colspan="9"><?php echo $this->translate("Deatails of interest collected by the member"); ?></TH>
                <TH><?php echo $this->translate("Amount in Rs."); ?></TD>
            </TR>
            <TR>
                <TD>1</TD>
                <TD colspan="9"><?php echo $this->translate("Paid amount"); ?></TD>
                <?php foreach ($this->paid as $paid) { ?>
                <td align="right"><?php echo $paid->paidAmt ; ?></td>
                <?php } ?>

            </TR>
             <TR>
                <TD>2</TD>
                <TD colspan="9"><?php echo $this->translate("Capital amount"); ?></TD>
                <?php foreach($this->details as $details) { ?>
                <td align="right"><?php echo $details->amount; ?></td>
                <?php } ?>
            </TR>
            <TR>
                <TD>3</TD>
                <TD colspan="9"><?php echo $this->translate("Total interet paid"); ?></TD>
                <?php foreach ($this->paid as $paid) { ?>
                <td align="right"><?php echo $paid->interest ; ?></td>
                <?php } ?>
            </TR>
        </table>
</div>
<?php $convertdate = new App_Model_dateConvertor(); ?>

<table id="hor-minimalist-b">
    <tr>
        <th><?php echo $this->translate("V No."); ?></td>
        <th><?php echo $this->translate("Transaction date"); ?></td>
        <th><?php echo $this->translate("Creidt"); ?></td>
        <th><?php echo $this->translate("Debit"); ?></td>
        <th><?php echo $this->translate("Payment mode"); ?></td>
        <th><?php echo $this->translate("Transacted by"); ?></td>  
    </tr>
    <?php foreach($this->tran as $transaction) : ?>
    <tr>
       <td><?php echo $transaction->id; ?></td>
       <td><?php echo $transaction->date; ?></td>
       <?php if ($transaction->cr) {?>
       <td><?php echo $transaction->cr; ?></td>
       <?php } else { ?>
       <td>----</td>
       <?php } ?>
       <?php if ($transaction->dt) { ?> 
       <td><?php echo $transaction->dt; ?></td>
       <?php } else { ?>
       <td>----</td>
       <?php } ?>

       <td><?php echo $transaction->mode; ?></td>
       <td><?php echo $transaction->name; ?></td>
    </tr>
    <?php endforeach; ?>
</table>
    <?php } else ?>
    <?php { if (!$this->details) { ?>

                <fieldset>
                    <legend><?php echo $this->translate("Search account"); ?></legend>
                    <form action="<?php echo $this->baseUrl();?>/memberldeatils/index/loandetails" method="POST">
                        <table class="fieldsets">
                            <tr>
                                <td><br><label for="fld1" class="mand"><?php echo $this->translate("Account number :"); ?></label></td>
                                <td><?php echo $this->form->accNum;?></td>
                            </tr>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Search;?><br><br>
                                <table><TR><TD><?php echo "<font color='red' size='2'>".$this->error."</font>";?></TD></TR></table>
                            </div>
                        </div>
                    </form>
                </fieldset>

    <?php } } ?>