<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/toggel.js"></script> 
<script type="text/javascript">
 $(document).ready(function(){

//$(".tmode option[value='5']").remove();


        $('.tmode').change(function() {
            var v = $(this).val();
            var id = $(this).attr('id');
        if(id == 'transactionMode'){
            if(v!=1){
                if(v==5){ 
			if($(this).val())
			{  
			memberid=$('.memberclass').val(); //alert(memberid);
			membertypeid=$('.membertypeclass').val(); //alert(membertypeid);
			path=$('.pathclass').val(); //alert(path);
			targeturl=path+"/loandisbursmentg/index/getaccount?memberid="+memberid+"&membertype="+membertypeid; //alert(targeturl);
			$.ajax({ url: targeturl, success: function(data){ $('#accountdiv').html(data) }});
			}
                        $('#etransfer').show();
			$('#selectetrans').show();
                        $('#textbox').hide();
                        $('#cheque').hide();
                }else{
                        $('#cheque').show();
                        $('#textbox').show();
                        $('#etransfer').hide();
			$('#selectetrans').hide();
                }
            }
            else{
                        $('#etransfer').hide();
                        $('#textbox').hide();
                        $('#cheque').hide();
			$('#selectetrans').hide();


            }
        }   
else
{

            if(v!=1){
                if(v==5){
			if($(this).val())
			{  
			memberid=$('.memberclass').val(); //alert(memberid);
			membertypeid=$('.membertypeclass').val(); //alert(membertypeid);
			path=$('.pathclass').val(); //alert(path);
			targeturl=path+"/loandisbursmentg/index/getaccount?memberid="+memberid+"&membertype="+membertypeid; //alert(targeturl);
			$.ajax({ url: targeturl, success: function(data){ $('#accountdiv').html(data) }});
			}
                        $('#etransfer1').show();
			$('#selectetrans').show();
                        $('#textbox1').hide();
                        $('#cheque1').hide();
                }else{
                        $('#cheque1').show();
                        $('#textbox1').show();
                        $('#etransfer1').hide();
			$('#selectetrans').hide();

                }
            }
            else{
                        $('#etransfer1').hide();
                        $('#textbox1').hide();
                        $('#cheque1').hide();
			$('#selectetrans').hide();


            }
    }
         });
     });
</script>
<div style="float:left;width:350px"> 
    <?php foreach($this->details as $details) { ?>
        <table id="hor-minimalist-s">
            <TR>
                <TH>Menber details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td>Name </td>
                <TD><?php echo $details->name ?></TD>
            </TR>
            <TR>
                <td>UID </td>
                <TD><?php echo $details->uid ?></TD>
            </TR>

            <TR>
                <td>Branch</td>
                <TD><?php echo $details->officename ?></TD>
            </TR>
            <TR>
                <td>Code</td>
                <TD><?php echo $details->code ?></TD>

            </TR>
            <TR>
                <td> Account code</td>
                <td><?php echo $details->number ?></TD>
            </TR>
            <TR>
                <TH>Loan Details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td>Loan name</b></td>
                <td><?php echo $details->loanname ?></TD>
            </TR>
            <TR>
                <td>Sanction Loan amount R$</b></td>
                <td><?php echo $details->amount ?></TD>
            </TR>

            <TR>
                <td>Remaining loan amount R$</b></td>
                <td><?php echo $this->balance ?></TD>
            </TR>

            <TR>
                <td>Interest rate %</td>
                <TD><?php echo $details->interest ?></TD>
            </TR>

            <TR>
            <td>Installments</td>
                <TD><?php echo $details->installments ?></TD>
            </TR>
            <TR>
                <td>Sanctioned date</b></td>
                <td><?php echo $details->sanctioned ?></TD>
            </TR>
            <?php if (count($this->fee)) {?>
            <tr>
                <TH>Fee</TH>
                <TH>Amount</TH>
            </tr>  
            <?php $feetotal=0; foreach($this->fee as $fee) { $feetotal+=$fee->feeamount; ?>
             <tr>
                <td><?php echo $fee->name; ?></td>
                <td><?php echo $fee->feeamount; ?></td>
            </tr> 
            <?php } ?>
            <tr>
                <td>Total</td>
                <td><?php echo sprintf("%4.2f",$feetotal); ?></td>
            </td> 
            <?php }?>
        </table> 
    <?php } ?>
    <br/>
</div>

<div style="float:right;width:350px"> 
<?php if($this->balance != 0) { ?>
    <fieldset>
        <legend> Loan disbursement </legend>
        <form name="form1" action="<?php echo $this->baseUrl();?>/loandisbursmentg/index/disbursment/accNum/<?php echo base64_encode($this->accNum);?>" method="POST">
            <table class="fieldsets">

                <TR>
                    <TD><label for="fld1" class="mand">Date</label></TD>
                    <TD><?php echo $this->loan->date; ?></TD>
                </TR>

                <TR>
                    <TD><label for="fld1" class="mand">Amount R$</label></TD>
                    <TD><?php echo $this->loan->Amount;?></TD>
                </TR>
				<TR>
                    <TD><label for="fld1" class="mand">Transaction mode</label></TD>
                    <TD><?php echo $this->loan->transactionMode; echo $this->loan->memberid; echo $this->loan->membertypeid; echo $this->loan->pathhidden; ?></TD>
                </TR>
                <tr>
                    <td id="cheque" style="display:none"><label for="fld1" class="mand">Voucher/cheque/draft</label></td>
                    <td id="etransfer" style="display:none"><label for="fld1" class="mand">Account number</label></td>
                    <td id="textbox" style="display:none"><?php echo $this->loan->othertext;?></td> 
                    <td id="selectetrans" style="display:none"><div id="accountdiv"><?php echo $this->loan->etransfer; ?></div></td>
                </tr>

                <TR>
                    <TD><label for="fld1" class="mand">Description</label></TD>
                    <TD><?php echo $this->loan->description;?></TD>
                </TR>

<!--                <TR>
                    <TD><label for="fld3">Send sms</label></TD>
                    <TD><?php echo $this->loan->sms;?></TD>
                </TR>-->
            </table>
            <br/>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->loan->Submit;?>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/loandisbursmentg/index"><?php echo $this->loan->Back;?></a>
                </div>
            </div>
        </form>
    </fieldset>
<?php } ?>

<?php if($this->disbursedetails){ ?>
        <table id="hor-minimalist-s" border="1">
        <tr>
            <th>S.No</th>
            <th>Disbursed amount</th>
            <th>Date</th>
        </tr>
        <?php $i=0; foreach($this->disbursedetails as $disbursed) { $i++; ?>
        <tr>
            <td><?php echo $i; ?></td>
            <td align="right"><?php echo $disbursed['amount_disbursed']; ?></td>
            <td><?php echo $this->dateconvector->phpnormalformat($disbursed['loandisbursement_date']); ?></td>
        </tr>
        <?php } ?>
        </table>
<?php } ?>
</div>

