<div style="float:left;width:350px"> 
    <?php foreach($this->details as $details) { ?>
        <table id="hor-minimalist-s">
            <TR>
                <TH>Menber details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td>Name </td>
                <TD><?php echo $details->name ?></TD>
            </TR>
            <TR>
                <td>UID </td>
                <TD><?php echo $details->uid ?></TD>
            </TR>

            <TR>
                <td>Branch</td>
                <TD><?php echo $details->officename ?></TD>
            </TR>
            <TR>
                <td>Code</td>
                <TD><?php echo $details->code ?></TD>

            </TR>
            <TR>
                <td> Account code</td>
                <td><?php echo $details->number ?></TD>
            </TR>
            <TR>
                <TH>Loan Details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td>Loan name</b></td>
                <td><?php echo $details->loanname ?></TD>
            </TR>
            <TR>
                <td>Sanction Loan amount R$</b></td>
                <td><?php echo $details->amount ?></TD>
            </TR>

            <TR>
                <td>Remaining loan amount R$</b></td>
                <td><?php echo $this->balance ?></TD>
            </TR>

            <TR>
                <td>Interest rate %</td>
                <TD><?php echo $details->interest ?></TD>
            </TR>

            <TR>
            <td>Installments</td>
                <TD><?php echo $details->installments ?></TD>
            </TR>
            <TR>
                <td>Sanctioned date</b></td>
                <td><?php echo $details->sanctioned ?></TD>
            </TR>
            <?php if (count($this->fee)) {?>
            <tr>
                <TH>Fee</TH>
                <TH></TH>
            </tr>  
            <?php foreach($this->fee as $fee) { ?>
             <tr>
                <td><?php echo $fee->name ?></td>
                <td><?php echo $fee->value ?></td>
            </tr> 
            <?php } ?> 
            <?php }?>
        </table> 
    <?php } ?>
    <br/>
</div>

<div style="float:right;width:350px"> 
<?php if($this->balance != 0) { ?>
    <fieldset>
        <legend> Loan disbursement </legend>
        <form name="form1" action="<?php echo $this->baseUrl();?>/loandisbursmentg/index/disbursment/accNum/<?php echo base64_encode($this->accNum);?>" method="POST">
            <table class="fieldsets">

                <TR>
                    <TD><label for="fld1" class="mand">Date</label></TD>
                    <TD><?php echo $this->loan->date; ?></TD>
                </TR>

                <TR>
                    <TD><label for="fld1" class="mand">Amount R$</label></TD>
                    <TD><?php echo $this->loan->Amount;?></TD>
                </TR>

                <TR>
                    <TD><label for="fld1" class="mand">Description</label></TD>
                    <TD><?php echo $this->loan->description;?></TD>
                </TR>

<!--                <TR>
                    <TD><label for="fld3">Send sms</label></TD>
                    <TD><?php echo $this->loan->sms;?></TD>
                </TR>-->
            </table>
            <br/>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->loan->Submit;?>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/loandisbursmentg/index"><?php echo $this->loan->Back;?></a>
                </div>
            </div>
        </form>
    </fieldset>
<?php } ?>

<?php if($this->disbursedetails){ ?>
        <table id="hor-minimalist-s" border="1">
        <tr>
            <th>S.No</th>
            <th>Disbursed amount</th>
            <th>Date</th>
        </tr>
        <?php $i=0; foreach($this->disbursedetails as $disbursed) { $i++; ?>
        <tr>
            <td><?php echo $i; ?></td>
            <td align="right"><?php echo $disbursed['amount_disbursed']; ?></td>
            <td><?php echo $this->dateconvector->phpnormalformat($disbursed['loandisbursement_date']); ?></td>
        </tr>
        <?php } ?>
        </table>
<?php } ?>
</div>

