<div> 
   <fieldset>
        <legend>Search account</legend>
        <form action="<?php echo $this->baseUrl();?>/loandisbursmentg/index" method="POST">
            <table class="fieldsets">
                <tr>
                    <td><label for="fld1" class="mand">Account number/Name</label></td>
                    <td><?php echo $this->form->accNum;?></td>
                </tr>
            </table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Search;?>
                </div>
            </div>
        </form>
    </fieldset>
</div>
<div>
<?php if($this->accounts) { ?>
	<table id="hor-minimalist-b">
		<tr>
			<a href="<?php echo $this->baseUrl();?>/loandisbursmentg/index/disbursment/accountNumber/<?php echo $account['account_number'];?>"><Th>Account number</Th></a>
			<Th>Name/Group name</th>
			<Th>Activity name</th>
		</tr>
        <?php foreach($this->accounts as $loandisbursement){ ?>
                <tr>
                      <td><?php echo $loandisbursement->number; ?></td>
                      <td><?php echo $loandisbursement->name; ?></td>
                      <td><?php echo $loandisbursement->loanname; ?></td>
                </tr>
        <?php } ?>
	</table>
<?php }?></div>