<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/meetingbookreport.js"></script>

<?php if($this->attendance) { ?>
        <table id="hor-minimalist-b">
            <TR >
                <th colspan='4'><label for="fld1" class="mand"><?php echo $this->translate("Group Information"); ?></th>
            </TR>
                <?php if($this->meeting) { $count = count($this->meeting); ?>
                <? foreach($this->meeting as $meeting) { } ?>
                <tr><td width="150px">Group name:</td><td><? echo $meeting['groupname'];?></td>
                <td  width="100px">Week Day:</td><td><? echo $meeting['weekday'];?></td>
                </td>
                </tr>
                
                <tr><td>Group head:</td><td><? echo $meeting['grouphead_name'];?></td>
                <td>Time:</td><td><? echo $meeting['time'];?></td></tr>
                
                <tr><td>Number of members:</td><td><? echo $count;?>
                <td>Place:</td><td><? echo $meeting['place'];?></td></tr>
                
                <tr><td>Loan Officer:</td><td><? echo $this->loanofficer;?></td> 
                <td></td>
                <td></td>
                </tr>
                <?php } ?>

            <TR >
                <th colspan='4'><label for="fld1" class="mand"><?php echo $this->translate("Attendance Information"); ?></th>
            </TR>

                <? foreach($this->attendance as $attendance) { } ?>
                <tr><td>Meeting name:</td><td><? echo $attendance['meetingname'];?></td>
                <td>Held on:</td><td><? echo $this->dateconvertor->phpnormalformat($attendance['meeting_date']);?></td>
                </td>
                </tr>
                
                <tr><td>Week: </td><td><? echo $attendance['week_no'];?></td>
                <td>Time:</td><td><? echo $attendance['time'];?></td>
                </tr>

            <TR>
                <td colspan="4">
<?php if($this->members) { $count = count($this->members); ?>
	<table id="hor-minimalist-b"> 
            <TR style="border-bottom: 4px solid #CBCBCB;">
                <th colspan='6' style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Member details"); ?></th>
                <th colspan='2' style="border-right: solid 1px #CBCBCB; text-align:center; !important;"><?php echo $this->translate("Savings"); ?></th>
                <th colspan='2' style="border-right: solid 1px #CBCBCB; text-align:center; !important;"><?php echo $this->translate("Loans"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; text-align:center; !important;"></th>
            </TR>

            <TR align="center" >
                <th style="width:5px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Sl"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Members"); ?></th>
                <th style="width:85px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("UID"); ?></th>
                <th style="width:5px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Attn."); ?></th>
                <th style="width:5px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Late"); ?></th>
                <th style="width:5px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Absent"); ?></th>
                <th style="width:55px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Balance"); ?></th>
                <th style="width:30px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("pay"); ?></th>
                <th style="width:55px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Outstanding"); ?></th>
                <th style="width:30px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Due"); ?></th>
                <th style="width:60px; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Total"); ?></th>
            </TR>

<? $no=1;  $Topay=0; $total1=0; $currentbalance1=0; $currentbalance2=0; $currentbalance3=0; $loandue1=0; $loandue2=0; $currentpay=0; $totallatefee=0; $totalabsentfee=0; $loanoutstanding1=0;
$currentbalance=new Meetingbookreport_Model_Meetingbook();
 foreach($this->members as $members) {  //echo '<pre>';print_r($this->members);
$memberid=$members['memberid'];  
?>
    <TR>
        <td><? echo $no;?> </td>
        <td><? echo $members['membername'];?> </td>
        <td><? echo $members['uid'];?></td>
        <td><? $memberabsent=$currentbalance->memberabsent($memberid,$attendance['id']);
               $memberlate=$currentbalance->memberlate($memberid,$attendance['id']);
               if($memberabsent) { echo 'A';} 
                else if($memberlate) { echo 'L';} else { echo 'P'; }
                ?> 
            </td>

        <td style="text-align:right;"><? if($memberlate) { 
                $totallatefee+=$latefee=$members['penalty_latecoming']; echo $latefee; } else { echo $latefee=0; }
                 ?> 
        </td>
        <td style="text-align:right;"><? if($memberabsent) { 
                    $totalabsentfee+=$absentfee=$members['penalty_notcoming']; echo $absentfee; } else { echo $absentfee=0; }
                 ?> 
        </td>
        <td style="text-align:right;">    <?php 
                    $creditbalance=$currentbalance->creditbalance($memberid);
                    $debitbalance=$currentbalance->debitbalance($memberid); 
                  if($creditbalance) { 
                           if($debitbalance) { $debitbalance1=$debitbalance; } else { $debitbalance1=0; }
                        $currentbalance1=$creditbalance[0]['currentbalance']-$debitbalance1[0]['currentbalance'];
                     echo $currentbalance1;  } else { echo '0'; }  $currentbalance2+=$currentbalance1;  ?>
        </td>
        <td style="text-align:right;"><?php echo $perweek=$members['saving_perweek'];?></td> 
        <td style="text-align:right;">    <?php  
                    $loanoutstanding=$currentbalance->loanoutstanding($memberid);
                  if($loanoutstanding[0]['outstanding']) { 
                        echo $loanoutstanding[0]['outstanding'];
                         $loanoutstanding1=$loanoutstanding[0]['outstanding'];
                        } else { echo $loanoutstanding1; }
                       $currentbalance3+=$loanoutstanding1;  ?>
        </td>
        <td style="text-align:right;"> <?php
                    $loandue=$currentbalance->loandue($memberid); 
                  if($loandue[0]['outstanding']) { 
                        echo $loandue[0]['outstanding'];
                         $loandue1=$loandue[0]['outstanding'];
                        } else { echo $loandue1; }
                       $loandue2+=$loandue1;  ?>
        </td>
        <td style="text-align:right;"><?php 
            $total=$latefee+$absentfee+$currentbalance1+$loandue1; 
            echo $total;
            $total1+=$total; ?></td> 
    </TR>
<? $no++; 
$Topay+=$members['saving_perweek']; 
 
} ?>
    <TR>
        <td></td>
        <td></td>
        <td></td>
        <td>Total</td>
        <td style="text-align:right;"><?php echo $totallatefee; ?></td>
        <td style="text-align:right;"><?php echo $totalabsentfee; ?></td>
        <td style="text-align:right;"><?php echo $currentbalance2; ?></td>
        <td style="text-align:right;"><?php echo $Topay; ?></td> 

        <td style="text-align:right;"><?php echo $currentbalance3; ?></td>
        <td style="text-align:right;"><?php echo $loandue2; ?></td>
        <td style="text-align:right;"><?php echo $total1; ?></td>
    </TR>
        </table>
<?php } else {
       echo "<font color='RED'>No Members in the branch you seleted</font>";
} ?>
                </td>

            </TR>

          
            </table>
	   </TD></tr>

        </table>
    </form>

<form action="<?php echo $this->baseUrl();?>/meetingbookreport/index/pdfmeeting" method="POST"
onClick="window.open('<?php echo $this->baseUrl(); ?>/meetingbookreport/index/reportdisplay/file/meetingbook.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <input type="hidden" name="meetingno" value="<?php echo $this->field1; ?>">
            <input type="hidden" name="meeting_name" value="<?php echo $this->branchid; ?>">
           <div class="btnhouse">
		<div class="ltbtns">
			<TD > <input type="submit" value="<?php echo $this->translate('PDF'); ?>" id="submit"></TD>
		</div>
            </div>
</form>


<?php } else {?>

<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate('Search'); ?></legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/meetingbookreport/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Meeting Name</td>
                                    <td><?php echo $this->attendanceform->meeting_name;?></td>
                                    <td class="label">Meeting Number:</td>
                                    <td  id='meetingnodiv'><?php echo $this->attendanceform->meetingno;?>
                                    </td>
                                </tr>

                                <tr>
                       <td><input type="submit" name="Search" value="<?php echo $this->translate('Search');?>"/>
                                    <td></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 
<?php } ?>