<fieldset>
	<legend>Enter/Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/sbwithdrawal/index/withdrawal" method="POST">
			<table class="fieldsets">
                            <TR>
                                <th><label class="mand">Group code :</label></TD>
                                <th><?php echo $this->form->membercode;?></TD>
                            </TR> 
                            <TR>
                                <th><label class="mand">Withdrawal amount :</label></TD>
                                <th><?php echo $this->form->amount;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Submit;?>
                            </div>
                        </div>
	       </form>
</fieldset>
<?php  if((count($this->paginator) ==0) && ($this->search == true))  {
echo "<font color='RED'>Records Not Found Try Again...</font>";
} ?>