<fieldset>
	<legend><?php echo $this->translate("Enter/Search member"); ?></legend>
		<form action="<?php echo $this->baseUrl();?>/sbwithdrawal/index/withdrawal" method="POST">
			<table class="fieldsets">
                            <TR>
                                <th><label class="mand"><?php echo $this->translate("Group code :"); ?></label></TD>
                                <th><?php echo $this->form->membercode;?></TD>
                            </TR> 
                            <TR>
                                <th><label class="mand"><?php echo $this->translate("Withdrawal amount :"); ?></label></TD>
                                <th><?php echo $this->form->amount;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                             <input type="Submit" name="Submit" value="<?php echo $this->translate("Search"); ?>"><br><br>
                            </div>
                        </div>
	       </form>
</fieldset>
<?php  if((count($this->paginator) ==0) && ($this->search == true))  {
echo "<font color='RED'>Records Not Found Try Again...</font>";
} ?>