<html>
<head><TITLE>SB Withdrawal</TITLE>
</head>
<body>
<?php $dateconvertor = new App_Model_dateConvertor();?>
<div id="searchDiv">
        <fieldset>
                <legend>SB Withdrawal</legend> 
                <p align="center"><b>Declaration to withdraw savings amount</b></p>
                <table border="2" width="100%" id="hor-minimalist-b">

                    <TR>
                        <TD colspan="2"><b>Group name and address</b></TD>
                        <td><b>date</b></td>
                        <td><?php echo $dateconvertor->phpnormalformat($this->createdate);?></td>
                    </tr>
                    <?php
                        $address = array();
                        $groupmembers = array();
                        $repmembers = array();
                        $address = $this->address;
                        $groupmembers = $this->groupmemberslist;
                        $repmembers = $this->repmemberslist;
                     ?>
                    <tr>
                        <td colspan="2"><?php echo $this->groupname;?></td>
                        <td><b>groupcode</b></td>
                        <td><?php echo $this->groupcode;?></td>
                    </tr> 
                    <tr>
                        <td colspan="2"><?php echo $this->addressline1."<br>";
                              echo $this->addressline2."<br>";
                              echo $this->city."<br>";
                              echo $this->state; ?></td>
                        <td valign="top"><b>group saving acc no</b></td>
                        <td valign="top"><?php echo $this->accno;?></td>
                    </tr> 
                </table>
                <p>
                We are authorising and decided the below identified group representative to withdraw the amount <b>Rs <?php echo $this->amount;?> </b>from our Saving Bank account
                <br>
                <p>
                <?php $i=1; foreach($repmembers as $representative) { 
                  echo $i++.") ";
                  echo $representative['membername']."<br>";
                 } ?>
                </p>
                <p>Notice:All members</p>
                <table border="2" width="100%" id="hor-minimalist-b">
                    <TR>
                        <th>Sl.No</th>
                        <th>Group Members</th>
                        <th>Signature</th>
                    </TR>   
                    <?php $i = 1; foreach($groupmembers as $groupmemb) { ?> 
                    <TR>
                        <TD><?php echo $i++;?></TD>
                        <TD><?php echo $groupmemb['membername'];?></TD>
                        <TD></TD>
                    </TR>
                    <?php } $i--;?>
                     <TR>
                        <td></td>
                        <TD>Total =<?php echo $i;?></TD>
                        <TD></TD>
                    </TR> 
                </table>
                <br>
                <table width="100%" >
                    <TR>
                        <td align="center">Village facilitator</td>
                        <td align="center">Field officer</td>
                        <td align="center">Block office, Signature</td>
                    </TR>   
                </table>
    </fieldset>
</div>
</body>
</html>
<form action="<?php echo $this->baseUrl();?>/sbwithdrawal/index/pdfdisplay" method="POST"
onClick="window.open('<?php echo $this->baseUrl(); ?>/sbwithdrawal/index/reportdisplay/file/sbwithdrawal.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <input type="hidden" name="amount" value="<?php echo $this->amount; ?>">
            <input type="hidden" name="membertype" value="<?php echo $this->membertype; ?>">
           <div class="btnhouse">
		<div class="ltbtns">
			<TD > <input type="submit" value="<?php echo $this->translate('PDF'); ?>" id="submit"></TD>
		</div>
            </div>
</form>
<?php

?>