<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
  <fieldset>
    <legend>Search</legend>
        <div class="search" style="margin-left:20px;">
            <form action="<?php echo $this->baseUrl();?>/product" method="POST">
                <table width="100%">
                    <tr>
                        <td class="label"><br>Product name:</td>
                        <td ><br><? echo $this->form->s1;?></td>
                        <td class="label"><br>Product description:</td>
                        <td ><br><? echo $this->form->s2;?></td>
                    </tr>
                    <tr>
                        <td class="label"><br>Short name:</td>
                        <td ><br><? echo $this->form->s3;?></td>
                        <td class="label"><br>Category:</td>
                        <td ><br><? echo $this->form->s4;?></td>
                    </tr>
               </table><br>
               <div class="btnhouse">
                    <div class="ltbtns">
<div > <span><?php echo $this->form->Search; ?></span></div>
                    </div>
               </div>		
          </form>	
      </div>
    </fieldset> 
</div>  

<table id="hor-minimalist-b">
    <tr>
        <th>Product Name</th>
        <th>category name</td>
        <th>Product description</th>
               <th>Product shortname</th>
               <th>Created date</th>

    </tr>
<?php $dateconvertor = new App_Model_dateConvertor();?>
        <?php foreach ($this->paginator as $product ): ?>
    <tr>
        <td><a href="<?php echo $this->baseUrl()."/category/index/categoryview/id/".$product['id']; ?>">
                     <?php echo $this->escape($product['name']); ?></a></td>
    <td><?php echo $this->escape($product['categoryname']);?></td>
    <td><?php echo $this->escape($product['description']);?></td>
        <td><?php echo $this->escape($product['shortname']);?></td>
        <td><?php echo $this->escape($product['created_date']);?></td>

                <?php endforeach; ?>
    </tr>
   
</table>
<div align="center" style="margin-top:10px;color:#CC6633;">
<?php echo $this->paginationControl($this->paginator,'Sliding','/partials/my_pagination_control.phtml',$this->requestvalues); ?>
</div>