<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<!--search for individual member !-->
<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate("Search"); ?></legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/family" method="POST">
                            <table width="100%">
                                <tr>
                                    <td><?php echo $this->translate("Family code :"); ?></td><td ><? echo $this->form->code;?></td>
                                    <td><?php echo $this->translate("Family ID :"); ?></td><td ><? echo $this->form->familyid;?></td>
                                </tr>
                                <tr>
                                <td><br><?php echo $this->translate("House number :"); ?></td><td><br><? echo $this->form->house;?></td>
                                <td><br><?php echo $this->translate("Village name :"); ?></td><td><br><? echo $this->form->office;?></td>
                                </tr>
                                <tr>
                                    <td colspan="4" align="left"><? echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 

<!-- display error message if search got failed  -->
<?php  if((count($this->paginator) ==0) && ($this->search == true))  {
echo "<font color='RED'>Records Not Found Try Again...</font>";
} 

// <!--List out individual member details !-->
 if (count($this->paginator) !=0 ){ ?>
    <table id="hor-minimalist-b">
        <tr>
            <th><?php echo $this->translate("Family code"); ?></th>
            <th><?php echo $this->translate("Family ID"); ?></th>
            <th><?php echo $this->translate("House number"); ?></td>
            <th><?php echo $this->translate("Village"); ?></td>
        </tr>

        <?php foreach ($this->paginator as $family){ ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl()."/familycommonview/index/commonview/id/".$family['id']; ?>">
                        <?php echo $this->escape($family['code']); ?></a></td>

            <td><?php echo $this->escape($family['family_id']);?></td>
            <td><?php echo $this->escape($family['house_no']);?></td>
            <td><?php echo $this->escape($family['villagename']);?></td>
        <?php } ?>

        </tr>

        <?php // foreach ($this->paginator as $family){ ?>
        <!--<tr>
            <td><a href="<?php // echo $this->baseUrl()."/familycommonview/index/commonview/id/".$family['id']; ?>">
                        <?php // echo $this->escape($family['code']); ?></a></td>

            <td><?php //echo $this->escape($family['headname']);?></td>
            <td><?php //echo $this->escape($family['villagename']);?></td>
            <td><?php// echo $this->escape($family['gendername']);?></td>
        <?php //} ?>

        </tr>-->
        <tr>
            <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                        '/partials/my_pagination_control.phtml'); ?></div></td>
        </tr>

    </table>  
<?php } ?> 

