 <?php if ($this->pageCount){ ?>
<div id="paginationControl">
<!-- Previous page link -->
Results <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> of <?php echo $this->totalItemCount; ?>

<!-- First page link -->
<?php if (isset($this->previous)){ ?>
<?php   if(($this->s1 != '') || ($this->s2 != '') || ($this->s3 != '')) { ?>
<a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->first;?>&s1=<?php echo $this->s1;?>&s2=<?php echo $this->s2;?>&s3=<?php echo $this->s3;?>"> &lt;First</a> |
<?php   } else { ?>
<a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->first;?>">&lt; First</a> |
<?php   } ?><?php } else{ ?>
  <span class="disabled">First</span> |
<?php } ?>

<?php if (isset($this->previous)){ ?>
<?php   if(($this->s1 != '') || ($this->s2 != '') || ($this->s3 != '')) { ?>
<a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->previous;?>&s1=<?php echo $this->s1;?>&s2=<?php echo $this->s2;?>&s3=<?php echo $this->s3;?>"> &lt;Previous</a> |
<?php   } else { ?>
<a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->previous;?>">&lt; Previous</a> |
<?php   } ?>
<?php }else { ?>
  <span class="disabled">&lt; Previous</span> |
<?php } ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page){ ?>
<?php if ($page != $this->current){ ?>
    <?php   if(($this->s1 != '') || ($this->s2 != '') || ($this->s3 != '')) { ?>
        <a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $page;?>&s1=<?php echo $this->s1;?>&s2=<?php echo $this->s2;?>&s3=<?php echo $this->s3;?>"><?php echo $page; ?></a> |
    <?php } else { ?>
        <a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $page;?>"><?php echo $page; ?></a> |
    <?php } ?>
<?php } else { ?>
<?php echo $page; ?> |
<?php } ?>
<?php } ?>

<!-- Next page link -->
<?php if (isset($this->next)) { ?>
        <?php   if(($this->s1 != '') || ($this->s2 != '') || ($this->s3 != '')) { ?>
            <a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->next;?>&s1=<?php echo $this->s1;?>&s2=<?php echo $this->s2;?>&s3=<?php echo $this->s3;?>">Next &gt;</a>
                <?php } else { ?>
            <a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->next;?>">Next &gt;</a>
        <?php } ?>
<?php } else { ?>
    <span class="disabled">Next &gt;</span>
<?php } ?>

<!-- Last page link -->
<?php if (isset($this->next)){ ?>
        <?php   if(($this->s1 != '') || ($this->s2 != '') || ($this->s3 != '')) { ?>
            <a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->last;?>&s1=<?php echo $this->s1;?>&s2=<?php echo $this->s2;?>&s3=<?php echo $this->s3;?>">Last &gt;</a>
                <?php } else { ?>
            <a href="<?php echo $this->baseUrl();?>/ledger/index?page=<?php echo $this->last;?>">Last &gt;</a>
        <?php } ?>
<?php } else { ?>
  <span class="disabled">Last</span>
<?php } ?>
</div>
<?php } ?>
