<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
function getgroups(branch,path) {
	if(branch) {
		targeturl=path+"/cashscroll/index/group?branch="+branch;
		$.ajax({ url: targeturl, success: function(data){ $("#groupdiv").html(data) }});
	}
}
$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});

</script>
<?php if($this->savingsDebit) { ?>
<h1><b><?php echo "Branch: ".$this->officename; ?></b></h1>
<h5 align="right"><?php echo $this->translate('As of'); ?> <?php echo "<font color='#039'>".$this->field1."</font>"; ?></h5> 
<h5 style="text-align:right">* <?php echo $this->translate("Amount in"); ?>  <font color="red"><?php echo $this->translate("Rs"); ?></font></h5>


<div style="float:left;width:370px">
            <?php 
              $i = 0;
              $j = 0;
              $k = 0;
              $l = 0;
              $amountCredit = "0";
              $amountDebit = "0";
              $grandTotal = "0";
              $total = "0";
              $countvalue1 =count($this->savingsCredit);
              $countvalue2 =count($this->savingsDebit);
              $count = $countvalue1>$countvalue2?$countvalue1:$countvalue2; 
            ?>

<h5><?php echo $this->translate("Credit"); ?></h5>
    <table id="hor-minimalist-s">
        <TR>
            <TH ><?php echo $this->translate("Sl No."); ?></TH>
            <TH ><?php echo $this->translate("Particulars"); ?></TH>
            <TH ><?php echo $this->translate("Amount"); ?></TH>
        </TR>
        <?php foreach($this->savingsCredit as $savingsCredit) { 
                $l++;  $i++;?>
        <TR>
            <TD ><?php echo $l; ?></TD>
            <TD ><?php echo $savingsCredit->account_number; ?></TD>
            <TD style="text-align:right;"><?php 
               echo $savingsCredit->amount_to_bank; 
               $amountCredit = $amountCredit + $savingsCredit->amount_to_bank; 
                ?></TD>
        </TR>

        <?php } ?>
	<?php 
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
				<tr>
				        <TD></TD>
					<TD><b><?php echo $this->translate("Total Receipt"); ?></b></TD>
					<td style="text-align:right;"><b><?php echo sprintf("%4.2f", $amountCredit);?></b></td>
				</tr>
				<tr>
                                        <TD></TD>
                                        <TD><b><?php echo $this->translate("Opening Cash"); ?></b></TD>
                                        <TD style="text-align:right;"><b><?php echo sprintf("%4.2f", $this->openingBalance)?></b></TD>
                                </tr>
                                <tr>
                                        <TD></TD>
                                        <TD><b>Total</b></TD>
                                        <?php if($amountCredit+$this->openingBalance != "0") { ?>
                                        <TD style="text-align:right;"><B><?php echo $grandTotal = sprintf("%4.2f", $amountCredit+$this->openingBalance); ?></TD></TD>
                                        <?php } else { ?>
                                        <TD style="text-align:right;" width = "52"  ><B>----</B></TD>
                                        <?php } ?>
                                </tr>
			<?php } else {?>
				<tr>
				        <TD></TD>
					<td><?php echo "----";?></td>
					<td style="text-align:right;"><?php echo "----";?></td>
				</tr>
		
			<?php } }  $i=0;$j=0; ?>
    </table>
  </div>

<div style="float:left;width:370px">
<h5><?php echo $this->translate("Debit"); ?></h5>
    <table id="hor-minimalist-s" >
        <TR>
            <TH ><?php echo $this->translate("Sl No."); ?></TH>
            <TH ><?php echo $this->translate("Particulars"); ?></TH>
            <TH ><?php echo $this->translate("Amount"); ?></TH>
        </TR>
        <?php foreach($this->savingsDebit as $savingsDebit) {
        $k++; $i++; ?>
        <TR>
            <TD ><?php echo $k; ?></TD>
            <TD ><?php echo $savingsDebit->account_number; ?></TD>
            <TD  style="text-align:right;"><?php
                echo $savingsDebit->amount_from_bank; 
                $amountDebit = $amountDebit + $savingsDebit->amount_from_bank;?></TD>
        </TR>

        <?php } ?>
		<?php
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
				<tr>
				        <TD></TD>
					<TD><b><?php echo $this->translate("Total Payment"); ?></b></TD>
					<td style="text-align:right;"><b><?php echo sprintf("%4.2f",$amountDebit);?></b></TD>
                                </tr>
				<tr>
                                        <TD></TD>
                                        <TD><b><?php echo $this->translate("Closing Cash"); ?></b></TD>
                                        <TD style="text-align:right;"><b><?php echo $total = sprintf("%4.2f",($grandTotal - $amountDebit)); ?></b></TD>
                                </tr>
                                <tr>
                                        <TD></TD>
                                        <TD><b><?php echo $this->translate("Total"); ?></b></TD>
                                        <?php if($amountDebit + $total != "0") { ?>
                                        <TD  style="text-align:right;"><B><?php echo sprintf("%4.2f", $amountDebit + $total); ?></TD></TD>
                                        <?php } else { ?>
                                        <TD width = "52" style="text-align:right;"><B>----</B></TD>
                                        <?php } ?>
                                </tr>
			<?php  } else {?>
				<tr>
       				        <TD></TD>
					<td><?php echo "----";?></td>
					<td style="text-align:right;"><?php echo "----";?></td>
				</tr>
		
			<?php } }  ?>
    </table>
</div>



<?php } else {?>
<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate("Search"); ?></legend>
 <form action="<?php echo $this->baseUrl();?>/cashscroll/index" method="POST">
             <table width="100%">
               
                 <tr>
                            <TD><?php echo $this->translate('From date'); ?></td>
                            <td><?php echo $this->form->datefrom;?></td>
 							<TD><?php echo $this->translate('To date'); ?></td>
                            <td><?php echo $this->form->dateto;?></td>
                   </tr>
  <tr>
							<TD><?php echo $this->translate('Hierarchy'); ?></td>
                            <TD id="show"><?php echo $this->form->hierarchy;?></td>
</tr><tr>

                            <TD><?php echo $this->translate('Branch'); ?></td>
                            <td><div id="statediv"><?php echo $this->form->branch;?></div></td>
</tr>
<tr id="hide">
							<TD><?php echo $this->translate('Group'); ?></td>
                            <td><div id="groupdiv"><?php echo $this->form->group;?></td>
</tr>

                       <td><input type="submit" name="Search" value="<?php echo $this->translate('Search');?>"> </td>
                       <td></td> 
                   </tr>
                
            </table>
       </form>
</fieldset>
</div>

<?php } ?>


