<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="container-1">
	<div class="register">
		<div class="profile_tab">
            <TABLE id="hor-minimalist-b">
<?php if(($this->holidaydetails)!=NULL) {
					foreach($this->holidaydetails as $edit_id) { ?>
<tr>
						<th class = "firsttd">Holiday details</th>
						<th class = "secondtd"></th>	
<th class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/holiday/index/holidayedit/id/<?php echo $edit_id['id'];?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th><th></th>
<th></th>
</tr>
<?php }}  ?>
        <?php  $convertdate = new App_Model_dateConvertor();
        foreach($this->holidaydetails as $holiday) {  ?>
                <TR>
                    <TD>Holiday Name</TD>
                    <TD><?php echo $holiday['name'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>Office name</TD>
                    <TD><?php echo $holiday['officename'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
 <TR>
                    <TD>Holiday from</TD>
                    <td><?php echo $convertdate->phpnormalformat($holiday['holiday_from']);?></div></td>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
 <TR>
                    <TD>Holiday upto</TD>
                    <td><?php echo $convertdate->phpnormalformat($holiday['holiday_upto']);?></div></td>
                    <TD></TD>
                    <TD></TD>
                </TR>
<TR>
                    <TD>Repayment date</TD>
                    <td><?php echo $convertdate->phpnormalformat($holiday['repayment_date']);?></div></td>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD></TD>
                    <TD></TD>
                    <TD><a href="<?php echo $this->baseUrl(); ?>/holiday">
                                <input name="submit" type="submit" class="officebutton" value="Back"></a></TD>
                    <TD></TD>
                    <TD></TD>
              </TR>
        </TABLE>
<?php } ?>
</div>
</div>
</div>

