<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
// // function getgroups(branch,path) {
// // 	if(branch) {
// // 		targeturl=path+"/cashscroll/index/group?branch="+branch;
// // 		$.ajax({ url: targeturl, success: function(data){ $("#groupdiv").html(data) }});
// // 	}
// // }
$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});

</script>
<?php if (!$this->result && !$this->accountBalanc ) { ?>
<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate('Search'); ?></legend>
           <form action="<?php echo $this->baseUrl();?>/depositsummary/index" method="POST">
             <table width="100%">

  					<tr>	<TD><?php echo $this->translate('Hierarchy'); ?></td>
                            <TD id="show"><?php echo $this->form->hierarchy;?></td>
  					</tr>
					<tr>    <TD><?php echo $this->translate('Branch'); ?></td>
                            <td><div id="statediv"><?php echo $this->form->branch;?></div></td>
					</tr>
					<tr><TD><br><input type="submit" name="Search" value="Search"></TD></tr>
            </table>
          </form>
    </fieldset>
</div>
<?php } ?>
<?php if ($this->result || $this->accountBalanc ) { ?>
        <div class="cont-rgt-data">
            <table id="hor-minimalist-b">

                    <TR bgcolor="Gray">
                            <?php if ($this->officeName) { ?>
                            <TD><B><font color="black"><?php echo $this->translate('Branch Name'); ?></font></B></TD>
                            <TD><B><font color="#039"><?php echo $this->officeName; ?></font></B></TD>

                            <?php } ?>
                    </TR>
            </table><BR>
            <table id="hor-minimalist-b">
                    <TR bgcolor="Silver">
			    <TD ><font color="black"><?php echo $this->translate('Type of savings'); ?></font></TD>
			    <TD align="center" ><font color="black"><?php echo $this->translate('Number of accounts'); ?></font></TD>
			    <TD  align="right"><font color="black"><?php echo $this->translate('Total Savings Amount'); ?></font></TD>
                    </TR>
                    <?php foreach($this->result as $savingsdetails){  ?>
                    <TR>
                       <TD><?php echo $savingsdetails['prodoffername'];?></TD>
			    	   <TD  align="center"><?php echo $savingsdetails['countvalue'];?></TD>
			    	   <TD  align="right"><?php $test=end($this->accountBalanc); echo $test['balance'];?></TD>
                    </TR>
	    </table> 
            <table align = "right" >
		     <TR>
                        <TH></TH>
                        <TH></TH>
		<Th align="left"><b>Total :</b></Th>
		<th align="right"><font color="#039"><b><?php $test=end($this->accountBalanc); echo $test['balance'];?></b></font></TH>
		   </TR><?  }?>
             </table>
        </div>
<form action="<?php echo $this->baseUrl();?>/depositsummary/index/pdftransaction" method="POST"
onClick="window.open('<?php echo $this->baseUrl(); ?>/depositsummary/index/reportdisplay/file/depositsummaryreport.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
<input type="hidden" name="field1" value="<?php echo $this->office_id;?>">
           <input type="submit" value="PDF" id="submit">
</form>


<?php } ?>

