<?php
/*
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################*/
              $totalCredit = "0";
              $totalTransferCredit = "0";
              $totalDebit = "0";
              $totalTransferDebit = "0";
              $i = 0;
              $j = 0;              
              $countvalue1 =count($this->savingsCredit);
              $countvalue2 =count($this->savingsDebit);
              $count = $countvalue1>$countvalue2?$countvalue1:$countvalue2; 
        ?>
<div style="float:left;width:367px">
    <legend>Receipt</legend>
    <table id="hor-minimalist-s">
        <TR>
            <TH >LF No.</TH>
            <TH >Particulars</TH>
            <TH>A/C No.</TH>
            <TH class = "label">Cash</TH>
            <TH class = "label">Transfer</TH>
        </TR>


        <?php foreach($this->savingsCredit as $savingsCredit) {
		if(($savingsCredit->paymenttype_id == 1) or ($savingsCredit->paymenttype_id == 5)) {  $i++;
	?>
        <TR>
            <TD ><?php echo $savingsCredit->glsubcode_id_to ?></TD>
            <TD ><?php echo $savingsCredit->account_number; ?></TD>
            <TD ><?php echo $savingsCredit->account_id ?></TD>
            <?php if($savingsCredit->paymenttype_id == 1) {?>
            <TD align = "right"><?php echo $savingsCredit->amount_to_bank; 
            $totalCredit = $totalCredit + $savingsCredit->amount_to_bank; ?></TD>
            <TD></TD>
            <?php } elseif($savingsCredit->paymenttype_id == 5) { ?>
            <TD></TD>
            <TD align = "right"><?php echo $savingsCredit->amount_to_bank; 
            $totalTransferCredit = $totalTransferCredit + $savingsCredit->amount_to_bank; ?></TD>
            <?php }}?>
        </TR>
        <?php } ?>
        <?php 
	for($j=$i;$j<=$count;$j++){ 
            if($j==$count){ ?>
                <TR>
                    <td><b>Total</b></td>
                    <td></td>
                    <td></td>
                    <?php if ($totalCredit != "0") { ?>
                    <td align="right"><b><?php echo sprintf("%4.2f", $totalCredit); ?></b></td>
                    <?php } else { ?>
                    <td align="right"><b>----</b></td>
                    <?php } ?>
                    <?php if ($totalCredit != "0") { ?>
                    <td align="right"><b><?php echo sprintf("%4.2f", $totalTransferCredit); ?></b></td>
                    <?php } else { ?>
                    <td align="right"><b>----</b></td>
                    <?php } ?>
                </TR>
            <?php } else {?>
		<tr>
		  <TD></TD>
		  <TD></TD>
		  <TD></TD>
		  <td><?php echo "----";?></td>
		  <td align = "right"><?php echo "----";?></td>
		</tr>
	<?php } }  $i=0;$j=0; ?>

    </table>
</div>
<div style="float:left;width:367px">
    <legend>Payment</legend>
    <table id="hor-minimalist-s">
        <TR>
            <TH >LF No.</TH>
            <TH >Particulars</TH>
            <TH>A/C No.</TH>
            <TH class = "label">Cash</TH>
            <TH class = "label">Transfer</TH>
        </TR>


        <?php foreach($this->savingsDebit as $savingsDebit) {
		if(($savingsDebit->paymenttype_id == 1) or ($savingsDebit->paymenttype_id == 5)) {  $i++;
	?>
        <TR>
            <TD ><?php echo $savingsDebit->glsubcode_id_to ?></TD>
            <TD ><?php echo $savingsDebit->account_number; ?></TD>
            <TD ><?php echo $savingsDebit->account_id ?></TD>
            <?php if($savingsDebit->paymenttype_id == 1) {?>
            <TD align = "right"><?php echo $savingsDebit->amount_from_bank; 
            $totalDebit = $totalDebit + $savingsDebit->amount_from_bank; ?></TD>
            <TD></TD>
            <?php } elseif($savingsDebit->paymenttype_id == 5) { ?>
            <TD></TD>
            <TD align = "right"><?php echo $savingsDebit->amount_from_bank; 
            $totalTransferDebit = $totalTransferDebit + $savingsDebit->amount_from_bank; ?></TD>
            <?php }}?>
        </TR>
        <?php } ?>
        <?php 
	for($j=$i;$j<=$count;$j++){ 
            if($j==$count){ ?>
                <TR>
                    <td><b>Total</b></td>
                    <td></td>
                    <td></td>
                    <?php if ($totalDebit != "0") { ?>
                    <td align="right"><b><?php echo sprintf("%4.2f", $totalDebit); ?></b></td>
                    <?php } else { ?>
                    <td align="right"><b>----</b></td>
                    <?php } ?>
                    <?php if ($totalDebit != "0") { ?>
                    <td align="right"><b><?php echo sprintf("%4.2f", $totalTransferDebit); ?></b></td>
                    <?php } else { ?>
                    <td align="right"><b>----</b></td>
                    <?php } ?>
                </TR>
            <?php } else {?>
		<tr>
		  <TD></TD>
		  <TD></TD>
		  <TD></TD>
		  <td><?php echo "----";?></td>
		  <td align = "right"><?php echo "----";?></td>
		</tr>
	<?php } }  $i=0;$j=0; ?>

    </table>
</div>
<div style="float:left;width:400px">
<form action="<?php echo $this->baseUrl();?>/sbcashscroll/index/pdftransaction" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/sbcashscroll/index/reportdisplay/file/sbcashscroll.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <input type="hidden" name="field1" value="<?php echo $this->field1; ?>">
            <input type="submit" value="PDF" id="submit">
</form>
</div>
