<form name="form1" action="<?php echo $this->baseUrl();?>/monthend/index/index" method="POST">
<table id="hor-minimalist-b">
    <tr>
        <th>Month end process for <?php echo $this->dateconvector->phpnormalformat($this->monthstart);?> - <?php echo $this->dateconvector->phpnormalformat($this->monthend);?></th>
        <th></th>
        <th></th>
    </tr>
    <tr>
    <td>Do you want month end process for loan</td>
    <td><input type = "submit" name = "continue" value = "Continue "></td>
    <td><a href="<?php echo $this->baseUrl();?>/maintenance/"><input type = "button" name = "cancel" value = "Cancel"></a></td></tr>
</table>
</form>
