<script> 
function getXMLHTTP() {
    var xmlhttp=false;	
        try{
            xmlhttp=new XMLHttpRequest();
        }
        catch(e) {
            try {	
                xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
            }
            catch(e){
                try {
                    xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
                }
                catch(e1){
                    xmlhttp=false;
                }
            }
        }
        return xmlhttp;
    }
function getInterests(interest,path,productId) {	
    var strURL=path+"/groupgrading/index/interest?interest="+interest+"&productId="+productId;

    var req = getXMLHTTP();
        if (req) {
            req.onreadystatechange = function() {
            if (req.readyState == 4) {
                if (req.status == 200) {
                    document.getElementById('interestratediv').innerHTML=req.responseText;
                } else {
                    alert("There was a problem while using XMLHTTP:\n" + req.statusText);
                  }
            }
        }
        req.open("GET", strURL, true);
        req.send(null);
        }
        var perioddescription=$('#perioddescription').val();
        if(perioddescription!='') {
            $('#errorspan').show();
        } else {
            $('#errorspan').hide();
          }
}


function displayRow(type) {
    var row = document.getElementById("funder");
    if(type == '2')
    row.style.display = 'none';
    else if (type == '1')
    row.style.display = '';

}
</script>
<?php 
if ($this->account) {
foreach ($this->account as $account) {
?>
<div style="float:left;width:380px"> 
    <table id="hor-minimalist-s" summary="Employee Pay Sheet">
        <TR>
            <TH><?php echo $this->translate("Member details"); ?></TH>
            <TH></TH>
        </TR>
        <TR>
            <td><?php echo $this->translate("Member code:"); ?></td>
            <TD><? echo $account->code; ?></TD>
        </TR>
        <TR>
            <td><?php echo $this->translate("Name:"); ?></td>
            <TD><?php echo $account->name;?></TD>
        </TR>
        <TR>
            <td><?php echo $this->translate("Branch:"); ?></td>
            <td><?php echo $account->officename ;?></TD>
        </TR>
        <TR>
            <TH><?php echo $this->translate("Product details"); ?></TH>
            <TH></TH>
        </TR>

        <TR>
            <td><?php echo $this->translate("Product name:"); ?></td>
            <TD><?php echo $account->productname;?></TD>
        </TR>
        <TR>
            <td><?php echo $this->translate("Min disbursement:"); ?></b></td>
            <TD><?php echo $account->minamount;?></TD>
        </TR>

        <TR>
            <td><?php echo $this->translate("Max disbursement:"); ?></td>
            <TD><?php echo $account->maxamount; ?></TD>
        </TR> 
        <TR>
            <td><?php echo $this->translate("Penal interest:"); ?></td>
            <TD><?php echo $account->penalInterest; ?></TD>
        </TR>
        <TR>
            <TH><?php echo $this->translate("Interest per annum"); ?></TH>
            <TH></TH>
        </TR>
        <TR>
            <TD><B><?php echo $this->translate("Periods in months"); ?></B></TD>
            <TD><B><?php echo $this->translate("Interest"); ?></B></TD>
        </TR>
        <?php if ($this->interestRates) {
              foreach ($this->interestRates as $interestRates) { ?>
              <TR>
                <td><?php echo $interestRates->period_ofrange_description; ?></td>
                <TD><?php echo $interestRates->Interest; ?></TD>
             </TR>
       <?php } } ?>
    </table>
<?php } } ?>
</div>
<div style="float:left;width:350px"> 
    <fieldset>
        <legend><?php echo $this->translate("Member"); ?>Loan account</legend>
            <form name="addform" action="<?php echo $this->baseUrl();?>/groupgrading/index/createaccount" method="POST">
            <table class="fieldsets">
                    <TR>
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Date of account"); ?></TD>
                        <TD><?php echo $this->loanForm->date;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Disbursement amount"); ?></TD>
                        <TD><?php echo $this->loanForm->amount;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Installments (Months)"); ?></TD>
                        <TD><?php echo $this->loanForm->installments;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Interest rate"); ?></TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->interest;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Interest type"); ?></TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->interesttype_id;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Transfer amount to"); ?></TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->savingAccount;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Fundings"); ?></TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->fundings;?></div></TD>
                    </TR>
                    <TR id = "funder" style="display:none">
                        <TD><label for="fld1" class="mand"><?php echo $this->translate("Funder"); ?></TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->funders;?></div></TD>
                    </TR>
                    <TR>
                        <TD><?php echo $this->loanForm->Submit; ?></TD>
                        <td><?php echo $this->loanForm->Back; ?></td>
                    </TR>
                    <?php echo '<font color=RED>'.$this->maxdate.'</font>'; ?>
                </table>
                <?php echo $this->loanForm->Id; ?> <?php echo $this->loanForm->code; ?> 
            </form>
</div>
