<div style="float:left;width:350px"> 
<table id="hor-minimalist-s">
      <TR>
           <TH><?php echo $this->translate("Member details"); ?></TH>
           <TH></TH>
      </TR>

    <?php foreach($this->result as $result) ?>
   <TR>
      <td><?php echo $this->translate("Member code"); ?></td><TD><? echo $result->code; ?></TD>
   </TR>
   <TR>
        <td><?php echo $this->translate("Name"); ?></td>
         <td><?php echo $result->name; ?></TD>
    </TR>
    <TR>
        <td><?php echo $this->translate("Branch"); ?></td><td><?php echo $result->officename ;?></td>
    </TR>
</table>
<br/>

<?php 
if ($this->products) { ?>
<table id="hor-minimalist-s">
     <tr>
         <th><?php echo $this->translate("Available Loan"); ?></th>
     </tr>
<?php foreach ($this->products as $products) { ?>

     <tr>
         <td><a href = "<?php echo $this->baseUrl();?>/groupgrading/index/createaccount/Id/<?php echo base64_encode($products->id);?>/code/<?php echo base64_encode($this->code);?>/" ><?php echo $products->name;?></a></td>
    </tr>
<?php }  ?>
</table>
<?php }  ?>
</div> 

<?php 
if ($this->account) { ?>
<div style="float:right;width:350px">
    <table id="hor-minimalist-s">

    
       <TR>
           <th><?php echo $this->translate("Active loan account"); ?></td>
           <th><?php echo $this->translate("Products"); ?></th>
       </TR>
        <?php foreach($this->account as $account)  { ?>

       <TR>
           <TD><?php echo $account->number;?></TD>
           <TD><?php echo $account->name;?></TD>
       </TR>
      <?php  }?>

     </table>
</div>
<?php } ?>
