<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script>

 <link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />


<script type="text/javascript">
$(document).ready(function() {
    $("#meetingregisterfrom").datepicker({"dateFormat":"dd/mm/yy"});
    $("#meetingregisterto").datepicker({"dateFormat":"dd/mm/yy"});

    $("#savingregisterfrom").datepicker({"dateFormat":"dd/mm/yy"});
    $("#savingregisterto").datepicker({"dateFormat":"dd/mm/yy"});

    $("#internalregfrom").datepicker({"dateFormat":"dd/mm/yy"});
    $("#internalregto").datepicker({"dateFormat":"dd/mm/yy"});

});
</script>

<form action="<?php echo $this->baseUrl();?>/loanprocess/index/jlgadvances" method="POST">
	<div class="profile_tab"> 
        <fieldset>
                <p><h3 align="center">ADDITIONAL INFORMATION FOR JLG ADVANCES</h3></p>
<tr><Td width="30%"><b>DATE : <?php echo date('d-m-Y');?></b></td></tr>
            <table border="1" width="100%">

                <TR>
                        <TD width="10%" align="center"><b>S.No</b></TD>
                        <td width="40%" colspan="3" align="center"><b>Particulars</b></td>
                        <td width="20%" colspan="2" align="center"><b>Details</b></td>
                        <td width="15%" colspan="2" align="center"><b>Maximum marks</b></td>
                        <td width="15%" colspan="2" align="center"><b>Scored marks</b></td>

                </TR>

                <tr>
                    <TD  align="center">1</TD>
                    <td class="label" colspan="3">Date of formation</TD>
                    <td  colspan="2"  ><?php echo $this->form->dateofformation;?></td>
                    <td colspan="2" align="center">100</td>
                    <td colspan="2" align="center"></td>
                </tr>

                <tr>    <TD  align="center">2</TD>
                        <td class="label" colspan="3">If any loan taken</TD>
                        <td  colspan="2" align="center"><?php echo $this->form->loantaken;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
		</tr>
		<tr>
                        <TD  align="center">3</TD>
                        <td class="label" colspan="3">Name of the bank/branch</TD>
                        <td  colspan="2"  ><?php echo $this->form->branchname;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
		</tr>
		<tr>
                        <TD  align="center">4</TD>
                        <td class="label" colspan="3">Limit enjoyed</TD>
                        <td  colspan="2"  ><?php echo $this->form->limitenjoy;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>

		</tr>
		<tr>
                        <TD align="center">5</TD>
	                <td class="label" colspan="3">Acc no</TD>
                        <td  colspan="2" ><?php echo $this->form->accno;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
		</tr>
		<tr>    <TD  align="center">6</TD>
                        <td class="label" colspan="3">Date of advance taken</td>
                        <td  colspan="2" ><?php echo $this->form->dateofadvance;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD  align="center">7</TD>
                        <td class="label" colspan="3">Date of closure</td>
                        <td  colspan="2"  ><?php echo $this->form->dateofclosure;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
		</tr>

                <tr>
                        <TD align="center">8</TD>
                        <td colspan="3">Total members</td>
                        <td colspan="2"  ><?php echo $this->form->totalmembers;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>

                </tr>

                <tr>
                        <TD align="center">9</TD>
                        <TD colspan="3">Any members debarred/diseased/etc</TD>
                        <td  colspan="2" ><?php echo $this->form->anymember;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
                </tr>

                <tr>
                        <TD align="center">10</TD>
                        <TD colspan="3">Periodic meetings weekly/fortnightly/monthly when was last meeting held</TD>
                        <td  colspan="2" align="center"><?php echo $this->form->periodicalmeeting;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
                </tr>

                <tr>
                        <TD align="center">11</TD>
                        <TD colspan="3">Any other bank branches in the JLG area</TD>
                        <td  colspan="2"  ><?php echo $this->form->otherbankbranch;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>

                <tr>
                        <TD align="center">12</TD>
                        <TD colspan="3">Repayment installment to commence from</TD>
                        <td  colspan="2"  colspan="2"><?php echo $this->form->repaymentinstallment;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">13</TD>
                        <TD colspan="3">Interest rate</TD>
                        <td  colspan="2"  colspan="2"><?php echo $this->form->interestrate;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">14</TD>
                        <TD colspan="3">Application sources existing activity</TD>
                        <td  colspan="2" align="center"><?php echo $this->form->appsource;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">15</TD>
                        <TD colspan="3">Same village SHG/TF/KCC members availed in the JLG</TD>
                        <td  colspan="2"  ><?php echo $this->form->samevillageavailability;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">16</TD>
                        <TD colspan="3">Declaration by each member</TD>
                        <td  colspan="2" align="center"><?php echo $this->form->declaration;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">17</TD>
                        <TD colspan="3">Whethers representatives being rotated periodically</TD>
                        <td align="center" colspan="2"><?php echo $this->form->rotatedperiod;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">18</TD>
                        <TD colspan="3">JLG maintaining SB a/c with any other bank</TD>
                        <td align="center" colspan="2"><?php echo $this->form->Jlgothrbankacc;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">19</TD>
                        <TD colspan="3">JLG members SB a/c with other bank</TD>
                        <td align="center" colspan="2"><?php echo $this->form->memberothrbankacc;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">20</TD>
                        <TD colspan="3">JLG same members availed with BC linked now to bank</TD>
                        <td align="center" colspan="2"><?php echo $this->form->memavailbc;?></td>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">21</TD>
                        <TD colspan="3">JLG maintaining books/records as per statutory requirement</TD>
                        <td align="center" colspan="2"><?php echo $this->form->statuoryreq;?></td> 
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
               </tr>
                <tr>
                        <TD align="center">22</TD>
                        <TD colspan="3">JLG meeting register maintained</TD>
                        <TD colspan="2" >From <?php echo $this->form->meetingregisterfrom;?><br>
                       &nbsp; To &nbsp;<?php echo $this->form->meetingregisterto;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">23</TD>
                        <TD colspan="3">JLG savings register ,cash register</TD>
                        <TD colspan="2" >From <?php echo $this->form->savingregisterfrom;?><br>
                       &nbsp; To &nbsp;<?php echo $this->form->savingregisterto;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">24</TD>
                        <TD colspan="3">JLG internal lending register</TD>
                        <TD colspan="2">From <?php echo $this->form->internalregfrom;?><br>
                       &nbsp; To &nbsp;<?php echo $this->form->internalregto;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD align="center">25</TD>
                        <TD  colspan="3">JLG Pass books of each member given</TD>
                        <TD colspan="2" align="center"><?php echo $this->form->jlgpassbook;?></td>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
                </tr>

                <tr>
                        <TD  colspan="10" align="center"><b>JLG</b></TD></tr>
                </tr>
                <tr>    <TD valign="top" align="center">26</TD>
                        <Td colspan="3">Total savings</Td>
                        <TD colspan="2" ><?php echo $this->form->totalsaving;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>    <TD   valign="top" align="center">27</TD>
                        <TD colspan="3">Total interest on internal lending/fine if any</TD>
                        <TD colspan="2" ><?php echo $this->form->totalinterest;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>    <TD   valign="top" align="center">28</TD>
                        <TD colspan="3">Revolving fund</TD>
                        <TD colspan="2" ><?php echo $this->form->revolvingfund;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD colspan="10" align="center"><b>Obsolute Or Functioning</b></td>

                </tr>
                <tr>    <TD valign="top" align="center">29</TD>
                        <TD colspan="3">If any grands/subsidary received from NGO/MLA/MP</TD>
                        <TD colspan="2" ><?php echo $this->form->onssubsidy;?></TD>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
                </tr>
                <tr>    <TD   valign="top" align="center">30</TD>
                        <td colspan="3">TOTAL corpus fund</TD>
                        <TD colspan="2" ><?php echo $this->form->totalcorpus;?></TD>
                        <td colspan="2" width="15%" align="center">50</td>
                        <td colspan="2" width="15%" align="center"></td>
                </tr>

                <tr>
                        <TD  colspan="10" align="center"><b>JLG</b></TD>

                </tr>
                <tr>    <TD valign="top" align="center">31</TD>
                        <TD colspan="3">Internal lending amount given to JLG members</TD>
                        <TD colspan="2" align="center"><?php echo $this->form->internallend;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>    <TD valign="top" align="center">32</TD>
                        <TD colspan="3">Other Expenses</TD>
                        <TD colspan="2" align="center"><?php echo $this->form->otherexpense;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                 <tr>   <TD valign="top" align="center">33</TD>
                        <TD colspan="3">Amount held in Bank</TD>
                        <TD colspan="2" align="center"><?php echo $this->form->cashonhand;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>

                <tr>
                        <TD colspan="10" align="center"><b>Obsolute Or Functioning</b></td>

                </tr>
                <tr>    <TD valign="top" align="center">34</TD>
                        <TD colspan="3">Amount held in Bank</TD>
                        <TD colspan="2" align="center"><?php echo $this->form->amountinbank;?></TD>
                        <td colspan="2" align="center">50</td>
                        <td colspan="2" align="center"></td>
                </tr>
                <tr>
                        <TD   align="center">35</TD>
                        <TD  colspan="3" align="center">Remarks</TD>
                        <TD  colspan="2" align="center"><textarea name="remarks" rows="4" cols="17"> </textarea></TD>
                        <td colspan="2" align="center"></td>
                        <td colspan="2" align="center"></td>
                </tr>

                <tr>   <td colspan="4" align="left"><input type="submit" name="Submit" id="Submit" value="Submit"></td>
		       <td colspan="6" align="right"><a href="<?php echo $this->baseUrl();?>/loanprocess/index"><input type="button" name="Back" value="Back"/></a></td>
                </tr>
             </table>
        </fieldset>
    </div>
</form>
