<fieldset>
    <legend>Search member</legend>
        <form action="<?php echo $this->baseUrl();?>/groupgrading/index/shgindex" method="POST">
            <table class="fieldsets">
                <TR>
                    <th><label for="fld3">Group code</label></TD>
                    <th><? echo $this->form->membercode;?></TD>
                </TR>
            </table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Submit;?>
                </div>
            </div>
        </form>
</fieldset>
<div>
<?php if($this->groupdetails) { 
?>
    <table id="hor-minimalist-b">
	<tr>
                <th>Code</th>
        	<th>Name</th>
	</tr>

	<?php foreach($this->groupdetails as $member) : ?>
	<tr>
                <td><a href="<?php echo $this->baseUrl();?>/groupgrading/index/shgadvances/id/<?php echo base64_encode($member['id']); ?>"><?php echo $member['groupcode'];?></a></td>
		<td><?php  echo $member['name'];?></td>
	</tr>
	<?php endforeach; ?>
	</table>
<?php }?>
</div>