<fieldset>
    <legend>Search member</legend>
        <form action="<?php echo $this->baseUrl();?>/groupgrading/index/shgadvances" method="POST">
            <table class="fieldsets">
                <TR>
                    <th><label class="mand">Group code :</label></TD>
                    <th><? echo $this->form->membercode;?></TD>
                </TR>
            </table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Submit;?>
                </div>
            </div>
        </form>
</fieldset>
