<div>
<?php if($this->viewdetails) { ?>
    <form action="<?php echo $this->baseUrl();?>/groupgrading/index/loanupdate/id/<?php echo base64_encode($this->id); ?>" method="POST">
    <table id="hor-minimalist-b">
	<tr>
	    <Th colspan="3">Loan details</Th>

	</tr>
	<?php foreach($this->viewdetails as $loan){ ?>
	<tr>
		<td>Group code / Individual code</td>
		<td colspan="2"><?php  echo $loan['code'];?></td>
        </tr>
        <tr>
		<td>Name</td>
		<td colspan="2"><?php  echo $loan['name'];?></td>
	</tr>
        <tr>
		<td>Loan amount</td>
		<td colspan="2"><?php  echo $loan['Amount'];?></td>
	</tr>
        <?php if($this->memtype==1) { ?>
        <tr>
		<td>Purpose</td>
		<td colspan="2"><?php  echo $loan['purpose'];?></td>
	</tr>
        <?php } ?>

                <?php if($this->getgroupmember) { ?>
                    <tr>
                    <th>Member name</th>
                    <th>Amount</th>
                    <th>Purpose</th>
                    </tr>
                    <?php $j=0; foreach($this->getgroupmember as $groupdetails) { $j++;?>
                    <tr>
                    <td><?php echo $groupdetails['memname']; ?></td>
                    <td><?php echo $groupdetails['Amount']; ?></td>
                    <td><?php echo $groupdetails['purposename']; ?>
                        <input type="Hidden" name="rquestid<?php echo $j; ?>" value="<?php echo $groupdetails['requestid'] ?>">
                    </td>
                    </tr>
                    <?php } ?>
                <?php } ?>

                <?php if($this->processnotes) { ?>
                    <tr>
                    <th>Officer name</th>
                    <th>Description</th>
                    <th>Process status</th>
                    </tr>
                    <?php $j=0; foreach($this->processnotes as $processdetails) { $j++;?>
                    <tr>
                    <td><?php echo $processdetails['officername']; ?></td>
                    <td><?php echo $processdetails['process_notes']; ?></td>
                    <td><?php echo $processdetails['statusname']; ?>
                        <input type="Hidden" name="rquestid<?php echo $j; ?>" value="<?php echo $groupdetails['requestid'] ?>">
                    </td>
                    </tr>
                    <?php } ?>
                <?php } ?>

	<?php } ?>
	</table>
</form>
<?php }  ?>
</div>