<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<style type="text/css">
tr#bcolor
{
background-color : silver;
}
</style>
<div class="profile_tab"> 
<?php if(!$this->groupname){ ?>
<!--search form action !-->
<fieldset>
	<legend>Resolution to withdraw money</legend>
		<form action="<?php echo $this->baseUrl();?>/groupresolution" method="POST">
			<table class="fieldsets">
					<tr>
						<td ><label class="mand">Group code:</label></td>
						<td ><? echo $this->form->membercode;?></td>
					</tr>
			</table>
			<input type="submit" name="Search" id="Submit" value="Search">			
		</form>	
</fieldset>
<?php } ?>
</div>

<div class="profile_tab"> 

  <?php if($this->groupname){ ?>
	<?php foreach($this->groupname as $member) : ?>
	<table width="100%">	

<tr><TD><b>Group name :</b><?php echo $member['groupname'];?></TD><td align="right"><b>Date :</b><?php echo date('d-m-Y');?></td></tr>
<tr><TD><br><b>Address &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</b><?php  echo $member['address1'];?></td><td align="right"><b>Group code :</b><?php  echo $member['groupcode'];?></td></tr>
<tr><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php  echo $member['address2'];?></TD></tr>
<tr><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php  echo $member['address3'];?></TD></tr>
<tr><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php  echo $member['city'];?></TD></tr>
<tr><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php  echo $member['state'];?></TD></tr>
<!-- <tr>
       <Td width="30%"><b>Group name : &nbsp;&nbsp;</b><?php  echo $member['groupname'];?><br>
		A<?php  echo $member['address1'];?>,<?php  echo $member['address2'];?>,<?php  echo $member['address3'];?><?php  echo $member['city'];?>,<?php  echo $member['state'];?>.</td>
        <Td align="right"><b>Date : &nbsp;&nbsp;</b><?php echo date('d-m-Y');?></td>
</tr>
<tr>
       <Td width="30%"><b>Group head: &nbsp;&nbsp;</b></td>
	<Td align="right"><b>Group id : &nbsp;&nbsp;</b><?php  echo $member['groupcode'];?></td>
</tr>
<tr>       <Td width="30%"></td>
	<Td align="right"><b>Group Name : &nbsp;&nbsp;</b><?php  echo $member['groupname'];?></td>
</tr>-->

</table>
<?php endforeach; ?>
<br><br>
	<table id="hor-minimalist-b">
<tr>
    	<tr class="tr  brownheading">
		<Th>S.no</Th>
		<Th>Member name</Th>
		<Th>Survey no</Th>
		<Th>Loan request amount</Th>
		<Th>Signature</Th>
</tr>

	<?php $i=0; foreach($this->groupmembers as $memberdetail) : 
?>
purpose - <?php  echo $memberdetail['purposename'];?>&nbsp;&nbsp;&nbsp;&nbsp;bank -<?php  echo $memberdetail['bank'];?>&nbsp;&nbsp;&nbsp;&nbsp;representative1-
<tr>
	<td><?php  echo $i;$i++;?></td>
	<td><?php  echo $memberdetail['membername'];?></td>
	<td><?php  echo $memberdetail['survey_no'];?></td>
	<td><?php  echo $memberdetail['request_amount'];?></td>

</tr>
<?php endforeach ; ?>


</table>

<form action="<?php echo $this->baseUrl();?>/groupresolution/index/pdfgeneration/membercode/<?php echo $this->groupid ?>" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/groupresolution/index/reportdisplay/file/groupresolution<? echo date('Y-m-d');?>.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">

           <BR> <input type="submit" value="PDF" id="submit">
</form><?php 
} ?>

<b style="color:red"><?php echo $this->error;?></b>


</div>
