<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<style type="text/css">
tr#bcolor
{
background-color : silver;
}
</style>
<div class="profile_tab"> 
<?php if(!$this->groupname){ ?>
<!--search form action !-->
<fieldset>
	<legend><?php echo $this->translate("Group Resolution"); ?></legend>
		<form action="<?php echo $this->baseUrl();?>/groupresolution" method="POST">
			<table class="fieldsets">
					<tr>
						<td ><label class="mand"><?php echo $this->translate("Group code:"); ?></label></td>
						<td ><? echo $this->form->membercode;?></td>
					</tr>
			</table>
			<input type="submit" name="Search" id="Submit" value="<?php echo $this->translate("Search"); ?>">			
		</form>	
</fieldset>
<?php } ?>
</div>

<div class="profile_tab"> 
  <?php if($this->groupname){ ?>
	<?php foreach($this->groupname as $member) : ?>
	<table width="100%" border="2" id="hor-minimalist-b">	
	<th colspan="4"><?php echo "<font color=green>";?>Group Resolution</th>

<tr><TD><b><?php echo $this->translate("Group name :"); ?></b><?php echo $member['groupname'];?></TD>
<td align="left"><b><?php echo $this->translate("Date :"); ?></b><?php echo date('d-m-Y');?></td></tr>
<tr><TD><br><b><?php echo $this->translate("Address:"); ?></b><?php  echo $member['address1'];?><?php  echo $member['address2'];?><?php  echo $member['address3'];?>
<br><b><?php echo $this->translate("City"); ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</b><?php  echo $member['city'];?>
<br><b><?php echo $this->translate("Sate"); ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</b><?php  echo $member['state'];?></td>
<td align="left"><b><?php echo $this->translate("Group code :"); ?></b><?php  echo $member['groupcode'];?></td></tr>
</table>
<?php endforeach; ?>
<br><br>

<tr><TD><b><?php echo $this->translate("Bank Name :"); ?></b><?php  echo $member['bankname'];?></TD><br><br>
	<TD><b><?php echo $this->translate("Branch :"); ?></b><?php  echo $member['branchname'];?></TD><br><br>
	<TD><b><?php echo $this->translate("Purpose :"); ?></b><?php  echo $member['purpose'];?></TD><br><br>
	<TD><b><?php echo $this->translate("Group name :"); ?></b><?php  echo $member['groupname'];?></TD><br><br>
	<TD><b><?php echo $this->translate("Loan Request Amount :"); ?></b><?php  echo $member['amount'];?></TD>


</tr>
<br><br>
	<table id="hor-minimalist-b" border="2">
<tr>
		<Th><?php echo $this->translate("S.no"); ?></Th>
		<Th><?php echo $this->translate("Member name"); ?></Th>
		<Th><?php echo $this->translate("Survey no"); ?></Th>
		<Th><?php echo $this->translate("Loan request amount"); ?></Th>
		<Th><?php echo $this->translate("Signature"); ?></Th>
</tr>

	<?php $i=1; foreach($this->groupmembers as $memberdetail) :?>

<tr>
	<td align="center"><?php  echo $i;$i++;?></td>
	<td><?php  echo $memberdetail['membername'];?></td>
	<td align="center" width="15%"><?php  echo $memberdetail['survey_no'];?></td>
	<td width="20%"><?php  echo $memberdetail['request_amount'];?></td>
	<td></td>

</tr>
<?php endforeach ; ?>


</table>

<form action="<?php echo $this->baseUrl();?>/groupresolution/index/pdfgeneration/membercode/<?php echo $this->groupid ?>" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/groupresolution/index/reportdisplay/file/groupresolution<? echo date('Y-m-d');?>.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">

           <BR> <input type="submit" value="<?php echo $this->translate("PDF"); ?>" id="submit">
</form><?php 
} ?>

<b style="color:red"><?php echo $this->error;?></b>


</div>
