<table id="hor-minimalist-b">
    <tr>
        <th>V No.</td>
<!--        <th >A/c number</td>-->
        <th>Transaction Date</td><TH></TH>
        <th width="10">Credit</td><TH></TH><TH></TH>
        <th width="10">Debit</td><TH></TH>
        <th >AccNo. / Ledger Code</td>
        <th>Payment mode / Details</td>
        <th>Transacted by</td>  
    </tr>
    <?php foreach($this->tran as $transaction) : ?>
    <tr>
       <td><?php echo $transaction->id; ?></td>
<!--       <td><?php echo $transaction->number; ?> </td>-->
       <td align="center"><?php echo $transaction->date; ?></td><td></td>
       <?php if ($transaction->cr) {?>
       <td align="right"><?php echo $transaction->cr; ?></td><td></td><td></td>
       <?php } else { ?>
       <td align="right">----</td><td></td><td></td>
       <?php } ?>
       <?php if ($transaction->dt) { ?> 
       <td align="right"><?php echo $transaction->dt; ?></td><td></td>
       <?php } else { ?>
       <td align="right">----</td><td></td>
       <?php } ?>
       <td align="center"><?php echo $transaction->number; ?> </td>
       <td>&nbsp;<?php echo $transaction->mode; echo '  ('; echo $transaction->details; echo ')'; ?></td>
       <td>&nbsp;<?php echo $transaction->name; ?></td>
    </tr>
    <?php endforeach; ?>
</table>

