<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
    <SCRIPT LANGUAGE="JavaScript">
        function Check(chk)
        {
            if(document.myform.Check_All.value=="Check All"){
                for (i = 0; i < chk.length; i++)
                chk[i].checked = true ;
                document.myform.Check_All.value="UnCheck All";
            } else {
                for (i = 0; i < chk.length; i++)
                chk[i].checked = false ;
            document.myform.Check_All.value="Check All";
            }
    }
    </script>
    
    <link rel="stylesheet" href="/Mahiti-OB/ourbank/transactionDayEnd/public/css/styleDay.css" type="text/css" />
    <script type='text/javascript' src='/Mahiti-OB/ourbank/transactionDayEnd/public/javascript/common.js'></script>
    <script type='text/javascript' src='/Mahiti-OB/ourbank/transactionDayEnd/public/javascript/css.js'></script>
    <script type='text/javascript' src='/Mahiti-OB/ourbank/transactionDayEnd/public/javascript/standardista-table-sorting.js'></script>
    </head>
    <body>
        <form action="<?php echo $this->baseUrl();?>/maintenance/dayend/" method="POST" name="myform">
	   <table class='sortable' id = "hor-minimalist-b">
		<thead>
                    <tr>
			<th>Tr No.</th>
                        <th >A/c From</th>
                        <th>Transaction Date</th>
                        <th>Creidt</th>
                        <th>Debit</th>
                        <th>Transaction Mode</th>
                        <th>Transacted By</th>  
                        <th><input type="button" name="Check_All" value="Check All" onClick="Check(document.myform)" class="NormalBtn"></th>
		  </tr>
		</thead>

		<tbody>
                    <?php  $i = 0; ?>
                    <?php foreach($this->paginator  as $transaction) : ?>
	            <tr>
                        <?php $i++; ?>
                        <td><?php echo $transaction->transaction_id;?></td>
                        <td><?php echo $transaction->account_number;?> </td>
                        <td><?php echo $transaction->transaction_date;?></td>
                        <?php if($transaction->amount_to_bank == 0.00) { ?>
                            <td>----</td>
                        <?php } else { ?>
                            <td><?php echo $transaction->amount_to_bank;?></td>
                        <?php } ?>
                        <?php if($transaction->amount_from_bank == 0.00) { ?>
                            <td>----</td>
                        <?php } else { ?>
                            <td><?php echo $transaction->amount_from_bank;?></td>
                        <?php } ?>
                        <td><?php echo $transaction->name;?></td>
                        <td><?php echo $transaction->login_name;?></td>
                        <input type = "hidden" name = "totalVNo" value = "<?php echo $i;?>">
                        <td><input type="checkbox" name="VoucherNo<?php echo $i?>" value="<?php echo $transaction->transaction_id;?>"></td>
                    </tr>
                    <?php endforeach; ?>
                    <tr>
	           <td colspan="10"><input type = "submit" name = "DayEndProcess" id= "DayEndProcess" value = "Day End Process"></td>
                </tr>
		</tbody>
	   </table>

	</form>
    </body>
</html>
