<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->



<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/meeting.js"></script>

<div id = "searchDiv">
<fieldset>
<legend>Edit meeting</legend>
    <form action="<?php echo $this->baseUrl();?>/officemeeting/index/meetingedit/meeting_id/<?php echo $this->meeting_id;?>" method="POST">
        <table class="fieldsets">
            <tr>
                <TD colspan="2" align="right"><a href="<?php echo $this->baseUrl();?>/officemeeting/index/meetingdelete/meeting_id/<?php echo $this->meeting_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a>
                </TD>
            </tr>
            <TR >
                <TD ><label for="fld1" class="mand">Meeting name</TD>
                <TD ><?php echo $this->meetingForm->meeting_name;?></TD>
            </TR>
            <TR >
                <TD ><label for="fld1" class="mand">Office level</TD>
                <TD ><?php echo $this->meetingForm->institute_bank_id;?></TD>
            </TR>
            <TR >
                <TD ><label for="fld1" class="mand">Office</TD>
                <TD ><div id="groupDiv"><?php echo $this->meetingForm->group_name;?></div><SPAN style="color:red"><?php echo $this->startMsg;?></SPAN></TD>
            </TR>

            <TR >
                <TD ><label for="fld1" class="mand">Meeting place</TD>
                <TD ><?php echo $this->meetingForm->meeting_place;?></TD>
            </TR>

            <TR >
                <TD ><label for="fld1" class="mand">Meeting Frequency</TD>
                <TD ><?php echo $this->meetingForm->meeting_day;?></TD>
            </TR>
        </table>
        <div class="btnhouse">
            <div class="ltbtns">
            <?php echo $this->meetingForm->Submit;?>
            </div>
            <div class="rtbtns">
            <a href="<?php echo $this->baseUrl();?>/officemeetingcommonview/index/index/meeting_id/<? echo $this->meeting_id; ?>"><?php echo $this->meetingForm->Back;?></a>
            </div>
        </div>
    </form>
</fieldset>
</div>
