<script>
$(document).ready(function() {
$('.show').click(function(){
var groupid = $(this).val();
        if($('input[name=group_'+groupid+']').is(':checked')){
            $('tr[name=row_'+groupid+']').show();
         } else {
            $('tr[name=row_'+groupid+']').hide();
       }

});
});
</script> 
<?php 
if($this->groups) { 
foreach($this->groups as $groups){
$dbobj = new Kootadefault_Model_Kootadefault();
$groupmembers =  $dbobj->getmemberdetails($groups['id']);
?>
    <table  id="hor-minimalist-s" >
        <tr>
            <th bgcolor="Silver" align="center" width="40%"><b>Group name</b></th>
            <th bgcolor="Silver" align="center" width="30%"><b>Group members </b></th>
        </tr>
                <td colspan="5">
                    <input type="checkbox" name="group_<?php echo $groups['id'];?>" id="<?php echo $groups['id'];?>" class="show"  value="<?php echo $groups["id"];?> "><? echo $groups["name"];?>
                </td>
        </tr>
<?php 
foreach($groupmembers as $groupmember){
?>
            <tr style="display: none" name="row_<?php echo $groupmember['group_id'];?>">
            <td></td>
            <td width="20%">
                <input type="checkbox" name="member_id[]" class="familymember" value="<?php echo $groupmember['group_id'];?>_<?php echo $groupmember["representative_id"];?>" ><?php echo $groupmember["membername"];?>
            </td>
            </tr>

        <?php } }
?>
    </table>
<?php  } else {
       echo "<font color='RED'>No Groups in the koota you seleted</font>";
 } ?>
