<head>
<script>
    var current =0;
    function addPerson() {
    current++;
    var id = document.getElementById("id").value;
     $(".hor-minimalist-b").append("<tr id=row"+id+"><td><input type='text' size='4' name='period_ofrange_monthfrom"+id+"' id='from" + id + "' class = 'txt_put'></td><td><input type='text' size='4' name='period_ofrange_monthto"+id+"' id='to" + id + "' class = 'txt_put'></td><td><input type='text' size='4' name='Interest"+id+"' id='rate" + id + "' class = 'txt_put'><td><a href='#' onClick='removeFormField(\"#row" + id + "\"); return false;'><img src='<? echo $this->baseUrl(); ?>/images/delete.gif'  border=0 width='16' height='16'></a></td></tr>");

    document.myform.memberCount.value = id;   
    id = (id - 1) + 2;
    document.getElementById("id").value = id;
    }
    $(document).ready(function(){
    $('#addPerson').click(addPerson)
   });

    function removeFormField(id) {
        $(id).remove();
    }
</script>
</head> 
<form action="<?php echo $this->baseUrl();?>/loans/index/loansedit/id/<?php echo $this->offerproduct_id;?>" method="POST" name= "myform">
  
        <div class="register">
            <div class="profile_tab">

            <table id="hor-minimalist-b" class="fieldsets">
                <tr><Th><b>Edit Loan</b></Th><th></th><th></th><th></th></tr>
                <TR>
                    <TH>Product Details</th>
                    <TH></TH>
                    <TH></TH>
                    <TH></TH>
                 </TR>
                <TR>
                    <TD><label class="mand required">Product Type</label></TD>
                    <TD><?php echo $this->form->product_id;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD  style="width:350px; !important"><label class="mand required">Productname</TD>
                    <TD><?php echo $this->form->offerproductupdate_id;echo $this->form->offerproductname;?></TD>
                    <TD  style="width:200px; !important"><label class="mand required">ShortName</TD>
                    <TD><?php echo $this->form->offerproductshortname;?></TD>
                </TR>
                <TR>
                    <TD><label class="mand required">Description</TD>
                    <TD><?php echo $this->form->offerproduct_description;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TH>Date</TH>
                    <TH></TH>
                    <TH></TH>
                    <TH></TH>
                 </TR>

                <TR>
                    <TD><label class="mand required">BeginDate</TD>
                    <TD><?php echo $this->form->begindate;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD><label class="mand required">CloseDate</TD>
                    <TD><?php echo $this->form->closedate;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD><label class="mand required">applicableTo</TD>
                    <TD><?php echo $this->form->applicableto;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
              <!--  <TR>
                    <TD><label class="mand">GL subcode</TD>
                    <TD><?php //echo $this->form->glsubcode_id;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>-->
                <TR>
                    <TH>loanAmount</TH>
                    <TH></TH>
                    <TH>Installments</TH>
                    <TH></TH>
                 </TR>
                <TR>
                    <TD><label class="mand">Minimum</TD>
                    <TD><?php echo $this->form->minmumloanamount;?></TD>
                    <TD><label class="mand">Minimum</TD>
                    <TD width="20"><?php echo $this->form->minimumfrequency;?></TD>
                </TR>
                <TR>
                    <TD><label class="mand">Maximum</TD>
                    <TD><?php echo $this->form->maximunloanamount;?></TD>
                    <TD><label class="mand">Maximum</TD>
                    <TD><?php echo $this->form->maximumfrequency;?></TD>
                </TR>
                <TR>
                    <TH>Penal Fee</TH>
                    <TH></TH>
                    <TH>Interest type</TH>
                    <TH></TH>
                 </TR>
                <TR>
                    <td><label class="mand">Penal Fee</td>
                    <TD><?php echo $this->form->penal_Interest;?></TD>
                    <TD><label class="mand">Interest type</TD>
                    <TD><?php echo $this->form->interesttype_id;?></TD>
                </TR>
                    <tr> 
                        <TD ><label class="mand">Penal glsubcode</TD>
                        <td><? echo $this->form->fee_glsubcode_id;?></td>
                        <TD ><label class="mand">Interest glsubcode</TD>
                        <td><? echo $this->form->interest_glsubcode_id;?></td>
                    </tr>
                <TR>
                    <TH>GracePeriod</TH>
                    <TH></TH>
                    <TH>InterestRates</TH>
                    <TH></TH>
                 </TR>
                <tr> 
                    <TD><label class="mand">GracePeriod</TD>
                    <TD><?php echo $this->form->graceperiodnumber;?></TD>
                    <td>
                        <input type="hidden" name="memberCount" id="memberCount" value=""  class="textfield" />
                        <table id="hor-minimalist-b" style="width:200px; !important">
                            <tr class="tdbrownheading"> 
                               	<Th width="10%">From</Th>
                                <Th width="5%">To</Th>
                                <Th width="3%">Rate</Th>
                                <th></th>

                            </tr>
                            <?php $count1 = 0; ?>
                <?php foreach($this->interest1 as $loan) { ?>
                        <?php $count1++; ?>
                        <input type = "hidden" name = "count1" value = " <?php echo $count1; ?>">
                        <input type = "hidden" name = "Interestperiod_id1<?php echo $count1?>" value = " <?php echo $loan->Interestperiod_id; ?>">
                            <tr id="row<? echo $count1;?>">
                            <td><input name ="period_ofrange_monthfrom<?php echo $count1?>" type="text" 
                                        value="<?php echo $loan['period_ofrange_monthfrom'];?>" size="4" class="txt_put">
                            </td>
                            <td><input name ="period_ofrange_monthto<?php echo $count1?>" type="text" 
                                        value="<?php echo $loan['period_ofrange_monthto'];?>" size="4" class="txt_put">
                            </td>
                            <td><input name ="Interest<?php echo $count1?>" type="text" 
                                        value="<?php echo $loan['Interest'];?>" size="4" class="txt_put">
                            </td>
                            <td><? if($count1>1) { ?>
                                <a href='#' onClick='removeFormField("#row<?php echo $count1?>"); return false;'> <img src='<? echo $this->baseUrl(); ?>/images/delete.gif'  border=0 width='16' height='16'><br></a> 
                                <? } ?></td>
                            </tr>
                <?php } ?>
                    <input type="hidden" id="id" value="<?php echo $count1+=1;?>">
                            </table>
                        <table id="hor-minimalist-b" class="hor-minimalist-b" style="width:200px; !important"></table>
                            <input type="button" id="addPerson" class="officebutton" value="addTerm">
                         </td>
                    <td></td>
                </tr>
                <TR>
                    <TD><input name="Update" type="submit" class="officebutton" value="Update"></TD>
                      <TD><a href="<?php echo $this->baseUrl(); ?>/loans/index">
                    <input name="submit" type="submit" class="officebutton" value="back"></a></td>
                </TR>
        </table>
            <div><?php echo $this->datesinfo; ?><?php echo $this->amounts; ?><?php echo $this->freequency; ?></div>
        <center style="color:red"><?php echo $this->updateerror; ?></center>
</div>
</div>

</form>
