<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
function getgroups(branch,path) {
	if(branch) {
		targeturl=path+"/cashscroll/index/group?branch="+branch;
		$.ajax({ url: targeturl, success: function(data){ $("#groupdiv").html(data) }});
	}
}
function Getofficer(branch,path) {
	if(id) { alert(hi);
		targeturl=path+"/overduelist/index/getloanofficer?id="+id;
		$.ajax({ url: targeturl, success: function(data){ $("#loandiv").html(data) }});
	}
}

$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});

</script>


<?php if(!$this->loanView){ ?>
<div id="searchDiv">
<form action="<?php echo $this->baseUrl();?>/overduelist" method="POST">
                    <TABLE id="hor-minimalist-b">
					<th colspan="4">Overdue List</th>
  					<tr>	<TD><label class="mand"><?php echo $this->translate('Hierarchy'); ?></label></TD>
                            <TD id="show"><?php echo $this->form->hierarchy;?></TD>
							<TD></TD><TD></TD>
  					</tr>
                    <tr>
                        	<td class="mand">Branch:</td>
                        	<td ><div id="statediv"><? echo $this->form->bank_id;?></div></td>
                            <td class="label">Date:</td>
                            <td ><? echo $this->form->datefrom;?></td>
                    </tr>
					<tr id="hide"><TD><label class="mand"><?php echo $this->translate('Group'); ?></label></td>
                            <td><div id="groupdiv"><?php echo $this->form->group;?></td>
			                <TD>Loan officer:</TD>
                        	<TD id="loandiv"><? echo $this->form->loanofficer;?></TD>
					</tr>
                	<tr><TD><input type="submit" name="Search" id="Submit" value="Search"></TD><td></td><td></td></tr>
                    </TABLE>
</form>
    </div>
<?php }  ?>

<?php if($this->loanView) { ?>

	<div class="cont-rgt-data">


 	<h5 align="right"><?php echo $this->translate('As of '); echo "<font color='#045'>".$this->dat."</font>"; ?></h5><br>
 	<?php if($this->bankname){?><h5 align="right"><?php echo $this->translate('Branch name '); echo "<font color='#045'>".$this->bankname."</font>"; ?></h5><? } ?><br>
 	<?php if($this->officername){?><h5 align="right"><?php echo $this->translate('Loan officer '); echo "<font color='#045'>".$this->officername."</font>"; ?></h5><? } ?>
       <br>
       <h5 style="text-align:right"><?php echo $this->translate('* Amount in '); ?><font color="red"><?php echo $this->translate('Rs'); ?></font></h5>
            <TABLE id="hor-minimalist-b" summary="">
                <tr>
                    <th class="label1"><?php echo $this->translate('Account Number'); ?></th>
                    <th class="label1"><?php echo $this->translate('Name'); ?></th>
                    <th class="label1"><?php echo $this->translate('Number of overdue'); ?></th>
                    <th class="label1"><?php echo $this->translate('Age(in days)'); ?></th>
                    <th class="label1"><?php echo $this->translate('OverDue Amount'); ?></th>
	        	</tr>
<?php
$outstanding_amount=0;
 foreach($this->loanView as $loandue) {
$outstanding_amount+=$loandue['overdue'];

?>
		<tr>
	            <td><?php echo $loandue['account_number']; ?></td>
                    <td><?php echo $loandue['name']; ?></td>
                     <td class="label1" align="center"><?php echo $loandue['totalinstallments']; ?></td>
		     <td class="label1" align="center"><?php echo $this->dateconvertor->dateDiff($loandue['installment_date'], $this->asofdate)?></td>
                    <td class="label" align="right"><?php echo sprintf("%4.2f",$loandue['overdue']); ?></td> 
                </tr>
<?php } ?>
                <tr>
                    <td><?php echo $this->translate('Total'); ?></td>
                    <td></td><td></td><td></td>
                    <td class="label" align="right"><?php echo sprintf("%4.2f",$outstanding_amount);  ?></td>
                </tr>
</TABLE>
</div>

<br>

<form action="<?php echo $this->baseUrl(); ?>/overduelist/index/pdftransaction" method="POST" onClick="window.open('<?php echo $this->baseUrl(); ?>/overduelist/index/reportdisplay/file/overduelist.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
<!-- <form action="<?php echo $this->baseUrl(); ?>/reports/loandue/pdftransaction" method="POST"> -->
           <TABLE>     <tr>
                    <td><input type="submit" name="pdf" value="PDF">
                    <input type="hidden" name="field1" value="<?php echo $this->asofdate; ?>">
                    <input type="hidden" name="field2" value="<?php echo $this->bankid;?>">
                    <input type="hidden" name="field3" value="<?php echo $this->loanofficerid;?>">
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr></TABLE>

</form>
<?php } ?>
