<?php if($this->loanView) { ?>
</fieldset>
	<div class="cont-rgt-data">


 	<h5 align="right"><?php echo $this->translate('As of '); echo "<font color='#039'>".$this->date1."</font>"; ?></h5>
 	<?php if($this->bankname){?><h3 align="right"><?php echo $this->translate('Bank name '); echo "<font color='#039'>".$this->bankname."</font>"; ?></h3><? } ?>
 	<?php if($this->officername){?><h5 align="right"><?php echo $this->translate('Loan officer '); echo "<font color='#039'>".$this->officername."</font>"; ?></h5><? } ?>
       <br>
       <h5 style="text-align:right"><?php echo $this->translate('* Amount in '); ?><font color="red"><?php echo $this->translate('Rs'); ?></font></h5>
            <TABLE id="hor-minimalist-b" summary="">
                <tr>
                    <th class="label1"><?php echo $this->translate('Account Number'); ?></th>
                    <th class="label1"><?php echo $this->translate('Name'); ?></th>
                    <th class="label1"><?php echo $this->translate('Number of overdue'); ?></th>
                    <th class="label1"><?php echo $this->translate('Age(in days)'); ?></th>
                    <th class="label1"><?php echo $this->translate('OverDue Amount'); ?></th>
	        	</tr>
<?php
$outstanding_amount=0;
 foreach($this->loanView as $loandue) {
$outstanding_amount+=$loandue['overdue'];

?>
		<tr>
	            <td><?php echo $loandue['account_number']; ?></td>
                    <td><?php echo $loandue['name']; ?></td>
                     <td class="label1" align="center"><?php echo $loandue['totalinstallments']; ?></td>
		     <td class="label1" align="center"><?php echo $this->dateconvertor->dateDiff($loandue['installment_date'], $this->field1)?></td>
                    <td class="label" align="right"><?php echo sprintf("%4.2f",$loandue['overdue']); ?></td> 
                </tr>
<?php } ?>
                <tr>
                    <td><?php echo $this->translate('Total'); ?></td>
                    <td></td><td></td><td></td>
                    <td class="label" align="right"><?php echo sprintf("%4.2f",$outstanding_amount);  ?></td>
                </tr>
</TABLE>
</div>

<br>

<?php } ?>

