<?php if(!$this->result && !$this->groupresult) { ?>
<div id="searchDiv">
<fieldset>
	<legend>Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/thumbdeclaration/index" method="POST">
			<table class="fieldsets">
                            <TR>
                                <TD><label class="mand">Group code:</label></TD>
                                <TD><? echo $this->form->membercode;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <input type="Submit" name="Submit" value="Search">

                            </div>
                        </div>
	 </form>

</fieldset>
</div>

<?php }
else { echo "<font color=red>".$this->errormsg."</font>"; } ?>

<?php if($this->groupresult){
$results = $this->groupresult;
foreach($results as $result) {  $dateconvert= new App_Model_dateConvertor();?>

    <table id="hor-minimalist-b" width="100%">
	<th colspan="4">Thumb impression declaration</th>
        <br>

		<tr><TD colspan="2">Bank :<?php echo "<font color=green>".$result['bankname']."</font>"?></TD><TD></TD></tr>
		<tr><TD colspan="2">Branch :<?php echo "<font color=green>".$result['branchname']."</font>"?></TD><TD></TD></tr>

    <tr><td colspan="4" align="center"><b>Thumb impression Declaration</b></td></tr>

	<tr><TD >
    <p align="justify"> I hereby declare that Smt/sri <?php echo "<font color=green>".$result['membername']."</font>"?> has given the thumb impression in the presence of me and his mother tongue ___________________________</p></td>
    <tr>

	<tr><TD>DATE :<?php echo "<font color=green>".date('d-m-Y')."</font>"?></TD><TD align="left">Yours sincerely</TD></tr>
	</table>

<?php  } }  ?>





