<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<head>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-1.3.2.js"></script>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/meetingbook.js"></script>
<script>
$(document).ready(function() {
    $('#myform').submit(function(e) {
        var isValid = true;
        $(this).find(':text.required').each(function() {
            if($(this).val().replace(/^\s+|\s+$/g,"") == "") {
                isValid = false;
                if($(this).next('span').length == 0 ) {
                    $(this).after('<span style="color: #FF0000"><br>Required</span>');
                }
                e.preventDefault();
                return;
            } else {
                if($(this).next('span').length < 0 )
                    $(this).next('span').remove();
            }
        });
//for madatory
        $(this).find(':text.numeric').each(function() {
            var regex = new RegExp(/^[1-9][0-9]*$/);
        // var regex = new RegExp('[-+]?\b[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?\b'); // float and numeric
            if(!regex.test($(this).val()) && isValid) {
                isValid = false;
                if($(this).next('span').length == 0 ) {
                   $(this).after('<span style="color: #FF0000">Numeric  only.</span>');
                }r float
                e.preventDefault();
                return;
            } else {
                if($(this).next('span').length > 0  && isValid)
                    $(this).next('span').remove();
            }
        });
//for non madatory
$(this).find(':text.numeric1').each(function() {
          var regex = new RegExp(/^[1-9][0-9]*$/);
            // var regex = new RegExp('[-+]?\b[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?\b');  //float and numeric
          if(!regex.test($(this).val()) && $(this).val() != "") {
              if($(this).next('span').length == 0 ) {
                 $(this).after('<span style="color: #FF0000">Numeric  only.</span>');
              }
              e.preventDefault();
              return;
          } else {
                  $(this).next('span').remove();
          }
      });

		

    });
});



    var current =0;
    function addPerson() {
        current++;
        var id = document.getElementById("id1").value; 
        $(".hor-minimalist-b1").append("<tr id=row"+id+"><td><select name = 'discussionlist[]'><?php foreach($this->discussionlist as $discussionlist){?><option value='<?php echo $discussionlist['id']?>'><?php echo $discussionlist['name']?></option><?php } ?></select> </td><td><a href='#' onClick='removeFormField(\"#row"+id+"\"); return false;'><img src='<? echo $this->baseUrl(); ?>/images/delete.gif'  border=0 width='16' height='16'></td><br></a></td></tr>");

        document.myform.memberCount.value = id;
        id1 = (id1 - 1) + 2;
        document.getElementById("id1").value = id;
    }
    $(document).ready(function(){  $('#adddiscussion').click(addPerson)    });

    function removeFormField(id1) { $(id1).remove();   }


    var current1 =0;
    function addPerson2() {
        current1++;
        var id = document.getElementById("id2").value;
        $(".hor-minimalist-b2").append("<tr id=row"+id+"><td><select name = 'decisionlist[]'><?php foreach($this->decissionlist as $decissionlist){?><option value='<?php echo $decissionlist['id']?>'><?php echo $decissionlist['name']?></option><?php } ?></select> </td><td><a href='#' onClick='removeFormField(\"#row"+id+"\"); return false;'><img src='<? echo $this->baseUrl(); ?>/images/delete.gif'  border=0 width='16' height='16'></td><br></a></td></tr>");

        document.myform.memberCount.value = id;
        id2 = (id2 - 1) + 2;
        document.getElementById("id2").value = id;
    }
    $(document).ready(function(){  $('#adddecision').click(addPerson2)    });

    function removeFormField(id2) { $(id2).remove();   }

</script>
<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }
em { font-weight: bold; padding-right: 1em; vertical-align: top; }
</style>
</head> 
<div id = "searchDiv">

<form name="myform" id="myform" action="<?php echo $this->baseUrl();?>/meetingbook/index/attendanceadd/attendance_id/<?php echo $this->attendance_id;?>" method="POST">
        <table id="hor-minimalist-b">

            <TR >
                <th colspan='4'><label for="fld1" class="mand"><?php echo $this->translate("Meeting Information"); ?></th>
            </TR>

            <TR >
                <TD style="width:34%; vertical-align:top; !important;"><br><label for="fld1" class="mand"><?php echo $this->translate("Meeting name"); ?></TD>
                <TD style="vertical-align:top; !important;"><?php echo $this->attendanceform->meeting_name;?></TD>
                <td></td>
                <td></td>
            </TR>

        <tr><td colspan="4"><div id="statediv1"></div></td></tr>

            <TR >
                <TD><label for="fld1" class="mand"><?php echo $this->translate("Meeting held date"); ?></TD>
                <TD><?php echo $this->attendanceform->meeting_date;?></TD>
                <TD><label for="fld1" class="mand"><?php echo $this->translate("Meeting held Time"); ?></TD>
                <TD><?php echo $this->attendanceform->meeting_time;?></TD>
            </TR>

           <tr><TD colspan="4">
                    <div id="statediv"></div>
	   </TD></tr>

            <TR style="border-bottom: 4px solid #CBCBCB;">
                  <th colspan='4' style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Discussions and Savings"); ?></th>
            </TR>

            <tr>
                <td style="vertical-align:top; !important;">Discussion</td>
                <td style="width:40%; vertical-align:top; border-right: solid 1px #CBCBCB; !important;"><input type="hidden" id="id1" value="1">
                     <input type="hidden" name="memberCount" id="memberCount" value=""  class="textfield" />
                        <table id="hor-minimalist-b" style="width:200px; !important">
                          <tr> <td>
		                <select name = "discussionlist[]">
		            	<option value=" ">select</option> 
		            	<?php foreach ($this->discussionlist as $discussionlist) { ?>
		           	 <option value="<?php echo $discussionlist['id']?>"><?php echo $discussionlist['name']?></option>
		            	<?php } ?>
		        	</select>
                                </td>
				<td>&nbsp;</td> 
				</td>
			     <td></td>
			   </tr>
                         </table> 
                            <table id="hor-minimalist-b" class="hor-minimalist-b1" style="width:200px; !important"></table>
                            <br>
                            <input type="button" id="adddiscussion" class="officebutton1" value="Add">
		  </td>

                <td style="vertical-align:top; !important;">Decision</td>
		<td style="width:40%; vertical-align:top; !important;">
                    <input type="hidden" id="id2" value="2">
                     <input type="hidden" name="memberCount" id="memberCount" value=""  class="textfield" />
                       <table id="hor-minimalist-b" style="width:200px; !important">
                        <tr> 	<td>
					<select name = "decisionlist[]">
				    	<option value=" ">select</option> 
				    	<?php foreach ($this->decissionlist as $decisionlist) { ?>
				   	 <option value="<?php echo $decisionlist['id']?>"><?php echo $decisionlist['name']?></option>
				   	 
				    	<?php } ?>
					</select>
                               	</td>
				<td>&nbsp;</td> 
				</td>
			     <td></td>
			   </tr>
                         </table> 
                            <table id="hor-minimalist-b" class="hor-minimalist-b2" style="width:200px; !important"></table>
                            <br>
                            <input type="button" id="adddecision" class="officebutton2" value="Add">
		</td>
            </tr>
            <TR>
                <TD><?php echo $this->translate("Notes"); ?></TD>
                <TD><?php echo $this->attendanceform->notes;?></TD>
                <TD><?php echo $this->translate("Resolution"); ?></TD>
                <TD><?php echo $this->attendanceform->resolution;?></TD>
            </TR>

        </table>

        <div class="btnhouse">
            <div class="ltbtns">
                <input type="Submit" name="Submit" name="Submit" value="<?php echo $this->translate('Submit'); ?>">
            </div>
            <div class="rtbtns">
                <a href="<?php echo $this->baseUrl();?>/attendanceindex"><input type="button" value="<?php echo $this->translate('Back'); ?>"></a>
            </div>
        </div>
    </form>

</div>
<?php echo $this->result; ?>
