<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<?php if($this->members) { $count = count($this->members); ?>
	<table id="hor-minimalist-b"> 

            <TR style="border-bottom: 4px solid #CBCBCB;">
                <th colspan='3' style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Attendance Details"); ?></th>
                <th colspan='3' style="border-right: solid 1px #CBCBCB; text-align:center; !important;"><?php echo $this->translate("Savings"); ?></th>
                <th colspan='3' style="border-right: solid 1px #CBCBCB; text-align:center; !important;"><?php echo $this->translate("Loans"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; text-align:center; !important;"><?php echo $this->translate("Total"); ?></th>
            </TR>

            <TR >
                <th style="width:0.5%; border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("No."); ?></th>
                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Members"); ?></th>
                <th style="width:1%;border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Absent/Late"); ?></th>


                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Balance"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("To be pay"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Paid"); ?></th>

                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Outstanding"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Due"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Paid"); ?></th>
                <th style="border-right: solid 1px #CBCBCB; !important;"><?php echo $this->translate("Paid"); ?></th>
            </TR>
<? $no=1;  $Topay=0; $currentbalance1=0; $currentbalance2=0; 
$currentbalance3=0; $loandue1=0; $loandue2=0; $currentpay=0;
//                     echo '<pre>'; print_r($this->members);
                foreach($this->members as $members) { $memberaccid=$members['group_id']; } 
                    //fetch group savings a/c no.
                    $currentbalance=new Meetingbook_Model_Attend();
                    $memberaccNum=$currentbalance->fetchaccNum($memberaccid);
                    ?>
             <input type="hidden" name="accNum" value="<?php if($memberaccNum) { echo $memberaccNum[0]['account_number']; } else {  echo ''; } ?>">
<?php
$totalmembers=count($this->members);
 foreach($this->members as $members) {
    $absent=$members['penalty_notcoming'];        $late=$members['penalty_latecoming'];
    $latesucode=$members['late_subglcode'];       $absntsubcode=$members['absent_subglcode']; 
  ?>
                    <input type="hidden" name="absentfee" value="<?php echo $absent;?>">
                    <input type="hidden" name="latefee" value="<?php echo $late;?>">
                    <input type="hidden" name="absentglsubcode" value="<?php echo $absntsubcode;?>">
                    <input type="hidden" name="lateglsubcode" value="<?php echo $latesucode;?>">

    <TR>
        <td><? echo $no;?> </td>
        <td><? echo $members['membername'];?> </td>
        <td>

<?php for($i=0;$i<sizeof($this->val);$i++)
     {
            $string_exploded = explode('_',$this->val[$i]);
            if($string_exploded[0]==$members['memberid']) 
            { ?>
                <?php if($string_exploded[1]=='1') {  ?>
                    <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'absent'.$members['id']; ?>" 
                    value="<?php echo 'absent_'.$no;?>" onchange="return absent(<?php echo $absent;?>,<?php echo $members['id'];?>);" checked="">
                    <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'late'.$members['id']; ?>" value="<?php echo 'late_'.$no;?>" onchange="return late(<?php echo $late;?>,<?php echo $members['id'];?>);">
                    <input type="text" class="totfee <?php echo 'fee'.$members['id']; ?>" id="<?php echo 'fee'.$members['id']; ?>" name="fee[]" readonly value="<?php echo $absent.'.00';?>"  size="2px">
                <?php }  ?>
                <?php if($string_exploded[1]=='2') { ?>
                    <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'absent'.$members['id']; ?>" 
                    value="<?php echo 'absent_'.$no;?>" onchange="return absent(<?php echo $absent;?>,<?php echo $members['id'];?>);">
                    <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'late'.$members['id']; ?>" value="<?php echo 'late_'.$no;?>" onchange="return late(<?php echo $late;?>,<?php echo $members['id'];?>);" checked="">
                    <input type="text" class="totfee <?php echo 'fee'.$members['id']; ?>" id="<?php echo 'fee'.$members['id']; ?>" name="fee[]" readonly value="<?php echo $late.'.00';?>"  size="2px">
                <?php }  ?>
        <?php //} else { ?>

<!--        <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'absent'.$members['id']; ?>" 
        value="<?php echo 'absent_'.$no;?>" onchange="return absent(<?php echo $absent;?>,<?php echo $members['id'];?>);">
        <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'late'.$members['id']; ?>" value="<?php echo 'late_'.$no;?>" onchange="return late(<?php echo $late;?>,<?php echo $members['id'];?>);">
        <input type="text" class="totfee <?php echo 'fee'.$members['id']; ?>" id="<?php echo 'fee'.$members['id']; ?>" name="fee[]" readonly value=""  size="2px">-->

        <?php } ?>



<?php } ?>
        </td>




        <?php //if($string_exploded[1]=='') { ?>

<!--        <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'absent'.$members['id']; ?>" 
        value="<?php echo 'absent_'.$no;?>" onchange="return absent(<?php echo $absent;?>,<?php echo $members['id'];?>);">
        <input type="radio" name="<?php echo $members['id']; ?>"  id="<?php echo 'late'.$members['id']; ?>" value="<?php echo 'late_'.$no;?>" onchange="return late(<?php echo $late;?>,<?php echo $members['id'];?>);">
        <input type="text" class="totfee <?php echo 'fee'.$members['id']; ?>" id="<?php echo 'fee'.$members['id']; ?>" name="fee[]" readonly value=""  size="2px">-->

         <?php //}  ?>


        <td style="text-align:right;">    <?php $memberid=$members['memberid']; 
                    $creditbalance=$currentbalance->creditbalance($memberid);
                    $debitbalance=$currentbalance->debitbalance($memberid); 
                  if($creditbalance) { 
                           if($debitbalance) { $debitbalance1=$debitbalance; } else { $debitbalance1=0; }
                        $currentbalance1=$creditbalance[0]['currentbalance']-$debitbalance1[0]['currentbalance'];
                     echo $currentbalance1;  }  $currentbalance2+=$currentbalance1;  ?>
        </td>
        <td style="text-align:right;"><?php echo $members['saving_perweek'];?></td>  

        <td>
        <?php //print_r($this->savingsdetails);
            if($memberaccNum) { 
                    foreach($this->savingsdetails as $savingsdetails){
              if($savingsdetails['member_id']==$members['memberid']) { 
        ?>
        <input type="text" id="<?php echo 'amount'.$members['id']; ?>" class="savingspaid numeric1" name="savingspaid[]"  value="<?php echo $savingsdetails['transaction_amount']; ?>"  size="5px" onkeyup = "calsavings(this.value),calculatetotalpaid(<?php echo $members['id']; ?>);">
        <?php } } } else { ?>
        <input type="text" id="<?php echo 'amount'.$members['id']; ?>" class="savingspaid" name="savingspaid[]"  value=""  size="5px" onkeyup = "calsavings(this.value),calculatetotalpaid(<?php echo $members['id']; ?>);" readonly>
        <?php } ?>
        </td>

        <td style="text-align:right;">    
                <?php  
                    $loanoutstanding=$currentbalance->loanoutstanding($memberid);
                  if($loanoutstanding) { 
                        echo $loanoutstanding[0]['outstanding'];
                         $loanoutstanding1=$loanoutstanding[0]['outstanding'];
                        }
                       $currentbalance3+=$loanoutstanding1;  ?>
        </td>
        <td style="text-align:right;"> <?php
                    $loandue=$currentbalance->loandue($memberid); 
                  if($loandue) { 
                        echo $loandue[0]['outstanding'];
                         $loandue1=$loandue[0]['outstanding'];
                        }
                       $loandue2+=$loandue1;  ?></td>
        <td style="text-align:right;">
        <?php 
                if($loanoutstanding[0]['account_number']) { 
                    foreach($this->savingsdetails as $savingsdetails){
              if($savingsdetails['member_id']==$members['memberid']) { ?>
          <input type="text" name="loanpaid[]" size="5px" class="loandue numeric1" id="<?php echo 'loandue'.$members['id'] ?>" value="<?php echo $savingsdetails['transaction_amount']; ?>" onkeyup = "calculateSum(this.value),calculatetotalpaid(<?php echo $members['id']; ?>);">
            <input type="hidden"  name="loanaccNum[]" value="<?php echo $loanoutstanding[0]['account_number']; ?>"> 
        <?php } } } else { ?>
          <input type="text" name="loanpaid[]" size="5px" class="loandue" id="<?php echo 'loandue'.$members['id'] ?>" readonly value="" onkeyup = "calculateSum(this.value),calculatetotalpaid(<?php echo $members['id']; ?>);">
            <input type="hidden"  name="loanaccNum[]" value="<?php echo $loanoutstanding[0]['account_number']; ?>"> 
        <?php } ?>
        </td>
        <td style="text-align:right;">
          <input type="text" name="totalpaid[]" readonly size="5px" class="totalpaid" value="" id="<?php echo 'totalpaid'.$members['id']; ?>"  onfocus="overalltot(this.value);"> 
        </td>
    </TR>
<? $no++; $Topay+=$members['saving_perweek']; }  ?>
<input type="hidden" name="length" value="<?php echo $no;?>">
    <TR>
        <td></td>
        <td></td>

        <td><input type="text" readonly size="2px" id="totalfee" value=""></td>
        <td style="text-align:right;"><?php echo $currentbalance2; ?></td>
        <td style="text-align:right;"><?php echo $Topay; ?></td> 
        <td><input type="text" readonly size="5px" name="totsavingspaid" class="saveamount" value=""></td>
        <td style="text-align:right;"><?php echo $currentbalance3; ?></td>
        <td style="text-align:right;"><?php echo $loandue2; ?></td>
        <td style="text-align:right;"><input type="text" readonly size="5px" class="dueamount" value=""></td>
        <td style="text-align:right;"><input type="text" readonly size="5px" id="overallpaid" class="overallpaid" value="" name="overallpaid"></td>
    </TR>
        </table>


<?php } else {
       echo "<font color='RED'>No Members in the branch you seleted</font>";
} ?>

