<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<form action="<?php echo $this->baseUrl();?>/personalsavings/index/pdfgeneration" method="POST">   

	<table id="hor-minimalist-b" summary="Employee Pay Sheet" width="50%">
    <th colspan="8"><b>Personal Savings Members</b></th>
        <div class="search">
                <TR>
                    <TH>Account Number</TH> 
                    <TH>Account Name</TH> 
                    <TH>Member Code</TH> 
                    <TH>Member Name</TH> 
                    <TH>Created Date</TH>
                    <TH>Balance</TH>
                    <TH>Created By</TH> 
                </TR>
<?php $dateconvertor = new App_Model_dateConvertor(); ?>

                 <?php foreach($this->savingslist as $savings){
                    if($savings['BalanceAmt']){
                ?>
                    <TR>
                        <TD><?php echo $savings['account_number']; ?></TD>   
                        <TD><?php echo $savings['offername']; ?></TD> 
                        <TD><?php echo $savings['membercode']; ?></TD> 
                        <TD><?php echo $savings['membername']; ?></TD> 
                        <TD><?php echo $dateconvertor->normalformat($savings['accountcreated_date']); ?></TD> 
                        <TD><?php echo $savings['BalanceAmt']; ?></TD> 
                        <TD><?php echo $savings['loginname']; ?></TD>  
                    </TR>
                <?php } } ?>

			 </div>
            </table>
            <input type="submit" value="PDF" id="submit">
	   <?php echo $this->Error;?>

</form>

