<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript">
$(document).ready(function() {

$('#feetype_id').change(function(){
baseurl=$('#baseurl').val();
 selectedval=$(this).val();

 url='<?php echo $this->baseUrl();?>/fee/index/getcategory'
  $.ajax({
  url:url,
  data: 'selectedval='+selectedval,
  success: function(data){
     $('#feefor_id').parent().html(data);
      },
  
  });

});


});

$(document).ready(function() {
$('#show').change(function(){
var va = $('#feetype_id').val();
if(va == 1){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});


</script>
<form action="<?php echo $this->baseUrl();?>/fee/index/editfeedetail/id/<?php echo $this->id; ?>" method="POST">
 	<div id="container-1">
		<div class="profile_tab">

			<fieldset>
			<table id="hor-minimalist-b">	

 <tr><Th>Edit fee Information</Th><th><a href="<?php echo $this->baseUrl();?>/fee/index/delete/id/<? echo $this->id; ?>" method="POST"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 align="right" width="16" height="16"></a></th></tr>					<table class="fieldsets">	

            <TR >
                <TD ><?php echo $this->form->name;?></TD>
            </TR>
<TR >
                <TD ><?php echo $this->form->description;?></TD>
            </TR>
			<TR >
                <TD ><?php echo $this->form->hierarchy_id;?></TD>
            </TR>
 			<TR >
                <TD ><label for="fld1" class="mand">Fee type</TD>

                <TD id="show"><?php echo $this->form->feetype_id;?></TD>
            </TR>
			<Tr id="hide">
                <TD ><label for="fld1" class="mand">Fee for</TD>

                <td  id="#feefor_id"><?php echo $this->form->category_id  ;?></td>
            </Tr>
<TR>
                <TD ><label for="fld1" class="mand">GL code</TD>
                <td><?php echo $this->form->glsubcode_id;?></td>
            </TR>
			<TR >
                <TD ><?php echo $this->form->amountype_id;?></TD>
            </TR>
			<TR >
                <TD ><?php echo $this->form->value;?></TD>
            </TR>
				</table>
						<div class="btnhouse">
							<div class="ltbtns">
 								<input type="submit" name="Update" id="Submit" value="Update">                 
							</div>
								<div class="rtbtns">
								<a href="<?php echo $this->baseUrl();?>/fee"><?php echo $this->form->Back;?></a>
								</div>
						</div>
			</fieldset>
		</div>
	</div>
</form>