
<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
function getgroups(branch,path) {
	if(branch) {
		targeturl=path+"/cashscroll/index/group?branch="+branch;
		$.ajax({ url: targeturl, success: function(data){ $("#groupdiv").html(data) }});
	}
}
$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});
</script>

<?php  if(!$this->ledegerListAssets && !$this->ledegerList) { ?>   
	<form action="<?php echo $this->baseUrl();?>/ledgerbalancebook" method="POST">  
		<div style="margin-left:25px;">
    		<fieldset>
        		<legend>Ledger details</legend>
        			<TABLE width="100%">
  						<tr>
                			<TD>&nbsp;&nbsp;&nbsp;<br><label class="mand">As of Date :</label></TD>
                			<TD><br><?php  echo $this->form->date1;?></TD>
							<TD><?php echo $this->translate('Hierarchy'); ?></td>
                            <TD id="show"><?php echo $this->form->hierarchy;?></td>
						</tr>
						<tr>
  							<TD></TD><TD></TD>
                            <TD><?php echo $this->translate('Branch'); ?></td>
                            <TD><div id="statediv"><?php echo $this->form->branch;?></div></TD>
						</tr>
<!--						<tr id="hide">
							<TD></TD><TD></TD>
							<TD><?php //echo $this->translate('Group'); ?></TD>
                            <TD><div id="groupdiv"><?php// echo $this->form->group;?></TD>
						</tr>-->
					</table>
				<div style="margin-left:20px;" class="ltbtns"><br>
					<input type="submit" name="Search" value="Search"/></div>
    		</fieldset>
		</div>
	</form>
<?}?>
  

<?php  if($this->ledegerListAssets || $this->ledegerList) { ?> 
	<h3 align="right">As of <?php echo "<font color='#039'>".$this->date1."</font>"; ?> </h3>
<br>
	<h3 style="text-align:right">* Amount in <font color="red">Rs</font></h3>

<div style="float:left;width:370px">
        <?php 
        $totalcredit = 0.00;
        $totaldebit = 0.00;
        $i = 0;
        $j = 0;
              $countvalue1 =count($this->ledegerList);
              $countvalue2 =count($this->ledegerListAssets);
              $count = $countvalue1>$countvalue2?$countvalue1:$countvalue2; 
        ?>

        <table id="hor-minimalist-s">
            <TR>
                <TH >GL.LF no</TH>
                <TH >Liabilities</TH>
                <TH align="right">Amount</TH>
            </div>
            <?php foreach($this->ledegerList as $savingsDebit) { $i++; ?>
            <TR>
                <td><?php echo $savingsDebit["glsubcode"];?></td>
                <td><?php echo $savingsDebit["subheader"];?></td>
                <td align="center"><?php echo $savingsDebit["liabilitiesBalance"];?></td>
                <?php $totalcredit=$totalcredit+$savingsDebit["liabilitiesBalance"]; ?>
            </td>
            <?php }?>
		<?php 
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
            <tr>
                <TD></TD>
                <TD>TOTAL</TD>
                <TD align="center"><?php echo sprintf("%4.2f", $totalcredit); ?></TD>
            </tr>

            	<?php } else {?>
				<tr>
				        <TD></TD>
					<td><?php echo "----";?></td>
					<td align = "center"><?php echo "----";?></td>
				</tr>
		
			<?php } }  $i=0;$j=0; ?>
        </table>
</div>
<div style="float:left;width:370px">
    <?php $totaldebit="0"; ?>
        <table id="hor-minimalist-s">
            <TR>
                <TH >GL.LF no</TH>
                <TH >Assets</TH>
                <TH align="right">Amount</TH>
            </TR>
            <?php foreach($this->ledegerListAssets as $savingsDebit) { $i++;?>
            <tr>
                <td><?php echo $savingsDebit["glsubcode"];?></td>
                <td><?php echo $savingsDebit["subheader"];?></td>
                <td align="center"><?php echo $savingsDebit["assetsBalance"];?></td>
                <?php  $totaldebit=$totaldebit+$savingsDebit["assetsBalance"]; ?>
            </TR>
            <?php }?>

            		<?php 
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
			             <tr>
                <TD></TD>
                <TD>TOTAL</TD>
                <TD align="center"><?php echo sprintf("%4.2f", $totaldebit); ?></TD>
            </tr>
            <?php } else {?>
				<tr>
				        <TD></TD>
					<td><?php echo "----";?></tr>
					<td align = "center"><?php echo "----";?></td>
				</tr>
		
			<?php } }  $i=0;$j=0; ?>
        </table>
</div>
<?php } ?>
