
<?php  if($this->ledegerListAssets || $this->ledegerList) { ?> 
	<h3 align="right">As of <?php echo "<font color='#039'>".$this->date1."</font>"; ?> </h3>
<br>
	<h3 style="text-align:right">* Amount in <font color="red">Rs</font></h3>

<div style="float:left;width:370px">
        <?php 
        $totalcredit = 0.00;
        $totaldebit = 0.00;
        $i = 0;
        $j = 0;
              $countvalue1 =count($this->ledegerList);
              $countvalue2 =count($this->ledegerListAssets);
              $count = $countvalue1>$countvalue2?$countvalue1:$countvalue2; 
        ?>

        <table id="hor-minimalist-s">
            <TR>
                <TH >GL.LF no</TH>
                <TH >Liabilities</TH>
                <TH align="right">Amount</TH>
            </div>
            <?php foreach($this->ledegerList as $savingsDebit) { $i++; ?>
            <TR>
                <td><?php echo $savingsDebit["glsubcode"];?></td>
                <td><?php echo $savingsDebit["subheader"];?></td>
                <td align="right"><?php echo $savingsDebit["liabilitiesBalance"];?></td>
                <?php $totalcredit=$totalcredit+$savingsDebit["liabilitiesBalance"]; ?>
            </td>
            <?php }?>
		<?php 
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
            <tr>
                <TD></TD>
                <TD>TOTAL</TD>
                <TD align="right"><?php echo sprintf("%4.2f", $totalcredit); ?></TD>
            </tr>
            
            			<?php } else {?>
				<tr>
				        <TD></TD>
					<td><?php echo "----";?></td>
					<td align = "right"><?php echo "----";?></td>
				</tr>
		
			<?php } }  $i=0;$j=0; ?>
        </table>
</div>
<div style="float:left;width:370px">
    <?php $totaldebit="0"; ?>
        <table id="hor-minimalist-s">
            <TR>
                <TH >GL.LF no</TH>
                <TH >Assets</TH>
                <TH align="right">Amount</TH>
            </TR>
            <?php foreach($this->ledegerListAssets as $savingsDebit) { $i++;?>
            <tr>
                <td><?php echo $savingsDebit["glsubcode"];?></td>
                <td><?php echo $savingsDebit["subheader"];?></td>
                <td align="right"><?php echo $savingsDebit["assetsBalance"];?></td>
                <?php $totaldebit=$totaldebit+$savingsDebit["assetsBalance"]; ?>
            </TR>
            <?php }?>

            		<?php 
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
			             <tr>
                <TD></TD>
                <TD>TOTAL</TD>
                <TD align="right"><?php echo sprintf("%4.2f", $totaldebit); ?></TD>
            </tr>
            <?php } else {?>
				<tr>
				        <TD></TD>
					<td><?php echo "----";?></tr>
					<td align = "right"><?php echo "----";?></td>
				</tr>
		
			<?php } }  $i=0;$j=0; ?>
        </table>
</div></tr></TR></table></fieldset>
<form action="<?php echo $this->baseUrl();?>/ledgerbalancebook/index/pdfdisplay" method="POST" onClick="window.open('<?php echo $this->baseUrl();?>/ledgerbalancebook/index/reportdisplay/file/ledgerbalancebook.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">

           <br><input type="submit" value="PDF" id="submit">
                <input type="hidden" name="field1" value="<?php echo $this->ledegerListAssets; ?>"/>
				<input type="hidden" name="date1" value="<?php echo $this->date1; ?>"/>

</form>
<?php } ?>
