<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<?php if(!$this->result && !$this->groupresult) { ?>
<div id="searchDiv">
<fieldset>
	<legend>Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/sbi" method="POST">
			<table class="fieldsets">
                            <TR>
                                <TD><label class="mand">Group code:</label></TD>
                                <TD><? echo $this->form->groupcode;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <input type="Submit" name="Submit" value="Search">

                            </div>
                        </div>
	 </form>

</fieldset>
</div>

<?php } else { echo "<font color=red>".$this->errormsg."</font>"; } ?>

<?php if($this->groupresult){ 
$results = $this->groupresult;
foreach($results as $result) { ?>
<div style=" height:500px; overflow-y: auto; padding-bottom:5px;">
<table id="hor-minimalist-b">
<th colspan="2" >Applicationto be submitted by SHG to Bank branch while applying for loan assistance</th>
    <tr>
		<td>Name of the self group: <?php echo "<font color=green>".$result['name']."</font>"?></td>
    </tr>
	<tr>
		<td>Address: <?php echo "<font color=green>".$result['address1'].' , '.$result['city'].' , '.$result['district'].' , '.$result['state'].'-'.$result['zipcode']."</font>"?></td>
    </tr>
	<tr>
		<td>Formed /established on:</td>
    </tr>
	<tr>
		<td>Registered: <?php echo "<font color=green>".$result['group_created_date']."</font>"?></td>
    </tr>
	<tr>
		<td>If registered give number and date and furnish the original certificate of rgistration:</td>
    </tr>
	<tr>
		<td>Number of members in the group: <?php echo "<font color=green>".$result['totalmember']."</font>"?></td>
    </tr>
	<tr>
		<td>Number of SHPI/NGO/VA assisting the group if any:</td>
    </tr>
	<tr>
		<td>Loan linkage number:</td>
    </tr>

</table>
<p><b>To<div style="float: right; width: 120px;">Place</div><br>The Branch manager<div style="float: right; width: 120px;">Date : <?php echo "<font color=green>".date('d-m-Y')."</font>"?></div><br>STATE BANK OF INDIA<br><br><br></b>Dear sir,<br><b><u>APPLICATION FOR LOAN</u></b><br>We the duly authorised representatives of the above SHG hereby apply for a loan aggregating
Rs (Rupees , .
.............................................................................:............. only) for on-lending to our members.
The financial particulars of the group as on.................................. are given in the enclosed sheet<br>2. REPAYMENT SCHEDULE :
We agree to repay the loan amount as per the repayment schedule which may be fix
by the Bank.<br>
3. A copy of the Inter-se Agreement executed by all the members of the group authorising
us inter alia to borrow on behalf of the SHG is enclosed.<br>
4. We hereby declare that the particulars given above are true and correct to the best of our
knowledge and belief.<br>
5. We hereby authorise the Bank to disclose all or any particulars or details OT information
relating to our loan accounts with the Bank, to any other financial institution including
NABARD, Government OT any agency as may be considered necessary or desirable by the
Bank. It will be in order for the Bank to disqualify the SHG from receiving any credit
facilities from the Bank and I or recall the entire loan amount or any part thereof granted
"V1 this application, if any of the information pertaining to the Group, furnished
herewith is found incorrect and I or containing misrepresentation of facts.</p>
<table id="hor-minimalist-b">
<tr>
	<TD><b>No</b></TD>
	<td><b>Particular</b></TD>
	<TD><b>Amount in rs</b></TD>
</tr>
</table>
<div style="float: right; width: 150px;">Yours faithfully</div>
<br>
<br>
<br>
<br>
<p>Name   ...................................................................... &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      ............................................................................................</p>
<p>Name   ...................................................................... &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       ............................................................................................</p>
<div style="float: right; width: 350px;">(Authorised representative)</div><br><br>
<b><u>Recommended for sanction</u></b><div style="float: right; width: 350px;"><u><b>Sanctioned Rs</b></u></div><br><br><br>
<b><u>Branch manager</u></b><div style="float: right; width: 350px;"><u><b>Fiald officer</b></u></div><br><br><br>
<b><u>State bank of India</u></b><div style="float: right; width: 100px;"><u><b>To</b></u></div><br><br>
<b>......................................................</b><div style="float: right; width: 100px;"><b>....................................................</b></div><br><br>
<b>.....................................Branch</b><div style="float: right; width: 100px;"><b>(Name of SHG)</b></div><br><br>
<div style="float: right; wigroupresultdth: 95px;"><b>.............................</b></div>
<b><u>ARRANGEMENT LETTER</u></b><br><br>
<b>(Term Loan I Cash Credit to Self Help Groups)</b><br><br>
<b>Dear sir/madam,</b><br><br>
<u><b>Term Loan/ Cash Credit to SHG</b></b><br><br></u>
<p>SHGWith
reference to your application dated requesting for grant of a Term
, Loan I Cash Credit of Rs. (Rupees ) for
- financing to members of your SHGs, we are pleased to inform you that a Term Loan I Cash
Credit of Rs. (Rupees ) has been
r sanctioned to you on the following terms and conditions:
" 1. Term Loan I Cash Credit has been granted by the Bank to you for on-lending to the
members of your group.<br>
2. Security: The loan will be secured by:
(i) Primary security (give brief particulars of security)
(ij) Collateral (give brief particulars of collateral security, if any)
(iii) Third party guarantee, if any (furnish the name of the guarantors)<br>
3. Interest:
Interest will be charged at the rate of below I above SBAR (SBAR __ % w.e.f.
____ ) with a minimum of p.a. rising and falling with the change in SBAR on
. the amount outstanding in the account with monthly I quarterly I half-yearly rests.<br>
4. Period of Advance & Repayment:
, To be availed within a period of months from the date of sanction. The term loan is
repayable in monthly I quarterly I half-yearly instalments of Rs. each
along with interest I the loan will be repayable on demand.<br>
-5
. Enhanced interest:
The Bank shall be entitled to charge at its discretion, enhanced interest. rates on the
account either on the entire outstandings or on a portion thereof, for any irregularity
including non-observance or non-compliance of the tenns and conditions of the advances
for such period as the Bank deems it necessary.<br>
..
6. All legal expenses such as lawyer's fees, registration charges, etc., should be borne •
by you.<br>
7. The Assets charged to the Bank should not be disposed of, sold or 'otherwlse ~
encumberedas long as the Bank loan remains unpaid.<br>
8. The advances is also subject to the tenns and conditions stipulated in the
documentsfor the loan granted and also other conditions, if any, stipulated by the Bank •
from time to time. The rate of interest is subject to change from time to time. ~<br>
9. The account shall be operatedby the authorized person(s)of the SHG.<br>
10. You will furnish verified statement in regard to utilization of the loan in such form ,
and manner as may be specified by the bank and if so required by the Bank" have such
statementverified by the auditors.<br>
11. The group will maintain books of accounts sufficient to reflect group's true and
correct financial position under supervision of the NGO _<br>
12. The Bank shall have a right to call up the loan on the happening of any event which,
in the opinion of the Bank, is likely to jeopardize Bank's interest.<br>
13. Security Documents:
The follo~ing security documents shall be executed by you and the guarantors
a) Articles of agreement-for financing Self Help Groups ,
b) Inter-sa agreement to be executed by the members of Self HeJpGroups.
c) Any other document as may be r~uired by the bank. '<br>
-
14. On agreeing to above terms and conditions. the duplicate hereof may please be
'returnedto us duly acknowledged by the authorised representativesof the SHG.</p>

<b>yours faithfully</b><br><br>
<div style="float: right; width: 100px;"><b>Received the original</b></div><br>
<b>Branch manager</b><br><br><br>
<div style="float: right; width: 100px;"><b>Authorised Representatives of SHG</b></div><br><br><br><br>
<div style="float: right; width: 150px;"><b>..........................................</b></div><br><br><br>
<div style="float: right; width: 150px;"><b>..........................................</b></div><br><br><br>
<b><u>ARTICLES OF AGREEMENT FOR FINANCING SELF-HELP GROUPS</u></b><br><br>
<p>The Articles of Agreement made on this ............................. day of .............20......... .
at....................................................................  by and between 
M/s .....................................
(Name of SHG)
an unregistered association of persons I individuals having its office
at............................................................................represented by its authorised representatives.
Smt/Shri ................................................representative1<br>
Smt/Shri ................................................representative2<br>
who. are fully authorised by all the members of the SHG, (a copy of such Authorisation is
annexed hereto and forms part of this agreement), hereinafter referred to as the "Borrower"
which expression shall unless repugnant to the subject or context thereof, mean and include
members of the unregistered association for the time being, their respective successors, legal
heirs, administrators and assigns of the one part AND State Bank of India a body corporate
constituted under State Bank of India Act. 1955, having its Central Office at Mumbai and
one of the Local Head Office at Bangalore and the Branches, inter alia, one
at ................................................. hereinafter called litheBank"which
expression shall unless repugnant to the subject or context thereof mean and include its
successors and assignees of the second part.
Where as the Borrower is an unregistered association of persons who have inter - se agreed to
help each other as self-help group with a view to developing and ameliorating the
socio-economic conditions of their members.
Whereas having formed the association as a self help group, the Borrower as per application
dated : made by the said
Smt/Shri ................................................representative1<br>
Smt/Shri ................................................representative2<br>
uly authorised to borrow in terms of its resolution dated (copy enclosed),
quested the Bank to *grant a loan / extend credit facility of *Rs /
pto the limit of Rs (Rupees .
........................................:.......... ; only) for on-lending to its members.
d whereas the Bank has agreed to grant the "Ioan I extend credit facility to the Borrower
n certain terms and conditions.
d whereas the Bank and the Borrower are desirous of reducing the agreed terms into writing</p><br>
<b><u>NOW, THEREFORE, THIS AGREEMENT WITNESSETH AS FOLLOWS</u></b><br><br>
<p>1. The Bank has agreed to grant and the Borrower has agreed to borrow by way of
term loan / cash credit (clean)upto the limit Rs ................................................
(Rupees only)
and the Bank has opened............................... (Specify the kind of loan account)
AccountNo .........................................of date.......................................... in the
name of the Borrower in its book of accounts.<br>  2. In case the facility availed is cash credit the Borrower will operate the cash credit account
satisfactorily and within the limit and the Borrower shall repay the outstanding liability in
the account inclusive of interest and other charges debited from time to time on demand
without demur.<br>
3. In case loan availed is demand Loan, without prejudice to the right of the Bank to recall
the loan on demand the Borrower undertakes to repay the loan with interest and other
charges within the period stipulated in terms of sanction.<br>
4. In case the credit facility availed of. by the Borrower is a term loan the same shall be
repayable in instalments in the manner specified here below in the repayment schedule.
(to be specified). Besides the Borrower will pay interest at the rates that may be prescribed
for such lending by RBI/ NABARD from time to time.<br>
5. It is clearly understood by and between the parties hereto that in the event of the
Borrower's failure to utilise the proceeds of the credit facility for the purpose for which
the same has been made available by the Bank to Borrower, the Borrower shall repay
immediately on demand without demure together with interest without prejudice to
Bank's right to initiate other legal action.<br>
6. The Borrower shall pay interest on the loans to be calculated on the daily balances in the
loan account and be debited thereto at monthly-/ quarterly rests or as the Bank may
decide.<br>
7. The Borrower should utilise the proceeds of the credit facility for the purpose of lending
to its members to improve the socio-economic conditions of their members and their
families.<br>
8. The Borrower shall repay the credit facility availed of together with interest payable
as per the interest rates that may be fixed by RBI / NABARD from time to time for such
lendings.<br>
9. The Borrower shall be liable to repay the facility on demand together with interest and
other charges payable by the Borrower to the Bank in accordance with the rules of the Bank.<br>
<u>(*delete which is not appropriate)</u><br><br>
<div style="float: right; width: 400px;"><u><b>REPAYMENT SCHEDULE</b>&nbsp;&nbsp;(please specify)</u></div><br>
................................................................................................................. , .
..................................................................................................................................................................................................................
In witness whereof the parties hereto have affixed their signature on the ,. date
and the month and year first herein above written.<br><br><br><br>
<b></b>For STATE BANK OF INDIA</b>
<div style="float: right; width: 150px;">1) AUTHORISED REPRESENTATIVE</div><br><br><br><br>
<div style="float: right; width: 150px;">2) AUTHORISED REPRESENTATIVE</div><br><br>


</p>
<b><u>INTER-SE AGREEMENT TO BE EXECUTED
BY THE MEMBERS OF THE SELF HELP GROUP (SHG)</u></b>
<p>This Agreement Made on this ........................day of........................................ month 20................................ year
between

Whoare membersof the ...................................................................
(Name of the SHG to be mentioned)
group, hereinafter referred to collectively as "the Self-Help. Group" (SHG) members which
expression shall, unless repugnant to the context or meaning, include every member of the
said SBG and their respective legal heirs, executors and administrators.
WHEREASall the SHG members above named have joined voluntarily together and formed
the SHG with intent to carryon savings and credit and other economic activities for mutual
benefit subject to the terms and conditions hereinafter appearing.<br><br><br><br></p>

<b><u>NOW THEREFORE THIS AGREEMENT WITNESSETH THAT</u></b><br><br>
<p>
1. Each member of the SHG shall save a sum of Rs........................................
(Rupees only)
or such sum as may be decided by the Group, on. weekly / fortnightly / monthly basis
which shall be deposited with the authorised member of the group .<br>
2. Each member shall strive for the success of the SHG and shall not act in any manner
detrimental to the busirtess interests of the SHG.<br>
3. The SHG members shall be jointly & severally liable for all the debts contracted by the SHG.<br>
4. All assets and goods acquired by the SHG shall be in the joint ownership of
all the members of the SHG and shall· ordinarily be in the constructive
custody of such members as may be authorised by the Group and shall be kept at the
place of business at ...........................................
which shall not be changed without consent of the SHG members.<br>
5. The SHG members hereby duly elect and appoint -
Smt. / Shri.....................................................
Smt. / Shri ....................................................
(by whatever name designated), hereinafter called "Authorised representatives"
of (Name of the SHG)
to look after and manage the day to day affairs of the SHG's activities and also act in
their name and on their behalf in all matters relating thereto. The authorised
representatives may, however, be removed at any time by majority vote of the members
and new representatives elected.<br>
6. Each of the SHG members hereby agrees to abide by and ratify all such acts, deeds
and things as the authorised representatives may do in the interest of the said activities.<br>
7. The authorised representatives shall take decisions in the day to day working of the
SHG and each representatives shall actively involve herself or himself and co-operate in
looking after the day-to-day affairs of the SHG activities in particular to attend to the
following activities. Every member of the SHG hereby authorises the representatives to
apply for the loan on behalf of the SHG and execute necessary agreements / documents
on behalf of the SHG, on the terms arid conditions as may be asked upon by the said
authorised representatives, for the purpose. The said authorised representatives are also
authorised to execute all types of undertakings and create securities on the assets of the
SHG. The authorised representatives may collect loan amounts from the Bank on behalf
of SHG, deposit the same in the savings account of the SHG for on-lending to members,
in accordance with the decision of the SHG and also deposit recovery of loan instalment
from members in the loan account! s of SHG with the Bank.<br>
8. The SHG members specifically authorise the representatives :
(i) The open Savings, Fixed Deposits and other accounts in State Bank of India, a Bank
approved by the SHG and operate the same under the joint signature of any two of
the following authorised representatives -
Smt. / Shri........................................
Smt. / Shri........................................
(ii) To keep or cause to be kept proper books of accounts of the savings, made by
the SHG members, loans granted to them and the recoveries made from them and
render every year the full accounts to the SHG members for the' anornval ,.,1:1<br>
(iii) To receive all payments due to the SHG and issue requisite receipts acknowledgements
for and on behalf of the SHG.<br>
(iv) To institute and defend on behalf of the SHG members any legal proceedings
and safeguard the interests of each member of the said SHG and for this purpose
engage or disengage any lawyer or advocate or agent and incur the necessary legal
expenses in connection therewith.<br>
9. In the event of death of any of the members of the SHG, his / her legal heirs shall be
entitled for the benefits an~ be liable for the obligations of the deceased member under
this agreement.<br>
10. It is agreed that no new person shall be inducted as a member of the SHG without
consent of all the existing members.<br>
I~ WITNFSS WHEREOF the aforesaid members of the SHG have set their respective hands
hereunto at the place.................................. and on............................................ day of.................................
......................................................................... month................................. year first herein appearing.

</p>

</body>
</html>

 </div>
<?php } }?>