<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/toggel.js"></script> 
<script type="text/javascript">
function unhide(obj,div)
{
    if(document.getElementById(obj).style.display=='none') {
        document.getElementById(obj).style.display='block';
    } else {
        document.getElementById(obj).style.display='none';
    }
    if(document.getElementById(div).style.display=='block') {
        document.getElementById(div).style.display='none';
    } else {
        document.getElementById(div).style.display='block';
    }

}
$(document).ready(function(){
	        //iterate through each textboxes and add keyup
        //handler to trigger sum event
	        $(".txt").each(function() {
 	            $(this).keyup(function(){
                calculateSum();
	            });
	        });
	    });
	    function calculateSum() {
	        var sum = 0;
	        //iterate through each textboxes and add the values
	        $(".txt").each(function() {
	 	            //add only if the value is number
            if(!isNaN(this.value) && this.value.length!=0) {
	                sum += parseFloat(this.value);
           }
	        });
	        //.toFixed() method will roundoff the final sum to 2 decimal places
	        $("#amount").val(sum.toFixed(2));
	        alert(sum.toFixed(2));
	    }
</script>

<div style="float:right;width:350px">

    <?php if(count($this->groupmember)) { ?>
	<div class="container">
	   <h2 class="trigger"><a href="#">Group Members</a></h2>
            <div class="toggle_container">
                <div class="block">
                    <table id="hor-minimalist-s">
                        <TR>
                            <TH>Member code </TH>
                            <TH>Member name</TH>
                            <TH>Total Balance</TH>
                        </TR>
                        <?php
                            $totalbalance=0; $currentbalance=0; foreach ($this->groupmember as $group) {  ?>
			  <TR>
                            <td><?php echo $group->code; ?></td>
                            <td><?php echo $group->name; ?></td>
                            <td align="right">
                            <?php 
                            $memberid=$group->code;
                            $accnum=$this->accNum;
                            $groupmodel = new Msdetails_Model_msdetails(); 
                            $credit=$groupmodel->getcredit($accnum,$memberid);
                            $debit=$groupmodel->getdebit($accnum,$memberid);
                            if($credit) { $currentbalance=$credit-$debit; echo sprintf("%4.2f",$currentbalance); }

                            ?>
                            </td>
                        </TR>
                        <?php $totalbalance+=$currentbalance; }?>
                        <tr>
                            <td>Total</td>
                            <td></td>
                            <td align="right"><?php echo sprintf("%4.2f",$totalbalance); ?></td>
                        </tr>
		    </table>
                </div>
            </div>
	</div>
        
    <?php } ?>

</div>

 <div style="float:left;width:350px"> 
    <?php foreach($this->details as $details) { ?>
        <table id="hor-minimalist-s">
            <TR>
                <TH>Member details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td>Name </td>
                <TD><?php echo $details->name ?></TD>
            </TR>

            <TR>
                <td>Branch</td>
                <TD><?php echo $details->officename ?></TD>
            </TR>
            <TR>
                <td>Code</td>
                <TD><?php echo $details->code ?></TD>

            </TR>
            <TR>
                <TH>Account details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td>Product name</td>
                <td><?php echo $details->offername ?></TD>
            </TR>
            <TR>
                <td>Created date</td>
                <td><?php echo $details->createdDate ?></TD>
            </TR>
            <TR>
                <td> Account number</td>
                <td><?php echo $details->number ?></TD>
            </TR>

            <TR>
                <td>Balance</td>
                <td><b><font color='green'><?php echo $this->balance; ?></font></b></TD>
            </TR>
    
        </table> 
    <?php } ?>
</div>
</br>
</br>

<?php if($this->details) { ?>
<table id="hor-minimalist-b" border="1">
    <tr>
        <th>V No.</td>
        <th>Tran.date</td>
        <th>Account number</th>
        <th>Group members</th>
        <th>Credit</th>
        <th>Debit</td>
        <th>Transacted by</td>  
    </tr>
    <?php foreach($this->tran as $transaction) : ?>
    <tr>
       <td align="center"><?php echo $transaction->id; ?></td>
       <td><?php echo $transaction->date; ?></td>
       <td align="center"><?php echo $transaction->member_id; ?></td>
       <td><?php echo $transaction->membername; ?></td>
       <?php if($transaction->mode=='credit'){ ?>
       <td align="right"><?php echo $transaction->transaction_amount; ?></td> 
       <?php } else { ?>
       <td align="right">----</td><?php } ?>

       <?php if($transaction->mode=='debit'){ ?>
       <td align="right"><?php echo $transaction->transaction_amount; ?></td> 
       <?php } else { ?>
       <td align="right">----</td><?php } ?>
       <td align="center"><?php echo $transaction->name; ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php } ?>
