<script type="text/javascript">
function Getuser(branch_id,path) { 
	if(branch_id) {
		targeturl=path+"/par/index/getofficer?branch_id="+branch_id; 
		$.ajax({ url: targeturl, success: function(data){ $("#officerdiv").html(data) }});
	}
}
</script>
<?php if($this->parrisk) { ?>
		<?php 
		$total30 = "0.00";
		$total60 = "0.00";
		$total90 = "0.00";
		$total180 = "0.00";
		$total360 = "0.00";
		$total360above = "0.00";
		
		//$today = date('Y-m-d');
                $today = $this->fromdate;
		$date30 = date('Y-m-d',strtotime(date("Y-m-d", strtotime($today)) . " -30 days"));
		$date60 = date('Y-m-d',strtotime(date("Y-m-d", strtotime($today)) . " -60 days"));
		$date90 = date('Y-m-d',strtotime(date("Y-m-d", strtotime($today)) . " -90 days"));
		$date180 = date('Y-m-d',strtotime(date("Y-m-d", strtotime($today)) . " -180 days"));
                $date360 = date('Y-m-d',strtotime(date("Y-m-d", strtotime($today)) . " -360 days"));
		
		$day30="0.00";$day60="0.00";$day90="0.00";$day180="0.00";
		$day360="0.00";$day360above="0.00";$r="0.00";
		$duedate='';
		?>
<h3 style="text-align:right;"><? echo $this->resultshow; ?></h3>
<br>
<h3 style="text-align:right"> <font color="red">*</font> Amount in <font color="red">Rs</font></h3>

<table id="hor-minimalist-b" border="1">
        <TR>
		<TD class="reporttd" rowspan="2"><br>Name</TD>
		<TD class="reporttd" rowspan="2"><br>Loan A/C</TD>
		<TD class="reporttd" rowspan="2"><br>On Time</TD>
		<TD class="reporttd" align="center" colspan="6">Days</TD>
		<TD class="reporttd" align="right" rowspan="2"><br>O/S Loan</TD>
        </TR>
	<tr>
		<TD class="reporttd" align="right"> 1 - 30</TD>
		<TD class="reporttd" align="right"> 31 - 60</TD>
		<TD class="reporttd" align="right"> 61 - 90</TD>
		<TD class="reporttd" align="right"> 91 - 180</TD>
		<TD class="reporttd" align="right"> 181 - 360</TD>
		<TD class="reporttd" align="right"> > 360</TD>

	</tr>
        <?php if($this->parrisk) { $a=array(); 
		foreach($this->parrisk as $parrisk1) { $a[]=$parrisk1->account_number; }
			$a=array_unique($a);	$a=array_values($a);

		for($i=0; $i<count($a); $i++) { $flag90_180=0; $flag180_360=0; $flag360_above=0;

		foreach($this->parrisk as $parrisk2) {
			$duedate=$parrisk2->installment_date;
			$modelObj=new Par_Model_Par();
			if($a[$i]==$parrisk2->account_number) {
				if($duedate>$date30 AND $duedate<=$today)
                                {
					$day30 = $parrisk2->installment_amount;
                                } 
				else if($duedate>$date60 AND $duedate<=$date30) 
                                { 
					$day60 = $parrisk2->installment_amount; 
                                }
				else if($duedate>$date90 AND $duedate<=$date60) 
                                { 
					$day90 = $parrisk2->installment_amount;
                                }
				else if($duedate>$date180 AND $duedate<=$date90)
                                { 
		
				    $amt1=$modelObj->getAmount($date180,$date90,$parrisk2->account_number);
                                    if($flag90_180==0) 
                                    {
                                        foreach($amt1 as $amt2) { $day180+= $amt2['sumofdue'];}
                                    }
				    $flag90_180++;
		
				}
				else if($duedate>=$date360 AND $duedate<=$date180)  
                                { 

                                    $amt3=$modelObj->getAmount($date360,$date180,$parrisk2->account_number);
                                    if($flag180_360==0) 
                                    {
                                    foreach($amt3 as $amt4) { $day360+= $amt4['sumofdue'];}
                                    }
                                    $flag180_360++;
			            /*$day360 = $parrisk2->accountinstallment_amount; */ 
				}

				else 
                                {
				    $amt5=$modelObj->getAmount1($date360,$parrisk2->account_number);
				    if($flag360_above==0) {
				    foreach($amt5 as $amt6) { $day360above+= $amt6['sumofdue'];}
				    }
				    $flag360_above++;
				//	$day360above = $parrisk2->accountinstallment_amount; 
				}
			}
		}
			$total30+=$day30;$total60+=$day60; $total90+=$day90;
			$total180+=$day180; $total360+=$day360;$total360above+=$day360above;
			?>
			<TR>

			<TD align="center"><? 
                        $mname=new Par_Model_Par();
                        $name=$mname->gettmembername($a[$i]);
                        foreach($name as $name1) {  echo $name1['name']; }
						?></TD>
			<TD ><?php echo $a[$i]; ?></TD>	
			<TD align="center"></TD>	
			<TD align="right"><?php  echo $day30; $r+=$day30; ?></TD>	
			<TD align="right"><?php echo $day60; $r+=$day60; ?></TD>	
			<TD align="right"><?php echo $day90; $r+=$day90; ?></TD>	
			<TD align="right"><?php echo $day180; $r+=$day180; ?></TD>	
			<TD align="right"><?php echo $day360; $r+=$day360; ?></TD>	
			<TD align="right"><?php echo $day360above; $r+=$day360above; ?></TD>	
			<TD align="right"><?php echo $r;?></TD>
			</TR>
			<? $day30="0.00";$day60="0.00";$day90="0.00";$day180="0.00";$day360="0.00";$day360above="0.00";$r="0.00";
			}
		} ?>
	<TR>
			<TD ></TD>
			<TD ></TD>
			<TD >Total(Rs)</TD>
			<TD align="right"><?php echo sprintf("%4.2f", $total30);?></TD>
			<TD align="right"><?php echo sprintf("%4.2f", $total60);?></TD>
			<TD align="right"><?php echo sprintf("%4.2f", $total90);?></TD>
			<TD align="right"><?php echo sprintf("%4.2f", $total180);?></TD>
			<TD align="right"><?php echo sprintf("%4.2f", $total360);?></TD>
			<TD align="right"><?php echo sprintf("%4.2f", $total360above);?></TD>
			<TD align="right"><?php echo  sprintf("%4.2f", ($total30 + $total60 + $total90 + $total180 + $total360 + $total360above));?></TD>
		</TR>
</table>
<div style="float:left;">
<form action="<?php echo $this->baseUrl();?>/par/index/pdftransaction" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/par/index/reportdisplay/file/par-<?php echo date('Y-m-d');?>.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
	<input type="hidden" name="fromdate" value="<? echo $this->fromdate; ?>">
	<input type="hidden" name="branch" value="<? echo $this->branch; ?>">
	<input type="hidden" name="officer" value="<? echo $this->officer; ?>">
            <input type="submit" value="PDF" name="pdf" id="pdf">
</form>
</div>

<div style="float:right;">
<form action="<?php echo $this->baseUrl();?>/par/index/exceltransaction" method="POST">
	<input type="hidden" name="fromdate" value="<? echo $this->fromdate; ?>">
	<input type="hidden" name="branch" value="<? echo $this->branch; ?>">
	<input type="hidden" name="officer" value="<? echo $this->officer; ?>">
            <input type="submit" value="Excel" name="excel" id="excel">
</form>
</div>

<? } else { ?>
<fieldset>
<legend> search </legend>
	<div class="cont-rgt-data">
		<form action="<?php echo $this->baseUrl();?>/par" method="POST">
	<table id="hor-minimalist-b">
			<TR>
				<TD >Date From</TD>
				<TD ><?php echo $this->form->fromdate;?></TD>
				<TD ></TD>
				<TD ></TD>
			</TR>
			<TR>
				<TD >Branch</TD>
				<TD ><?php echo $this->form->branch;?></TD>
				<TD >Loan officer</TD>
				<TD id="officerdiv"><?php echo $this->form->loanofficer; ?></TD>
			</TR>
			<TR>
				<TD ></TD>
				<TD ></TD>
				<TD ></TD>
				<TD ><?php echo $this->form->Search;?></TD>
			</TR>
	</table>
		</form>
<? echo $this->errormsg; ?>
	</div>
</fieldset>
<? }
?>


