<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script language="JavaScript" type="text/javascript">
 $(document).ready(function(){
       $("a#open").click(function(event){
            $("table.show").toggle();
//             $("a.close").toggle();
/*            $("a.open").hide();*/
       });
     });
//  $(document).ready(function(){
//        $("a#close").click(function(event){
//             $("table.show").hide();
//             $("a.close").toggle();
//             $("a.open").show();
// 
//        });
//      });
</script>
<?php 
$dateconvertor = new App_Model_dateConvertor();
?>
<div>
    <div style="width:350px;float:left">

            <table id="hor-minimalist-bjinu">
                <Tr>
                    <td><b >Product name</b></td>
                    <TD><?php echo $this->offerproductname;?></TD>
                </TR>
                <TR>
                    <td><b >Account number:</b></td>
                    <TD><?php echo $this->accountnumber;?></TR>
                </TR>
                <Tr>
                    <td><b >Member name</b></td>
                    <TD><?php echo $this->membername;?></TD>
                </TR>
                <TR>
                    <td><b >Begin date:</b></td>
                    <TD><?php echo $dateconvertor->phpnormalformat($this->begin_date);?></TD>
                </TR>
                <TR>
                    <td><b >Mature date:</b></td>
                    <TD><?php echo $dateconvertor->phpnormalformat($this->mature_date);?></TD>
                </TR>
                <TR>
                    <td><b >Amount:</b></td>
                    <TD><?php echo $this->fixed_amount;?></TD>
                </TR>
                <TR>
                    <td><b >Interest rates:</b></td>
                    <TD><?php echo $this->fixed_interest;?></TD>
                </TR>

                <TR>
                    <td><b ><SPAN style="color:red">Matured interest:</SPAN></b></td>
                    <TD><SPAN style="color:red"><?php echo round($this->interestamount,2);?></SPAN></TD>
                </TR>
                <TR>
                    <td><b ><SPAN style="color:red">Total matured amount:</SPAN></b></td>
                    <TD><SPAN style="color:red"><?php echo round($this->Totalamount,2);?></SPAN></TD>
                </TR>
            </table>

    </div>
</div>

<DIV style="float:left;width:50%">
<?php If($this->membertype_id==2 or $this->membertype_id==3) { ?>
<a href="#" id="open" class="open">Show / Hide group members</a>
<div class="box">
<div id="content1">
        <div class="cont-rgt-data">
            <table id="hor-minimalist-bjinu"  summary="Employee Pay Sheet" style="display: none" class="show">
                <tr class="tdbrownheading" bgcolor="Silver">
                        <td width="30%"><font color="Black">Name</font></td>
                        <td width="50%"><font color="Black">Code</font></td>
                </tr>
                   <?php foreach($this->groupMembersDetails as $arrayroles1)  { ?>
                <tr class="tdbrownheading">
                    <TD width="30%"><?php echo $arrayroles1['name'];?></TD>
                    <TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
                 </tr>
                <?php } ?>

            </table>
        </div>
</div>
</div>
<?php } ?>
<table width="100%"><TR><TD></TD></TR></table>
</DIV>

<div>
    <div style="width:350px;float:left">
        <table id="hor-minimalist-bjinu" summary="Employee Pay Sheet">
            <?php if($this->mature_date < $this->currentdate) { ?>
            <TR><td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/fixedtransaction/index/renewal/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/memberId/<?php echo base64_encode($this->memberid);?>">Account renewal</a></TD>
            </TR>
            <?php } ?>
            <?php if($this->status_id == 1 || $this->status_id == 3) { ?>
            <TR><td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/fixedtransaction/index/transferfunds/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/memberId/<?php echo base64_encode($this->memberid);?>">Close account and tranfer amount</a></TD>
            </TR>
            <? } ?>
            <TR><td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/fixedtransaction/index/status/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/memberId/<?php echo base64_encode($this->memberid);?>">Account status</a></TD>
            </TR>
        </table>
    </div>
</div>

