<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript">
 $(document).ready(function(){
       $("a#groupmem").click(function(event){
            $("tr.two").toggle();
      });
        $('#paymenttype').change(function() {
            var v = $(this).val();
            if(v!=1){
                if(v==5){
                        $('#etransfer').show();
                        $('#textbox').show();
                        $('#cheque').hide();
                }else{
                        $('#cheque').show();
                        $('#textbox').show();
                        $('#etransfer').hide();
                }
            }
            else{
                        $('#etransfer').hide();
                        $('#textbox').hide();
                        $('#cheque').hide();

            }
         });
     });
</script>
<BODY></BODY> 
<?php if(!$this->noaccount) {?> 
<div>
    <div style="width:350px;float:left">
        <table id="hor-minimalist-bjinu" summary="Employee Pay Sheet">
            <Tr>
                <td><b class="star">Name</b></td>
                <TD><?php echo $this->offerproductname;?></TD>
            </TR>
            <TR>
                <td><b class="star">Account number:</b></td>
                <TD><?php echo $this->accountnumber;?></TR>
            </TR>
            <TR>
                <td><b class="star">Begin date:</b></td>
                <TD><?php echo $this->begin_date;?></TD>
            </TR>
            <TR>
                <td><b class="star">Mature date:</b></td>
                <TD><?php echo $this->mature_date;?></TD>
            </TR>
            <TR>
                <td><b class="star">Amount:</b></td>
                <TD><?php echo $this->fixed_amount;?></TD>
            </TR>
            <TR>
                <td><b class="star">Interest rates:</b></td>
                <TD><?php echo $this->fixed_interest;?></TD>
            </TR>
            <TR>
                <td><b class="star"><SPAN style="color:green">Matured interest:</SPAN></b></td>
                <TD><SPAN style="color:green"><?php echo $this->interestamount;?></SPAN></TD>
            </TR>
            <TR>
                <td><b><SPAN style="color:green">Total matured amount:</SPAN></b></td>
                <TD><SPAN style="color:green"><?php echo $this->Totalamount;?></SPAN></TD>
            </TR>
        </table>
    </div>
</div>
<DIV style="float:left;width:50%">
<?php if(($this->membertype_id==3) or ($this->membertype_id==2))  { ?>
<a href="#" id="groupmem">Show / Hide group members</a>
<div class="box">
<div id="content1">

    <div class="cont-rgt-data">
        <table id="hor-minimalist-s" summary="Employee Pay Sheet">
             <TR style="display:none;" class="two">
                <td width="30%">Name</td>
                <td width="50%">Code</td>
            </tr>
            <?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
             <TR style="display:none;" class="two">
                <TD width="30%"><?php echo $arrayroles1['name'];?></TD>
                <TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
            </tr>
            <?php }?>
        </table>
    </div>
</div>
</div>
<?php }	?>
<table width="100%"><TR><TD></TD></TR></table>
</DIV>


<div style="float:left;width:350px">

    <div class="cont-rgt-data">
        <table id="hor-minimalist-bjinu" summary="Employee Pay Sheet" >
            <TR>
                <td><b class="star"><SPAN style="color:green">Capital amount:</SPAN></b></td>
                <TD><SPAN style="color:green"><?php echo $this->fixed_amount;?></SPAN></TD>
            </TR>
            <TR>
                <td><b class="star"><SPAN style="color:green">Interest amount:</SPAN></b></td>
                <TD><SPAN style="color:green"><?php echo $this->interestamountfrombank;?></SPAN></TD>
            </TR>
            <?php if($this->currentdate < $this->mature_date) { ?>
            <TR>
                <td><b class="star"><SPAN style="color:green">Penal interest amount:</SPAN></b></td>
                <TD><SPAN style="color:green"><?php echo $this->prematureinterestamountfrombank;?></SPAN></TD>
            </TR>
            <?php } ?>
            <TR>
                <td><b class="star"><SPAN style="color:green">Total amount:</SPAN></b></td>
                <TD><SPAN style="color:green"><?php echo $this->maturedinterestamount;?></SPAN></TD>
            </TR>
        </table>
    </div>

</div>

<?php if(!$this->Submit) { ?>
<div>
    <div style="width:50%;float:left">

        <form name="form1" action="<?php echo $this->baseUrl();?>/fixedtransaction/index/transferfunds" method="POST" onsubmit='return validate(this)'>
            <table id="hor-minimalist-bjinu" summary="Employee Pay Sheet" class="fieldsets">
                <tr >
                    <td width="40%"><label for="fld1" class="mand">Transaction mode </label></td>
                    <td width="60%" colspan="2"><?php echo $this->form2->paymenttype;?><?php //echo $this->form2->paymenttype_details;?></td>
                    
                </tr>
                <tr>
                    <td id="cheque" style="display:none"><label for="fld1" class="mand">Voucher/cheque/draft</label></td>
                    <td id="etransfer" style="display:none"><label for="fld1" class="mand">Account number</label></td>
                    <td id="textbox" style="display:none"><?php echo $this->form2->othertext;?></td> 
                </tr>
                <tr>
                    <td width="40%"><label for="fld1" class="mand">Description</label> </td>
                    <td width="60%" colspan="2"><?php echo $this->form2->transactiondescription;?>
                    </td>
               </tr>
               <tr style="display:none;"><TD colspan="2"><?php  
                            echo $this->form2->accountId;
                            echo $this->form2->productId; 
                            echo $this->form2->memberId; 
                            echo $this->form2->capitalamount;
                            echo $this->form2->interestamountto; 
                            echo $this->form2->penalinterest;
                            echo $this->form2->maturedinterestamount;?></TD></tr>
            </table>
            <table class="fieldsets">
                <tr>
                       <td><label for="fld1" class="mand"> Marked fields are mandatory</label></td>
                </tr>
                <TR>
                    <TD><?php echo $this->form2->Confirm;?></TD>
                    <td><a href="<?php echo $this->baseUrl();?>/fixedtransaction/index/fixed/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>">
                    <input name="submit" type="submit" value="back"></a></TD>
                </TR>
                <tr>
                    <td colspan="4"><B style="color:red"><?php echo $this->noaccount1;?></B></td>
                </tr>
            </table>
        </form>

    </div>
</div>
<?php } ?>

<?php if($this->Submit) { ?>
<div>
    <div style="width:50%;float:left">

        <form name="form1" action="<?php echo $this->baseUrl();?>/fixedtransaction/index/transferfunds" method="POST" onsubmit='return validate(this)'>
            <table id="hor-minimalist-bjinu" summary="Employee Pay Sheet">
               <tr >
                    <td width="40%">Transaction mode</td>
                    <td width="60%" colspan="2"><?php echo $this->form2->paymenttype;?><?php //echo $this->form2->paymenttype_details;?></td>
                    
                </tr>
                <tr>
                    <td id="cheque" style="display:none">Voucher/cheque/draft</td>
                    <td id="etransfer" style="display:none">Account number</td>
                    <td id="textbox" style="display:none"><?php echo $this->form2->othertext;?></td> 
                </tr>
                <tr>
                    <td width="40%"><label for="fld1">Description</label></td>
                    <td width="60%"><?php echo $this->form2->transactiondescription;?></td>
                </tr>
               <tr >
                    <TD colspan="2"><?php  
                    echo $this->form2->accountId;echo $this->form2->productId; echo $this->form2->memberId; echo $this->form2->capitalamount;echo $this->form2->interestamountto; echo $this->form2->penalinterest;
                    echo $this->form2->paymenttype1;
                    echo $this->form2->paymenttype_details1;
                    echo $this->form2->transactiondescription1;
                    echo $this->form2->maturedinterestamount;?>
                    </TD>
                </tr>
            </table>
            <table id="hor-minimalist-bjinu">

            <div class="btnhouse">
                <div class="ltbtns">
                   <?php echo $this->form2->Submit;?>
                </div>
                <div class="rtbtns">
                   <a href="<?php echo $this->baseUrl();?>/fixedtransaction/index/fixed/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>">
                    <input name="submit" type="submit" value="back"></a>
                </div>
            </div>

             <tr>
                       <td colspan="4"><B style="color:red"><? echo $this->noaccount1;?></B></td>
             </tr>
            </table>
        </form>

    </div>
</div>
<?php } ?>

    <? } else { ?>
    <B style="color:red"><? echo $this->noaccount; } ?></B>


