<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script language="javascript">
 function getInterests(interest) {	
            targeturl='<?php echo $this->baseUrl();?>/fixedaccount/index/getinterests?interest='+interest;
            $.ajax({ url: targeturl, success: function(data){ $('#interestdiv').html(data) }});
       }



 $(document).ready(function(){
       $("a#groupmem").click(function(event){
            $("tr.two").toggle();
      }); 
    }); 

 $(document).ready(function(){
	        //iterate through each textboxes and add keyup
        //handler to trigger sum event
	        $(".txt").each(function() {
 	            $(this).keyup(function(){
                calculateSum();
	            });
	        });
	
	    function calculateSum() {

	        var sum = 0;
	        //iterate through each textboxes and add the values
	        $(".txt").each(function() {
	 	            //add only if the value is number
            if(!isNaN(this.value) && this.value.length!=0) {
	                sum += parseFloat(this.value);
           }
	        });
	        //.toFixed() method will roundoff the final sum to 2 decimal places
	        $(".amount1").val(sum.toFixed(2)); 
	    }
    });
</script>

<div style="float:left;width:380px"> 
    <table id="hor-minimalist-s" summary="Employee Pay Sheet">

        <?php $a =1;
foreach($this->account as $account) {
if($a == 1) {
?>
            <TR>
                <TH>Member details</TH>
                <TH></TH>
            </TR>
            <TR>
                <TD>Member code:</td>
                <TD><? echo $account['code']; ?></TD>
            </TR>
            <TR>
                <TD>Name:</td>
                <TD><?php echo $account['name'];?></TD>
            </TR>
            <TR>
                <TD>Branch:</td>
                <TD><?php echo $account['officename'];?></TD>
            </TR>
            <TR>
                <td>Group name</td><td><?php echo $account['groupname'];?></td>
            </TR>
<?php  } 
foreach($this->offerdetails as $offer) {
?>

            <TR>
                <TH>Product details</TH>
                <TH></TH>
            </TR>
            <TR>
                <TD>Product name:</td>
                <TD><?php echo $offer['productname'];?></TD>
            </TR>
            <TR>
                <TD>Min balance:</b></td>
                <TD><?php echo $offer['minbalance'];?></TD>
            </TR> 
            <TR>
                <TD>Max balance:</b></td>
                <TD><?php echo $offer['maxbalance'];?></TD>
            </TR>
            <TR>
                <TD>Penal interest</td>
                <TD><?php echo $offer['mininterest']; ?></TD>
            </TR>
            <TR>
                <TH>Interest per annum</TH>
                <TH></TH>
            </TR>
            <TR>
                <TD><B>Periods in months</B></TD>
                <TD><B>Interest</B></TD>
            </TR>
        <?php $a++; } }  ?>
        <?php if ($this->interestRates) {
                foreach ($this->interestRates as $interestRates) { ?>
                    <TR>
                        <TD><?php echo $interestRates->period_ofrange_description; ?></TD>
                        <TD><?php echo $interestRates->Interest; ?></TD>
                    </TR>
                <?php } 
        } ?>
    </table>

</div>
<div style="float:left;width:350px">
   <?php if(count($this->gp_members)) { ?>
        <a href="#" id="groupmem">Individual / Group deposit </a>
    <?php } ?> 
<fieldset>
    <br>
    <legend>New fixed account</legend>
    <form name="fixedform" id="validation" action="<?php echo $this->baseUrl();?>/fixedaccount/index/createaccount" method="POST">
<div class="one">
    <table class="fieldsets">
        <TR>
            <TD><label for="fld1" class="mand">Date of account</label></TD>
            <TD><?php echo $this->fixedForm->date;?></TD>
        </TR>
        
        <?php if($this->gp_members) {
                foreach ($this->gp_members as $group) { ?>
        <TR style="display:none;" class="two">
            <TD><label for="fld1"><?php echo $group['name']; ?></label></TD>
            <TD><input type = "text" name="<?php echo $group['id']; ?>"  class="txt" onchange = "calculateSum(this.value)"></TD>
        </TR>
        <?php } }?>

        <TR>
            <TD><label for="fld1" class="mand">Period</label></TD>
            <TD><?php echo $this->fixedForm->period;?></TD>
        </TR>
        <TR>
            <TD><label for="fld1" class="mand">Interest</label></TD>
            <TD><div id="interestdiv"><?php echo $this->fixedForm->interest;?></div></TD>
        </TR>
        <TR>
            <TD><label for="fld1" class="mand">Fixed amount</label></TD>
            <TD class="amount1"><?php echo $this->fixedForm->tAmount;?></TD>
        </TR>

         <TR>
            <TD  colspan="2" style="display:none;" id="ertxt"><input type="text" class="Error" name="Error" id="Error"/></TD>
        </TR>
        <TR>
            <TD><?php echo $this->fixedForm->Submit; ?></TD>
            <td><a href="<?php echo $this->baseUrl();?>/fixedaccount/index"><?php echo $this->fixedForm->Back; ?></a></td>
        </Td>
        <?php echo '<font color=RED>'.$this->maxdate.'</font>'; ?>
    </table>
</div>
<?php echo $this->fixedForm->Id; ?> 
<?php echo $this->fixedForm->memberId; ?> 
 <?php echo $this->fixedForm->code; ?> 
    </form>
</div>
