<form name="addform" action="<?php echo $this->baseUrl();?>/bank/index/addbank" method="POST">
	<fieldset>
    	<legend>Add bank</legend> 
    	<table class="fieldsets"> 
            <?php echo $this->form;?>
        </table>
        <div class="btnhouse">
	    	<div class="ltbtns">
				<?php echo $this->submitform->Submit;?>
	   		</div>
	   		<div class="rtbtns">
				<a href="<?php echo $this->baseUrl();?>/bank"><input type = "button" name = "Back" value = "Back"></a>
	   		</div>
        </div>
	</fieldset>
</form>


 
