<fieldset>
    <legend>Delete Bank</legend>
	<form name = "deleteform" action="<?php echo $this->baseUrl();?>/bank/index/deletebank" method="POST">
	   <table class="fieldsets">
			<TR>
            	<TD  ><label for="fld1" class="mand">Remarks</label></TD>
		    	<TD  ><?php echo $this->form->remarks;?></TD>					
			</TR>
		</table>
		<div class="btnhouse">
	   		<div class="ltbtns">
				<?php echo $this->submitform->Submit;?>
	   		</div>
	   		<div class="rtbtns">
				<a href="<?php echo $this->baseUrl();?>/institution"><input type = "button" name = "Back" value = "Back"></a>
	   		</div>
        </div>
	    <input type = "hidden" name = "id" value = "<?php echo $this->id; ?>">
	</form>
</fieldset>
