<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<html>
</head>
   <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("ಕಟುಂಬದ ವಿವರ"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    $i=0;
    foreach($this->membername as $family_view){  $i++; ?>

    <tr>
        <!--<td ><?php echo $this->translate("ಕುಟುಂಬದ ಕೋಡ :"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td> -->
        <td ><?php echo $this->translate("ಮನೆ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("ರೇಷನ್ ಕಾರ್ಡ್:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("ಬೀದಿ /ರಸ್ತೆ:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("ಆರೋಗ್ಯ ವಿಮೆ:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಕಂದಾಯ ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("ಉದ್ಯೋಗಖಾತ್ರಿ ಜಾಬ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>   
    </tr>

    <tr>
        <td ><?php echo $this->translate(" ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("ಆದಾಯದ ಪ್ರಮುಖ ಮೂಲ:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ವಿಧ :"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("ದೂರವಾಣಿ:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("ಜಾತಿ:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("ಮೊಬೈಲ್ :"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>

   <!-- <tr>
        <td ><?php echo $this->translate("ಜಾತಿ:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td></td>
        <td></td>
    </tr>-->
   <?php } ?>
</table> 
<br/>

<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">      
    <form name="form1" id="pluginForm" action="<?php echo $this->baseUrl();?>/familymembers/index/editfamily/id/<?php echo $this->id; ?>/subId/<?php echo $this->subId; ?>/modId/<?php echo $this->modId; ?>" method="POST">
        <table id="hor-minimalist-b" class="family">
            <tr> 
                <!--<th><?php echo $this->translate("* Name"); ?></th>-->
                <th><?php echo $this->translate("ಹೆಸರು"); ?></th>
                <!--<th><?php echo $this->translate("Alias"); ?></th>-->
                <th><?php echo $this->translate("ಅಲಿಯಾಸ್"); ?></th>
                <th><?php echo $this->translate("ತಂದೆಯ ಹೆಸರು"); ?></th>
                <th><?php echo $this->translate("ಯು ಎಯೇ ಡೀ"); ?></th>
                <th><?php echo $this->translate("ಪ್ರ್ಧಧಾನ ಸಂಪಾದಕ"); ?></th>
                <th><?php echo $this->translate("ಕುಟುಂಬದ ಮುಖ್ಯಸ್ಥ"); ?></th>
                <th><?php echo $this->translate("* ಲಿಂಗ"); ?></th>
                <th><?php echo $this->translate("* ಜನ್ಮ ದಿನಾಂಕ"); ?></th>
                <th><?php echo $this->translate("ವಯಸ್ಸು"); ?></th>
                <th><?php echo $this->translate("* ಸಂಬಂಧ"); ?></th>
                <!--<th><?php echo $this->translate("* ಲಿಂಗ"); ?></th>-->
                <th><?php echo $this->translate("* ವೈವಾಹಿಕ ಸ್ಥಿತಿ"); ?></th>
                <th><?php echo $this->translate("ಪೆನ್ಷನ್"); ?></th>
                <th><?php echo $this->translate("* ವಿಧ್ಯಾಬ್ಯಾಸ"); ?></th>
                <th><?php echo $this->translate("* ಉಧ್ಯೋಗ"); ?></th>
                <th><?php echo $this->translate("ವೃತ್ತಿ"); ?></th>
                <th><?php echo $this->translate("* ಸಂಘ"); ?></th>
                <th><?php echo $this->translate("* ಸಂಘದ ಹೆಸರು"); ?></th>
                <th><?php echo $this->translate("* ಖಾತೆ ವಿದ"); ?></th>
                <th><?php echo $this->translate("* ಬ್ಯಾಂಕ್/ ಅಂಚೆ"); ?></th>
                <th><?php echo $this->translate("* ಶಾಖೆ"); ?></th>
                <th><?php echo $this->translate("* ಬ್ಯಾಂಕ್ ಸಂಖ್ಯೆ"); ?></th>
                <th><?php echo $this->translate("ದೂರವಾಣಿ"); ?></th>
                <th><?php echo $this->translate("* ಬ್ಲಡ್ ಗ್ರೂಪ್"); ?></th>
                <th><?php echo $this->translate("Can Sign"); ?></th><th></th>

            </tr>
            <?php $i = 0; ?>
            <?php foreach ($this->familydetails as $familydetails) { $i++;?>
             <?php if ($i == 1) { ?>
             <tr id='tmp'>
            <?php } else { ?>
            <tr>
            <?php } ?>
                <td><INPUT type="text" name = "mem_name[]" class="required" value="<?php echo $familydetails['name']; ?>" maxlength="30" size="15"></td>
                <!--<td><INPUT type="text" name = "mem_relname[]"  value="<?php echo $familydetails['name_inregional']; ?>" size="15" maxlength="30" class="noncharacters" readonly="true"></td>-->
                <td><INPUT type="text" name = "alias_name[]" size="15" value="<?php echo $familydetails['alias']; ?>" maxlength="20" ></td>
                <!--<td><INPUT type="text" name = "alias_relname[]" size="15" value="<?php echo $familydetails['alias_inregional']; ?>" maxlength="20" class="noncharacters" readonly="true"></td>-->
               <td><INPUT type="text" name = "father_name[]" maxlength="30" size="15" value="<?php echo $familydetails['father_name']; ?>"></td>
                <td><INPUT type="text" name = "uid[]" id="uid-<?php echo $i ?>" value="<?php echo $familydetails['uid']; ?>" maxlength="16" size="15" class="numeric uidvalid uidvaltext">
		<div id="uiddiv-<?php echo $i ?>" class="uidclass"><input type="hidden" id="hiddenid-<?php echo $i; ?>" name="uidhidden" value=1></div>
                </td>

                <?php if($familydetails['breadwinner_id']==1){ ?>
                <td align="center"><INPUT type="radio" name = "breadwinner[]" checked="true" value="<?php echo $i ?>"></td>
                <?php } else { ?>
                <td align="center"><INPUT type="radio" name = "breadwinner[]" value="<?php echo $i ?>"></td>
                <?php } ?>

                <?php if($familydetails['head_id']==1){ ?>
                <td align="center"><INPUT type="radio" name = "head[]" checked="true" value="<?php echo $i ?>"></td>
                <?php } else { ?>
                <td align="center"><INPUT type="radio" name = "head[]" value="<?php echo $i ?>"></td>
                <?php } ?>

                <td><select name = "gender[]" class="selectvalid required">
                <option value=0>select</option>
                <?php 
                foreach ($this->gender as $gender) 
                {
                    if($gender['id']!= $familydetails["gender_id"]) { ?>
                        <option value="<?php echo $gender['id']?>"><?php echo $gender['id'];echo ".  "; echo $gender['name_regional']?></option>

                <?php } else { ?>
                        <OPTION value="<?php echo $familydetails["gender_id"]; ?>" selected="">
                            <?php echo $gender['id'];echo ".  "; echo $familydetails["gendername"]; ?>
                        </OPTION>
                <?php } }     ?>
                </select>
                </td>

                <td><INPUT type="text" name = "dob[]" class="date required datechange" id="date-<?php echo $i; ?>" value="<?php echo $convertdate->normalformat($familydetails['dob']); ?>"></td>
                <INPUT type="hidden" name = "currentdate[]" id="currentdate" value="<?php echo $this->currentdate?>"></td>
                <td><INPUT type="text" name = "age[]" size="3" maxlength="3" value="<?php echo $familydetails['age']?>" class="agechange" id="age-<?php echo $i; ?>"></td> 
                <td>
                    <select name = "relation[]" class="selectvalid required">
                    <option value=0>select</option>
                    <?php 
                    foreach ($this->relation as $relation) 
                    {
                        if($relation['id']!= $familydetails["relationship_id"]) { ?>
                            <option value="<?php echo $relation['id']?>"><?php echo $relation['id']; echo ".  " ; echo $relation['name_regional']?></option>
                        <?php } else { ?>
                                <OPTION value="<?php echo $familydetails["relationship_id"]; ?>" selected="">
                                <?php echo $familydetails["relationship_id"]; echo ".  ";  echo $familydetails["relationname"]; ?>
                            </OPTION>
                <?php }
                    }     ?>
                    </select>
                </td>


                <!--<td><select name = "gender[]" class="selectvalid required">
                <option value=0>select</option>
                <?php 
                foreach ($this->gender as $gender) 
                {
                    if($gender['id']!= $familydetails["gender_id"]) { ?>
                        <option value="<?php echo $gender['id']?>"><?php echo $gender['id'];echo ".  "; echo $gender['name_regional']?></option>

                <?php } else { ?>
                        <OPTION value="<?php echo $familydetails["gender_id"]; ?>" selected="">
                            <?php echo $gender['id'];echo ".  "; echo $familydetails["gendername"]; ?>
                        </OPTION>
                <?php } }     ?>
                </select>
                </td>-->

                <td><select name = "marital[]" class="selectvalid required">
                        <option value=0>select</option>
                <?php 
                foreach ($this->marital as $marital) 
                {
                    if($marital['id']!= $familydetails["maritalstatus_id"]) { ?>
                        <option value="<?php echo $marital['id']?>"><?php echo $marital['id']; echo ".  "; echo $marital['name_regional']?></option>

                    <?php } else { ?>
                        <OPTION value="<?php echo $familydetails["maritalstatus_id"]; ?>" selected="">
                            <?php echo $familydetails["maritalstatus_id"]; echo ".  "; echo $familydetails["maritalname"]; ?>
                        </OPTION>
                <?php } } ?>
                </select>
                </td>
         <?php 
			$signlist = array();
            $entitlelist = array();
            $proflist = array();
            $familyobj = new Familymembers_Model_Familymembers();
            $professionlist=$familyobj->getprofession($familydetails['id']);
	    if($professionlist){
	    $profnone=1;
            foreach($professionlist as $professionlist){ 
                    $proflist[] = $professionlist['profession_id'];
            //print_r($proflist);
            }}
	    else{
	    $profnone=0;
		}
                $entitlementslist=$familyobj->getentitlement($familydetails['id']);
		if($entitlementslist){
		$entitlenone=1;
                foreach($entitlementslist as $entitlementslist){ 
                $entitlelist[] = $entitlementslist['entitlement_id']; 
            	}}
		else {
		$entitlenone=0;
		} ?>
                <td>
                <div style="OVERFLOW-Y:scroll; WIDTH:200px; HEIGHT:50px">
		<?php if($entitlenone==0) { ?>
		<input type="checkbox" name="entitle-<?php echo $i; ?>-[]" value=0 checked class="entitleid1 entitlenone-<?php echo $i; ?>">None<br />
		<?php } else { ?>
		<input type="checkbox" name="entitle-<?php echo $i; ?>-[]" value=0 class="entitleid1 entitlenone-<?php echo $i; ?>">None<br />
		<?php } ?>
                <?php foreach ($this->entitlements as $entitlements) {
                if(in_array($entitlements['id'],$entitlelist)) {  
                 ?>
                <input type="checkbox" name="entitle-<?php echo $i; ?>-[]" value="<?php echo $entitlements['id'];  ?>" checked class ="entitleid entitlevalid-<?php echo $i; ?>"><?php echo $entitlements['id']; echo ".  "; echo $entitlements['name'];  ?><br />
                <?php } else { ?><input type="checkbox" name="entitle-<?php echo $i; ?>-[]" value="<?php echo $entitlements['id'];  ?>" class="entitleid entitlevalid-<?php echo $i; ?>"><?php echo $entitlements['id'];  echo ".  " ; echo $entitlements['name_regional'];  ?><br />

                <?php } } ?>
                <div>
                </td>

                <td><select name = "education[]" class="selectvalid required">
                        <option value=0>select</option>
                    <?php foreach ($this->qualify as $qualify) { 
                                if($qualify['id']!= $familydetails["eductaion_id"]) { ?>
                    <option value="<?php echo $qualify['id']?>"><?php echo $qualify['id']; echo ".  "; echo $qualify['name_regional']?></option>

                    <?php } else { ?> 
                        <OPTION value="<?php echo $familydetails["eductaion_id"]; ?>" selected="">
                            <?php echo $familydetails["eductaion_id"]; echo ".  "; echo $familydetails["qualifyname"]; ?>
                        </OPTION>
                    <?php } } ?>
                </select>    
                </td>

                <td>
                <select name = "employ_status[]" class="selectvalid required">
                        <option value=0>select</option>
                    <?php foreach ($this->employment as $employment) { 
                                if($employment['id']!= $familydetails["employment_status"]) { ?>
                    <option value="<?php echo $employment['id']?>"><?php echo $employment['id']; echo ".  "; echo $employment['name_regional']?></option>

                    <?php } else { ?>
                        <OPTION value="<?php echo $familydetails["employment_status"]; ?>" selected="">
                            <?php echo $familydetails["employment_status"]; echo ".  "; echo $familydetails["employmentname"]; ?>
                        </OPTION>
                    <?php } } ?>
                </select>
                </td>


                <td>
                <div style="OVERFLOW-Y:scroll; WIDTH:200px; HEIGHT:50px">
		<?php if($profnone==0){ ?>
		<input type="checkbox" name="profid-<?php echo $i; ?>-[]" value=0 checked class="profid1 profidnone-<?php echo $i; ?>">None<br />
		<?php } else { ?>
		<input type="checkbox" name="profid-<?php echo $i; ?>-[]" value=0 class="profid1 profidnone-<?php echo $i; ?>">None<br />
		<?php } ?>
                <?php foreach ($this->proffession as $proffession) { 
                if(in_array($proffession['id'],$proflist)) {
		?>
                <input type="checkbox" name="profid-<?php echo $i; ?>-[]" value="<?php echo $proffession['id']; ?>" checked class="profid profidvalid-<?php echo $i; ?>"><?php echo $proffession['id']; echo ".  "; echo $proffession['name_regional'];  ?><br />
		<?php } else { ?>
                <input type="checkbox" name="profid-<?php echo $i; ?>-[]" value="<?php echo $proffession['id'];  ?>" class="profid profidvalid-<?php echo $i; ?>"><?php echo $proffession['id']; echo ".  "; echo $proffession['name_regional'];  ?><br />
		<?php }} ?>
                <div>
                </td>

                <?php
                      $familymodel=new Familymembers_Model_Familymembers();
                     $branchname=$familymodel->getbranch($familydetails["bank"]);
                     $cbos=$familymodel->getcbo($familydetails["promoter_id"]);
					 $gpdetails=$familymodel->getgpid($this->village1);
        			 $gpid=$gpdetails[0]['panchayath_id'];
                     $banknames=$familymodel->getbank($familydetails["accouttype_id"],$gpid);
                ?>

               <td>
                <select name = "cbopromoter[]" class="selectvalid cbofilter"  id="cbopromoter-<?php echo $i; ?>">
                        <option value=0>select</option>
                    <?php foreach ($this->promoter as $cbopromoter) { 
                                if($cbopromoter['id']!= $familydetails["promoter_id"]) { ?>
                    <option value="<?php echo $cbopromoter['id']?>"><?php echo $cbopromoter['id']; echo ".  "; echo $cbopromoter['name_regional']?></option>

                    <?php } else { ?>
                        <OPTION value="<?php echo $familydetails["promoter_id"]; ?>" selected="">
                            <?php echo $familydetails["promoter_id"]; echo ".  "; echo $familydetails["promoter"]; ?>
                        </OPTION>
                    <?php } } ?>
                </select>
                </td>

                <td><div id="cbodiv-<?php echo $i; ?>" class="cboclass">
                        <select name = "cbo[]" class="selectvalid required" id="cbo-<?php echo $i; ?>">
                        <option value=0>Select</option>
                     <?php
                     foreach ($cbos as $cbos) {  
                     if($cbos['id']!= $familydetails["cbo_id"]) { ?>
                    <option value="<?php echo $cbos['id']?>"><?php echo $cbos['id']; echo ".  "; echo $cbos['cboname']?></option>
                    <?php } else { ?> 
                    <OPTION value="<?php echo $familydetails["cbo_id"]; ?>" selected="">
                        <?php echo $familydetails["cbo_id"]; echo ".  "; echo $familydetails["cbos"]; ?>
                    </OPTION>
                    <?php } } ?>
                        </select>
                    </div>
                </td>

                <td><select name = "accounttype[]" class="selectvalid findbank" id="accounttype-<?php echo $i; ?>">
                    <option value=0>Select</option>
                    <?php foreach ($this->accounttype as $accounttype) {
                    if($accounttype['id']!= $familydetails["accouttype_id"]) {?>
                    <option value="<?php echo $accounttype['id']?>"><?php echo $accounttype['id']; echo ".  "; echo $accounttype['name_regional']?></option>
                    <?php } else { ?> 
                    <OPTION value="<?php echo $familydetails["accouttype_id"]; ?>" selected="">
                        <?php echo $familydetails["accouttype_id"]; echo ".  "; echo $familydetails["accountype"]; ?>
                    </OPTION>
                    <?php } } ?>
                </select>
                <INPUT type="hidden" name = "baseurl[]" id="baseurl" value="<?php echo $this->baseurl?>"></td>
                </td>

                <td>
                <div id="bankdiv-<?php echo $i; ?>" class="bankclass">
                    <select name = "bank[]" class="selectvalid bankfilter" id="bank-<?php echo $i; ?>">
                        <option value=0>select</option>
                <?php
                        foreach ($banknames as $banknames) {  
                        if($banknames['bank_id']!= $familydetails["bank"]) { ?>
                        <option value="<?php echo $banknames['bank_id']?>"><?php echo $banknames['bank_id']; echo ".  "; echo $banknames['bankname']?></option>
                        <?php } else { ?> 
                        <OPTION value="<?php echo $familydetails["bank"]; ?>" selected="">
                            <?php echo $familydetails["bank"]; echo ".  "; echo $familydetails["bankname"]; ?>
                        </OPTION>
                        <?php }} ?>
                    </select>
                </div>
                    <INPUT type="hidden" name = "baseurl[]" id="baseurl" value="<?php echo $this->baseurl?>"></td>
                </td>

                <td>

                <div id="branchdiv-<?php echo $i; ?>" class="branchclass">
                    <select name = "branch[]" class="selectvalid required">
                        <option value=0>select</option>
                    <?php
                     foreach ($branchname as $branch) {  
                     if($branch['id']!= $familydetails["branch_po"]) { ?>
                    <option value="<?php echo $branch['id']?>"><?php echo $branch['id']; echo ".  "; echo $branch['branchname']?></option>
                    <?php } else { ?> 
                    <OPTION value="<?php echo $familydetails["branch_po"]; ?>" selected="">
                        <?php echo $familydetails["branch_po"]; echo ".  "; echo $familydetails["branchname"]; ?>
                    </OPTION>
                    <?php } } ?>
                </select>
                </div>
                </td>
                <td><INPUT type="text" name = "bankAccount[]" value="<?php echo $familydetails['bank_ac']?>" maxlength="17"></td>


                <td><INPUT type="text" name = "mobile[]" value="<?php echo $familydetails['mobile_number']?>" class="numeric" maxlength="10">
                   <INPUT type="hidden" name = "recordid[]" value="<?php echo $familydetails['id']?>">
                </td>

                <td><select name = "blood[]" class="selectvalid required">
                        <option value=0>select</option>
                    <?php echo '<pre>'; print_r($this->blood); foreach ($this->blood as $blood) { 
                      if($blood['id']!= $familydetails["blood_id"]) { ?>
                    <option value="<?php echo $blood['id']?>"><?php echo $blood['name']?></option>
                    <?php } else { ?> 
                    <OPTION value="<?php echo $familydetails["blood_id"]; ?>" selected="">
                    <?php echo $familydetails["blood"]; ?>
                    </OPTION>
                    <?php } } ?>
                </select>
                </td>

                <?php if($familydetails['sign']==1){ ?>
                <td align="center"><INPUT type="checkbox" name = "sign[]" checked="true" value="<?php echo $i ?>"></td>
                <?php } else { ?>
                <td align="center"><INPUT type="checkbox" name = "sign[]" value="<?php echo $i ?>"></td>
                <?php } ?>

                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
            </tr>
<?php } ?>
           <input type="hidden" name="villageid" id="villageid" value="<?php echo $this->village1; ?>">
        </table>  

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="submit" id="Update" name="Update" value="<?php echo $this->translate("Update"); ?>">
<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->id ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
</div>

</html>