<script type="text/javascript">
    $('.bankfilter').change(function() {
        var id=$(this).attr("id").split("-");
        if($(this).val())
        {  bank_id=$(this).val();
           path=$('#baseurl').val();
           targeturl=path+"/familymembers/index/getbranch?bank_id="+bank_id;
	   $.ajax({ url: targeturl, success: function(data){ $('#branchdiv-'+id[1]).html(data) }});
        }
    });
</script>
<select name = "bank[]" class="selectvalid bankfilter" id="<?php echo "bank-".$this->selectid; ?>">
                     <option value=0>Select</option>
                    <?php foreach ($this->banknames as $banknames) { ?>
                    <option  value="<?php echo $banknames['id']?>"><?php echo $banknames['bankname']?></option>
                    <?php } ?>
</select>

