<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                <form action="<?php echo $this->baseUrl();?>/officemeetingindex/index" method="POST">
                    <table width="100%">
                        <tr>
                            <td class="label">Meeting frequency:</td>
                            <td ><? echo $this->form->frequency;?></td>
                            <td class="label">Meeting name:</td>
                            <td ><? echo $this->form->meetingname;?></td>
                        </tr>

                        <tr>
                            <td class="label">Meeting place:</td>
                            <td ><? echo $this->form->place;?></td>
                            <td class="label">Office Level:</td>
                            <td ><? echo $this->form->office;?></td>
                        </tr>

                    </table>
                    <div class="btnhouse">
                        <div class="ltbtns">
                        <input type="Submit" name="Search" value="Search">
                        </div>
                    </div>
                </form>	
            </div>
    </fieldset> 
</div> 

<?php if ((count($this->paginator)) != 0 ) : ?>
    <table id="hor-minimalist-b" summary="">
        <tr class="tdbrownheading">
            <th>Meeting name</th>
            <th>Office</th>
        </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $meeting ): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl()."/officemeetingcommonview/index/index/meeting_id/".$meeting['id']; ?>"><?php echo $this->escape($meeting['name']);?></a></td>
            <td><?php echo $this->escape($meeting['officename']); ?></td>
        <?php endforeach; ?>
        <?php endif; ?>

        <tr>
            <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                        '/partials/my_pagination_control.phtml'); ?></div></td>
        </tr>
        </tr>
    </table>
<?php endif; ?>

<?php /*echo $this->translate('Category Name');*/ ?>