<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script src="<?php  echo $this->baseUrl();?>/js/lib/jquery.js" type="text/javascript"></script>
<script src="<?php  echo $this->baseUrl();?>/js/lib/jquery.metadata.js" type="text/javascript"></script>
<script src="<?php  echo $this->baseUrl();?>/js/lib/jquery.validate.js" type="text/javascript"></script>
<script type="text/javascript">
$.metadata.setType("attr", "validate");

$(document).ready(function() {
	$("#form1").validate();
	$("#selecttest").validate();
});
</script>

<style type="text/css">
.block { display: block; }
form.cmxform label.error { display: none; }	
</style>
 <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("ಕಟುಂಬದ ವಿವರ"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    foreach($this->membername as $family_view){ ?>

<!--<tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ಕೋಡ :"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>-->
    <tr>
        <td ><?php echo $this->translate("ಮನೆ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("ರೇಷನ್ ಕಾರ್ಡ್:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಬೀದಿ /ರಸ್ತೆ:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("ಆರೋಗ್ಯ ವಿಮೆ:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಕಂದಾಯ ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("ಉದ್ಯೋಗಖಾತ್ರಿ ಜಾಬ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate(" ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("ಆದಾಯದ ಪ್ರಮುಖ ಮೂಲ:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ವಿಧ :"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("ದೂರವಾಣಿ:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಜಾತಿ:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate(" ಮೊಬೈಲ್ :"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>   <?php } ?>
</table> 
<br/>
<div >
	<form method="POST" class="cmxform" id="form1">
	<table id="hor-minimalist-b" >
		<tr> 
    			<th><?php echo $this->translate("ಕ್ರ.ಸಂ"); ?></th>
    			<th><?php echo $this->translate("ಮೂಲಭೂತ ಸೌಕರ್ಯದ ವಿವರ"); ?></th>
    			<th><?php echo $this->translate("ವಿಧ "); ?></th>
		</tr>
		<tr>
		   <td>1</td>
		    <td><font color="green"><b>* </b></font> ಮನೆ ವಿದ</td>
		    <td valign="top">
			<?php foreach($this->housetype as $housetype) { ?>
			<label style="float:left;width:100px;"> 
<input type="Radio" name="housetype" value="<?php echo $housetype['id']; ?>" validate="required:true" />
<?php echo $housetype['name_regional']; ?></label>
			<?php } ?><BR />
			<label for="housetype" class="error" style="float:left; color:red;">Please select your House Type</label>
		   </td>
		</tr> 

		<tr>
			<td>2</td>
			<td><font color="green"><b>* </b></font> ಮನೆ ಮಾಲಿಕತ್ವ</td>
		    <td valign="top">
			<?php foreach($this->ownership as $ownership) { ?>
			<label style="float:left;width:100px;"> 
<input type="Radio" name="ownership" value="<?php echo $ownership['id']; ?>" validate="required:true" />
<?php echo $ownership['name_regional']; ?> 
                        </label>
			<?php } ?><br>
			<label for="ownership" class="error" style="float:left; color:red;">Please select Ownership</label>
		   </td>
		</tr> 
		<tr>
			<td>3</td>
			<td><font color="green"><b>* </b></font> ಅಡುಗೆ ಇಂಧನ</td>
		    <td valign="top">
			<?php foreach($this->cookingfuel as $cookingfuel) { ?>
			<label style="float:left;width:100px;"> 
<input type="Radio" name="cookingfuel" value="<?php echo $cookingfuel['id']; ?>" validate="required:true" />
<?php echo $cookingfuel['name_regional']; ?> 
                    </label>
			<?php } ?><BR /><BR /><BR>
			<label for="cookingfuel" class="error" style="float:left; color:red;">Please select Primary Cooking fuel</label>
		   </td>
		</tr> 

		<tr> 
			<td>
<input type="submit" id="submit" name="submit" value="<?php echo $this->translate('Submit'); ?>" >
                        </td><td><a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>">
				<input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a></td>
			
		</tr>
	</table>
	</form>
</div>
