<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<div >
 <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("Family information"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    foreach($this->membername as $family_view){ ?>
<tr>
        <td ><?php echo $this->translate("Family ID:"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>
    <tr>
        <td ><?php echo $this->translate("House No:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("Ration card:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Street/Road/Lane:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("Health Insurance:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Rev Village:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("NREGS Job Card No:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate("Colony/Habitation:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("Major source of income:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("Family type:"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("Contact Phone:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Category:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("Mobile:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>
   <?php } ?>
</table> 
<br/>
<form action="<?php echo $this->baseUrl();?>/infrastructure/index/edit/id/<?php echo $this->memberid; ?>" method="POST">
<table id="hor-minimalist-b">
		<tr> 
    			<th width="3%"><?php echo $this->translate("SL"); ?></th>
    			<th width="35%"><?php echo $this->translate("Access to Basic Infrastructure"); ?></th>
    			<th width="auto"><?php echo $this->translate("Types"); ?></th>
		</tr>
		<tr>
		   <td>1</td>
		    <td>Housing Type</td>
		    <td valign="top">
			<?php 
			if($this->edithousingtype) { 
			foreach($this->edithousingtype as $edithousingtype) {  $edithousing[]=$edithousingtype['housetype_id'];  }
			} else { $edithousing[]='0'; }
			foreach($this->housetype as $housetype) { 
				
			if(in_array($housetype['id'],$edithousing,true)){ ?>
<div style="float:left;width:80px;"> <input type="Radio" checked='true' name="housetype" value="<?php echo $housetype['id']; ?>"><?php echo $housetype['name']; ?></div>
			<?php } else { ?>
	<div style="float:left;width:80px;"> <input type="Radio" name="housetype" value="<?php echo $housetype['id']; ?>"><?php echo $housetype['name']; ?></div>
			<?php } } ?>
		   </td>
		</tr> 

		<tr>
			<td>2</td>
			<td>House Ownership</td>
		    <td>
			<?php if($this->editownership) { 
				foreach($this->editownership as $editownership) {  $editowner[]=$editownership['ownership_id'];  } 
			} else { $editowner[]='0'; }

			foreach($this->ownership as $ownership) {
				
			if(in_array($ownership['id'],$editowner,true)){ ?>
<div style="float:left;width:80px;"><input type="Radio" checked='true' name="ownership" value="<?php echo $ownership['id']; ?>"><?php echo $ownership['name']; ?></div>
			<?php } else { ?>
<div style="float:left;width:80px;"> <input type="Radio" name="ownership" value="<?php echo $ownership['id']; ?>">  <?php echo $ownership['name']; ?> </div>
			<?php } } ?>
		   </td>

		</tr> 
		<tr>
			<td>3</td>
			<td>Primary cooking fuel</td>


		    <td>
			<?php 
			if($this->editcookfuel) { 
			foreach($this->editcookfuel as $editcookfuel) { $editcook[]=$editcookfuel['fuel_id'];  } } else { $editcook[]='0'; }
			foreach($this->cookingfuel as $cookingfuel) {
				
			if(in_array($cookingfuel['id'],$editcook,true)){ ?>
<div style="float:left;width:80px;"> <input type="Radio" checked='true' name="cookingfuel"  value="<?php echo $cookingfuel['id']; ?>">  <?php echo $cookingfuel['name']; ?> </div>
			<?php } else { ?>
<div style="float:left;width:80px;"> <input type="Radio" name="cookingfuel" value="<?php echo $cookingfuel['id']; ?>">  <?php echo $cookingfuel['name']; ?> </div>
			<?php } } ?>
		   </td>


		</tr> 
			<td><input type="submit" id="update" name="update" value="<?php echo $this->translate('Update'); ?>"></td><td><a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>">
				<input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a></td>
			
		</tr>

</table>
</form>
</div>
 ?>
		   </td>


		</tr> 
			<td><input type="submit" id="update" name="update" value="<?php echo $this->translate('Update'); ?>"></td><td><a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>">
				<input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a></td>
			
		</tr>

</table>
</form>
</div>
