<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/toggel.js"></script> 
<script type="text/javascript">
 $(document).ready(function(){

$(".tmode option[value='5']").remove();


        $('.tmode').change(function() {
            var v = $(this).val();
            var id = $(this).attr('id');
        if(id == 'transactionMode'){
            if(v!=1){
                if(v==5){
                        $('#etransfer').show();
                        $('#textbox').show();
                        $('#cheque').hide();
                }else{
                        $('#cheque').show();
                        $('#textbox').show();
                        $('#etransfer').hide();
                }
            }
            else{
                        $('#etransfer').hide();
                        $('#textbox').hide();
                        $('#cheque').hide();

            }
        }   
else
{

            if(v!=1){
                if(v==5){
                        $('#etransfer1').show();
                        $('#textbox1').show();
                        $('#cheque1').hide();
                }else{
                        $('#cheque1').show();
                        $('#textbox1').show();
                        $('#etransfer1').hide();
                }
            }
            else{
                        $('#etransfer1').hide();
                        $('#textbox1').hide();
                        $('#cheque1').hide();

            }
    }
         });
     });
</script>
<?php if(count($this->details)) { ?>

<div style="float:left;width:350px"> 
    <?php foreach($this->details as $details) { ?>
        <table id="hor-minimalist-s">
            <TR>
                <TH>Member details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td>Name </td>
                <TD><?php echo $details->name ?></TD>
            </TR>

            <TR>
                <td>Branch</td>
                <TD><?php echo $details->officename ?></TD>
            </TR>
            <TR>
                <td>Code</td>
                <TD><?php echo $details->code ?></TD>

            </TR>
            <TR>
                <TH>Account details</TH>
                <TH></TH>
            </TR>
            <TR>
                <td> Account number</td>
                <td><?php echo $details->number ?></TD>
            </TR>
            <TR>
                <td>Product name</td>
                <td><?php echo $details->offername ?></TD>
            </TR>
            <TR>
                <td>Created date</td>
                <td><?php echo $details->createdDate ?></TD>
            </TR>
            <TR>
                <td>Balance</td>
                <td><?php echo $this->balance ?></TD>
            </TR>
        </table> 
    <?php } ?>
    <?php if(count($this->group)) { ?>
	<div class="container">
	   <h2 class="trigger"><a href="#">Group Members</a></h2>
            <div class="toggle_container">
                <div class="block">
                    <table id="hor-minimalist-s">
                        <TR>
                            <TH>Member code </TH>
                            <TH>Member name</TH>
                        </TR>
                        <?php foreach ($this->group as $group) { ?>
			  <TR>
                            <td><?php echo $group->code; ?></b></td>
                            <td><?php echo $group->name; ?></TD>
                        </TR>
                        <?php }?>
		    </table>
                </div>
            </div>
	</div>
    <?php } ?>
</div>
<?php } ?>
<div style="float:right;width:350px"> 
    <?php if(count($this->group)) { ?>
        <a href="javascript:unhide('group','sum');" >Individual / Group deposit</a>
    <?php } ?> 
    <fieldset>
        <legend>Savings deposit </legend>
        <form name="form1" action="<?php echo $this->baseUrl();?>/savingsdeposit/index/deposit/" method="POST">
 
        <div id="sum" style="display:block">
            <table class="fieldsets">

                <TR>
                    <TD><label for="fld1" class="mand">Date</label></TD>
                    <TD><?php echo $this->form->date; ?></TD>
                </TR>

                <TR>
                    <TD><label for="fld1" class="mand">Amount R$</label></TD>
                    <TD><?php echo $this->form->amount;?></TD>
                </TR>
				<TR>
                    <TD><label for="fld1" class="mand">Transaction mode</label></TD>
                    <TD><?php echo $this->form->transactionMode;?></TD>
                </TR>
                <tr>
                    <td id="cheque" style="display:none">Voucher/cheque/draft</td>
                    <td id="etransfer" style="display:none">Account number</td>
                    <td id="textbox" style="display:none"><?php echo $this->form->othertext;?></td> 
                </tr>
                <TR>
                    <TD><label for="fld1" class="mand">Description</label></TD>
                    <TD><?php echo $this->form->description;?></TD>
                </TR>
<?php echo '<font color=RED>'.$this->maxdate.'</font>'; ?>

            </table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Submit;?>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/savingsdeposit/index"><?php echo $this->form->Back;?></a>
                </div>
            </div>
        </div>
            <?php if (count($this->group) != 0) { ?>
            <div id="group" style="display:none">
            <table class="fieldsets">
                <TR>
                    <TD><label for="fld1" class="mand">Date</label></TD>
                    <TD><?php echo $this->form->date1; ?></TD>
                </TR>
                
                <?php foreach ($this->group as $group) { ?>
                <TR>
                    <TD><label for="fld1"><?php echo $group->name; ?></label></TD>
                    <TD><input type = "text" name="<?php echo $group->code; ?>" size="12" class="txt" onchange = "calculateSum(this.value)"></TD>
                </TR>

                <?php } ?>
                <TR>
                    <TD><label for="fld1">Total amount</label></TD>
                    <TD><input class = "amount1" type = "text" name="amount1" size="12" class="txt_put" readonly="true"></TD>
                </TR>
		<TR>
                    <TD><label for="fld1" class="mand">Transaction mode</label></TD>
                    <TD><?php echo $this->form->transactionMode1;?></TD>
                </TR>
                <tr>
                    <td id="cheque1" style="display:none">Voucher/cheque/draft</td>
                    <td id="etransfer1" style="display:none">Account number</td>
                    <td id="textbox1" style="display:none"><?php echo $this->form->othertext1;?></td> 
                </tr>
                <TR>
                    <TD><label for="fld1" class="mand">Description</label></TD>
                    <TD><?php echo $this->form->description1;?></TD>
                </TR>
            </table>
            <div class="btnhouse">

                <div class="ltbtns">
                    <?php echo $this->form->Submit;?>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/savingsdeposit/index"><?php echo $this->form->Back;?></a>
                </div>
           </div>         </div>

         <?php } ?>
    	   <?php echo $this->form->accNum; ?>
        </form>
    </fieldset>

</div>
<?php if(count($this->tran) > 0) { ?>
<table id="hor-minimalist-b">
    <tr>
        <th>V No.</td>
        <th>Transaction date</td>
        <th>Credit</td>
        <th>Debit</td>
        <th>Payment mode</td>
        <th>Transacted by</td>  
    </tr>
    <?php foreach($this->tran as $transaction) : ?>
    <tr>
       <td><?php echo $transaction->id; ?></td>
       <td><?php echo $transaction->date; ?></td>
       <?php if ($transaction->cr) {?>
       <td><?php echo $transaction->cr; ?></td>
       <?php } else { ?>
       <td>----</td>
       <?php } ?>
       <?php if ($transaction->dt) { ?> 
       <td><?php echo $transaction->dt; ?></td>
       <?php } else { ?>
       <td>----</td>
       <?php } ?>

       <td><?php echo $transaction->mode; ?></td>
       <td><?php echo $transaction->name; ?></td>
    </tr>
    <?php endforeach;  ?>
</table>
<p align="right"><font color="green"><b>Current Balance :<?php echo $this->balance;?></b></font></p>
<?php } ?>
