<fieldset>
    <legend>Search account</legend>
    <form action="<?php echo $this->baseUrl();?>/savingsdeposit/index" method="POST">
        <table class="fieldsets">
            <tr>
                <td><label for="fld1" class="mand">Account number</label></td>
                <td><?php echo $this->form->accNum;?></td>
            </tr>
        </table>
        <div class="btnhouse">
            <div class="ltbtns">
                <?php echo $this->form->Search;?><br><br>
                <table><TR><TD><font color="red" size="2"><?php echo $this->error;?></font></TD></TR></table>
            </div>
        </div>
    </form>
</fieldset>