<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?php echo $this->escape($this->title); ?></title>


</head>
<body>
<div id="container">

    <div id="header"><?php echo $this->render('accountheader.phtml'); ?></div>

  <div id="leftnavig">


        <?php if($this->pageTitle == "Accounting") { ?>
	<h4><a href="#">Accounting</a></h4>
        <ul>
           <li ><a href="<?php echo $this->baseUrl();?>/savingaccount">Personal savings</a></li>
           <li ><a href="<?php echo $this->baseUrl();?>/fixedaccount">Fixed savings</a></li>
	   	   <li ><a href="<?php echo $this->baseUrl();?>/recurringaccount">Recurring savings</a></li>
	   	   <li ><a href="<?php echo $this->baseUrl();?>/loanaccount">Loan a/c</a></li>

	</ul>
	<?php } ?>
        <?php if($this->pageTitle == "Savings") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/savingaccount">Personal savings</a></li>
                </ul>
	<?php } ?>

        <?php if($this->pageTitle == "Fixed") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/fixedaccount">Fixed savings</a></li>
                </ul>
	<?php } ?>

        <?php if($this->pageTitle == "Recurring") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/recurringaccount">Recurring savings</a></li>
                </ul>
	<?php } ?>

	<?php if($this->pageTitle == "Loans") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/loanaccount">Loan a/c</a></li>
                </ul>
	<?php } ?>
  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>

  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>

</html>

