<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?php echo $this->escape($this->title); ?></title>
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset-min.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/styles.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />

<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script> 
<script>
$(document).ready(function() {
    $("#loanAccountdate").datepicker({"dateFormat":"dd/mm/yy"});
    $("#date").datepicker({"dateFormat":"dd/mm/yy"});
    $("#date1").datepicker({"dateFormat":"dd/mm/yy"});

});
</script>
</head>
<body>
<div id="container">

    <div id="header"><?php echo $this->render('accountheader.phtml'); ?></div>

  <div id="leftnavig">


        <?php if($this->pageTitle == "Accounting") { ?>
	<h4><a href="#">Accounting</a></h4>
        <ul>
           <li ><a href="<?php echo $this->baseUrl();?>/savingaccount">Personal savings</a></li>
           <li ><a href="<?php echo $this->baseUrl();?>/fixedaccount">Fixed savings</a></li>
	   <li ><a href="<?php echo $this->baseUrl();?>/recurringaccount">Recurring savings</a></li>
	   <li ><a href="<?php echo $this->baseUrl();?>/loanaccount">Loan a/c</a></li>
	   <li ><a href="<?php echo $this->baseUrl();?>/loanprocess">Loan Request</a></li>
<!--             <li ><a href="<?php echo $this->baseUrl();?>/declaration">Declaration</a></li>-->
	</ul>
	<?php } ?>
        <?php if($this->pageTitle == "Savings") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/savingaccount">Personal savings</a></li>
                </ul>
	<?php } ?>

        <?php if($this->pageTitle == "Fixed") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/fixedaccount">Fixed savings</a></li>
                </ul>
	<?php } ?>

        <?php if($this->pageTitle == "Recurring") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/recurringaccount">Recurring savings</a></li>
                </ul>
	<?php } ?>

	<?php if($this->pageTitle == "Loans") { ?>
		<h4><a href="#">Accounting</a></h4>
		<ul>
                    <li ><a href="<?php echo $this->baseUrl();?>/loanaccount">Loan a/c</a></li>
                </ul>
	<?php } ?>

<?php if($this->pageTitle == "Loan request" || $this->pageTitle == $this->levelname.' approval process') { ?>
               <h4><a href="#">Accounting</a></h4>
 
               <ul>
                   <li><a href="<?php  echo $this->baseUrl();?>/loanprocess/index"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64.png" border=0 width="16" height="16">Search</a></li>
                   <li ><a href="<?php echo $this->baseUrl();?>/loanprocess/index/newprocess"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New loan request</a></li>
               </ul>
               <ul>
                   <li ><a href="<?php echo $this->baseUrl();?>/loanprocess/index/loanstatus">Requested status</a></li>
               </ul>
                <ul>
<!--                    <li ><a href="<?php //echo $this->baseUrl();?>/loanprocess/index/jlgadvances">Jlg advances</a></li> -->
               </ul>
               <ul>
<!--                    <li ><a href="<?php //echo $this->baseUrl();?>/loanprocess/index/shgindex">Shg advances</a></li> -->
               </ul>
       <?php } ?>
	
                <?php if($this->pageTitle == "Declaration") { ?>
                                <h4><a href="#">Accounting</a></h4>
                                <ul>
                                    <li ><a href="<?php echo $this->baseUrl();?>/declaration">Declaration</a></li>
                                </ul>
                        <?php } ?>
  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>

  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>

</html>

