<?php echo $this->render('header.phtml'); ?>


    <div id="navigation">
      <div id="mainmenu">
     <ul>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/accounting"><span>Accounting</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/transaction"><span>Transaction</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/maintenance"><span>Maintenance</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/meetingmain"><span>Meeting</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/membership"><span>Membership</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/management"><span>Management</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/dropdown"><span>Setting</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/reports"><span>Reports</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/loanprocessing"><span>Loan process</span></a></li>
        </ul>
      </div>
      <div id="submenu">
        <ul>
	   <?php if($this->pageTitle == "Account") { ?>
	   	<li class="selected"><a href="<?php echo $this->baseUrl();?>/account">Loans</a></li>
	   <?php } else { ?>
           <li ><a href="<?php echo $this->baseUrl();?>/savingaccount">Personal savings</a></li>
           <li ><a href="<?php echo $this->baseUrl();?>/fixedaccount">Fixed savings</a></li>
            <li ><a href="<?php echo $this->baseUrl();?>/recurringaccount">Recurring savings</a></li>
            <li ><a href="<?php echo $this->baseUrl();?>/loanaccount">Loan a/c</a></li>
    	   <li ><a href="<?php echo $this->baseUrl();?>/loanprocess">Loan request</a></li>
<!--            <li ><a href="<?php echo $this->baseUrl();?>/declaration">Declaration</a></li>-->


	   <?php } ?>
        </ul>
      </div>
    </div>


