<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<head>
<title><?php echo $this->escape($this->title); ?></title>
<link href="<?php  echo $this->baseUrl();?>/css/reset-min.css" rel="stylesheet" type="text/css" />
<link href="<?php  echo $this->baseUrl();?>/css/styles.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="container">

    <div id="header"><?php echo $this->render('defaultheader.phtml'); ?></div>


    <div id="pagetitle">
        <h2><?php echo $this->pageTitle;?></h2>
    </div>
  <div id="leftnavig">
    <h4><a href="#">Home</a></h4>
    <ul>
      <li><a href="<?php  echo $this->baseUrl();?>/index/address"> Contact us</a></li>
      <li><a href="#">Site map</a></li>
      <li><a href="#">Site news</a></li>
      <li><a href="#">Learning centre</a></li>
    </ul>
  </div>

    <div id="pagecontent">
        <?php echo $this->layout()->content; ?>
    </div>

  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>
</html>
