<div id="ourbanklogo">
      <h1><a href="#" title="OurBank">OurBank</a></h1>
    </div>
    <div id="welcomebar"><span class="welcomusr">Welcome <a href="#"><?php echo $this->username;?></a></span> <span class="longdate"><?php echo date("r");?></span><span class="signout"><a href="<?php  echo $this->baseUrl();?>/index/logout">signout</a></span>
    </div>

    <div id="navigation">
      <div id="mainmenu">
       <ul>
	<li><a href="<?php  echo $this->baseUrl();?>/accounting"><span>Accounting</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/transaction"><span>Transaction</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/maintenance"><span>Maintenance</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/meetingmain"><span>Meeting</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/membership"><span>Membership</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/management"><span>Management</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/dropdown"><span>settings</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/reports"><span>Reports</span></a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/loanprocessing"><span>Loan process</span></a></li>



        </ul>
      </div>
        <?php if(!$this->member1){ ?>
      <div id="submenu">
           <ul>
         </ul>
      </div>
      <?php } ?> 
</div>

