<head>
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset-min.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/styles.css" />
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script> 
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />


<script>
$(document).ready(function() {
    $("#field1").datepicker({"dateFormat":"dd/mm/yy"});
   
});
</script>
</head> 
<body>
<div id="container">
    <div id="header"><?php echo $this->render('loanprocessingheader.phtml'); ?></div>
  <div id="leftnavig">
   <h4><a>Templates</a></h4>
   <ul>
		<li class="selected"><a href="<?php  echo $this->baseUrl();?>/grouplaw">1. Group by law</a></li>
		<li class="selected"><a href="<?php  echo $this->baseUrl();?>/groupprofile">2. Group social economic</a></li>
		<li class="selected"><a href="<?php  echo $this->baseUrl();?>/groupresolution">3. Group resolution to open a bank account</a></li>
		<li class="selected"><a href="<?php  echo $this->baseUrl();?>/sbwithdrawal">4. Group resolution to withdraw from SB account</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/groupresolutionkoota">5. Group resolution to become a member of koota</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/internalloan">6. Individual loan request</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/memberldeatils">7. Internal loan application by member</a></li>
 		<li class="selected"><a href="<?php  echo $this->baseUrl();?>/groupgrading/index/shgindex">8. Group grading</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/familyform">9. External loan application individualy</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/thumbdeclaration">10. Literate declaration</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/affidavit">11. Member affidavit  for bank loan</a></li>
    	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/externalloan">12. Group resolution for Bankloan</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/sbi">13. SBI loan application</a></li>
   </ul>
  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>

  <div id="footer">
    <div id="copytxt"> Mahiti Infotech Pvt. Ltd., <a href="#">Terms &amp; Conditions</a></div>
  </div>
</div>
</BODY>
</html>

