<?php echo $this->render('header.phtml'); ?>


    <div id="navigation">
      <div id="mainmenu">
     <ul>
	<li ><a href="<?php  echo $this->baseUrl();?>/accounting"><span>Accounting</span></a></li>
	<li ><a href="<?php  echo $this->baseUrl();?>/transaction"><span>Transaction</span></a></li>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/maintenance"><span>Maintenance</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/meetingmain"><span>Meeting</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/membership"><span>Membership</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/management"><span>Management</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/dropdown"><span>Settings</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/reports"><span>Reports</span></a></li>
                <li><a href="<?php  echo $this->baseUrl();?>/loanprocessing"><span>Loan process</span></a></li>

        </ul>
      </div>
      <div id="submenu">
        <ul>
           <?php if($this->pageTitle == "Day end") { ?>
	   	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/maintenance/dayend">Day end</a></li>
	   <?php } else { ?>
	   	<li><a href="<?php  echo $this->baseUrl();?>/maintenance">Day end</a></li>
	   <?php } ?>
	   <?php if($this->pageTitle == "Month end") { ?>
	   	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/monthend">Month end</a></li>
	   <?php } else { ?>
	   	<li><a href="<?php  echo $this->baseUrl();?>/monthend">Month end</a></li>
	   <?php } ?>
        </ul>
      </div>
    </div>


