<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?php echo $this->escape($this->title); ?></title>
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset-min.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/styles.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script> 

<script>
$(document).ready(function() {
    $("#loanAccountdate").datepicker({"dateFormat":"dd/mm/yy"});
    $("#date").datepicker({"dateFormat":"dd/mm/yy"});
    $("#date1").datepicker({"dateFormat":"dd/mm/yy"});

});
</script>
</head>
<body>
<div id="container">

    <div id="header"><?php echo $this->render('maintenanceheader.phtml'); ?></div>

  <div id="leftnavig">


        <?php if($this->pageTitle == "Maintenance" || $this->pageTitle == "Day end" || $this->pageTitle == "Month end") { ?>
	<h4><a href="#">Maintenance</a></h4>
        <ul>
           <li ><a href="<?php echo $this->baseUrl();?>/maintenance/index">Day end</a></li>
           <li ><a href="<?php echo $this->baseUrl();?>/monthend">Month end</a></li>

	</ul>
	<?php } ?>
       

  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>

  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>

</html>

