<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<link type="image/x-icon" href="<?php echo $this->baseUrl();?>/images/linklog.jpeg" rel="shortcut icon"/>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery-1.2.3.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/runonload.js"></script>
<!--<script src="<?php echo $this->baseUrl();?>/js/member/jqueryval.js"></script>-->
<script language="JavaScript" src="<?php echo $this->baseUrl();?>/js/member/jquery.autotab.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery-1.1.3.1.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery.history_remote.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery.tabs.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/member.js"></script>
<title><?php echo $this->escape($this->title); ?></title>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery.tabs.pack.js"></script>
<link href="<?php  echo $this->baseUrl();?>/css/reset-min.css" rel="stylesheet" type="text/css" />
<link href="<?php  echo $this->baseUrl();?>/css/styles.css" rel="stylesheet" type="text/css" />
<?php echo $this->jQuery(); ?>
</head>
<body>
<div id="container">

    <div id="header"><?php echo $this->render('membershipheader.phtml'); ?></div>

  <div id="leftnavig">
     <ul>
            <?php if($this->pageTitle == "Membership") { ?>
	      <h4><a href="#">Membership</a></h4>
	      <li><a href="<?php  echo $this->baseUrl();?>/individualm">Individual</a></li>
  	      <li><a href="<?php  echo $this->baseUrl();?>/groupm">Group</a></li>
            <?php } ?>
   </ul>


 
<?php if($this->pageTitle == "Group") { ?>
   <h4><a href="#">Group</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/groupm/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
     <li><a href="<?php  echo $this->baseUrl();?>/groupmdefault/index/addgroup"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New group</a></li>
   </ul>
<?php } ?>

<?php if($this->pageTitle == "Individual" || $this->pageTitle == "Family members details" || $this->pageTitle == "Individual crop details" || $this->pageTitle == "Agriculture" || $this->pageTitle == "Non living assets" || $this->pageTitle == "Living assets" || $this->pageTitle == "Expense details" || $this->pageTitle == "Loan details" || $this->pageTitle == "Income details" || $this->pageTitle == "Services required by the family") { ?>
   <h4><a href="#">Individual</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/individualm/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
     <li><a href="<?php  echo $this->baseUrl();?>/individualdefault/index/addmembername"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New Individual</a></li>
   </ul>
<?php } ?>

<?php if($this->pageTitle == "Crop") { ?>
   <h4><a href="#">Individual</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/individualm/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
     <li><a href="<?php  echo $this->baseUrl();?>/individualdefault/index/addmembername"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New Individual</a></li>
   </ul>
<?php } ?>

   
  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>
  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>
</html>
