
<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->  
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<link type="image/x-icon" href="<?php echo $this->baseUrl();?>/images/linklog.jpeg" rel="shortcut icon"/>
<title><?php echo $this->escape($this->title); ?></title>


<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset-min.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/styles.css" />

<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/dp/jquery.datepick.css" />
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-1.3.1.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/dp/jquery.datepick.js"></script>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/familymembers.js"></script>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/familydefault.js"></script>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/assets.js"></script>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery.selectboxes.pack.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#memberdateofbirth").datepick({dateFormat: 'dd/mm/yyyy'});
    $("#Created_Date").datepick({dateFormat: 'dd/mm/yyyy'});
});
</script>
</head>
<body>
<div id="container">
    <div id="header"><?php echo $this->render('membershipheader.phtml'); ?></div>
  <div id="leftnavig">
     <ul>
            <?php if($this->pageTitle == "Membership") { ?>
	      <h4><a href="#">Membership</a></h4>
	      <li><a href="<?php  echo $this->baseUrl();?>/family">Family</a></li>
  	      <li><a href="<?php  echo $this->baseUrl();?>/individual">Individual</a></li>
  	      <li><a href="<?php  echo $this->baseUrl();?>/groupm">Group</a></li>
<!--               <li><a href="<?php // echo $this->baseUrl();?>/koota">Koota</a></li> -->
            <?php } ?>
   </ul>


 
<?php if($this->pageTitle == "Group") { ?>
   <h4><a href="#">Group</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/groupm/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
     <li><a href="<?php  echo $this->baseUrl();?>/groupmdefault/index/addgroup"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New group</a></li>
   </ul>
<?php } ?>

<?php if($this->pageTitle == "koota") { ?>
   <h4><a href="#">Koota</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/koota/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
     <li><a href="<?php  echo $this->baseUrl();?>/kootadefault/index/addkoota"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New koota</a></li>
   </ul>
<?php } ?> 

<?php if($this->pageTitle == "Individual") { ?>
   <h4><a href="#">Individual</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/individual/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
   </ul>
<?php } ?>




<?php if($this->pageTitle == "Family" || $this->pageTitle == "Family Information" || $this->pageTitle == "Individual crop details" || $this->pageTitle == "Agriculture" || $this->pageTitle == "Other assets owned" || $this->pageTitle == "Livestock" || $this->pageTitle == "Expense details" || $this->pageTitle == "Loan details" || $this->pageTitle == "Income details" || $this->pageTitle == "Services required by the family" || $this->pageTitle == "Family loan details" || $this->pageTitle == "Family savings details" || $this->pageTitle == "Health"  || $this->pageTitle == "(PRA Based) Service Requirement at family member level" || $this->pageTitle == "Basic Infrastructure" || $this->pageTitle == "Family Member Details") { ?>
   <h4><a href="#">Family</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/family/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
     <li><a href="<?php  echo $this->baseUrl();?>/familydefault/index/addfamily"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New family</a></li>
   </ul>
<?php } ?>

<?php if($this->pageTitle == "Insurance") { ?>
   <h4><a href="#">Insurance</a></h4>
   <ul>
     <li><a href="<?php  echo $this->baseUrl();?>/insurance/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Insurance</a></li>
   </ul>
<?php } ?>

</div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>
  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>
</html>
