<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<head>
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset-min.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/styles.css" />
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script> 
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />


<script>
$(document).ready(function() {
    $("#field1").datepicker({"dateFormat":"dd/mm/yy"});
    $("#field2").datepicker({"dateFormat":"dd/mm/yy"});
   $("#datefrom").datepicker({"dateFormat":"dd/mm/yy"});
    $("#dateto").datepicker({"dateFormat":"dd/mm/yy"});
    $("#date1").datepicker({"dateFormat":"dd/mm/yy"});
});
</script>
</head> 
<body>
<div id="container">
    <div id="header"><?php echo $this->render('reportsheader.phtml'); ?></div>


  <div id="leftnavig">
    <?php if($this->type == "savings") { ?>
    <h4><a>Savings</a></h4>
    <ul>
      <li><a href="<?php  echo $this->baseUrl();?>/reports/sbcashscroll/index/type/savings">SB supplementary</a></li>
      <li><a href="<?php  echo $this->baseUrl();?>/reports/personalsavings/index/type/savings"> personal savings Details</a></li>
      <li><a href="<?php  echo $this->baseUrl();?>/reports/Savingsummary/index/type/savings">Savings summary</a></li>
      <li><a href="<?php  echo $this->baseUrl();?>/reports/Saccountsummary/index/type/savings">Savings account Summary</a></li>
    </ul>
    <?php } ?>
<?php if(($this->pageTitle == "Reports") && (!$this->type == "generalFields"))  { ?>
    <h4><a href="#">Reports</a></h4>
    <ul>
        <li><a href="<?php  echo $this->baseUrl();?>/reports/index/index/type/generalFields">General Fields</a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/reports/index/index/type/financialReports">Financial Reports</a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/reports/index/index/type/operationalReports">Operational Reports</a></li>
     </ul>
    <?php } ?>


   <?php if($this->type == "generalFields") { ?>
   <h4><a>Genaral fields</a></h4>
   <ul>
	<li><a href="<?php  echo $this->baseUrl();?>/ledgerbalancebook">Ledger balance book</a></li>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/generalledger">General ledger</a></li>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/loanledger">Loan ledger</a></li>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/summarymfi">Summary of MFI</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/depositsummary">Deposit summary</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/savingsledger">Savings ledger</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/personalsavings">Personal savings</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/overduelist">Overdue list</a></li>


   </ul>
   <?php } ?>

    <?php if($this->type == "financialReports") { ?>
    <h4><a>Financial reports</a></h4>
    <ul>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/cashscroll">Cash Scroll</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/daybook">Day Book</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/transferscroll">Transfer Scroll</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/loansupplementary">Loan supplementary</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/meetingbookreport">Meetingbook Report</a></li>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/sbcashscroll">Sb supplementary</a></li>
    </ul>
    <?php } ?>

      <?php if($this->type == "operationalReport") { ?>
    <h4><a>Oparational reports</a></h4>
    <ul>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/incomeexpenditure">Income & expenditure</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/receiptpayment">Receipt & payment</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/dcb">DCB</a></li>
        <li class="selected"><a href="<?php  echo $this->baseUrl();?>/par">PAR</a></li>
    </ul>
    <?php } ?>
  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>

  <div id="footer">
    <div id="copytxt"> Mahiti Infotech Pvt. Ltd., <a href="#">Terms &amp; Conditions</a></div>
  </div>
</div>
</BODY>
</html>

