<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<head>
<title><?php echo $this->escape($this->title); ?></title>

</head>


<body>
<div id="container">
    	<div id="header"><?php echo $this->render('settingsheader.phtml'); ?>
	</div>


  	<div id="leftnavig">

    	<h4><a href="#">Settings</a></h4>
     		<ul>
		 <li><a href="<?php  echo $this->baseUrl();?>/dropdown">Master Data</a></li>
<!--         <li><a href="<?php  echo $this->baseUrl();?>/language/">Languages</a></li>
		 <li><a href="<?php  echo $this->baseUrl();?>/sms">SMS</a></li>-->
     		</ul>
  	</div>

    	<div id="pagecontent">
        	<h3><?php echo $this->pageTitle;?></h3>
        	<?php echo $this->layout()->content; ?>
    	</div>

  	<div id="footer">
    		<?php echo $this->render('footer.phtml'); ?>
  	</div>
</div>
</body>
</html>

