<head>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-1.3.1.js"></script>
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset-min.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/styles.css" />
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script> 
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />


<script>
$(document).ready(function() {
    $("#loanAccountdate").datepicker({"dateFormat":"dd/mm/yy"});
    $("#date").datepicker({"dateFormat":"dd/mm/yy"});
    $("#date1").datepicker({"dateFormat":"dd/mm/yy"});
    $("#recurringDate").datepicker({"dateFormat":"yy-mm-dd"});
     $("#transactiondate").datepicker({"dateFormat":"yy-mm-dd"});

});
</script>
</head> 



<?php echo $this->render('header.phtml'); ?>


    <div id="navigation">
      <div id="mainmenu">
     <ul>
	<li ><a href="<?php  echo $this->baseUrl();?>/accounting"><span>Accounting</span></a></li>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/transaction"><span>Transaction</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/maintenance"><span>Maintenance</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/meetingmain"><span>Meeting</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/membership"><span>Membership</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/management"><span>Management</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/dropdown"><span>Settings</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/reports"><span>Reports</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/loanprocessing"><span>Loan process</span></a></li>

        </ul>
      </div>
      <div id="submenu">
        <ul>
           <?php if($this->pageTitle == "Savings") { ?>
	   	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/savingsdeposit">Savings</a></li>
	   <?php } else { ?>
	   	<li><a href="<?php  echo $this->baseUrl();?>/savingsdeposit">Savings</a></li>
	   <?php } ?>
		
	   <?php if($this->pageTitle == "Loans") { ?>
	   
	   	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/loandisbursmentg">Loans</a></li>
	   <?php } else { ?>
	   	<li><a href="<?php  echo $this->baseUrl();?>/loandisbursmentg">Loans</a></li>
	   <?php } ?>
       	   <?php if($this->pageTitle == "Loans") { ?>
	   
	   	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/recurringtransaction">Recurring</a></li>
	   <?php } else { ?>
	   	<li><a href="<?php  echo $this->baseUrl();?>/recurringtransaction">Recurring</a></li>
	   <?php } ?>

            <?php if($this->pageTitle == "Savings") { ?>
            <li class="selected"><a href="<?php  echo $this->baseUrl();?>/fixedtransaction">Fixed</a></li>
	   <?php } else { ?>
	   	<li><a href="<?php  echo $this->baseUrl();?>/fixedtransaction">Fixed</a></li>
	   <?php } ?>
	   <li ><a href="<?php echo $this->baseUrl();?>/ledgerreport">Ledger Report</a></li>
	   <li ><a href="<?php echo $this->baseUrl();?>/receipts">Receipts and payments</a></li>
	   <li ><a href="<?php echo $this->baseUrl();?>/cashtransactions">Cash Transactions</a></li>
   	   <li ><a href="<?php echo $this->baseUrl();?>/altertransaction">Alter transaction</a></li>
           <li ><a href="<?php echo $this->baseUrl();?>/amounttransfer">Amount transfer</a></li>

        </ul>
      </div>
    </div>


