<!--<script type="text/javascript">
$(document).ready(
  function() {
//     $('#showemi').click()(function() {
	    $('#showemi').click(function(){
    $('#emichart').slideToggle();
});
});
</script>-->
<script type="text/javascript">
function toggle(showHideDiv) {
       var ele = document.getElementById(showHideDiv);
       if(ele.style.display == "block") {
               ele.style.display = "none";
//               imageEle.innerHTML = '<img src="<?php echo $this->baseUrl();?>/images/down.png/"/>';
       }
       else {
               ele.style.display = "block";
//               imageEle.innerHTML = '<img src="<?php echo $this->baseUrl();?>/images/down.png/"/>';
       }
}
</script>
<?php if (count($this->details)) { ?>
 <div style="float:left;width:350px"> 
    <?php foreach($this->details as $details) { ?>
        <table id="hor-minimalist-s">
            <tr>
                <th>Menber details</th>
                <th></th>
            </tr>
            <tr>
                <td>Name </td>
                <td><?php echo $details->name ?></td>
            </tr>

            <tr>
                <td>Branch</td>
                <td><?php echo $details->officename ?></td>
            </tr>
            <tr>
                <td>Code</td>
                <td><?php echo $details->code ?></td>

            </tr>
            <tr>
                <td> Account code</td>
                <td><?php echo $details->number ?></td>
            </tr>
            <tr>
                <th>Loan Details</th>
                <th></th>
            </tr>
            <tr>
                <td>Loan name</td>
                <td><?php echo $details->loanname ?></td>
            </tr>
            <tr>
                <td>Loan amount R$</td>
                <td><?php echo $details->amount ?></td>
            </tr>
            <tr>
                <td>Interest rate %</td>
                <td><?php echo $details->interest ?></td>
            </tr>

            <tr>
            <td>Installments</td>
                <td><?php echo $details->installments ?></td>
            </tr>
            <tr>
                <td>Sanctioned date</td>
                <td><?php echo $details->sanctioned ?></td>
            </tr>
            <tr>
                <td>Fee</td>
                <td></td>
            </tr> 
        </table> 
    <?php } ?>
    <br/>
</div>
<div style="float:right;width:350px"> 
        <table id="hor-minimalist-s" border="1">
            <tr>
                <th colspan="9">Installment status</th>
               <?php if($this->intesttype!=3) { ?> <th>No.</th> <?php } ?>
                <th colspan="9">Amount (R$)</th>
            </tr>
            <tr>
                <td colspan="9">Paid</td>
				<?php foreach ($this->paid as $paid) { ?>
<?php if($this->intesttype!=3) { ?><td><?php echo $paid->paidCount ; ?></td> 
                                <td colspan="9"><?php echo $paid->paidAmt; ?></td>
<?php } else { ?>
                <td colspan="9"><?php echo sprintf("%4.2f",$this->paidamound); ?></td>
				<?php } } ?>
            </tr>
            <tr>
                <td colspan="9">Due</td>
				<?php foreach ($this->unpaid as $unpaid) { ?>
<?php if($this->intesttype!=3) { ?><td><?php echo $unpaid->unpaidCount ; ?></td> 
                <td colspan="9"><?php echo $unpaid->unpaidAmt ; ?></td>
<?php } else { ?>
                <td colspan="9"><?php echo sprintf("%4.2f",$this->balanceamount); ?></td>
				<?php } } ?>
            </tr>

</table>
</div>
<?php $convertdate = new App_Model_dateConvertor(); ?>
<div id="headerDivImg">
    <div id="titleTextImg">
    <span><a title="Expand/Collapse" href="javascript:toggle('contentDivImg_1');">&nbsp;EMI Chart</a></span>
</div>
<div id="contentDivImg_1" style="display: none;">
    <table id="hor-minimalist-b" border="1">
        <tr>
            <th>Inst.</th>
            <th>Inst.principal (R$)</th>
            <th>Inst.interest (R$)</th>
            <th>Inst. amt (R$)</th>
            <th>Due date</th>
            <th>Status</th>
<?php if($this->intesttype==3) { ?>
            <th>Paid amount (R$)</th>

            <th>Balance (R$)</th>
<?php } ?>
        </tr>
        <?php 
            $total1 = 0;
            $total2 = 0;
            $total3 = 0;
            $total4 = 0;
            $total5 = 0;
            $total6 = 0;
        ?>
        <?php foreach($this->instalments as $instalments) { ?>
        <tr>
            <td><?php echo $instalments['installment_id']; ?></td>
            <td align="right"><?php echo $instalments['installment_principal_amount']; 
                            $total1 = $total1 + $instalments['installment_principal_amount'];
                        ?></td>
            <td align="right"><?php echo $instalments['installment_interest_amount'];

                            $total2 = $total2 + $instalments['installment_interest_amount'];
                        ?></td>

            <td align="right"><?php echo $instalments['installment_amount'];
                            $total4 = $total4 + $instalments['installment_amount'];
                             ?></td>


            <td align="right"><?php echo $convertdate->phpnormalformat($instalments['installment_date']);  ?></td>
            <td align="right"><?php echo $instalments['name'];  ?></td>
	<?php if($this->intesttype==3) { ?>
            <td align="right"><?php echo $instalments['paid_amount']; 
                $total5 = $total5 + $instalments['paid_amount'];
                ?></td>
            <td align="right"><?php echo $instalments['balance']; 
                $total6 = $total6 + $instalments['balance'];
                ?></td>
	<?php } ?>
        </tr>
        <?php } ?>
        <tr>
            <td>Total</td>
            <td align="right"><?php echo sprintf("%4.2f", $total1); ?></td>
            <td align="right"><?php echo sprintf("%4.2f", $total2); ?></td>
            <td align="right"><?php echo sprintf("%4.2f", $total4); ?></td>
            <td></th>
            <td></td>
<?php if($this->intesttype==3) { ?>
            <td align="right"><?php echo sprintf("%4.2f", $total5); ?></td>
            <td align="right"><?php echo sprintf("%4.2f", $total6	); ?></td>
<?php } ?>
        </tr>
    </table>
</div>
</div>
<br>
    <?php if($this->intesttype==3){ ?>
    <table id="hor-minimalist-b" border="1">
        <tr>
            <th>S.No</th>
            <th>Repayment Date</th>
            <th>Payment mode</th>
            <th>Credit (R$)</th>
            <th>Debit (R$)</th>
            <th>Balance amount (R$)</th>
        </tr>

        <?php $i=0; $totaldeclain=0; $balanceamount=0; foreach($this->declainedpaid as $declainedpaid) { $i++; ?>
        <tr>
	    <td><?php echo $i; ?></td>
            <td><?php echo $convertdate->phpnormalformat($declainedpaid['paid_date']); ?></td>
            <td><?php echo "By ".$declainedpaid['paymentmode']." ".$declainedpaid['transaction_description']; ?></td>
            <td align="right"><?php echo sprintf("%4.2f", $declainedpaid['paid_amount']);
		$totaldeclain+=$declainedpaid['paid_amount'];
		 ?></td>
            <td align="right"><?php echo sprintf("%4.2f", $declainedpaid['paid_interest']);
		 ?></td>           
            <td align="right"><?php echo sprintf("%4.2f", $declainedpaid['balanceamount']);
		$balanceamount+=$declainedpaid['balanceamount'];
		 ?></td>
        </tr>
        <?php } ?>
        <tr>
            <td>Total</td>
            <td></td>
            <td align="right"></td>
            <td align="right">Rs <?php echo sprintf("%4.2f", $totaldeclain) ; ?></td>
            <td></td>
            <td></td>
        </tr>
    </table>
	<?	} 
	} else { ?>
    Invalid number
<?php } ?>