<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("Family information"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    foreach($this->membernames as $family_view){ ?>
<tr>
        <td ><?php echo $this->translate("Family ID:"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>
    <tr>
        <td ><?php echo $this->translate("House No:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("Ration card:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Street/Road/Lane:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("Health Insurance:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Rev Village:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("NREGS Job Card No:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate("Colony/Habitation:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("Major source of income:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("Family type:"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("Contact Phone:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Category:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("Mobile:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>
	 <?php } ?>
</table> 
<br/>
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;"> 
    <form id="pluginForm" action="<?php echo $this->baseUrl();?>/loandetails/index/add/id/<?php echo $this->memberid; ?>" method="POST">
        <table id="hor-minimalist-b" class="family">
            <tr> 
                <th width="27%"><?php echo $this->translate("Source"); ?></th>
                <th width="17%"><?php echo $this->translate("Family member"); ?></th>
                <th width="27%"><?php echo $this->translate("Loan amount"); ?></th>
                <th width="17%"><?php echo $this->translate("Interest Per Annum %"); ?></th>
                <th width="37%"><?php echo $this->translate("Outstanding amount"); ?></th>
                <th width="10%"><?php echo $this->translate("Purpose"); ?></th>
                <th width="10%"><?php echo $this->translate("Savings / deposit amount"); ?></th>
                <th></th>
            </tr>

        <tr id='tmp'>
                <td>
                <select name = "source[]" class="selectvalid interest" id="source-1">
                    <option value=0>Select</option>
                    <?php foreach ($this->loanDetails as $loanDetails) { ?>
                    <option value="<?php echo $loanDetails['id']?>"><?php echo $loanDetails['name']?></option>

                    <?php } ?>
                </select>   
                </td>

               <td>
                <select name = "member[]" class="selectvalid">
                    <option value=0>Select</option>
                    <?php foreach ($this->familymember as $member) { ?>
                    <option value="<?php echo $member['id']?>"><?php echo $member['name']?></option>

                    <?php } ?>
                </select>
                </td>

                <td><INPUT type="text" name = "loan[]" class="required numeric" maxlength="30" size="15"></td>
                <td><INPUT type="text" name = "interest[]" class="numeric disableid" maxlength="2" size="5" id="disable-1"></td>
                <td><INPUT type="text" name = "outstanding[]" maxlength="30" size="15"></td>
                <td>
                <select name = "purpose[]" class="selectvalid">
                   <option value=0>Select</option>
                    <?php foreach ($this->purpose as $purpose) { ?>
                    <option value="<?php echo $purpose['id']?>"><?php echo $purpose['name']?></option>

                    <?php } ?>
                </select>
                </td>
                <td><INPUT type="text" name = "savingamount[]" class="numeric disableamt" maxlength="30" size="15" id="amtdisable-1"></td>

                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif"       border=0 width='16' height='16'></td>
            </tr>
        </table>

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>"><input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>"><a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>

    </form>
</div>