<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


   <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("ಕಟುಂಬದ ವಿವರ"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    foreach($this->membernames as $family_view){ ?>

    <tr>
       <!-- <td ><?php echo $this->translate("ಕುಟುಂಬದ ಕೋಡ :"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>-->
        <td ><?php echo $this->translate("ಮನೆ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("ರೇಷನ್ ಕಾರ್ಡ್:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td> </tr>
    <tr>
        <td ><?php echo $this->translate("ಬೀದಿ /ರಸ್ತೆ:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("ಆರೋಗ್ಯ ವಿಮೆ:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಕಂದಾಯ ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("ಉದ್ಯೋಗಖಾತ್ರಿ ಜಾಬ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>
    </tr>
    <tr>
        <td ><?php echo $this->translate(" ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("ಆದಾಯದ ಪ್ರಮುಖ ಮೂಲ:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>

    <tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ವಿಧ :"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("ದೂರವಾಣಿ:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಜಾತಿ:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("ಮೊಬೈಲ್ :"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>

   <!-- <tr>
        <td ><?php echo $this->translate("ಜಾತಿ:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td></td>
        <td></td>

    </tr>   -->
<?php } ?>
</table> 
<br/>
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;"> 
<form id="pluginForm" action="<?php echo $this->baseUrl();?>/loandetails/index/edit/id/<?php echo $this->memberid; ?>" method="POST" >
<table id="hor-minimalist-b" class="family">
            <tr> 
                <th width="27%"><?php echo $this->translate("ಮೂಲ"); ?></th>
                <th width="17%"><?php echo $this->translate("ಕುಟುಂಬದ ಸದಸ್ಯ"); ?></th>
                <th width="17%"><?php echo $this->translate("ವಾರ್ಷೀಕ ಬಡ್ಡಿ  %"); ?></th>
                <th width="27%"><?php echo $this->translate("ಸಾಲದ ಮೊತ್ತ"); ?></th>
                <th width="37%"><?php echo $this->translate("ಬಾಕಿಯಿರುವ ಸಾಲ"); ?></th>
                <th width="10%"><?php echo $this->translate("ಕಾರಣ"); ?></th>
                <th width="10%"><?php echo $this->translate("ಉಳಿತಾಯ.. ಉಳಿತಾಯ./ಠೆವಣಿ ಮೊತ್ತ"); ?></th>
                <th></th>
            </tr>
            <?php $i=0; foreach ($this->loandetails as $loandetails) { $i++; ?>
            <?php if ($i == 1) { ?>
             <tr id='tmp'>
            <?php } else { ?>
        <tr>
            <?php } ?>
                <td>
                <select name = "source[]" class="selectvalid interest" id="source-<?php echo $i; ?>">
                    
                    <OPTION value="<?php echo $loandetails["source_id"]; ?>">
                        <?php echo $loandetails["source_id"]; echo ".  "; echo $loandetails["sourcename"]; ?>
                    </OPTION>
                    <option value=0>Select</option>
                    <?php foreach ($this->loanDetails as $source) {
                        if($source['id']!= $loandetails["source_id"]) {  ?>
                    <option value="<?php echo $source['id']?>"><?php echo $source['id']; echo ".  "; echo $source['name_regional']?></option>
                    <?php }} ?>
                </select> 
                </td>

               <td>
                <select name = "member[]" class="selectvalid interest required">
                    <OPTION value="<?php echo $loandetails["member_id"]; ?>">
                        <?php echo $loandetails["membername"]; ?>
                    </OPTION>
                    <option value=0>Select</option>
                    <?php foreach ($this->familymember as $member) { 
                        if($member['id']!= $loandetails["member_id"]) {
                    ?>
                    <option value="<?php echo $member['id']?>"><?php echo $member['name']?></option>

                    <?php }} ?>
                </select>
                </td>
                <td><INPUT type="text" name = "interest[]" class="numeric disableid" max="99" size="5" value="<?php echo $loandetails['interest']; ?>"  id="disable-<?php echo $i; ?>"></td>
                <td><INPUT type="text" name = "loan[]" class="required numeric" maxlength="12" size="15" value="<?php echo $loandetails['loanamount']; ?>"></td>
                <td><INPUT type="text" name = "outstanding[]" maxlength="12" size="15" value="<?php echo $loandetails['outstanding_amount']; ?>"></td>
                <td>
                <select name = "purpose[]" class="selectvalid">
                    <OPTION value="<?php echo $loandetails["purpose_id"]; ?>">
                        <?php $loandetails["purpose_id"]; echo ".  "; echo $loandetails["purposename"]; ?>
                    </OPTION>
                    <option value=0>Select</option>
                    <?php foreach ($this->purpose as $purpose) {
                     if($purpose['id']!= $loandetails["purpose_id"]) {  ?>
                    <option value="<?php echo $purpose['id']?>"><?php echo $purpose['id']; echo ".  "; echo $purpose['name_regional']?></option>

                    <?php }} ?>
                </select>
                </td>
                <td><INPUT type="text" name = "savingamount[]" class="numeric disableamt" maxlength="12" size="15" value="<?php echo $loandetails['deposit']; ?>" id="amtdisable-<?php echo $i; ?>">
                <INPUT type="hidden" name = "recordid[]" value="<?php echo $loandetails['id']?>">
                </td>

                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif"       border=0 width='16' height='16'></td>
            </tr>
        <?php }  ?>
</table>

<input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="submit" id="update" name="update" value="<?php echo $this->translate("Update"); ?>">
<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>

</form>
</div>