
<?php if($this->members) { $count = count($this->members); ?>
<table  border='0' id="hor-minimalist-b" style="width:auto; border:no; !important;">
 <? foreach($this->members as $members) { } ?>
<tr><td>Group name:</td><td><? echo $members['groupname'];?></td></tr>
<tr><td>Group head:</td><td><? echo $members['grouphead_name'];?></td></tr>
<tr><td>Number of members:</td><td><? echo $count;?></td></tr>
<tr><td>meeting Time:</td><td><? echo $members['time'];?></td></tr>
<tr><td>meeting date:</td><td><? echo $members['day'];?></td></tr>
<tr><td>meeting place:</td><td><? echo $members['place'];?></td></tr>
</table>
<?php } ?>