 <script type="text/javascript"> 
$(document).ready(function() {
    $(".d").datepicker({"dateFormat":"dd/mm/yy"});

  $('input#tmpAddRow').click(function(){
      newRow = $('tr#tmp').clone(true).removeAttr('id');
      inputobj = newRow.find("input:text");
      inputobj.val("");     
      newRow.appendTo('.tmpadd tbody');
});
 $('.delete-icon').click(function() {
        $(this).closest('tr').not('#tmp').remove();
    });
});

 </script> 
<div class="searchDiv">
	<table id="hor-minimalist-b">
			<tr>
                        <th colspan="2">Product information</th>
                        </tr>
			<TR >
				<TD>Product name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->form->offerproductname;?><?php echo $this->form->currentdates;?><?php echo $this->errorofferproductname; ?></TD>
			</TR>
			<tr>
				<TD  >Short name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->form->offerproductshortname;?></TD>
			</TR>
			<TR >
				<TD >Description<span class="reqMark">*</span></TD>
				<TD><?php echo $this->form->offerproduct_description;?></TD>
			</TR>
			<tr>
				<th colspan="2">Dates</th> 
			</tr>
			<tr> 
				<td >Begin date:<span class="reqMark">*</span><B style='color:red'>dd/mm/yyyy</b></td>
				<td ><?php echo $this->form->begindate;?></td>
			</tr>

			<tr> 
				<td >Closed date:<span class="reqMark">*</span><B 	style='color:red'>dd/mm/yyyy</b></td>
				<td><?php echo $this->form->closedate;?></td>
			</tr>

			<tr> 
				<td >Applicable to:<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->applicableto;?></td>
			</tr>
			<tr> 
<!-- 				<td >GL subcode:<span class="reqMark">*</span></td> -->
<!-- 				<td ><?php //echo $this->form->glsubcode_id;?></td> -->
			</tr>
			<tr>
				<th colspan="2">Interest and terms</th>
			</tr>
			<tr > 
				<td>Minimum Recurring amount:<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->minimum_deposit_amount;?></td>
			</tr>
			<tr> 
				<td >Maximum Recurring amount:<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->maximum_deposit_amount;?></td>
			</tr>
			<tr>
				<td >Frequency of deposit:<span class="reqMark">*</span></td>
				<td ><? echo $this->form->frequency_of_deposit;?></td>
			</tr>
			<tr>
				<td >Penal interest:<span class="reqMark">(%)*</span></td>
				<td ><?php echo $this->form->penal_Interest;?></td>
			</tr>
                        <tr>
<!-- 				<td >Penal glsubcode:<span class="reqMark">*</span></td> -->
<!-- 				<td ><?php //echo $this->form->feeglcode;?></td> -->
			</tr>
	              
			<tr>
				<th colspan="2">Periods and rates</th> 
			</tr>
                    </table>
                    <table class="tmpadd" id="hor-minimalist-s">
			<tr>
				<td >From (Month)  </td><td >To (Month)  </td><td >Rate of interest</td><td></td>
				
			</tr>
			<tr id="tmp">
				<td><input type='text' size='3' name='interestfrom[]' id='interestfrom' value="" class = 'txt_put'></td>
				<td><input type='text' size='3' name='interestto[]' id='interestto' value="" class = 'txt_put'></td>
                                <td><input type='text' size='3' name='interestrate[]' id='interestrate' value="" class = 'txt_put'></td>
                                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
			
			</tr>
			</table>
                        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add");?>">
		
			
</div>
