<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<?php if($this->transaction) { ?>
<?php 
$cr = 0;
$db = 0;
?>
<table id="hor-minimalist-b" border="1">
    <tr>
        <th >V No.</th>

        <th >Transaction date</th>

        <th align="right">Creidt</th>
        <th align="right">Debit</th>

    </tr>
    <?php foreach($this->transaction as $transaction) : ?>
    <tr>
       <td ><?php echo $transaction["id"]; ?></td>

       <td ><?php echo $transaction["transaction_date"]; ?></td>
       <?php if ($transaction["amount_to_bank"]) {?>
       <td align="right"><?php $cr = $cr + $transaction["amount_to_bank"]; echo $transaction["amount_to_bank"]; ?></td>
       <?php } else { ?>
       <td align="right">----</td>
       <?php } ?>
       <?php if ($transaction["amount_from_bank"]) { ?> 
       <td align="right"><?php $db = $db + $transaction["amount_from_bank"]; echo $transaction["amount_from_bank"]; ?></td>
       <?php } else { ?>
       <td align="right">----</td>
       <?php } ?>

    </tr>
    <?php endforeach; ?>
    <tr>
        <th >Total</td>
        <th ></td>
        <th align="right"><?php echo sprintf("%4.2f", $cr);?></th>
        <th align="right"><?php echo sprintf("%4.2f", $db);?></th>

    </tr>
    </table>

<?php } else {?>
<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate("Search"); ?></legend>
             <table width="100%">
                <form action="<?php echo $this->baseUrl();?>/ledgerreport/index" method="POST">
                   <tr>
                            <TD><?php echo $this->translate('Sub ledger'); ?></td>
                            <td><?php echo $this->form->glsubcode;?></td>
                            <td><input type="submit" name="Search" value="<?php echo $this->translate('Search'); ?>"/></td>
                   </tr>
                </form>
            </table>
       
</fieldset>
</div>

<?php } ?>


