<?php if(!$this->result or !$this->group) { ?>
<fieldset>
	<legend>Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/loanprocess/index/newprocess" method="POST">
			<table class="fieldsets">
                            <TR>
                                <TD><label for="fld3">Member code / Group code</label></TD>
                                <TD><? echo $this->form->membercode;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Submit;?>
                            </div> 
                        </div>
	       </form>
</fieldset>
<?php } ?>
<div>
<?php if($this->result) { ?>
    <table id="hor-minimalist-b">
	<tr>
	    <Th colspan="2">Member details</Th>
	</tr>
	<?php foreach($this->result as $member) : ?>
	<tr>
		<td>Name</td>
		<td><?php  echo $member['name'];?></td>
        </tr>
        <?php if($this->typeid==1) { ?>
	<tr>
		<td>UID</td>
		<td><?php  echo $member['uid'];?></td>
        </tr>
        <?php } ?>
        <tr>
		<td>Code</td>
		<td><?php  echo $member['code'];?></td>
	</tr> 
        <tr>
		<td>Village name</td>
		<td><?php  echo $member['villagename'];?></td>
	</tr>
	<?php endforeach; ?>
	</table>

</div>
<br>
<div>
<fieldset>

        <form action="<?php echo $this->baseUrl();?>/loanprocess/index/application/id/<?php echo base64_encode($this->id); ?>" method="POST">
    <table id="hor-minimalist-b">
            <tr>
                <TD>Purpose</TD>
                <TD><?php echo $this->appform->purpose;?></TD>
            </tr>
            <tr>
                <TD>Amount required Rs</TD>
                <TD><?php echo $this->appform->amount;?></TD>
                </tr>
<tr>
                <TD>Loan tenures</TD>
                <TD><?php echo $this->appform->duration;?>(Months)</TD>
</tr>
<tr>
                <TD>Need in</TD>
                <TD><?php echo $this->appform->period;?>(Months)</TD>
            </TR>
            </table>
            <input type="hidden" name="type" value="<?php echo $this->grouptypeid;?>">
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Submit;?>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/loanprocess/index"><input type="button" name="Back" value="Back"/></a>
                </div>
            </div>
        </form>

</fieldset>
<?php }?>
</div>

<?php if (count($this->group)) { ?>
        <table id="hor-minimalist-s">
            <tr> 
                <th ><?php echo $this->translate("Group details"); ?></th>
                <th></th>
            </tr>
            <?php foreach($this->groupDeatils as $details) { ?>
            <tr> 
                <td ><?php echo $this->translate("Group name"); ?></td>
                <td><?php echo $details->groupname; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("Group code"); ?></td>
                <td><?php echo $details->groupcode; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("Village"); ?></td>
                <td><?php echo $details->officename; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("No. of members"); ?></td>
                <td><?php echo $details->groupNum; ?></td>
            </tr>
            <?php } ?>
        </table>       
    <form action="<?php echo $this->baseUrl();?>/loanprocess/index/add" method="POST">
        <table id="hor-minimalist-b">
            <tr> 
                <th width="5%"><?php echo $this->translate("Sl no"); ?></th>
                <th width="17%"><?php echo $this->translate("Member code"); ?></th>
                <th width="17%"><?php echo $this->translate("Group member"); ?></th>
                <th width="17%"><?php echo $this->translate("UID"); ?></th>
                <th width="27%"><?php echo $this->translate("Purpose"); ?></th>
                <th width="20%"><?php echo $this->translate("Amount"); ?></th>
                <th width="30%"><?php echo $this->translate("Required with in the period"); ?></th>
            </tr>
            <?php $i = 1; 
            foreach($this->group as $loandetails) { 

                $c = 'purpose_id'.$i;
                $g = 'amount'.$i;
                $h = 'need'.$i;
                ?>
            <tr>
                <td><?php echo $i;?></td>
                <td><?php echo $loandetails->familycode; ?></td>
                <td><?php echo $loandetails->name; ?></td>
                <td><?php echo $loandetails->uid; ?></td>
                <td><?php echo $this->form->$c; ?></td>
                <td><?php echo $this->form->$g; ?></td>
                <td><?php echo $this->form->$h; ?></td>
            </tr>
            <input type="hidden" name=member_id<?php echo $i?> value = "<?php echo $loandetails->id;?> ">
            <?php $i++; } ?>
            <tr>
                <td><input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>"></td>
                <td><a href="<? echo $this->baseUrl();?>/loanprocess/index"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a></td>
            </tr>
        </table>
        <input type="hidden" name="membercode" value = "<?php echo $this->membercode;?> ">

    </form>
<?php } ?>


