<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<style type="text/css" >
td.info
{
   border: 2px solid #C8BBBE;
}
input.txt , textarea.txt
{
   background-color: #EBDDE2;
}

</style>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/accounting/sumcalculation.js">
</script>
<form action="<?php echo $this->baseUrl();?>/loanprocess/index/shgadvances" method="POST">
    <div class="profile_tab"> 
    <fieldset>
        <p><h3 align="center">SUJEEVANA PROGRAMME</h3></p>
              <table  width="100%">	
                <tr>
                    <TD width="30%">SHG/JLG Group : <?php echo "<b>".$this->groupname."</b>";?></TD>
                    <TD width="50%" colspan="3" align="center"><h3>SHG/JLG QUALITY EVALUATION</h3></TD>
                    <td width="20%">Village facilitator</td>
                </tr>
                <tr>
                    <TD width="30%">Village : <?php echo "<b>".$this->villagename."</b>";?></TD>
                    <TD width="50%" colspan="3" align="center"></TD>
                    <td width="20%">Area officer</td>
                </tr>
                <tr>
                    <TD width="20%">Farmer's group</TD>
                    <TD width="50%" colspan="3" align="center"></TD>
                    <Th width="30%">Date : <?php echo "<b>".date('d/m/Y')."</b>";?></td>
                </tr>
            </table>
            <table border="1" width="100%">
                <TR>
                    <Td width="10%" align="center">S.No</Td>         
                    <Td width="50%" colspan="2" align="center">Quality indicators</Td>
                    <Td width="20%"  align="center">Maximum marks</Td>
                    <Td width="20%"  align="center">Scored marks</Td>
                </TR>
                <tr>
                    <TD align="center"><b>#</b></TD>
                    <td colspan="2"><b>Group meeting & other information</b></TD>
                    <TD align="center"><b>350</b></TD>
                    <TD></TD>
                </tr> 
                <tr>
                    <TD align="center">1</TD>
                    <TD colspan="2">Attendance(<50%=0)</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->gattendance?></TD>
                    <input type="hidden" name="gattendanceV" value="50"/>
                </tr> 
                <tr>
                    <TD align="center">2</TD>
                    <TD colspan="2">Savings(<50%=0)</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->gsaving?></TD>
                    <input type="hidden" name="gsavingV" value="50"/>
                </tr>
                <tr>
                    <TD align="center">3</TD>
                    <TD colspan="2">Meeting discipline ?</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->gmeetdiscipline?></TD>
                    <input type="hidden" name="gmeetdisciplineV" value="20"/>
                </tr>
                <tr>
                    <TD align="center">4</TD>
                    <TD colspan="2">Participation of members in discussion ?</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->gparticipation?></TD>
                    <input type="hidden" name="gparticipationV" value="20"/>
                </tr>
                <tr>
                    <TD align="center">5</TD>
                    <TD colspan="2">Weekly meeting limit(<80%=0)</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->gweeklymeet?></TD>   
                 <input type="hidden" name="gweeklymeetV" value="20"/>
                </tr>
                <tr>
                    <TD align="center">6</TD>
                    <TD colspan="2">Change of membership(<50%=0)</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->gchangememb?></TD>
                    <input type="hidden" name="gchangemembV" value="50"/>
                </tr>
                <tr>
                    <TD align="center">7</TD>
                    <TD colspan="2">Preparation of workplan for the meeting</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->gpreparation?></TD>
                    <input type="hidden" name="gpreparationV" value="20"/>

                </tr>
                <tr>
                    <TD align="center">8</TD>
                    <TD colspan="2">Number of signing members</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->gsigningmemb?></TD>
                    <input type="hidden" name="gsigningmembV" value="20"/>

                </tr>
                <tr>
                    <TD align="center">9</TD>
                    <TD colspan="2">Group members co operation</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->ggroupcooperation?></TD>
                    <input type="hidden" name="ggroupcooperationV" value="50"/>

                </tr> 
                <tr>
                    <TD align="center">10</TD>
                    <TD colspan="2">Group sustainability training</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->ggroupsustaiable?></TD>
                    <input type="hidden" name="ggroupsustaiableV" value="50"/>

                </tr>

                <tr>
                    <TD align="center"><b>#</b></TD>
                    <td colspan="2"><b>Book Keeping</b></TD>
                    <TD align="center"><b>250</b></TD>
                    <TD></TD>
                </tr>
                <tr>
                    <TD align="center">1</TD>
                    <TD colspan="2">Savings-attendance sheet</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->bsavingattend?></TD>
                    <input type="hidden" name="bsavingattendV" value="50"/>

                </tr> 
                <tr>
                    <TD align="center">2</TD>
                    <TD colspan="2">Loan disbursement</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->bloandisburse?></TD>
                    <input type="hidden" name="bloandisburseV" value="20"/>

                </tr>
                <tr>
                    <TD align="center">3</TD>
                    <TD colspan="2">Discussion and decisions</TD>
                    <TD align="center">30</TD>
                    <TD><?php echo $this->form->bdiscussion?></TD>
                    <input type="hidden" name="bdiscussionV" value="30"/>

                </tr>
                <tr>
                    <TD align="center">4</TD>
                    <TD colspan="2">Weekly Income - Expenditure details</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->bincomeandexpend?></TD>
                    <input type="hidden" name="bincomeandexpendV" value="50"/>

                </tr>
                <tr>
                    <TD align="center">5</TD>
                    <TD colspan="2">Individual saving account</TD>
                    <TD align="center">30</TD>
                    <TD><?php echo $this->form->bindividualsave?></TD>
                    <input type="hidden" name="bindividualsaveV" value="30"/>

                </tr>
                <tr>
                    <TD align="center">6</TD>
                    <TD colspan="2">Individual loan account</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->bindividualloan?></TD>
                    <input type="hidden" name="bindividualloanV" value="20"/>

                </tr>
                <tr>
                    <TD align="center">7</TD>
                    <TD colspan="2">General account</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->bgeneralacc?></TD>
                    <input type="hidden" name="bgeneralaccV" value="50"/>

                </tr>
                <tr>
                    <TD align="center"><b>#</b></TD>
                    <td colspan="2"><b>Previous loan information</b></TD>
                    <TD align="center"><b>250</b></TD>
                    <TD></TD>
                </tr>
                <tr>
                    <TD align="center">1</TD>
                    <TD colspan="2">Loan holders percentage(<50%=0)</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->ploanholder?></TD>
                    <input type="hidden" name="ploanholderV" value="50"/>

                </tr> 
                <tr>
                    <TD align="center">2</TD>
                    <TD colspan="2">Usage of savings/loans for income generating activities </TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->pusageofsaving?></TD>
                    <input type="hidden" name="pusageofsavingV" value="50"/>

                </tr>
                <tr>
                    <TD align="center">3</TD>
                    <TD colspan="2">Loan repayment percentage(<50%=0)</TD>
                    <TD align="center">100</TD>
                    <TD><?php echo $this->form->ploanrepayment?></TD>
                    <input type="hidden" name="ploanrepaymentV" value="100"/>

                </tr>
                <tr>
                    <TD align="center">4</TD>
                    <TD colspan="2">Minimum repayment</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->pminimumrepay?></TD>
                    <input type="hidden" name="pminimumrepayV" value="50"/>

                </tr>
                <tr>
                    <TD align="center"><b>#</b></TD>
                    <td colspan="2"><b>Farmers school & information</b></TD>
                    <TD align="center"><b>150</b></TD>
                    <TD></TD>

                </tr>
                <tr>
                    <TD align="center">1</TD>
                    <TD colspan="2">Participation(<70%=0)</TD>
                    <TD align="center">30</TD>
                    <TD><?php echo $this->form->fparticipation?></TD>
                    <input type="hidden" name="fparticipationV" value="30"/>

                </tr> 
                <tr>
                    <TD align="center">2</TD>
                    <TD colspan="2">Farmer school </TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->ffarmerschool?></TD>
                    <input type="hidden" name="ffarmerschoolV" value="50"/>

                </tr>
                <tr>
                    <TD align="center">3</TD>
                    <TD colspan="2">Weekly plan</TD>
                    <TD align="center">20</TD>
                    <TD><?php echo $this->form->fweeklyplan?></TD>
                    <input type="hidden" name="fweeklyplanV" value="20"/>

                </tr>
                <tr>
                    <TD align="center">4</TD>
                    <TD colspan="2">School learnings followup percentage(<50%=0)</TD>
                    <TD align="center">50</TD>
                    <TD><?php echo $this->form->fschoollearning?></TD>
                    <input type="hidden" name="fschoollearningV" value="50"/>

                </tr>
                <tr>
                    <TD align="center"><b>#</b></TD>
                    <td colspan="2"><b>Total marks</b></TD>
                    <TD align="center"><b>1000</b></TD>
                    <TD><?php echo $this->form->totalmarks?></TD>
                </tr>
            </table>
    </fieldset>
</div>
</form>
<fieldset>
<legend>Percentage calculation</legend>
<div style="float:left; width:300px">
            <table border="1">
            <tr>
                <Td>Currently applicable total marks</Td>
                <td><input type="textbox" name="marks" class="marks" value="" readonly="true"/></td>
            </tr> 
            <tr>
                <TD>Scored marks</TD>
                <TD><?php echo $this->form->totalmarks?></TD>
            </tr> 
            <tr>
                <TD>Percentage of marks (%)</TD>
                <TD><?php echo $this->form->percentage?></TD>
            </tr>
            <tr>
            <TD>
                  Grade
            </TD>
             <TD>
                 <input type="text" class="grade" name="grade" readonly="true"></label>
            </TD>
            </tr>
            </table>
<br>
 <table border="1" width="100%">
    <TR>
        <TD width="30%" valign="top">
            Observed - good points
        </TD>
        <td width="70%"><?php echo $this->form->observe?></td>
    </TR>
    </table>
</div>

<div style="float:right; width:300px" align="right">
  <table width="100%">
                        <tr>
                            <td width="50%" align="center" class="info">> 80%</td>
                            <td width="50%" align="center" class="info">A</td>
                        </tr> 
                        <tr>
                            <td width="50%" align="center" class="info">70 - 80%</td>
                            <td width="50%" align="center" class="info">B</td>
                        </tr> 
                        <tr>
                            <td width="50%" align="center" class="info">60 - 70%</td>
                            <td width="50%" align="center" class="info">C</td>
                        </tr>
                        <tr>
                            <td width="50%" align="center" class="info">< 60%</td>
                            <td width="50%" align="center" class="info">D</td>
                        </tr> 
                    </table>
</div>
</fieldset>
            <br>
            <p>Observed - need changes in</p>
            <p align="right">Evaluator name & signature</p>

<form action="<?php echo $this->baseUrl();?>/loanprocess/index/pdfdisplay" method="POST"
onClick="window.open('<?php echo $this->baseUrl(); ?>/loanprocess/index/reportdisplay/file/shgadvances.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <input type="hidden" name="groupid" value="<?php echo $this->groupid; ?>">
           <div class="btnhouse">
		<div class="ltbtns">
			<TD > <input type="submit" value="<?php echo $this->translate('PDF'); ?>" id="submit"></TD>
		</div>
            </div>
</form>