<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
 *  view funder details and filtered search details
-->
 

<div id="searchDiv">
    <fieldset>
        <legend>
	<!--to change language -->
	<?php echo $this->translate("Search"); ?>
	</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/funder" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label"><?php echo $this->translate("Funder code:"); ?></td>
                                    <td ><? echo $this->form->code;?></td>
                                    <td class="label"><?php echo $this->translate("Funder name:"); ?></td>
                                    <td ><? echo $this->form->name;?></td>
                                </tr>
                                <tr>
                                    <td class="label"><br><?php echo $this->translate("Funder type:"); ?></td>
                                    <td ><br><? echo $this->form->type;?></td>
                                </tr>
                                <tr> 	<!--button object -->
                                    <td colspan="4" align="center"></td>
                                </tr>
                        </table><br />
                         <div class="ltbtns">
                        <? echo $this->form->Search;?>
                        </div>
                    </form>	
            </div>
    </fieldset> 
</div> 


<!--  view list of funder details and filtered search details -->
<?
// check search result is not empty and assign values
if($this->errormsg==0) { 
    if (count($this->paginator)): 
?>
<table id="hor-minimalist-b">
    <tr>
        <th><?php echo $this->translate("Funder name"); ?></th>
        <th><?php echo $this->translate("Funder type"); ?></th>

    </tr>
    <?php foreach ($this->paginator as $funder): ?>
    <tr>
        <td><a href="<?php echo $this->baseUrl()."/fundercommonview/index/commonview/id/".$funder['id']; ?>">
        <?php echo $this->escape($funder['name']); ?></a></td>
        <td><?php echo $this->escape($funder['fundertype']); ?></td>

    <?php endforeach; ?>
    <?php endif; ?>
    </tr>
    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
        '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>
</table>
<?php } else { echo "<font color='RED'>Records Not Found Try Again...</font>";
	} ?>
<br>
