<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

     <script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-1.3.2.js1"></script>
    <script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery.validate.js"></script>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jqueryAddmethod.js"></script>

<script type='text/javascript'>






 
$(document).ready(
  function() {
  $("#valueForm").validate();
  

  
   $('input#tmpAddRow').click(
      function() {

      tableobj=$(this).parent();
        selectedval=[];
     rowindex=$('tr',tableobj).length;
    
     var newRow = $('tr#tmp').clone(true).removeAttr('id');
                selectobj=newRow.find("select");
                newrowobj=$(this).children(':first');
                inputobj=newRow.find("input:text");
                
                inputobj.val("");
                 acreObj=newRow.find("input.EitherOr");
                 acreObj.attr('id','acre'+rowindex);
                  
                selectobj=newRow.find("select");
                //selectobj="Select";
                $.each(selectobj,function() {
                   nameselect=$(this).attr('name');
                    $(this).val("");
                   //$('<option value="" selected="selected">Select</option>').appendTo(this);

                
                 });




        newRow.appendTo('.agriculture tbody');

//This is for removing option
//       rowindex=$('tr',tableobj).length;
//       trobjec=$('tr',tableobj);
//        $('tr',tableobj).each(function (index, domEle) {
//            if(index!=rowindex && index!=0)
//              {
//               sval=$("#select"+index).selectedValues();
//                selectedval.push(sval);}
//         });
//      
//         $(selectobj).attr('id', 'select'+rowindex);
//              trobjec.each(function (index, domEle) {
//                    if(index!=0 && index!=rowindex)
//                      {
//                       sval=$("#select"+index).selectedValues();

//                     $("#select"+rowindex+" option[value='"+sval+"']").remove();
//                 }
    });

 
  $('tr input[type=text]').focus(
      function() {
        $(this).addClass('myFocused');   
      }
   ).blur(
      function() {
        $(this).removeClass('myFocused');
     }
    );

  $('.delete-icon').click(function() {
        $(this).closest('tr').not('#tmp').remove();
    });   
  
  




    
      }
    );
    </script>
    <style>
    label.error{
    clear:both;
    color:red;
    float:left;
    }
    </style>

  <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("Family information"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    foreach($this->membername as $family_view){ ?>

   <tr>
        <td ><?php echo $this->translate("Family ID:"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>
    <tr>
        <td ><?php echo $this->translate("House No:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("Ration card:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td><?php echo $this->translate("Street/Road/Lane:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("Health Insurance:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Rev Village:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("NREGS Job Card No:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate("Colony/Habitation:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("Major source of income:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("Family type:"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("Contact Phone:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Category:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("Mobile:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>
   <?php } ?>
</table> 
<br/>
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">
<form  id="valueForm" action="<?php echo $this->baseUrl();?>/agriculture/index/edit/id/<?php echo $this->memberid; ?>" method="POST">
<table id="hor-minimalist-b" class="agriculture" <?php $records=sizeof($this->agriculture); $emt=0; $i =0;  ?>>
<tr> 
    <th><?php echo $this->translate("Land holding"); ?></th>
    <th><?php echo $this->translate("Ownership type"); ?></th>

    <th><?php echo $this->translate("Acre"); ?></th>
    <th><?php echo $this->translate("Gunta"); ?></th>
    <th><?php echo $this->translate("Owner name"); ?></th>
    <th><?php echo $this->translate("Survey No"); ?></th>
    <th><?php echo $this->translate("Village"); ?></th>
    <th>Action</th>
</tr>

<?php if( $records== $emt) { ?>
<tr id='tmp'>
            <td <?php $i = 1;  ?>><select name = tenant[] class="selectvalid required" >
                    <option value="">Select</option>

                            <?php foreach ($this->land_details as $land_details) { ?>
                            <option value="<?php echo $land_details['id']?>"><?php echo $land_details['name']?></option>
                            <?php } ?>
                        </select>
            </td>  
			<td><select name = acquistion[] class="selectvalid required">
                    <option value="">Select</option>

                            <?php foreach ($this->acquistion as $acquistion) { ?>
                            <option value="<?php echo $acquistion['id']?>"><?php echo $acquistion['name']?></option>
                            <?php } ?>
                        </select>
            </td>
			<td><INPUT type="text" name = "acre[]" size="5"  class="number EitherOr"  id="acre1" maxlength="3" ></td>
            <td><INPUT type="text" name = "gunta[]" size="5" class="acre number"  min="0" max="39"></td>
 			<td><select name = ownername[] class="selectvalid required">
                    <option value="">Select</option>

			<?php foreach ($this->owner as $owner) { ?>

			<option value="<?php echo $owner['landowner_name']?>"><?php echo $owner['name']?></option>
			<?php } ?>
                            </select>
            </td> 
            <td><INPUT type="text" name = "survey[]" size="5" maxlength="8" class="noSpecialChars"></td>
								<td><select name = villagename[] class="selectvalid required">
                    <option value="">Select</option>


                                <?php foreach ($this->village as $village) { ?>
                                <option value="<?php echo $village['id']?>"><?php echo $village['name']?></option>
                                <?php } ?>
                            </select>
            </td> 
            <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
        </tr>

 <?php } ?>
           
            <?php
                foreach ($this->agriculture as $agri) { $i++; ?>
                <tr<?php if ($i==1) { ?> id="tmp" <?php } ?>>

              <td><select name = "tenant[]" class="required">
                                                  <option value="">select</option>

                    <?php foreach ($this->land_details as $assetdetails) {  ?>
                       
                           <option <?php if($assetdetails['id'] == $agri["land_id"] ) { echo 'selected="selected"';?>
                           <?php } ?> value="<?php echo $assetdetails['id']?>"><?php echo $assetdetails['name']?></option>
                    <?php  } $dateconvert= new App_Model_dateConvertor();
					?></select></td>
  <td><select name = "acquistion[]" class="required">
                                   <option value="">select</option>

                    <?php foreach ($this->acquistion as $acquistion) {  ?>
                       <option <?php if($agri["acquistion_id"] == $acquistion['id'] ) { echo 'selected="selected"';?>
                           <?php } ?> value="<?php echo $acquistion['id']?>"><?php echo $acquistion['name']?>
                           
                           </option>
                    <?php  } $dateconvert= new App_Model_dateConvertor();
					?></select></td>
                    <td><INPUT type="text" name = "acre[]" id="acre<?php echo $i; ?>" size="5"   class="number EitherOr" maxlength="3" value = "<?php echo $agri["acre"];?>"></td>
            <td><INPUT type="text" name = "gunta[]" size="5" class="acre number" maxlength="2" min="0" max="39" value="<?php echo $agri["gunta"]; ?>"></td>


          <td><select name = "ownername[]" class="required">

                    <OPTION value="<?php echo $agri["landowner_name"]; ?>">
                    <?php echo $agri["ownername"]; ?>
                    </OPTION>
                                   <option value="">select</option>

                    <?php foreach ($this->owner as $owner) {  ?>
                        <? if($agri["ownername"] != $owner["name"] ) {?>
                           <option value="<?php echo $owner['id']?>"><?php echo $owner['name']?></option>
                    <?php } } $dateconvert= new App_Model_dateConvertor();
					?></select></td>

            <td><INPUT type="text" name = "survey[]" size="5" class="noSpecialChars" maxlength="8" value = "<?php echo $agri["survey_no"];?>"></td>
  <td><select name = "villagename[]" class="required">

                    <OPTION value="<?php echo $agri["villagename"]; ?>">
                    <?php echo $agri["village"]; ?>
                    </OPTION>
                                   <option value="">select</option>

                    <?php foreach ($this->village as $village) {  ?>
                        <? if($agri["village"] != $village["village"] ) {?>
                           <option value="<?php echo $village['id']?>"><?php echo $village['name']?></option>
                    <?php } } $dateconvert= new App_Model_dateConvertor();
					?></select></td>
            </td> 
           
            <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
        </tr>
        <?php } ?>
    </table> 
<?php if( $records== $emt) { ?>

 <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>"  >
    <input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>"><a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
<?php } ?>
<?php if( $records <> $emt) { ?>
<input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>"  >
    <input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Update"); ?>"><a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
<?php } ?>

    </form>
</div>

