<html>
<head>
<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }
em { font-weight: bold; padding-right: 1em; vertical-align: top; }
</style>
</head>
<body>
 <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("ಕಟುಂಬದ ವಿವರ"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    foreach($this->membername as $family_view){ ?>
<!--<tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ಕೋಡ :"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>-->
    <tr>
        <td ><?php echo $this->translate("ಮನೆ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("ರೇಷನ್ ಕಾರ್ಡ್:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಬೀದಿ /ರಸ್ತೆ:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("ಆರೋಗ್ಯ ವಿಮೆ:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಕಂದಾಯ ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("ಉದ್ಯೋಗಖಾತ್ರಿ ಜಾಬ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate(" ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("ಆದಾಯದ ಪ್ರಮುಖ ಮೂಲ:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ವಿಧ :"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("ದೂರವಾಣಿ:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಜಾತಿ:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("ಮೊಬೈಲ್ :"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>   <?php } ?>
</table> 
<br/>
<form name="form1" id = "pluginFormlive" action="<?php echo $this->baseUrl();?>/livingassets/index/addasset/id/<?php echo $this->memberid; ?>" method="POST">
<table id="hor-minimalist-b" class="asset">
<tr> 
    <th><?php echo $this->translate("ಸ್ವತ್ತು"); ?></th>
    <th><?php echo $this->translate("ಎಷ್ಟು"); ?></th>
    <th><?php echo $this->translate("ಸ್ವತ್ತಿನ ಮೌಲ್ಯ"); ?></th>
    <th><?php echo $this->translate("ಮೌಲ್ಯದ ದಿನಾಂಕ"); ?></th>
    <th><?php echo $this->translate("Action"); ?></th>
</tr>
 <tr id='tmp'>
            <td><select name = assettype[] id="select1" class="select">
                <option>Select</option>
                            <?php foreach ($this->liveasset_details as $liveassets) { ?>
                            <option value="<?php echo $liveassets['id']?>"><?php echo $liveassets['id']; echo".  "; echo $liveassets['name_regional']?></option>
                            <?php } ?>
                        </select>
            </td>  
            <td><INPUT type="text" size="6" name = "number[]" class="required numeric" maxlength="6" id="numcheck"></td>
            <td><INPUT type="text" name = "value[]"  maxlength="6" class="numeric"></td>
   <td><INPUT type="text" name = "date[]" class="date" readonly autocomplete="OFF"></td>

                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
<input type="hidden" name="subid" value="<?php echo $this->submoduleid;?>">
        </tr>
    </table>  
<input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>"><td>&nbsp;&nbsp;</td><input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>">&nbsp;&nbsp;<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
</body>