<html>
 <head>
<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }
em { font-weight: bold; padding-right: 1em; vertical-align: top; }
</style>
</head>
<BODY>
 <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("Family information"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    foreach($this->membername as $family_view){ ?>
<tr>
        <td ><?php echo $this->translate("Family ID:"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>
    <tr>
        <td ><?php echo $this->translate("House No:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("Ration card:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Street/Road/Lane:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("Health Insurance:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Rev Village:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("NREGS Job Card No:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate("Colony/Habitation:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("Major source of income:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("Family type:"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("Contact Phone:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Category:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("Mobile:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>
   <?php } ?>
</table> 
<br/><form name="form1" id = "pluginFormlive" action="<?php echo $this->baseUrl();?>/livingassets/index/editasset/id/<?php echo $this->memberid; ?>" method="POST">
<table id="hor-minimalist-b" class="asset">
<tr> 
    <th><?php echo $this->translate("Assets"); ?></th>
    <th><?php echo $this->translate("Quantity"); ?></th>
    <th><?php echo $this->translate("Asset value"); ?></th>
    <th><?php echo $this->translate("Date of value"); ?></th>

    <th>Action</th>
</tr>
 <?php $i = 0; ?>
            <?php foreach ($this->editAsset as $editAsset) { $i++;?>
             <?php if ($i == 1) { ?>
             <tr id='tmp'>
            <?php } else { ?>
            <tr>
            <?php } ?>
        <td>
            <select name = "assettype[]" id="select1" class="select">
                    <OPTION value="<?php echo $editAsset["liveasset_id"]; ?>">
                        <?php echo $editAsset["name"]; ?>
                    </OPTION>
        <option>Select</option>
                    <?php foreach ($this->liveasset_details as $assetdetails) { ?>
                        <? if($editAsset["name"] != $assetdetails["name"] ) {?>
                           <option value="<?php echo $assetdetails['id']?>"><?php echo $assetdetails['name_regional']?></option>
                    <?php } } $dateconvert= new App_Model_dateConvertor();
					?>
                </select>    
                </td>
                <td><INPUT type="text" name = "number[]" size="6" class="required numeric " maxlength="6" value = "<?php echo $editAsset["number"] ;?>" class="required"></td>
                <td><INPUT type="text" name = "value[]"  maxlength="6" class="numeric" value = "<?php echo $editAsset["value"];?>" ></td>
		<td><INPUT type="text" name = "date[]" class="date" readonly autocomplete="OFF" value = "<?php if($editAsset['date_of_value'] != null) { echo $dateconvert->phpnormalformat($editAsset['date_of_value']); } else { echo "Null"; }  ?>"></td>
                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
            </tr> 
				<input type="hidden" name="subid" value="<?php echo $this->submoduleid;?>">

       <?php } ?>
        </table>  

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">
&nbsp;&nbsp;<input type="submit" id="submit" name="Submit" value="<?php echo $this->translate("Update"); ?>">&nbsp;&nbsp;<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>

       <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">
&nbsp;&nbsp;<input type="submit" id="submit" name="Submit" value="<?php echo $this->translate("Update"); ?>">&nbsp;&nbsp;<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>

