<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<?php
function checkConnection()
{
    //Initiates a socket connection to www.itechroom.com at port 80
    $conn = @fsockopen("www.itechroom.com", 80, $errno, $errstr, 30);
    if ($conn)
    {
        $status = "OK";
        fclose($conn);
    }
    else
    {
        $status = "NO";
//         $status .= "$errstr ($errno)";
    }
    return $status;
}
$status = checkConnection();

if($status == "OK"){
?>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<title>Group Location</title>
<link href="http://code.google.com/apis/maps/documentation/javascript/examples/standard.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
  var geocoder;
  var map;
  var infowindow = new google.maps.InfoWindow();
  var marker;
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(15.085866972731804,76.94207031250001);
    var myOptions = {
      zoom: 10,
      center: latlng,
      mapTypeId: 'roadmap'
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    var input = document.getElementById("latlng").value;
    var latlngStr = input.split(",",2);
    var lat = parseFloat(latlngStr[0]);
    var lng = parseFloat(latlngStr[1]);
    var latlng = new google.maps.LatLng(lat, lng);
    geocoder.geocode({'latLng': latlng}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        if (results[1]) {
          map.setZoom(11);
          marker = new google.maps.Marker({
              position: latlng,
              map: map,
          });
          infowindow.setContent(results[1].formatted_address);
          infowindow.open(map, marker);
        } else {
          alert("No results found");
        }
      } else {
        alert("Geocoder failed due to: " + status);
      }
    });
  }
</script>
</head>

<body onload="initialize()">
<div>
  <input id="latlng" type="hidden" value="<?php echo $this->latitude.",".$this->longitude;?>">
</div>
<div id="map_canvas" style="width: 350px; height: 300px; border: 1px solid black;"></div>
<?php } else {

echo "<font color ='red'>Internet connection is not available due to that google map not displayed...</font>";

} ?>
<div id = "searchDiv">
<table id="hor-minimalist-b">
    <tr>
            <th class = "firsttd">Group information</th>
            <th class = "secondtd"></th>
            <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/groupmdefault/index/editgroup/id/<?php echo $this->groupid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th> 
    </tr>
    <?php $dateconvertor = new App_Model_dateConvertor(); ?>
        <? foreach($this->groupname as $groups){}?>
	<tr>
            <td class = "firsttd">Group type</td>
            <td class = "secondtd"><?php if(substr($groups['groupcode'],4,1) == 2) { echo "SHG"; } else { echo "JLG";} ?></td>
            <td class = "thirdtd"></td>
	</tr><tr>
            <td class = "firsttd">Group name</td>
            <td class = "secondtd"><?php echo $groups['groupname']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
	<tr>
            <td class = "firsttd">Village name</td>
            <td class = "secondtd"><?php echo $groups['officename']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
        <tr>
            <td class = "firsttd">Bank name</td>
            <td class = "secondtd"><?php echo $groups['bankname']; ?></td>
            <td class = "thirdtd"></td>
	</tr><tr>
            <td class = "firsttd">Branch name</td>
            <td class = "secondtd"><?php echo $groups['branchname']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
        <tr>
            <td class = "firsttd">Saving per week</td>
            <td class = "secondtd"><?php echo $groups['saving_perweek']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
        <tr>
            <td class = "firsttd">Penalty for late attendance</td>
            <td class = "secondtd"><?php echo $groups['penalty_latecoming']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
        <tr>
            <td class = "firsttd">Penalty for absence</td>
            <td class = "secondtd"><?php echo $groups['penalty_notcoming']; ?></td>
            <td class = "thirdtd"></td>
	</tr> 
        <tr>
            <td class = "firsttd">Place</td>
            <td class = "secondtd"><?php echo $groups['place']; ?></td>
            <td class = "thirdtd"></td>
	</tr> 
        <tr>
            <td class = "firsttd">Time</td>
            <td class = "secondtd"><?php echo $groups['time']; ?></td>
            <td class = "thirdtd"></td>
	</tr>  
         <tr>
            <td class = "firsttd">Day</td>
            <td class = "secondtd"><?php echo $groups['weekday']; ?></td>
            <td class = "thirdtd"></td>
	</tr>

         <tr>
            <td class = "firsttd">Group lending Interest (%)</td>
            <td class = "secondtd"><?php echo $groups['rateinterest']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
	<tr>
            <td class = "firsttd">Created date</td>
            <td class = "secondtd"><?php echo $dateconvertor->phpnormalformat($groups['group_created_date']); ?></td>
            <td class = "thirdtd"></td>
	</tr>
	
        <?php if(count($this->address)!=0) { ?>
        <tr>
            <th class = "firsttd">Address information</th>
            <th class = "secondtd"></th>
            <th class = "secondtd"><a href="<?php echo $this->baseUrl();?>/address/index/edit/id/<?php echo $this->groupid; ?>/subId/<?php 
            echo $this->sub_id;?>/modId/<?php echo $this->mod_id;?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a>   </th>
    </tr><? } else { ?>
        <tr>
        <th class = "firsttd">Address information</th>
        <th class = "secondtd"></th>
        <th><a href="<?php echo $this->baseUrl();?>/address/index/add/id/<?php echo $this->groupid; ?>/subId/<?php 
        echo $this->sub_id;?>/modId/<?php echo $this->mod_id;?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"></a></th>
        </tr>
        <?php } ?>
        
        <?php if($this->address){
                    foreach($this->address as $address_view){
            ?>

        <tr>
                <td class = "firsttd">Address line1</td>
                <td class = "secondtd"><?php echo $address_view['address1']; ?></td>
                <td class = "thirdtd"></td>
        </tr>
        <tr>
                <td class = "firsttd">Address line2</td>
                <td class = "secondtd"><?php echo $address_view['address2']; ?></td>
                <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd">Address line3</td>
            <td class = "secondtd"><?php echo $address_view['address3']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd">City</td>
            <td class = "secondtd"><?php echo $address_view['city']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd">State</td>
            <td class = "secondtd"><?php echo $address_view['state']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
       <!-- <tr>
            <td class = "firsttd">Country</td>
            <td class = "secondtd"><?php //echo $address_view['country']; ?></td>
            <td class = "thirdtd"></td>
        </tr>-->
        <tr>
            <td class = "firsttd">Pin code</td>
            <td class = "secondtd"><?php echo $address_view['zipcode']; ?></td>
            <td class = "thirdtd"></td>
        </tr>


    <?php } } ?>
    <br/>

        <?php if(count($this->contact)!=0) { ?>
        <tr>
            <th class = "firsttd">Contact information</th>
            <th class = "secondtd"></th>
            <th class = "secondtd"><a href="<?php echo $this->baseUrl();?>/contactdetails/index/editcontact/id/<?php echo $this->groupid; ?>/subId/<?php 
            echo $this->sub_id;?>/modId/<?php echo $this->mod_id;?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a>   </th>
    </tr><? } else { ?>
        <tr>
        <th class = "firsttd">Contact information</th>
        <th class = "secondtd"></th>
        <th><a href="<?php echo $this->baseUrl();?>/contactdetails/index/addcontact/id/<?php echo $this->groupid; ?>/subId/<?php 
        echo $this->sub_id;?>/modId/<?php echo $this->mod_id;?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"></a></th>
        </tr>
        <?php } ?>
    <?php foreach($this->contact as $contact){ ?>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Contact person:"); ?></td>
        <td class = "secondtd"><?php echo $contact['contact_person']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Telephone number:"); ?></td>
        <td class = "secondtd"><?php echo $contact['telephone']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Mobile number:"); ?></td>
        <td class = "secondtd"><?php echo $contact['mobile']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Email ID:"); ?></td>
        <td class = "secondtd"><?php echo $contact['email']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <?php } ?>
    <tr>
        <th class = "firsttd">Member's list</th>
        <th class = "secondtd"></th>
        <th class = "secondtd"></th>
    </tr>

    <?php $m=0; foreach($this->groupmembers as $groupmem){ $m++; ?>

        <tr>
        <td class = "firsttd"><?php echo $m.")   "; echo $groupmem['name']; if($groupmem['member_id'] == $this->grouphead) { echo "  <font color='green'>(Head)</font>"; }?></td>
        <td class = "secondtd"></td>
        <td class = "thirdtd"></td>
        </tr>
     <?php } ?> 
    <tr>
        <th class = "firsttd" align="center">Representative's list</th>
        <th class = "secondtd"></th>
        <th class = "secondtd"></th>
    </tr>

    <?php $g=0; foreach($this->groupreps as $grouprep){ $g++;?>

        <tr>
        <td class = "firsttd"><?php echo $g.")   "; echo $grouprep['name'];?></td>
        <td class = "secondtd"></td>
        <td class = "thirdtd"></td>
        </tr>
     <?php } ?>
      <tr><td><a href="<?php echo $this->baseUrl(); ?>/groupm"><input type="button" name="back" value="Back"></a></TD></tr>
</table>
</div>

</body>
</html>
 
