<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<form action="<?php echo $this->baseUrl();?>/ledger/index/deleteledger/id/<?php echo $this->id;?>" method="POST"  name= "deleteledger">
    <table id="hor-minimalist-b" summary="Employee Pay Sheet" >
        <tr><Th colspan="2">Delete Ledger</TD></tr>
        <tr>
            <td><b><B style="color:red">Are you sure you want to delete Ledger "<? echo $this->glcode;?>"</b></td>
             <td><font color="green"><b>*</b></font>Remarks<?php echo $this->form->remarks;?></label></td>

        </tr>
        <TR>
            <TD > <input name="Delete" type="submit" class="officebutton" value="Yes"></td>
            <td align="right"><a href=<?php echo $this->baseUrl();?>/ledger/index>
            <input name="submit" type="button" class="officebutton" value="No"></a></td>
        </TR>
    </table>
<?php  echo "<font color=red>".$this->errormsg."</font>";?>
</form>