    <TABLE id="hor-minimalist-b">
        <TR>
            <TH class = "firsttd">Ledger information</TH>
            <TH class = "secondtd"></TH>
            <TH class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/ledger/index/editsubledger/id/<?php echo $this->id;?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></TH>
        </TR>
        <TR>
            <TD >Ledger code</TD>
            <TD ><?php echo $this->glcode;?></TD>
            <TD></TD>

        </TR>
        <TR>
            <TD >Sub ledger code</TD>
            <TD ><?php echo $this->glsubcode;?></TD>
            <TD></TD>
        </TR>
        <TR>
            <TD >Gl header</TD>
            <TD ><?php echo $this->subheader;?></TD>
            <TD></TD>
        </TR>
        <TR>
            <TD >Office name</TD>
            <TD ><?php echo $this->officename;?></TD>
            <TD></TD>
        </TR>
        <TR>
            <TD >Description</TD>
            <TD >
            <?php echo $this->glsubaccountdescription;?></TD>
            <TD></TD>
        </TR>
        <TR>
            <TD >Created by</TD>
            <TD ><?php echo $this->login_name;?></TD>
            <TD></TD>
        </TR>
        <TR>
            <TD>Created date</TD>
            <TD ><?php $dateconvert = new App_Model_dateConvertor();
                        $d=explode(' ',$this->created_date); 
                        echo $dateconvert->phpnormalformat($d[0]);?></TD>
            <TD></TD>
        </TR>
        <TR>
                <TD></TD>
            <TD></TD>
            <td><a href=<?php echo $this->baseUrl(); ?>/ledger/index>
                    <input name="submit" type="submit" class="officebutton" value="Back"></a></td>
        </TR>
</TABLE>
