<form name="editform" action="<?php echo $this->baseUrl();?>/bank/index/editbank" method="POST">
	<fieldset>
    	<legend>Edit bank<a href="<?php echo $this->baseUrl();?>/bank/index/deletebank/id/<?php echo $this->id;?>">
                        <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="20" height="20" align="right"></a></legend> 
        <table class="fieldsets"> 
            <?php echo $this->form;?>
        </table>
        <div class="btnhouse">
	   		<div class="ltbtns">
				<?php echo $this->submitform->Submit;?>
	   		</div>
	   		<div class="rtbtns">
				<a href="<?php echo $this->baseUrl();?>/bank"><input type = "button" name = "Back" value = "Back"></a>
	   		</div>
        </div>
	</fieldset>
</form>

