<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<style type="text/css">
tr#bcolor
{
background-color : silver;
}
</style>
<div class="profile_tab"> 
<?php if(!$this->groupname){ ?>
<!--search form action !-->
<fieldset>
	<legend>Group Resolution</legend>
		<form action="<?php echo $this->baseUrl();?>/groupresolutionkoota" method="POST">
			<table class="fieldsets">
					<tr>
						<td ><label class="mand">Group code:</label></td>
						<td ><? echo $this->form->membercode;?></td>
					</tr>
			</table>
			<input type="submit" name="Search" id="Submit" value="Search">			
		</form>	
</fieldset>
<?php } ?>
</div>

<div class="profile_tab"> 
  <?php $i=0; if($this->groupname){ $i++ ?>
	<?php foreach($this->groupname as $member) : ?>
	<table width="100%" border="2" id="hor-minimalist-b">	
	<th colspan="4"><?php echo "<font color=green>";?>Group Resolution</th>

<tr><TD><b>Group name :</b><?php echo $member['groupname'];?></TD>
<td align="left"><b>Date :</b><?php echo date('d-m-Y');?></td></tr>
<tr><TD><br><b>Address:</b><?php  echo $member['address1'];?><?php  echo $member['address2'];?><?php  echo $member['address3'];?>
<br><b>City&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</b><?php  echo $member['city'];?>
<br><b>Sate&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</b><?php  echo $member['state'];?></td>
<td align="left"><b>Group code :</b><?php  echo $member['groupcode'];?></td></tr>
</table>
<?php endforeach; ?>
<br><br>
        <p>1) cdsjsjlkdsfjlkd sfjkldfjlksdfjsd   kfjdsfhjdsfhds  jgfgiuiqup</p>
        <p>2) cdsjsjlkdsfjlkd sfjkldfjlksdfjsd   kfjdsfhjdsfhds  jgfgiuiqup</p>
        <p>3) cdsjsjlkdsfjlkd sfjkldfjlksdfjsd   kfjdsfhjdsfhds  jgfgiuiqup</p>
        <p>4) cdsjsjlkdsfjlkd sfjkldfjlksdfjsd   kfjdsfhjdsfhds  jgfgiuiqup</p>
<?php $i=0; foreach($this->represent as $name){ $i++ ?>
<?php echo $i.")"; ?>&nbsp;<?php echo "<font color=green>".$name['memnames']."</font>"?><br><br>
<?php } ?>
<br><br>

	<table id="hor-minimalist-b" border="2">
<tr>
		<Th>S.no</Th>
		<Th>Member name</Th>
<!--		<Th>Survey no</Th>
		<Th>Loan request amount</Th>-->
		<Th>Signature</Th>
</tr>

	<?php $i=1; foreach($this->groupmembers as $memberdetail) :?>

<tr>
	<td align="center" width="5%"><?php  echo $i;$i++;?></td>
	<td width="25%"><?php  echo $memberdetail['membername'];?></td>
<!--<td align="center" width="15%"><?php // echo $memberdetail['survey_no'];?></td>
	<td width="20%"><?php  //echo $memberdetail['request_amount'];?></td>-->
	<td width="20%"></td>

</tr>
<?php endforeach ; ?>


</table>

<form action="<?php echo $this->baseUrl();?>/groupresolutionkoota/index/pdfgeneration/membercode/<?php echo $this->groupid ?>" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/groupresolution/index/reportdisplay/file/groupresolution<? echo date('Y-m-d');?>.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">

           <BR> <input type="submit" value="PDF" id="submit">
</form><?php 
} ?>

<b style="color:red"><?php echo $this->error;?></b>


</div>
