<BODY ></BODY>  <!--onload="toggleField();"-->
<script>
$(document).ready(function() {

path=$("#baseurl").val();

    $('#toglcode').change(function(){
    getglsubcode();
    });

        $('#fromglcode').change(function(){
        getglcode();
        });

$('#officeType').change(function(){
getBranch();
});

$('#amount').keyup(function(){
getLatestBalanceFrom();
});

    function getLatestBalanceFrom(){
    var strURL=path+"/receipts/index/latestbalancefrom";
    var amount=$("#amount").val();
    var balance1=$("#balance1").val();
    $.ajax({
        url: strURL,
        data : { amount: amount, balance1: balance1 },
        success: function(result){
    $('#amt1').html(result);
    }
    }); getLatestBalanceTo();}

function getLatestBalanceTo(){
var strURL=path+"/receipts/index/latestbalanceto";
var amount=$("#amount").val();
var balance2=$("#balance2").val();
$.ajax({
    url: strURL,
    data : { amount: amount, balance2: balance2 },
    success: function(result){
$('#amt2').html(result);
}
}); }

    function getBranch(){
    var strURL=path+"/receipts/index/getbranch";
    $.ajax({
        url: strURL,
        data:"id="+$("#officeType option:selected").val(),
        success: function(result){
    $('#statediv').html(result);
        }
    }); }

function getglcode(){
var strURL=path+"/receipts/index/glsubcode";
$.ajax({
  url: strURL,
  data:"glcode="+$("#fromglcode option:selected").val(),
  success: function(result){
$('#tect2').html(result);
  }
}); }

    function getglsubcode(){

    var strURL=path+"/receipts/index/getglsubcode";
    $.ajax({
    url: strURL,
    data:"glcode="+$("#toglcode option:selected").val(),
    success: function(result){
    $('#tect1').html(result);	

    }
    }); }

});


function getdateamount() {
    var date = $('#transactiondate').val();
    var amount = $('#amount').val();
    $('#transactiondate1').val(date);
    $('#amount1').val(amount);
}

function toggleField1() {
var ptype = $('#paymenttype').val();
if(ptype!=1){
$('.show').show();
}else{
$('.show').hide();
}
// $('#details').show();
// $('#details1').show();
// $('#details2').show();
// $('#details3').show();
// } else {
// $('#toglcode').hide();
// $('#details1').hide();
// $('#details2').hide();
// $('#details3').hide();
// }
}
</script> 

<fieldset>
	<legend>Receipt and payment<br/>
<?php $receipts= new Receipts_Model_Receipts();
                $mainBranch = $receipts->getHeadOffice($this->username); foreach($mainBranch as $mainBranch) { if($mainBranch) { ?>
<p align="right" style="Bold"><font color="Navy"><?php echo $mainBranch['type']; ?></font> :
<?php echo $mainBranch['name']; ?> <br/>
<?php $officeid= $mainBranch['id']; }} $branch= $receipts->getBranch($officeid); foreach($branch as $branch) { if ($branch) {?>
<font color="Navy"><?php echo $branch['type']; ?></font> :
<?php echo $branch['name']; }}?></p></legend> 

	<div class="cont-rgt-data">
		<form action="<?php echo $this->baseUrl();?>/receipts" method="POST">
<input type="hidden" value="<?php  echo $this->baseUrl();?>" id="baseurl"/>
<font color="Purple"><B>Ledger Details</B></font>
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">

				<tr>
					<td>From GL code</td>
					<td><?php echo $this->form->fromglcode;?></td>
					<td >* To GL code</td>
					<td ><?php echo $this->form->toglcode;?></td> 
				</tr>

				<tr>
					<td>From GL subcode</td>
					<td><div id="errorspan2" style="display:none" class="reqMark"><div id="statediv2"></div></div><div id="tect2"  class="reqMark"><?php echo $this->form->fromglsubcode;?></div></td>
                                        <td >* To GL subcode</td>
					<td ><div id="errorspan1" style="display:none" class="reqMark"><div id="statediv1"></div></div><div id="tect1"  class="reqMark"><?php echo $this->form->toglsubcode;?></div></td> <td></td>
				</tr>

                                <tr>
                                    <td>Current Balance: </td>
                                    <td><div id="statediv3"><?php  echo $this->form->balance1;?></div></td>
                                    <td>Current Balance: </td>
                                    <td><div id="statediv3"><?php  echo $this->form->balance2;?></div></td>
                                </tr>

                        </table><br/><br/><br/>
<font color="Purple"><B>Transaction Details</B></font>
                        <table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<tr>
					<td>* Transaction mode</td>
					<td><div id="tect3"><?php echo $this->form->paymenttype;?></div></td>
					<td>  Description</td>
					<td><?php echo $this->form->description;?></td></tr>

				<tr>	<td></td><td class="show" style="display:none"><?php echo $this->form->paymenttype_details;?>Voucher/cheque/draft/E-Transfer</td>
                                        <td></td><td></td><td></td><td></td>
				</tr>

                        </table><br/><br/><br/>
<font color="Purple"><B>Amount Details</B></font>
                        <table id="hor-minimalist-b" summary="Employee Pay Sheet">

				<tr>
					<td>* Amount</td>
					<td><?php echo $this->form->amount;?></td>
					<td>* Date</td>
					<td><?php echo $this->form->transactiondate;?></td>
				</tr>
                                <tr>
                                    <td>Latest Balance :</td>
                                    <td><div id="amt1"><?php  echo $this->form->latestbalancefrom; ?></div></td>
                                    <td>Latest Balance :</td>
                                    <td><div id="amt2"><?php  echo $this->form->latestbalanceto; ?></div></td>
                                </tr>

				<tr>
					<TD colspan = "2"><?php echo $this->form->Submit;?></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
				</tr>
			</table>
</div>



		</form>
	</h>
</fieldset>

