<BODY ></BODY>  <!--onload="toggleField();"-->
<script>
function getXMLHTTP() { //fuction to return the xml http object
		var xmlhttp=false;	
		try{
			xmlhttp=new XMLHttpRequest();
		}
		catch(e)	{		
			try{			
				xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
			}
			catch(e){
				try{
				xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
				}
				catch(e1){
					xmlhttp=false;
				}
			}
		}
		 	
		return xmlhttp;
    }

    function getBranch(office_id,path) {		
    var strURL = path +"/receipts/index/getbranch?id="+office_id;

    var req = getXMLHTTP();
    if (req) {
        req.onreadystatechange = function() {
        if (req.readyState == 4) {   // only if "OK"
        if (req.status == 200) {	
            document.getElementById('statediv').innerHTML=req.responseText;						
        } else {
               alert("There was a problem while using XMLHTTP:\n" + req.statusText);
            }
        }
            }	
        req.open("GET", strURL, true);
        req.send(null);
        }
	}
	
$(document).ready(function() {

path=$("#baseurl").val();

    $('#toglcode').change(function(){
    getglsubcode();
    });

        $('#fromglcode').change(function(){
        getglcode();
        });

function getglcode(){
var strURL=path+"/receipts/index/glsubcode";
$.ajax({
  url: strURL,
  data:"glcode="+$("#fromglcode option:selected").val(),
  success: function(result){
$('#tect2').html(result);
  }
});
 }

function getglsubcode(){

var strURL=path+"/receipts/index/getglsubcode";
$.ajax({
  url: strURL,
  data:"glcode="+$("#toglcode option:selected").val(),
  success: function(result){

$('#tect1').html(result);	

  }
});
 }
});


function getdateamount() {
    var date = $('#transactiondate').val();
    var amount = $('#amount').val();
    // alert(date);
    $('#transactiondate1').val(date);
    $('#amount1').val(amount);
}


function toggleField1() {
var ptype = $('#paymenttype').val();
if(ptype!=1){
$('.show').show();
}else{
$('.show').hide();
}
// $('#details').show();
// $('#details1').show();
// $('#details2').show();
// $('#details3').show();
// } else {
// $('#toglcode').hide();
// $('#details1').hide();
// $('#details2').hide();
// $('#details3').hide();
// }
}
</script> 

<fieldset>
	<legend>Receipt and payment</legend>
	<div class="cont-rgt-data">
		<form action="<?php echo $this->baseUrl();?>/receipts" method="POST">
<input type="hidden" value="<?php  echo $this->baseUrl();?>" id="baseurl"/>
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
                                <tr>
                                    <td>Office Levels</td>
                                    <td><?php  echo $this->form->officeType;?></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>Branch</td>
                                    <td><div id="statediv"><?php  echo $this->form->subOffice;?><span class="reqMark"></span></div></td>
                                    <td></td>
                                    <td></td>
                                </tr>
				<tr>
					<td>Date</td>
					<td><?php echo $this->form->transactiondate;?></td>
					<td></td>
					<td><?php //echo $this->form->transactiondate1;?></td>
				</tr>
				<tr>
					<td>Amount</td>
					<td><?php echo $this->form->amount;?></td>
					<td></td>
					<td><?php //echo $this->form->amount1;?></td>
				</tr>

				<tr>
					<td>From GL code</td>
					<td><?php echo $this->form->fromglcode;?></td>
					<td >To GL code</td>
					<td ><?php echo $this->form->toglcode;?></td> 
				</tr>

				<tr>
					<td>From GL subcode</td>
					<td><div id="errorspan2" style="display:none" class="reqMark"><div id="statediv2"></div></div><div id="tect2"  class="reqMark"><?php echo $this->form->fromglsubcode;?></div></td>
                                        <td >To GL subcode</td>
					<td ><div id="errorspan1" style="display:none" class="reqMark"><div id="statediv1"></div></div><div id="tect1"  class="reqMark"><?php echo $this->form->toglsubcode;?></div></td> <td></td>
				</tr>

                                <tr>
                                    <td>Balance:</td>
                                    <td><div id="statediv3"><?php  echo $this->form->balance1;?></div></td>
                                    <td>Balance:</td>
                                    <td><div id="statediv3"><?php  echo $this->form->balance2;?></div></td>
                                </tr>

				<tr>
					<td >Transaction mode</td>
					<td ><?php echo $this->form->paymenttype;?></td> 
					<td class="show" style="display:none"><?php echo $this->form->paymenttype_details;?>Voucher/cheque/draft</td>
					<td></td> <td></td>
				</tr>

				<tr>
					<td>Description</td>
					<td><?php echo $this->form->description;?></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<TD colspan = "2"><?php echo $this->form->Submit;?></TD>
                                    <td></td>
                                    <td></td>
                                    <td></td>
				</tr>
			</table>
		</form>
	</h>
</fieldset>

