<?php if (count($this->membercode)) { ?>
            <table id="hor-minimalist-s">
            <tr> 
                <th ><?php echo $this->translate("Group details"); ?></th>
                <th></th>
            </tr>
            <?php  
      foreach($this->groupDeatils as $details) { ?> 
            <tr> 
                <td ><?php echo $this->translate("Group name"); ?></td>
                <td><?php echo $details->groupname; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("Group code"); ?></td>
                <td><?php echo $details->groupcode; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("Village"); ?></td>
                <td><?php echo $details->officename; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("No. of members"); ?></td>
                <td><?php echo $details->groupNum; ?></td>
            </tr>
            <?php } ?>
        </table> 
        <br>
<!--     <form action="<?php //echo $this->baseUrl();?>/groupprofile/index/add" method="POST"> -->
        <table id="hor-minimalist-b" border="1">
            <tr> 
                <th width="10%"><?php echo $this->translate("Sl no"); ?></th>
                <th width="20%"><?php echo $this->translate("Member name"); ?></th>
                <th width="5%"><?php echo $this->translate("Age"); ?></th>
                <th width="20%"><?php echo $this->translate("Education"); ?></th>
                <th width="14%"><?php echo $this->translate("Member code"); ?></th>
                <th width="5%"><?php echo $this->translate("Caste"); ?></th>
                <th width="15%"><?php echo $this->translate("Primary Occupation"); ?></th>
                <th width="35%"><?php echo $this->translate("land"); ?></th>
         </tr>

         <?php 
			$adm = new App_Model_Adm();$i = 1; 
     foreach($this->group as $loandetails) { ?>
            <tr>
                <td width="5%" align="center"><?php echo $i++;?></td>
                <td><?php echo $loandetails['membername']; ?></td>
                              <td align="center"><?php echo $loandetails['age']; ?></td>
                              <td align="center"><?php echo $loandetails['education']; ?></td>
                              <td align="center"><?php echo $loandetails['familycode']; ?></td>
                              <td align="center"><?php echo $loandetails['caste']; ?></td>
                              <td align="center"><?php echo $loandetails['profession'];?></td>
            <?php  } ?>
        
 <?php $i =1; foreach($this->landDetails as $landdetails) { ?>
 
         <td align="center"><?php echo $landdetails['name'];?> </td>
   </tr>   
 
 
 
<?php } ?>
    
        
   
        
        </table>
    </form>
    </fieldset>
<?php }  ?>
<?php if(!$this->membercode) { ?>

<fieldset>
	<legend>Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/groupprofile/index" method="POST">
			<table class="fieldsets">
                            <TR>
                                <th><label class="mand">Group code :</label></TD>
                                <th><? echo $this->form->s1;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Submit;?><br><br>
                                <table><TR><TD><?php echo "<font color='red' size='2'>".$this->error."</font>";?></TD></TR></table>
                            </div>
                        </div>
	       </form>
</fieldset>
<?php } ?>

