<?php if (count($this->group)) { ?>
            <table id="hor-minimalist-s">
            <tr> 
                <th ><?php echo $this->translate("Group details"); ?></th>
                <th></th>
            </tr>
            <?php foreach($this->groupDeatils as $details) { ?>
            <tr> 
                <td ><?php echo $this->translate("Group name"); ?></td>
                <td><?php echo $details->groupname; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("Group code"); ?></td>
                <td><?php echo $details->groupcode; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("Village"); ?></td>
                <td><?php echo $details->officename; ?></td>
            </tr>
            <tr>
                <td ><?php echo $this->translate("No. of members"); ?></td>
                <td><?php echo $details->groupNum; ?></td>
            </tr>
            <?php } ?>
        </table> 
        <br>
    <form action="<?php echo $this->baseUrl();?>/groupprofile/index/add" method="POST">
        <table id="hor-minimalist-b" border="1">
            <tr> 
                <th width="10%"><?php echo $this->translate("Sl no"); ?></th>
                <th width="20%"><?php echo $this->translate("Member name"); ?></th>
                <th width="5%"><?php echo $this->translate("Age"); ?></th>
                <th width="15%"><?php echo $this->translate("Education"); ?></th>
                <th width="14%"><?php echo $this->translate("Member code"); ?></th>
                <th width="20%"><?php echo $this->translate("Caste"); ?></th>
                <th width="20%"><?php echo $this->translate("land"); ?></th>
                <th width="20%"><?php echo $this->translate("Occupation"); ?></th>
            </tr>
            <?php $i = 1; 
            foreach($this->group as $loandetails) { ?>
            <tr>
                <td><?php echo $i;?></td>
                <td><?php echo $loandetails->name; ?></td>
                <td><?php echo $loandetails->age; ?></td>
                <td><?php echo $loandetails->education; ?></td>
                <td><?php echo $loandetails->familycode; ?></td>
                <td><?php echo $loandetails->catse; ?> - <?php echo $loandetails->subcatse; ?></td>
                <td><?php echo $loandetails->acre; ?>  - <?php echo $loandetails->gunta; ?></td>
                <td><?php echo $loandetails->profession; ?></td>
            </tr>
            <?php $i++; } ?>
        </table>
    </form>
    </fieldset>
<?php } else { ?>
<fieldset>
	<legend>Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/groupprofile/index" method="POST">
			<table class="fieldsets">
                            <TR>
                                <th><label class="mand">Group code :</label></TD>
                                <th><? echo $this->form->membercode;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Submit;?>
                            </div>
                        </div>
	       </form>
</fieldset>
<?php } ?>

