<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<html>
<body>
<div id = "searchDiv">
<table id="hor-minimalist-b">
    <tr>
            <th class = "firsttd">Group information</th>
            <th class = "secondtd"></th>
			<th></th>
<!--             <th class="thirdtd"><a href="<?php //echo $this->baseUrl();?>/kootadefault/index/editkoota/id/<?php //echo $this->kootaid; ?>"><img src="<?php //echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th>  -->
    </tr>
    <?php $dateconvertor = new App_Model_dateConvertor(); ?>
        <? foreach($this->kootadetails as $koota){}?>
	<tr>
            <td class = "firsttd">Koota name</td>
            <td class = "secondtd"><?php echo $koota['kootaname']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
        <tr>
            <td class = "firsttd">Penalty for late attendance</td>
            <td class = "secondtd"><?php echo $koota['penalty_latecoming']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
        <tr>
            <td class = "firsttd">Penalty for absence</td>
            <td class = "secondtd"><?php echo $koota['penalty_notcoming']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
         <tr>
            <td class = "firsttd">Group lending Interest (%)</td>
            <td class = "secondtd"><?php echo $koota['rateinterest']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
	<tr>
            <td class = "firsttd">Created date</td>
            <td class = "secondtd"><?php echo $dateconvertor->phpnormalformat($koota['register_date']); ?></td>
            <td class = "thirdtd"></td>
	</tr>

    <tr>
        <th class = "firsttd">Member's list</th>
        <th class = "secondtd"></th>
        <th class = "secondtd"></th>
    </tr>

    <? foreach($this->kootamembers as $kootamembers){ ?>

        <tr>
        <td class = "firsttd"><?php echo $kootamembers['name']; ?></td>
        <td class = "secondtd"></td>
        <td class = "thirdtd"></td>
        </tr>
     <?php } ?>
      <tr><td><a href="<?php echo $this->baseUrl(); ?>/koota"><input type="button" name="back" value="Back"></a></TD></tr>
</table>
</div>

</body>
</html>
 
