<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/holiday/index/holidayedit/id/<? echo $this->id; ?>" method="POST">
 	<div id="container-1">
		<div class="profile_tab">
		     <table id="hor-minimalist-b" class="fieldsets">	
                                                <tr><Th>Edit holiday Information</Th><th><a href="<?php echo $this->baseUrl();?>/holiday/index/holidaydelete/id/<? echo $this->id; ?>" method="POST"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 align="right" width="16" height="16"></a></th></tr>
						
						<?php echo $this->form;?>

<tr><TD align="left"><input type="submit" name="Update" id="Submit" value="Update"></TD>
    <TD align="right"><a href="<?php echo $this->baseUrl();?>/holiday"><input type="button" name="Back"  value="Back"></a></TD>
</tr>
 					</table>
		</div>
	</div>
</form>