<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--<a href="#" id="open"></B>Change Log</B></a>

<div id="content1">
<fieldset>
<legend>Members in account</legend>

<table id="hor-minimalist-b">
<tr >
<th >Feild Name</th>
<th >Old Value</td>
<th >New Value</td>
<th >Changed By</td>
<th >Change Date</th>
</tr>

<?php //foreach ($this->changelog as $changelog): ?>
<tr >
<td ><?php //echo $this->escape($changelog['filedname']);?></td>
<td ><?php //echo $this->escape($changelog['previous_data']);?></td>
<td ><?php //echo $this->escape($changelog['current_data']);?></td>
<td ><?php //echo $this->escape($changelog['login_name']);?></td>
<td ><?php //echo $this->escape($changelog['modified_date']);?></td>
</tr>
<?php //endforeach; ?>
</table>
</fieldset>
<p><a href="#" id="close">hide</a></p>
</div>  
<br/><br/>-->

<script type="text/javascript">
$(document).ready(function() {
    $("#s3").datepicker({"dateFormat":"dd/mm/yy"});
    $("#s4").datepicker({"dateFormat":"dd/mm/yy"});
});
</script>
<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
<!--search form action !-->
                    <form action="<?php echo $this->baseUrl();?>/holiday" method="POST">
                            <table width="100%">
                                <tr>
                                                        <td class="label">Holiday name:</td>
							<td ><?php echo $this->form->s1;?></td>
							<td class="label">Office name:</td>
							<td ><?php echo $this->form->s2;?></td>
                                </tr>
                                <tr>
                                                        <td class="label"><br>Holiday from:</td>
							<td ><?php echo $this->form->s3;?></td>
							<td class="label"><br>Holiday upto:</td>
							<td ><br><?php echo $this->form->s4;?></td>
                                </tr>
                            </table><br>
                              <div class="ltbtns">
					<input type="submit" name="Search" id="Submit" value="Search"></div>		
                    </form>	
            </div>
    </fieldset> 
</div>  
<?php if ($this->paginator) { ?>
<table id="hor-minimalist-b" >
    	<tr class="tdbrownheading">
                <th>Holiday name</th>
                <th>Office name</th>
                <th>Holiday from</th>
		<th>Holiday upto</th>
		<th>Repayment date</th>

        </tr>
        <?php $dateconvert= new App_Model_dateConvertor();
      foreach ($this->paginator as $category ): ?>
    <tr>
        <td><a href="<?php echo $this->baseUrl()."/holidaycommonview/index/holidayview/id/".$category['id']; ?>"><?php echo $this->escape($category['name']);?>
            </a>
        </td>
             <td><?php echo $this->escape($category['officename']);?>
            </td>
            <td><?php echo $this->escape($dateconvert->normalformat($category['holiday_from']));?>
            </td>
            <td><?php echo $this->escape($dateconvert->normalformat($category['holiday_upto']));?>
            </td>
            <td><?php echo $this->escape($dateconvert->normalformat($category['repayment_date']));?>
            </td>
   </tr>
     <?php endforeach; ?>
   
</table>
<?php } ?>

<div align="center" style="margin-top:10px;color:#CC6633;">
<?php echo $this->paginationControl($this->paginator,'Sliding','/partials/my_pagination_control.phtml',$this->requestvalues); ?>
</div>
