<script> 
$(document).ready(
  function() {

    $('.getamount').click(function() {
	var id=$(this).attr("name").split("-");
        if($('#fee-'+id[1]).is(':checked')) {
        if($(this).val())
        {
                     $('#feeamount-'+id[1]).show();
          uid=$(this).val();
           path=$('#baseurl').val();
           targeturl=$('.pathid').val()+"/loanaccount/index/feeamount?feeid="+$(this).val()+"&loanamount="+$('.amountclass').val()+"&hidden="+id[1];
	   $.ajax({ url: targeturl, success: function(data){ $('#feeamount-'+id[1]).html(data) }});
        }

        } else {
            $('#feeamount-'+id[1]).hide(); 
        }
    });

    $(".getinterest").change( function() { 
        if($(this).val())
        {  uid=$(this).val();
           path=$('#baseurl').val();
           targeturl=$('.pathid').val()+"/loanaccount/index/interest?interest="+$(this).val()+"&productId="+$('.productid').val();
	   $.ajax({ url: targeturl, success: function(data){ $('#interestratediv').html(data) }});
        }
    }); 
});

function displayRow(type) {
    var row = document.getElementById("funder");
    if(type == '0')
    row.style.display = 'none';
    else if (type == '1')
    row.style.display = '';

}
</script>
<?php 
if ($this->account) {
foreach ($this->account as $account) {
?>
<div style="float:left;width:380px"> 
    <table id="hor-minimalist-s" summary="Employee Pay Sheet">
        <TR>
            <TH>Member details</TH>
            <TH></TH>
        </TR>
        <TR>
            <td>Member code:</td>
            <TD><? echo $account->code; ?></TD>
        </TR>
        <TR>
            <td>Name:</td>
            <TD><?php echo $account->name;?></TD>
        </TR>
        <TR>
            <td>Branch:</td>
            <td><?php echo $account->officename ;?></TD>
        </TR>
        <TR>
            <TH>Product details</TH>
            <TH></TH>
        </TR>

        <TR>
            <td>Product name:</td>
            <TD><?php echo $account->productname;?></TD>
        </TR>
        <TR>
            <td>Min disbursement:</b></td>
            <TD><?php echo $account->minamount;?></TD>
        </TR>

        <TR>
            <td>Max disbursement:</td>
            <TD><?php echo $account->maxamount; ?></TD>
        </TR> 
        <TR>
            <td>Penal interest:</td>
            <TD><?php echo $account->penalInterest; ?></TD>
        </TR>
        <TR>
            <td>Requested loan amount:</td>
            <TD><?php echo $account->requestamount; ?></TD>
        </TR>
        <TR>
            <TH>Interest per annum</TH>
            <TH></TH>
        </TR>
        <TR>
            <TD><B>Periods in months</B></TD>
            <TD><B>Interest</B></TD>
        </TR>
        <?php if ($this->interestRates) {
              foreach ($this->interestRates as $interestRates) { ?>
              <TR>
                <td><?php echo $interestRates->period_ofrange_description; ?></td>
                <TD><?php echo $interestRates->Interest; ?></TD>
             </TR>
       <?php } } ?>
    </table>
<?php } } ?>
</div>
<div style="float:left;width:350px"> 
    <fieldset>
        <legend>Loan account</legend>
            <form name="addform" action="<?php echo $this->baseUrl();?>/loanaccount/index/createaccount" method="POST">
            <table class="fieldsets">
                    <TR>
                        <TD><label for="fld1" class="mand">Date of account</TD>
                        <TD><?php echo $this->loanForm->date;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Loan amount</TD>
                        <TD><?php echo $this->loanForm->amount;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Installments (Months)</TD>
                        <TD><?php echo $this->loanForm->installments;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Interest rate</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->interest;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Interest type</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->interesttype_id;?></div></TD>
                    </TR>
                   <!-- <TR>
                        <TD><label for="fld1" class="mand">Transfer amount to</TD>
                        <TD><div id="interestratediv"><?php //echo $this->loanForm->savingAccount;?></div></TD>
                    </TR>-->
                    <TR>
                        <TD><label for="fld1" class="mand">Fundings</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->fundings;?></div></TD>
                    </TR>
                    <TR id = "funder" style="display:none">
                        <TD><label for="fld1" class="mand">Funder</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->funders;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Fee</TD>
                        <TD><?php $i=0; foreach($this->feedetails as $fee) { $i++ ?>
                        <div>
                        <div style="width:auto; float:left;"><input type="checkbox" name="fee-<?php echo $i; ?>" id="fee-<?php echo $i; ?>" class="txt_put getamount" value="<?php echo $fee['id']; ?>">
                        <?php echo $fee['name']; ?>:&nbsp;</div><div style="width:auto; float:left;" id="feeamount-<?php echo $i ?>"></div></div><br>
                        <?php } ?>
                        </TD>
                    </TR>
                    <TR>
                        <TD><?php echo $this->loanForm->Submit; ?></TD>
                        <td><a href="<?php echo $this->baseUrl();?>/loanaccount"<?php echo $this->loanForm->Back; ?></a></td>
                    </TR>
                    <?php echo '<font color=RED>'.$this->maxdate.'</font>'; ?>
                </table>
                <?php echo $this->loanForm->Id; echo $this->loanForm->code; echo $this->loanForm->path; echo $this->loanForm->productid; ?> <?php  ?> 
            </form>
</div>
