<fieldset>
	<legend>Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/loanaccount" method="POST">
			<table class="fieldsets">
                            <TR>
                                <TD><label for="fld3">Member code / Name / Group Name</label></TD>
                                <TD><? echo $this->form->s1;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Submit;?>
                            </div>
                        </div>
	 </form>

</fieldset>

    <table id="hor-minimalist-b" summary="Employee Pay Sheet">
	<tr>
	    <Th>Member Code</Th>
	    <Th>Name / Group Name</th>
            <Th>Branch</th>
	    <td class="centertd" align="center">Type</td>
            <th></th>
	</tr>
	<?php foreach($this->loanaccount as $member) : ?>
	<tr>
		<td><a href="<?php echo $this->baseUrl();?>/loanaccount/index/details/code/<?php echo base64_encode($member->code);?>"><?php echo $member->code;?></a></td>
		<td><?php  echo $member->name;?></td>
		<td><?php  echo $member->officename;?></td>
		<td>
		<?php if ($member->type==1) { 
		 echo $member->membertype;;  
		} else {
		  echo "-"; 
		} ?>
		</td>
		<td>
		<?php if($member->type==2 || $member->type==3) { 
		echo $member->membertype;
		} else {
		echo "-";
		}?>
		</td>
	</tr>
	<?php endforeach; ?>
	
     
   <?php if ($this->paginator) { ?>

	<div align="center" style="margin-top:10px;color:#CC6633;">
       <tr>
       <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding','/partials/my_pagination_control.phtml',$this->requestvalues); ?>
        </div></td></tr>

        </table>
  
    <?php } ?>


</table>