<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id = "searchDiv">
    <fieldset>
        <form action="<?php echo $this->baseUrl();?>/kootadefault/index/deletekoota/id/<?php echo $this->kootaid; ?>" method="POST">
            <table class = "fieldsets">
                <TR>
                    <TD><font color="red">Are you sure you want to delete</font></TD>
                    <TD><?php echo $this->form->remarks;?></TD>
                </TR>
                <tr>
            <div class="btnhouse">
                <div class="ltbtns">
                    <td class = "firsttd"><?php echo $this->form->Submit;?></td>
                </div>
                <div class="rtbtns">
                    <td class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/kootacommonview/index/commonview/id/<?echo $this->kootaid; ?>"><?php echo $this->form->Back;?></a></td>
                </div>
            </div>
                </tr>
        </table>
        </form>
    </fieldset>
</div>


