<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
function getgroups(branch,path) {
	if(branch) {
		targeturl=path+"/cashscroll/index/group?branch="+branch;
		$.ajax({ url: targeturl, success: function(data){ $("#groupdiv").html(data) }});
	}
}
$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});

</script>


<?php
if((!$this->income) && (!$this->expenditure)){ ?>
<form action="<?php echo $this->baseUrl();?>/incomeexpenditure/index" method="POST">
<div id="searchDiv">
            <div class="search">
                <TABLE id="hor-minimalist-b">
				<th colspan="4">Search</th>
                   <tr>
  <TR>
							<TD><?php echo $this->translate('Hierarchy'); ?></td>
                            <TD id="show"><?php echo $this->form->hierarchy;?></td>
  
                            <TD><br><?php echo $this->translate('As of date :'); ?></td>
                            <td><?php echo $this->form->datefrom;?></td>
 						
</tr><tr>

                            <TD><?php echo $this->translate('Branch'); ?></td>
                            <td><div id="statediv"><?php echo $this->form->branch;?></div></td>
						<td></td>
<td></td>
</tr>
<tr id="hide">
							<TD><?php echo $this->translate('Group'); ?></td>
                            <td><div id="groupdiv"><?php echo $this->form->group;?></td>
<td></td>
<td></td>

</tr>




                            <td><input type="submit" name="Search" value="Search"/></td>
                   </tr>
        	</TABLE>
	   </div>
</div>
</form>
<?php } ?>
<?php  
$i=0;
$j=0;
$totalincome=0;$totalexpe=0;
$countvalue1 =count($this->income);
$countvalue2 =count($this->expenditure);
$count = $countvalue1>$countvalue2?$countvalue1:$countvalue2; 
if(($this->income) && ($this->incomeheader)) { ?>
	<h5 align="right"><?php echo $this->translate('As of'); ?> <font color='#039'><?php echo $this->asofdate;?></font></h5>
	<h5 style="text-align:right">* <?php echo $this->translate('Amount in'); ?> <font color="red"><?php echo $this->translate('Rs'); ?></font></h5>
<div style="float:left;width:370px">
<h5>Credit</h5>
            <TABLE id="hor-minimalist-s" summary="">
                <tr bgcolor="Silver" >
	            <td><font color="black"><?php echo $this->translate('Income'); ?></font></td>
	            <td align="right"><font color="black"><?php echo $this->translate('Amount'); ?></font></td>
                </tr>
		<tr>
                <?php foreach($this->incomeheader as $income) { $i++; ?>
<!--		<tr>-->
                    <td><?php echo $income['header']; ?></td>
                <?php } ?>
                <?php foreach($this->income as $income) { $i++; ?>
		    <td align="right"><?php echo $income['credit']; $totalincome +=$income['credit'];?></td>
                <?php } ?>
                </tr> 
 		<!--<?php //} ?>-->
                <tr>
                        <?php foreach($this->cashcredit as $cashcredit) { ?>
                        <td align="left"><?php echo $this->translate('Cash');?></td>
                        <td align="right"><?php echo $cashcredit['balance']=number_format ($cashcredit['balance'], 2, ".", ""); $totalincome += $cashcredit['balance'];?></td>
                        <?php } ?>
                </tr>
		<?php $i = $i - 1 ; ?>
		<?php 
			for($j=$i;$j<=$count;$j++){
			 if($j==$count){ ?>
				<tr>
					<TD><b><?php echo $this->translate('Sub Total'); ?></b></TD>
					<td align="right"><b><?php echo sprintf("%4.2f",$totalincome);?></b></td>
				</tr>
			<?php } else {?>
				<tr>
					<td><?php echo "----";?></td>
					<td align="right"><?php echo "----";?></td>
				</tr>
		
			<?php } } ?>
	   </TABLE>
	
 </div>
 <?php $i=0;$j=0; ?>
	 
<div style="float:right;width:370px">
<h5>Debit</h5>
	<TABLE id="hor-minimalist-s" summary="">
                <tr bgcolor="Silver">
	            <td><font color="black"><?php echo $this->translate('Expenditure'); ?></font></td>
	            <td align="right"><font color="black"><?php echo $this->translate('Amount'); ?></font></td>
                </tr>
		<tr>
		<tr >
                <?php foreach($this->expenditureheader as $expe1) { $i++; ?>
                    <td><?php echo $expe1['header']; ?></td>
                <?php } ?>
                <?php foreach($this->expenditure as $expe) { $i++; ?>
		    <td align="right"><?php echo $expe['credit']; $totalexpe +=$expe['credit']?></td>
		<?php }  ?>
                </tr>
                <tr>
                        <?php foreach($this->cashdebit as $cashdebit) { ?>
                        <td align="left"><?php echo $this->translate('Cash');?></td>
                        <td align="right"><?php echo $cashdebit['balance']; $totalexpe += $cashdebit['balance'];?></td>
                        <?php } ?>
                </tr>
		<?php $i = $i - 1 ; ?>
		<?php
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
				<tr>
					<TD><b><?php echo $this->translate('Sub Total'); ?></b></TD>
					<td align="right"><b><?php echo sprintf("%4.2f",$totalexpe);?></b></TD>
				</tr>
			<?php  } else {?>
				<tr>
					<td><?php echo "----";?></td>
					<td align="right"><?php echo "----";?></td>
				</tr>
		
			<?php } }  ?>
		</TABLE>
</div>	

<?php if ($totalincome > $totalexpe) {
$profit = $totalincome - $totalexpe;
$loss = 0;
$tot = $totalexpe+$profit;
} else {
$profit =0;
$loss = $totalexpe - $totalincome; 
$tot = $totalincome-$loss; }  ?>

<div style="float:left;width:370px">
        <TABLE id="hor-minimalist-s" summary="">
                <tr>
                        <td align="left"><B><?php echo $this->translate('Loss');?></B></td>
                        <td align="right"><?php if($loss!=0) {echo $loss = " " . str_replace('-', '', number_format ($loss, 2, ".", ",")) . "";} else {echo "----";}?></td>
                </tr>
                <tr>
                        <td align="left"><B><?php echo $this->translate('Total');?></B></td>
                        <td align="right"><?php  echo sprintf("%4.2f",$tot); ?></td>
                </tr>
        </TABLE>
</div>
<div style="float:right;width:370px">
        <TABLE id="hor-minimalist-s" summary="">
                <tr>
                        <td align="left"><B><?php echo $this->translate('Profit');?></B></td>
                        <td align="right"><?php if($profit!=0) {echo $profit = " " . str_replace('-', '', number_format ($profit, 2, ".", ",")) . "";} else {echo "----";} ?></td>
                </tr>
                <tr>
                        <td align="left"><B><?php echo $this->translate('Total');?></B></td>
                        <td align="right"><?php echo sprintf("%4.2f",$tot); ?></td>
                </tr>
        </TABLE>

</div>
	
<div style="float:left;width:800px">
<form action="<?php echo $this->baseUrl();?>/incomeexpenditure/index/pdftransaction" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/incomeexpenditure/index/reportdisplay/file/<?php echo $this->fdate; ?>incomeexpenditure.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <input type="hidden" name="fdate" value="<?php echo $this->fdate; ?>">

            <input type="submit" value="PDF" id="submit">

</form>
</div>
<?php } ?>
<?php  
if(($this->income) && ($this->expenditure)){  ?>

<?php 
if($totalincome>$totalexpe){
$result = $totalincome-$totalexpe;
	 echo "<font color='green'><h5>".$this->translate('Excess of income')." <font color='red'>".$result."</font>"; ?>/-<?php echo " ".$this->translate('over expenditure')."</h5></font>"; 
}
if($totalincome<$totalexpe){
$result = $totalexpe-$totalincome;
	 echo "<font color='green'><h5>".$this->translate('Excess of expenditure')." <font color='red'>".$result."</font>"; ?>/-<?php echo " ".$this->translate('over income')."</h5></font>"; 

} } ?>