<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Family Information Format</title>

<link rel="stylesheet" href="css/phone.css" type="text/css" media="screen" />
<link rel="stylesheet" href="css/phone.css" type="text/css" media="handheld" />

</head>

<body>
<div id="wrapper">
  <div class="formsets">
    <fieldset>
      <form id = "1" name="addform" action="<?php echo $this->baseUrl();?>/phone/index/addphone" method="POST">
      <legend>1. Family Details*</legend>
      <ul>
        <li>
          <label>Family ID
            <select name="select1_0" id="select1_0">
              <option>21983012983</option>
              <option>09128309128</option>
              <option>98091283091</option>
              <option>09128309128</option>
            </select>
          </label>
        </li>
        <li>
          <label>House No
            <input type="text" name="textfield1_0" id="textfield1_0">
          </label>
        </li>
        <li>
          <label>Street/Road/Lane
            <input type="text" name="textfield1_1" id="textfield1_1">
          </label>
        </li>
        <li>
          <label>Colony/Village
            <select name="select1_1" id="select1_1">
              <option>Abc Colony</option>
              <option>XYZ Village</option>
              <option>Some Post</option>
              <option>Some Colony</option>
            </select>
          </label>
        </li>
        <li>
          <label>Rev Village
            <select name="select1_2" id="select1_2">
              <option>ABC Village</option>
              <option>XYZ Village</option>
              <option>CER Village</option>
              <option>MER Village</option>
            </select>
          </label>
        </li>
        <li> <span class="frmlab">Family Type</span>
          <label>
            <input type="radio" name="RadioGroup1_0" value="radio1" id="RadioGroup1_0">
            Nuclear/Small Family </label>
          <label>
            <input type="radio" name="RadioGroup1_0" value="radio2" id="RadioGroup1_1">
            Joint Family </label>
          <br>
        </li>
        <li><span class="frmlab">Category</span>
          <label>
            <input type="radio" name="RadioGroup1_1" value="radio1" id="RadioGroup2_0">
            SC</label>
          <label>
            <input type="radio" name="RadioGroup1_1" value="radio2" id="RadioGroup2_1">
            ST</label>
          <label>
            <input type="radio" name="RadioGroup1_1" value="radio3" id="RadioGroup2_2">
            OBC</label>
          <label>
            <input type="radio" name="RadioGroup1_1" value="radio4" id="RadioGroup2_3">
            Others</label>
          <label>
            <input type="checkbox" name="checkbox1_0" id="checkbox1_0">
            Minority</label>
        </li>
        <li>
          <label>Caste
            <select name="select1_3" id="select1_3">
              <option>Cast 1</option>
              <option>Cast 2</option>
              <option>Cast 3</option>
              <option>Cast 4</option>
            </select>
          </label>
        </li>
        <li><span class="frmlab">Ration Card</span>
          <label>
            <input type="radio" name="RadioGroup1_3" value="radio1" id="RadioGroup1_3">
            APL</label>
          <label>
            <input type="radio" name="RadioGroup1_3" value="radio2" id="RadioGroup1_3">
            BPL</label>
          <label>
            <input type="radio" name="RadioGroup1_3" value="radio3" id="RadioGroup1_3">
            AAY</label>
          <label>
            <input type="radio" name="RadioGroup1_3" value="radio4" id="RadioGroup1_3">
            None</label>
        </li>
        <li><span class="frmlab">Health Insurance</span>
          <label>
            <input type="checkbox" name="RadioGroup1_4" value="radio1" id="RadioGroup1_4">
            None</label>
          <label>
            <input type="checkbox" name="RadioGroup1_4" value="radio2" id="RadioGroup1_4">
            Yeshaswini</label>
          <label>
            <input type="checkbox" name="RadioGroup1_4" value="radio3" id="RadioGroup1_4">
            Aryogyashree</label>
          <label>
            <input type="checkbox" name="RadioGroup1_4" value="radio4" id="RadioGroup1_4">
            RSBY</label>
          <label>
            <input type="checkbox" name="RadioGroup1_4" value="radio5" id="RadioGroup1_4">
            Private</label>
        </li>
        <li>
          <label>NREGS Job Card No
            <input type="text" name="textfield1_2" id="textfield1_2">
          </label>
        </li>
        <li><span class="frmlab">Major source of income</span>
          <label>
            <input type="radio" name="RadioGroup1_5" value="radio1" id="RadioGroup1_5">
            Daily wage</label>
          <label>
            <input type="radio" name="RadioGroup1_5" value="radio2" id="RadioGroup1_5">
            Cultivation</label>
          <label>
            <input type="radio" name="RadioGroup1_5" value="radio3" id="RadioGroup1_5">
            Salary</label>
          <label>
            <input type="radio" name="RadioGroup1_5" value="radio4" id="RadioGroup1_5">
            Others</label>
        </li>
        <li>
          <label>Primary breadwinner - Serial number of the family member
            <select name="select1_4" id="select1_4">
              <option>98091283091</option>
              <option>09128309128</option>
              <option>21983012983</option>
              <option>09128309128</option>
            </select>
          </label>
        </li>
      </ul>
    </fieldset>
  </div>
  <div class="formsets">
    <fieldset>
      <legend>2. Family Member Details*</legend>
      <ol>
        <li>
          <ul>
            <li>
              <label>Name of Member
                <select name="select2_1_1" id="select2_1_1">
                  <option>Member Name 1</option>
                  <option>Member Name 2</option>
                  <option>Member Name 3</option>
                  <option>Member Name 4</option>
                </select>
              </label>
            </li>
            <li>
              <label>Date of Birth
                <select name="select2_1_2" id="select2_1_2">
                  <option>01</option>
                  <option>02</option>
                  <option>03</option>
                  <option>04</option>
                </select>
                <select name="select2_1_3" id="select2_1_3">
                  <option>01</option>
                  <option>02</option>
                  <option>03</option>
                  <option>04</option>
                </select>
                <select name="select2_1_4" id="select2_1_4">
                  <option>1947</option>
                  <option>1948</option>
                  <option>1949</option>
                  <option>1950</option>
                </select>
              </label>
            </li>
            <li>
              <label>Age
                <select name="select2_1_5" id="select2_1_5">
                  <option>18</option>
                  <option>19</option>
                  <option>20</option>
                  <option>21</option>
                </select>
              </label>
            </li>
            <li>
              <label>Relation to HOF
                <select name="select2_1_6" id="select2_1_6">
                  <option>Husband</option>
                  <option>Wife</option>
                  <option>Child</option>
                  <option>Father</option>
                  <option>Mother</option>
                </select>
              </label>
            </li>
            <li>
              <label>Marital Status
                <select name="select2_1_7" id="select2_1_7">
                  <option>Married</option>
                  <option>Not Married</option>
                  <option>Child Marriage</option>
                </select>
              </label>
            </li>
            <li>
              <label>Entitlements
                <select name="select2_1_8" id="select2_1_8">
                  <option>Yes</option>
                  <option>No</option>
                  <option>May be</option>
                </select>
              </label>
            </li>
            <li>
              <label>Education Level
                <select name="select2_1_9" id="select2_1_9">
                  <option>Under Graduate</option>
                  <option>Over Graduate</option>
                  <option>Educated</option>
                  <option>Uneducated</option>
                </select>
              </label>
            </li>
            <li>
              <label>Employment Status
                <select name="select2_1_10" id="select2_1_10">
                  <option>Working</option>
                  <option>Retired</option>
                  <option>Unemployed</option>
                </select>
              </label>
            </li>
            <li>
              <label>Profession Status
                <select name="select2_1_11" id="select2_1_11">
                  <option>Working</option>
                  <option>Retired</option>
                  <option>Unemployed</option>
                </select>
              </label>
            </li>
            <li>
              <label>CBO Status
                <select name="select2_1_12" id="select2_1_12">
                  <option>Dont Know</option>
                  <option>Yes i do</option>
                  <option>No i dont</option>
                </select>
              </label>
            </li>
            <li>
              <label>Bank/PO
                <select name="select2_1_13" id="select2_1_13">
                  <option>Yes</option>
                  <option>No</option>
                  <option>May be</option>
                </select>
              </label>
            </li>
            <li>
              <label>Branch
                <select name="select2_1_14" id="select2_1_14">
                  <option>Urban</option>
                  <option>Rural</option>
                  <option>International</option>
                </select>
              </label>
            </li>
            <li>
              <label>Bank Account No
                <input type="text" name="textfield2_1_1" id="textfield2_1_1">
              </label>
            </li>
            <li>
              <label>Mobile Phone No
                <input type="text" name="textfield2_1_2" id="textfield2_1_2">
              </label>
            </li>
          </ul>
        </li>
      <input type="submit" name="Submit" value="Save">
      </form>
    </fieldset>
  </div>
</div>
</body>
</html>
