<fieldset>
	<legend>Enter/Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/affidavit/index" method="POST">
			<table class="fieldsets">
                            <TR>
                                <th><label class="mand">Group code :</label></TD>
                                <th><?php echo $this->form->membercode;?></TD>
                            </TR> 
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Submit;?>
                            </div>
                        </div>
	       </form>
</fieldset>
<?php  if((count($this->paginator) ==0) && ($this->search == true))  {
echo "<font color='RED'>Records Not Found Try Again...</font>";
}
if(count($this->paginator)!=0) { ?>
    <table id="hor-minimalist-b">
        <tr class="tdbrownheading">
            <th>Group code</th>
            <th>Group name</td>
        </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $individual): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl().'/affidavit/index/declaration/id/'.base64_encode($individual['groupid']).'/membercode/'.base64_encode($individual['groupcode']); ?>">
                        <?php echo $this->escape($individual['groupcode']); ?></a></td>
        <td><?php echo $this->escape($individual['group_name']);?></td>
            <?php endforeach; ?>
            <?php endif; ?>
        </tr>
        <tr>
            <td colspan="8" align="right">
                <div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                '/partials/my_pagination_control.phtml'); ?>
                </div>
            </td>
        </tr>
    </table>
<?php } 
