    <fieldset>
        <legend>Search account</legend>
        <form action="<?php echo $this->baseUrl();?>/loanledger/index/loandetails" method="POST">
            <table class="fieldsets" style="margin-left:20px;">
                <tr>
                    <td><br><label class="mand">Account number :</label></td>
                    <td><?php echo $this->form->accNum;?></td>
                </tr>
            </table>
            <div class="btnhouse">
                <div class="ltbtns" style="margin-left:20px;">
                    <?php echo $this->form->Search;?>
                </div>
            </div>
        </form>
    </fieldset>

