


<?php if (count($this->details)) { ?>
 <div style="float:left;width:350px"> 
    <?php foreach($this->details as $details) { ?>
        <table id="hor-minimalist-b" border="2">
            <TR>
                <TH colspan="2">Member details</TH>
                <TH colspan="2">Loan Details</TH>
            </TR>
            <TR>
                <td>Name </td>
                <TD><?php echo $details->name ?></TD>
                <td>Loan name</b></td>
                <td><?php echo $details->loanname ?></TD>
            </TR>
            <TR>
                <td>Branch</td>
                <TD><?php echo $details->officename ?></TD>
                <td>Loan amount R$</b></td>
                <td><font color="green"><?php echo $details->amount ?></font></TD>
            </TR>
            <TR>
                <td>Code</td>
                <TD><?php echo $details->code ?></TD>
                <td>Interest rate %</td>
                <TD><?php echo $details->interest ?></TD>
            </TR>
            <TR>
                <td> Account code</td>
                <td><?php echo $details->number ?></TD>
				<td>Installments</td>
                <TD><?php echo $details->installments ?></TD>
            </TR>
			<TR>
				<TD></TD><TD></TD>
                <td>Sanctioned date</b></td>
                <td><?php echo $details->sanctioned ?></TD>
			</TR>
        </table> 
    <?php } ?>
    <br/>
</div>

<?php $convertdate = new App_Model_dateConvertor(); ?>
<table id="hor-minimalist-b">
	<tr><th colspan="6">Transaction Details</th></tr>
    <tr>
        <th>V No.</td>
        <th>Transaction date</td>
        <th>Creidt</td>
        <th>Debit</td>
        <th>Payment mode</td>
        <th>Transacted by</td>  
    </tr>
	<?php $total="0"; ?>

    <?php foreach($this->tran as $transaction) : ?>
       <td><?php echo $transaction->id; ?></td>
       <td><?php echo $transaction->date; ?></td>
       <?php if ($transaction->cr) {?>
       <td><?php echo $transaction->cr; ?></td>
       <?php } else { ?>
       <td>----</td>
       <?php } ?>
       <?php if ($transaction->dt) { ?> 
       <td><?php echo $transaction->dt; ?></td>
       <?php } else { ?>
       <td>----</td>
       <?php } ?>

       <td><?php echo $transaction->mode; ?></td>
       <td><?php echo $transaction->name; ?></td>
    </tr>
	   <?php endforeach; ?>

       <?php  $total=$transaction->dt - $transaction->cr; ?>
<tr><TD></TD><TD align="right"><b>Total</b></TD><TD align="right"><b><?php echo $total; ?></b></TD><TD></TD></tr>

</table>
<form action="<?php echo $this->baseUrl();?>/loanledger/index/pdfdisplay" <? echo $this->view->result;?> method="POST" onClick="window.open('<?php echo $this->baseUrl();?>/loanledger/index/reportdisplay/file/loanledger.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">

           <BR> <input type="submit" value="<?php echo $this->translate('PDF'); ?>" id="submit">
                <input type="hidden" name="accNum" value="<?php echo $this->accNum; ?>"/>

</form>
    <?php } else { ?>
    <font color="red"><b>Invalid Number</b></font>
<?php } ?>