<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script src="<?php echo $this->baseUrl();?>/js/jquery-latest.js"></script>
<script language="javascript">
$(document).ready(function(){
        $('.none').click(function(){ // All none categories
        ids = $(this).attr('id').split('-'); // split the value to get id
        if($("#none-"+ids[1]).is(':checked')) {
            $('.alldisease'+ids[1]).attr('disabled',true);
            $('.alldisease'+ids[1]).attr('checked',false);
        } else {
            $('.alldisease'+ids[1]).attr('disabled',false);
        }
        });


        $('.nonehabit').click(function(){ // All none categories
            ids = $(this).attr('id').split('-'); // split the value to get id
            if($("#nonehabit-"+ids[1]).is(':checked')) {
                $('.habit-'+ids[1]).attr('disabled',true);
                $('.habit-'+ids[1]).attr('checked',false);
            } else {
                $('.habit-'+ids[1]).attr('disabled',false);
            }
        }); 

        $('.nonechal').click(function(){ // All none categories
            ids = $(this).attr('id').split('-'); // split the value to get id
            if($("#nonechal-"+ids[1]).is(':checked')) {
                $('.challenge-'+ids[1]).attr('disabled',true);
                $('.challenge-'+ids[1]).attr('checked',false);
            } else {
                $('.challenge-'+ids[1]).attr('disabled',false);
            }
        });


        $(":checkbox").click(function(){

        ids = $(this).attr('id').split('-');
            if(ids[0] == 'habit'){
                habitfields = $("input[name='habit-"+ ids[1] +"[]']").serializeArray(); 
                len = habitfields.length;
                if(len != 0){
                    $("#nonehabit-"+ids[1]).attr('disabled',true);
                }
                else {
                    $("#nonehabit-"+ids[1]).attr('disabled',false);
                } 
           }

            if(ids[0] == 'challenge'){
                chlgfields = $("input[name='challenge-"+ ids[1] +"[]']").serializeArray(); 
                len = chlgfields.length;
                if(len != 0){
                    $("#nonechal-"+ids[1]).attr('disabled',true);
                }
                else {
                    $("#nonechal-"+ids[1]).attr('disabled',false);
                } 
           }
            if(ids[0] != 'none'){
                noneid = ids[0].substring(13);
            }else {
                noneid = ids[1];
            }

            healthfields = $("input[name='healthdisease"+ noneid +"[]']").serializeArray(); 
            len = healthfields.length;
            if(len != 0){
                $("#none-"+noneid).attr('disabled',true);
            }
            else {
                $("#none-"+noneid).attr('disabled',false);
            }
        });
    });
</script>
<!--<script language="javascript">
$(document).ready(function(){
        $('.none').click(function(){
        ids = $(this).attr('id').split('_');
        if($("#none_"+ids[1]).is(':checked')) {
            
            $('.alldisease'+ids[1]).attr('disabled',true);
            $('.alldisease'+ids[1]).attr('checked',false);
        } else {
            $('.alldisease'+ids[1]).attr('disabled',false);
        }
        });
});
</script>-->
 <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("ಕಟುಂಬದ ವಿವರ"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    foreach($this->membernames as $family_view){ ?>

<!--<tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ಕೋಡ :"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>-->
    <tr>
        <td ><?php echo $this->translate("ಮನೆ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("ರೇಷನ್ ಕಾರ್ಡ್:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಬೀದಿ /ರಸ್ತೆ:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("ಆರೋಗ್ಯ ವಿಮೆ:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಕಂದಾಯ ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("ಉದ್ಯೋಗಖಾತ್ರಿ ಜಾಬ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate(" ಗ್ರಾಮ:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("ಆದಾಯದ ಪ್ರಮುಖ ಮೂಲ:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("ಕುಟುಂಬದ ವಿಧ :"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("ದೂರವಾಣಿ:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("ಜಾತಿ:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("ಮೊಬೈಲ್ :"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>
   <?php } ?>
</table> 
<br/>
<form action="<?php echo $this->baseUrl();?>/health/index/edithealth/id/<?php echo $this->memberid; ?>" method="POST">
<div style="width:750px; height=500px; overflow-x:auto; overflow-y:auto; bottom-padding:10px">
<?php 
$dbmodel=new Health_Model_health();


$hlen = count($this->habitdetails);
$clen = count($this->challengedetails);
$actlen = $hlen > $clen ? $hlen : $clen;
$actlen = $actlen*2+1;
$names = array();
$nameid = array();
foreach($this->membername as $name){
 $nameid[] = $name['memberid'];
 $names[] = $name['membername'];
}
 ?>

    <table id="hor-minimalist-b" border="1" width="100%">
        <tr>
        <th  align="left" width="5%"> ಕ್ರ.ಸಂ.</th><th width="20%">ಸದಸ್ಯರ ಹೆಸರು</th>
        <th colspan="<?php echo $actlen; ?>" align="center" width="75%"> ವಿವರಗಳು</th>
        </tr>
    </table>
<?php 
$adm = new App_Model_Adm();
for($i=0;$i<$this->membercount;$i++) { 
$selectedHabits = array();
$selectedChallenges = array();
?>
<br>
    <table id="hor-minimalist-b" border="1" width="100%">
        <tr>
        <td width="5%"><?php echo $nameid[$i];?></td><td width="20%"><?php  echo "<b>$names[$i] "."'s<b>";?></td><td width="75%"></td>

        </tr></table><table id="hor-minimalist-b" border="1" width="100%">
        <tr>
        <td width="5%"></td>
        <TD width="20%">ಕಳೆದ 6 ತಿಂಗಳಲ್ಲಿ ಪಡೆದ ಔಷದೋಪಚಾರ( ಸದಾಕಾಲ ಇರುವ ಖಾಯಿಲೆಗಳು)</TD>

<td colspan="2" width="75%">


<input type="checkbox" name="none" class="none"  id="none-<?php echo $nameid[$i];?>" />None <br>


        <?php 

            $b='healthdisease'.$nameid[$i];
            echo $this->form->$b;
        ?>
        </TD>

        </tr>

    </table>
<table id="hor-minimalist-b" border="1" width="100%">
<tr><td width="5%"></td>
    <td width="20%"><b>ದುರಭ್ಯಾಸ</b>
    </td>
    <?php $c=0; foreach($this->habitdetails as $habits){ $c++; ?>
    <?php if($c == 1) { ?>
        <td colspan="2">
                <input type="checkbox" name="nonehabit" class="nonehabit" id="nonehabit-<?php echo $nameid[$i];?>" />None <br>
        </td>
    <?php } 

    $selectedHab = $dbmodel->getselectedhabit($nameid[$i]); // get selected health id's

    foreach ($selectedHab as $selectedHabit){
        $selectedHabits[] = $selectedHabit['habit_id']; // set all avail health list 
    }

 if(in_array($habits['id'],$selectedHabits)) { ?>
    <td>
        <input type="checkbox" checked="true" name="habit-<?php echo $nameid[$i];?>[]" id="habit-<?php echo $nameid[$i];?>" class="habit-<?php echo $nameid[$i];?>" value="<?php echo $nameid[$i].'_'.$habits['id'];?>">
        <?php echo $habits['name_regional']; ?> 
    </td>
<?php  }  else { ?>
    <td>
        <input type="checkbox" name="habit-<?php echo $nameid[$i];?>[]" id="habit-<?php echo $nameid[$i];?>" class="habit-<?php echo $nameid[$i];?>" value="<?php echo $nameid[$i].'_'.$habits['id'];?>">
        <?php echo $habits['name_regional']; ?> 
    </td>
<?php } 
}

?>
</tr>
<tr><td width="5%"></td>
    <td width="20%"><b> ಅಂಗವಿಕಲತೆ ಇದ್ದರೆ ಇತ್ಯಾದಿ</b>
    </td>
    <?php $p = 0; foreach($this->challengedetails as $challenge){ $p++; ?>
    <?php if($p == 1) { ?>
    <td colspan="2">
            <input type="checkbox" name="nonechal" class="nonechal" id="nonechal-<?php echo $nameid[$i];?>" />None <br>
    </td>
    <?php } 
    $selectedPhysical = $dbmodel->getphysicalchallenge($nameid[$i]); // get selected physical challenge id's
    foreach ($selectedPhysical as $selectedPhy){
        $selectedChallenges[] = $selectedPhy['phychallenge_id']; // set all avail physical challenge list 
    }
 if(in_array($challenge['id'],$selectedChallenges)) { ?>
    <td>
        <input type="checkbox" checked="true" name="challenge-<?php echo $nameid[$i];?>[]" id="challenge-<?php echo $nameid[$i];?>" class="challenge-<?php echo $nameid[$i];?>" value="<?php echo $nameid[$i].'_'.$challenge['id'];?>">
        <?php  echo $challenge['name_regional']; ?>
    </td>
    <?php }  
        else { ?>
     <td>
        <input type="checkbox" name="challenge-<?php echo $nameid[$i];?>[]" id="challenge-<?php echo $nameid[$i];?>" class="challenge-<?php echo $nameid[$i];?>" value="<?php echo $nameid[$i].'_'.$challenge['id'];?>">
        <?php  echo $challenge['name_regional']; ?>
    </td>
   <?php } 
    }  
?>
</tr>
</table>
<?php
}

?>
</div>
<table>
<input type="hidden" name="subId" value="<?php echo $this->submoduleid; ?>">
<input type="hidden" name="memId" value="<?php echo $this->memberid; ?>">

<tr><td><input type="submit" id="submit" name="update" value="<?php echo $this->translate("Update"); ?>"></td>
<td><a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a></td>
</tr>
</table>

</form>
