<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<!--search for individual member !-->
<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}

$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});

</script>

<?php if (!$this->result) { ?>
<fieldset>
	<legend><?php echo $this->translate("Search Family"); ?></legend>
		<form action="<?php echo $this->baseUrl();?>/prakoota/index" method="POST">
			<table width="100%">
                        <tr align="center"><td><?php echo $this->translate('Hierarchy :'); ?></td>
                            <td id="show" align="left"><?php echo $this->form->hierarchy;?></td></tr>
						<tr align="center"><td><br><?php echo $this->translate('Branch :'); ?></td>
                            <td align="left"><br><div id="statediv"><?php echo $this->form->branch;?></div></td></tr>
					<tr align="center"><td><br><input type="submit" name="Search" value="Search"></td>
					</tr>
           </table>


	 </form>
</fieldset>
<?php } ?>

<?php if ($this->result) { ?>
	<table id="hor-minimalist-b" border="2">
		<?php  foreach($this->result as $pradetails) {?>
		<th width="5%">S.No</th><th>Service Sector <font color="green"><b><?php echo $pradetails['village'];?></b></th><th>No of Members</th>
		<tr><TD align="center">1</TD><TD>Widow Pension</TD><TD><?php  echo $pradetails['wpension'];?></TD></tr>
		<tr><TD align="center">2</TD><TD>Housing Construction/Repair</TD><TD><?php  echo $pradetails['hcrepair'];?></TD></tr>
		<tr><TD align="center">3</TD><TD>Ration Card</TD><TD><?php  echo $pradetails['rcard'];?></TD></tr>
		<tr><TD align="center">4</TD><TD>Old Age Pension</TD><TD><?php  echo $pradetails['oapension'];?></TD></tr>
		<tr><TD align="center">5</TD><TD>Disability Pension</TD><TD><?php  echo $pradetails['dpension'];?></TD></tr>
		<tr><TD align="center">6</TD><TD>NREGS Job Card</TD><TD><?php  echo $pradetails['nregs'];?></TD></tr>
		<tr><TD align="center">7</TD><TD>Skills Training</TD><TD><?php  echo $pradetails['skills'];?></TD></tr>
		<tr><TD align="center">8</TD><TD>J2G</TD><TD><?php  echo $pradetails['j2g'];?></TD></tr>
		<tr><TD align="center">9</TD><TD>Health Insurance</TD><TD><?php  echo $pradetails['Hinsurance'];?></TD></tr>
		<tr><TD align="center">10</TD><TD>Sanitation</TD><TD><?php  echo $pradetails['Sanitation'];?></TD></tr>
		<?php } }?>
	</table>
