<!-- add individual member action !-->
<form action="<?php echo $this->baseUrl();?>/familydefault/index/addfamily" method="POST" id="validation" name="addForm">
<span id=details></span>
<fieldset>
            <table class="fieldsets" id="hor-minimalist-b" > 
	<th colspan="2">ಕಟುಂಬದ ವಿವರ</th>
        <!--<tr>
            <td><label class="mand">Family ID :</td>
            <td><?php //echo $this->form->familyid; ?></td>
        </tr>-->
        <tr>
            <td> &nbsp;&nbsp;<label class="mand"> ಸುಙೀವನ ನಂ: :</td>
            <td><?php echo $this->form->sujeevana; ?></td>
        </tr>
        <tr>
            <td> &nbsp;&nbsp; ಮನೆ ಸಂಖ್ಯೆ  :</td>
            <td><?php echo $this->form->houseno; ?></td>
        </tr>
        <tr> 
            <td> &nbsp;&nbsp; ಬೀದಿ /ರಸ್ತೆ :</td>
            <td><?php echo $this->form->street; ?></td>
        </tr>

        <tr>
            <td><label class="mand">ಕೂಟ:</td>
            <td><?php echo $this->form->koota; ?></td>
        </tr>

        <tr>
            <td><label class="mand">ಕಂದಾಯ ಗ್ರಾಮ:</td>
            <td><div id="revdiv"><?php echo $this->form->rev_village; ?></div></td>
        </tr>

        <tr>
            <td> &nbsp;&nbsp; ತಾಲ್ಲೂಕು:</td>
            <td><div id="talukdiv"></div></td>
        </tr>

        <tr>
            <td> &nbsp;&nbsp; ಪಿನ್:</td>
            <td><div id="pincodediv"></div></td>
        </tr>
        <tr>
            <td><label class="mand">ಗ್ರಾಮ :</td>
            <td><div id="village"><?php echo $this->form->village; ?></div></td>
        </tr>
        <tr>
            <td><label class="mand">ಕುಟುಂಬದ ವಿಧ  :</td>
            <td><?php echo $this->form->familytype; ?></td>
        </tr>
        <tr>
            <td><label class="mand">ಜಾತಿ :</td>
            <td><?php echo $this->form->caste; ?></td>
        </tr>
		 <tr>
            <td>&nbsp;&nbsp; ಅಲ್ಪಸಂಖ್ಯಾತರು :</td>
            <td><?php echo $this->form->minority; ?></td>
        </tr>
        <!--<tr>
            <td><label class="mand">Caste</td>
            <td class="subcaste"><?php echo $this->form->subcaste; ?></td>
        </tr>-->
        <tr>
            <td><label class="mand"> ರೇಷನ್ ಕಾರ್ಡ್ :</td>
            <td><?php echo $this->form->ration; ?></td>
        </tr>
      <tr>
            <td style="vertical-align: top;"><label class="mand">ಆರೋಗ್ಯ ವಿಮೆ:</td>
            <td><?php echo $this->form->health; ?>
                <input type="hidden" name="count" id="count" value="<?php echo $this->countvalue; ?>">
            </td>
        </tr>
        <tr>
            <td>&nbsp;&nbsp; ಉದ್ಯೋಗಖಾತ್ರಿ ಜಾಬ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ :</td>
            <td><?php echo $this->form->jobno; ?></td>
        </tr>
        <tr>
            <td><label class="mand">ಆದಾಯದ ಪ್ರಮುಖ ಮೂಲ :</td>
            <td><?php echo $this->form->income; ?></td>
        </tr>
        <tr>
            <td>&nbsp;&nbsp; ದೂರವಾಣಿ :</td>
            <td><?php echo $this->form->phone; ?></td>
        </tr>
        <tr>
            <td><label class="mand"> ಮೊಬೈಲ್  :</td>
            <td><?php echo $this->form->mobile; ?></td>
        </tr>
    </table>
    <div class="btnhouse">
        <div class="ltbtns">
            <input type="submit" name="Submit" id="Submit" value="<?php echo $this->translate("Submit"); ?>">
        </div>
        <div class="rtbtns">
            <a href="<?php echo $this->baseUrl();?>/family"><input type="submit" name="back" id="back" value="<?php echo $this->translate("Back"); ?>"></a>
        </div>
    </div>

</fieldset>
</form>


<?php if ($this->error_msg) { ?>

           <table><TR><TD><?php echo "<font color='red' size='2'>".$this->error_msg."</font>";?></TD></TR></table>
           <!-- <?php// $this->error_msg = '' ?> -->
<?php } ?>
