<!-- add individual member action !-->
<form action="<?php echo $this->baseUrl();?>/familydefault/index/addfamily" method="POST" id="validation" name="addForm">
<span id=details></span>
<fieldset>
            <table class="fieldsets" id="hor-minimalist-b" > 
	<th colspan="2">Family Details</th>
        <!--<tr>
            <td><label class="mand">Family ID :</td>
            <td><?php //echo $this->form->familyid; ?></td>
        </tr>-->
        <tr>
            <td> &nbsp;&nbsp;<label class="mand"> Sujeevana No :</td>
            <td><?php echo $this->form->sujeevana; ?></td>
        </tr>
        <tr>
            <td> &nbsp;&nbsp; House Number:</td>
            <td><?php echo $this->form->houseno; ?></td>
        </tr>
        <tr> 
            <td> &nbsp;&nbsp;Street/Lane:</td>
            <td><?php echo $this->form->street; ?></td>
        </tr>

        <tr>
            <td><label class="mand">Area:</td>
            <td><?php echo $this->form->koota; ?></td>
        </tr>

        <tr>
            <td><label class="mand">Village:</td>
            <td><div id="revdiv"><?php echo $this->form->rev_village; ?></div></td>
        </tr>

        <tr>
            <td> &nbsp;&nbsp; Taluk:</td>
            <td><div id="talukdiv"></div></td>
        </tr>

        <tr>
            <td> &nbsp;&nbsp; Pin Code:</td>
            <td><div id="pincodediv"></div></td>
        </tr>
        <tr>
            <td><label class="mand">Habitation: [ Settings ]</td>
            <td><div id="village"><?php echo $this->form->village; ?></div></td>
        </tr>
        <tr>
            <td><label class="mand">Family Type:</td>
            <td><?php echo $this->form->familytype; ?></td>
        </tr>
        <tr>
            <td><label class="mand">Caste :</td>
            <td><?php echo $this->form->caste; ?></td>
        </tr>
		 <tr>
            <td>&nbsp;&nbsp; Minority :</td>
            <td><?php echo $this->form->minority; ?></td>
        </tr>
        <!--<tr>
            <td><label class="mand">Caste</td>
            <td class="subcaste"><?php echo $this->form->subcaste; ?></td>
        </tr>-->
        <tr>
            <td><label class="mand"> Ration:</td>
            <td><?php echo $this->form->ration; ?></td>
        </tr>
      <tr>
            <td style="vertical-align: top;"><label class="mand">Health :</td>
            <td><?php echo $this->form->health; ?>
                <input type="hidden" name="count" id="count" value="<?php echo $this->countvalue; ?>">
            </td>
        </tr>
        <tr>
            <td>&nbsp;&nbsp;Job Number :</td>
            <td><?php echo $this->form->jobno; ?></td>
        </tr>
        <tr>
            <td><label class="mand">Income Details :</td>
            <td><?php echo $this->form->income; ?></td>
        </tr>
        <tr>
            <td>&nbsp;&nbsp; Phone :</td>
            <td><?php echo $this->form->phone; ?></td>
        </tr>
        <tr>
            <td><label class="mand"> Mobile  :</td>
            <td><?php echo $this->form->mobile; ?></td>
        </tr>
    </table>
    <div class="btnhouse">
        <div class="ltbtns">
            <input type="submit" name="Submit" id="Submit" value="<?php echo $this->translate("Submit"); ?>">
        </div>
        <div class="rtbtns">
            <a href="<?php echo $this->baseUrl();?>/family"><input type="submit" name="back" id="back" value="<?php echo $this->translate("Back"); ?>"></a>
        </div>
    </div>

</fieldset>
</form>


<?php if ($this->error_msg) { ?>

           <table><TR><TD><?php echo "<font color='red' size='2'>".$this->error_msg."</font>";?></TD></TR></table>
           <!-- <?php// $this->error_msg = '' ?> -->
<?php } ?>
