<!--delete individual member action !-->
<form action="<?php echo $this->baseUrl();?>/familydefault/index/deletemember/id/<?php echo $this->memberid; ?>/modId/<?php echo $this->mod_id; ?>/subId/<?php echo $this->sub_id; ?>" method="POST">
<div class="register">
	<div class="profile_tab"> 

		<table id="hor-minimalist-b">
                           <tr><th>Member Information</th><th></th><th></th><th></th></tr>

			<tr><td><font color="red">Do you want to delete</font><?php echo $this->delete; ?></td><td></td><td></td><td></td></tr> 
			<tr><td></td><td><a href="<?php echo $this->baseUrl();?>/familycommonview/index/commonview/id/<?php echo $this->memberid ?>"><input type="button" name="no" value="<?php echo $this->translate("Cancel"); ?>"></a></td></td><td></td><td></tr>
			
		</table>
</div>
</div>
</form>
