<!--edit indiviudal member action !-->
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/city.js"></script>

<form action="<?php echo $this->baseUrl();?>/individualdefault/index/editmembername/id/<?php echo $this->memberid; ?>" method="POST">
<fieldset>
<legend>Member details</legend>
<div class="btnhouse">
<div class="rtbtns">
    <td><a href="<?php echo $this->baseUrl();?>/individualdefault/index/deletemember/id/<?php echo $this->memberid; ?>/sub_id/<?php echo $this->sub_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
	</div>
</div>
    <table class="fieldsets">
    <?php echo $this->form; ?>
    </table>
    <div class="btnhouse">
    <div class="ltbtns">
        <input type="submit" name="Update" id="Update" value="<?php echo $this->translate("Update"); ?>">
        </div>
    <div class="rtbtns">
        <a href="<?php echo $this->baseUrl();?>/individualmcommonview/index/commonview/id/<?php echo $this->memberid; ?>"><input type="submit" name="back" id="back" value="<?php echo $this->translate("Back"); ?>"></a>
    </div>
</fieldset>
</form>
