<script src="<?php echo $this->baseUrl();?>/js/jquery-latest.js"></script>
<script language="javascript">
 function getBranch(bankid) { 
            targeturl='<?php echo $this->baseUrl();?>/groupmdefault/index/branch?bankid='+bankid; 
            $.ajax({ url: targeturl, success: function(data){ $('#branch').html(data) }});
       }

</script>
<?php
function checkConnection()
{
    //Initiates a socket connection to www.itechroom.com at port 80
    $conn = @fsockopen("www.itechroom.com", 80, $errno, $errstr, 30);
    if ($conn)
    {
        $status = "OK";
        fclose($conn);
    }
    else
    {
        $status = "NO";
//         $status .= "$errstr ($errno)";
    }
    return $status;
}

$status = checkConnection();

if($status == "OK"){
?>
<head> 
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" /> 
  <script src="http://maps.google.com/maps/api/js?sensor=false" 
          type="text/javascript">
   </script>
</head>
<?php } ?>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/group/membershipgroupm.js"></script>
<script>
</script>
<div id = "searchDiv">
    <fieldset>
        <legend>Group details</legend>
        <form action="<?php echo $this->baseUrl();?>/groupmdefault/index/groupaccount" method="POST" onsubmit="return valid()" id="addgroup">
            <table class="fieldsets"> 
                
                <tr>
                    <TD><label class="mand">Group type</label></td>
                    <td colspan="3">
                    <?php if($this->gtype) { $gtype = $this->gtype; } ?>
                    <input type="radio" name="grouptype" id="grouptype" class ="required"  <?php if($gtype == 2) { ?> checked <?php } ?> value=2>SHG
                    <input type="radio" name="grouptype" id="grouptype" class ="required" <?php if($gtype == 3) { ?> checked <?php } ?> value=3>JLG
                    </TD>
               </TR>
                <TR>
                    <TD><label for="fld1" class="mand">Village name</td>
                    <TD><?php echo $this->form->office;?></TD>
                    <TD><?php echo $this->form->bank;?></TD>
                    <TD><label class="mand">Bank branch</label></TD>
                    <TD><div id="branch"><?php echo $this->form->branch;?></div></TD>
                    <TD><?php echo $this->form->groupname;?></TD>
                </TR> 
                 <TR>
                    <TD><?php echo $this->form->savingamt;?></td>
                    <TD><?php echo $this->form->penaltylate;?></TD>
                    <TD><?php echo $this->form->penaltyabsence;?></TD>
                </TR>  

                <TR>
                    <TD><?php echo $this->form->place;?></td>
                    <TD><?php echo $this->form->times;?></TD>
                    <TD><?php echo $this->form->day;?></TD>
                </TR>
                <TR>
                    <TD><?php echo $this->form->interest;?></TD>
                    <TD colspan="2"><?php echo $this->form->Created_Date;?></TD>
                </tr>
            </table><br/>
         <div id='error'>&nbsp;</div>

            <table class="fieldsets" width="100%">
        <div style="width:600px; height=500px; overflow-x:auto; overflow-y:auto; bottom-padding:10px">
            <TR  align="center" id="membersdiv">
            </TR>
        </div>
</table>
<br>
<?php 
if($status == "OK"){
?>
        <div id="map" style="width: 250px; height:200px; overflow-x:auto; overflow-y:auto; bottom-padding:10px">
        </div>
            <input type="text" id="latitude" name = "latitude" size="15"/>
            <input type="text" id="longitude" name = "longitude" size="15"/>
 
            
              <script type="text/javascript">
                var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 5,
                center: new google.maps.LatLng(15.085866972731804,76.94207031250001),
                mapTypeId: google.maps.MapTypeId.ROADMAP
                });
                google.maps.event.addListener(map, 'click', function(event) {
                if (event.latLng) {
                    document.getElementById('latitude').value = event.latLng.lat();
                    document.getElementById('longitude').value = event.latLng.lng();
                }
                });
            </script>
<?php } else {

echo "<font color ='red'>Internet connection is not available due to that google map not displayed...</font>";

}?>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Submit;?>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/groupm/index"><?php echo $this->form->Back;?></a>
                </div>
            </div>
        </form>
    </fieldset>
</div>
<?php if($this->error) { echo "<font color = 'red'><b>".$this->error."</b></font>"; } ?>


