<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id = "searchDiv">
    <fieldset><legend>Group Delete</legend>
        <form action="<?php echo $this->baseUrl();?>/groupmdefault/index/deletegroup/id/<?php echo $this->groupid; ?>" method="POST">
            <table >
                <TR>
                    <TD><?php echo $this->form->remarks;?></TD>
	            </TR>
				<tr><TD><font color="red">Are you sure you want to delete ?</font></TD></tr>
                <tr>
                    <td class = "firsttd"><input type = "Submit" name = "Submit" id="Submit" value = "Delete"/></td>
                    <td class = "secondtd"><a href="<?php echo $this->baseUrl();?>/groupcommonview/index/commonview/id/<?echo $this->groupid; ?>"><input type = "Button" name = "Back" id="Back" value = "cancel"/></a></td>
                </tr>
        </table>
        </form>
    </fieldset>
</div>


