<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<fieldset>
    <legend> search </legend>

            <table >
                <form action="<?php echo $this->baseUrl();?>/savingsledger/index" method="POST">
                    <TR>
                            <TD align="center"><br>Date from :</TD>
                            <TD ><?php echo $this->form->datefrom;?></TD>
                            <TD ><br>Date to :</TD>
                            <TD ><?php echo $this->form->dateto;?></TD>
                    </TR>
                    <TR>
                            <TD align="center"><br>Account number :</TD>
                            <TD ><?php echo $this->form->acc;?></TD>
                            <TD ></TD>

                    </TR>
                        <tr><TD align="center"><?php echo $this->form->Search;?></TD></tr>
                </form>
            </table>

</fieldset>


