<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<script type="text/javascript">
function getlevels(hierarchy,path) {
	if(hierarchy) {
		targeturl=path+"/cashscroll/index/sublevel?hierarchy="+hierarchy;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
function getgroups(branch,path) {
	if(branch) {
		targeturl=path+"/cashscroll/index/group?branch="+branch;
		$.ajax({ url: targeturl, success: function(data){ $("#groupdiv").html(data) }});
	}
}
$(document).ready(function() {
$('#show').change(function(){
var va = $('#hierarchy').val();
if(va != 4){
$("#hide").hide();
}else {
$("#hide").show();

}
});
});

</script>
<fieldset>
    <legend> search </legend>

            <table width="100%" class="fieldsets">
                <form action="<?php echo $this->baseUrl();?>/savingsledger/index" method="POST">

  					<tr>	<TD><label class="mand"><?php echo $this->translate('Hierarchy'); ?></label></TD>
                            <TD id="show"><?php echo $this->form->hierarchy;?></TD>
                            <TD ><label class="mand"><?php echo $this->translate('Date from'); ?></label></TD>
                            <TD ><?php echo $this->form->datefrom;?></TD>
  					</tr>
					<tr>    <TD><label class="mand"><?php echo $this->translate('Branch'); ?></label></td>
                            <td><div id="statediv"><?php echo $this->form->branch;?></div></td>
                            <TD ><label class="mand"><?php echo $this->translate('Date to'); ?></label></TD>
                            <TD ><?php echo $this->form->dateto;?></TD>
					</tr>
					<tr id="hide"><TD><label class="mand"><?php echo $this->translate('Group'); ?></label></td>
                            <td><div id="groupdiv"><?php echo $this->form->group;?></td>
					</tr>
					<tr>   <TD><label class="mand"><?php echo $this->translate('Account Number'); ?></label></TD>
                            <TD><?php echo $this->form->acc;?></TD></tr>


                        <tr><TD><?php echo $this->form->Search;?></TD></tr>
                </form>
            </table>

</fieldset>


