<html>
  <head>
    <script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-1.3.2.js"></script>
    <script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery.validate.js"></script>
<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jqueryAddmethod.js"></script>

<script type='text/javascript'>
function calculateacre(bal) {
            var sum=0;
	    //iterate through each textboxes and add the values
	    $(".acre").each(function() {
            if(!isNaN(this.value) && (this.value.length!=0)) {
	    sum += parseFloat(this.value); //alert(sum);
           }
	   });
	   $(".totalacre").val(Number(sum)); 
            caltotalacre();
}

function calculateguntas(thi) {
            var sum=0;
	    //iterate through each textboxes and add the values
	    $(".gunta").each(function() {
            if(!isNaN(this.value) && (this.value.length!=0)) {
	    sum += parseFloat(this.value); //alert(sum);
           }
	   });
	   $(".totalgunta").val(sum); 
            calguntas();
}
function calguntas() {
            var sum=0;
	    //iterate through each textboxes and add the values
	    var res=$(".totalgunta").val();
            var rem=res%40; 
            var bal=parseInt(res/40); 
	   $(".totalgunta").val(rem);
            caltotalacre(bal); //alert("Hi"+bal);
}
function caltotalacre(bal) {
            if(bal) { 
	    var res=Number($(".totalacre").val())+Number(bal);  //alert(bal);
                } else { 
	    var res=Number($(".totalacre").val()); //alert("Hi"+res);
                }
	    //iterate through each textboxes and add the values

	   $(".caltotalacre").val(res);
}


$(document).ready(
  function() {
 $('#valueForm').validate();
        $(".numeric1").keyup(
    function(){
        currentObject=$(this).attr('name')
       if (currentObject=='marketed[]'){
             Qobj=$(this).parent().next();
       
            tobj=$(this).parent().next().next();}
       else
          {
                 Qobj=$(this).parent().prev();
       
                tobj=$(this).parent().next();
        }   
       
        Qty=$('input',Qobj).val();
       tot=$(this).val()*Qty;
        $('input',tobj).val(tot)

     });
    $('input#tmpAddRow').click(
      function() {
       tableobj=$(this).parent();
        selectedval=[];
     rowindex=$('tr',tableobj).length;
        var newRow = $('tr#tmp').clone(true).removeAttr('id');
     selectobj=newRow.find("select");
                //selectobj="Select";
                $.each(selectobj,function() {
                  
                  nameselect=$(this).attr('name');
                    $(this).val("");

                
                 });
        newRow.find("input:text").val("");
         acreObj=newRow.find("input.EitherOr");
                 acreObj.attr('id','acre'+rowindex);
        newRow.find("input:checkbox").removeAttr('checked');
        newRow.appendTo('.crop tbody');
        $('tr#tmp').closest('table').find('input:text.date').each(function() {
           $(this).removeClass('hasDatepick').datepick({dateFormat: 'dd/mm/yyyy',maxDate: '+0D'});
        });
        
        
//         arrangeCheckboxNames();
            arrangehiddenid();
      }
    );

    $('tr input[type=text]').focus(
      function() {
        $(this).addClass('myFocused');
      }
    ).blur(
      function() {
        $(this).removeClass('myFocused');
      }
    );

    $('.delete-icon').click(function() {
    $(this).closest('tr').not('#tmp').remove();
       // arrangeCheckboxNames();
    });
$(".date").datepick({dateFormat: 'dd/mm/yyyy',maxDate: '+0D'});  
  }
);

var arrangehiddenid = function() {
var length = 1;
length++;

$('tr#tmp').nextAll('tr').each( function() {
$(this).find('input.acre').attr( 'id', 'acre'+length );
$(this).find('input.gunta').attr( 'id', 'gunta'+length );
$(this).find('input.quantity').attr( 'id', 'quantity'+length );
$(this).find('input.marketed').attr( 'id', 'marketed'+length );
length++;
});
};



</script>
<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }
em { font-weight: bold; padding-right: 1em; vertical-align: top; }
</style>

  </head>
  <BODY>
   <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("Family information"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    foreach($this->membername as $family_view){ ?>
<tr>
        <td ><?php echo $this->translate("Family ID:"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>
    <tr>
        <td ><?php echo $this->translate("House No:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("Ration card:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td><?php echo $this->translate("Street/Road/Lane:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("Health Insurance:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Rev Village:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("NREGS Job Card No:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate("Colony/Habitation:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("Major source of income:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("Family type:"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("Contact Phone:"); ?></td>
        <td ><?php echo $family_view['phone']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Category:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("Mobile:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>
   <?php } ?>
</table> 
<br/>
<!-- for Agriculture view -->
<div>
<?php if($this->agriculture){ ?>
<table id="hor-minimalist-b" border="1">
    <tr>
        <th align="right"><?php echo $this->translate("Land holding"); ?></th>


 		<th align="right"><?php echo $this->translate("Acre"); ?></th>
        <th align="right"><?php echo $this->translate("Gunta"); ?></th>
        <th align="right"><?php echo $this->translate("name of owner"); ?></th>
        <th align="right"><?php echo $this->translate("Survey No"); ?></th>
        <th align="right"><?php echo $this->translate("Village"); ?></th>
       
    </tr>
    <?php foreach($this->agriculture as $agri){   ?>
    <tr>
        <td><?php echo $agri['name_regional']; ?></td>
        <td align="right"><?php echo $agri['acre']; ?></td>
        <td align="right"><?php echo $agri['gunta']; ?></td>
        <td><?php echo $agri['membername']; ?></td>
        <td align="right"><?php echo $agri['survey_no']; ?></td>
        <td><?php echo $agri['villagenames']; ?></td>

    </tr>
    <?php } ?>
    <tr>
    <?php foreach($this->acretotal as $total){   ?>

   <td><?php echo $this->translate("Total"); ?></td>
      <td align="right"><?php echo $total['total']; ?></td>
<?php } ?>
    <?php foreach($this->guntatotal as $gunta){   ?>
      <td align="right"><?php echo $gunta['total']; ?></td>
<?php } ?>

   <td></td>
   <td></td>
   <td></td>
</tr>
</table>
<?php } ?>
</div>
<br/>
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">      
    <form name="form1" id = "valueForm" action="<?php echo $this->baseUrl();?>/crop/index/addcrop/id/<?php echo $this->id; ?>/subId/<?php echo $this->subId; ?>/modId/<?php echo $this->modId; ?>" method="POST">
        <table id="hor-minimalist-b" class = 'crop'>
            <tr> 
                <th ><?php echo $this->translate("Land holding"); ?></th>

                <th ><?php echo $this->translate("Crop"); ?></th>
                <th ><?php echo $this->translate("Season"); ?></th>
                <th ><?php echo $this->translate("Acre"); ?></th>
                <th ><?php echo $this->translate("Gunta"); ?></th>
                <th ><?php echo $this->translate("Unit"); ?></th>
                <th ><?php echo $this->translate("Quantity produced in units"); ?></th>
                <th ><?php echo $this->translate("Quantity sold in units"); ?></th>
                <th ><?php echo $this->translate("Price per units"); ?></th>
                <th ><?php echo $this->translate("Price realised"); ?></th>
                <th ><?php echo $this->translate("Sold date"); ?></th>
                <th ><?php echo $this->translate("Action"); ?></th>
            </tr>
            <tr id='tmp'>
 <td <?php $i = 1;  ?>><select name = tenant[] class="selectvalid required">
                    <option value="">Select</option>

                            <?php foreach ($this->agriculture as $land_details) {  ?>
                            <option value="<?php echo $land_details['land_id']?>"><?php echo $land_details['name_regional']?></option>

                            <?php }
 ?>
                        </select></td>

                <td><select name = "crop_id[]" class="selectvalid required" >
                    <option value="">Select</option>

                    <?php foreach ($this->cropdetails as $cropdetails) { ?>
                    <option value="<?php echo $cropdetails['id']?>"><?php echo $cropdetails['name_regional']?></option>

                    <?php } ?>


                </select>    
                </td>
 

                <td><select name = "season[]" class="selectvalid required">
                    <option value="">Select</option>

                    <?php foreach ($this->seasondetails as $seasondetails) { ?>
                    <option value="<?php echo $seasondetails['id']?>"><?php echo $seasondetails['name_regional']?></option>

                    <?php } ?>
             </select> </td>
                <td><INPUT type="text" maxlength="3" name = "acre[]" class="number EitherOr"  id="acre1" size = 10 required_group="eithergroup" 
 class="acre number eithergroup" onkeyup = "calculateacre(this.value);"></td>
                <td><INPUT type="text" name = "gunta[]" id = "gunta1" size = 5 maxlength="2" class="acre number" min="0" max="40" onkeyup = "calculateguntas(this.value);"></td>
<td><select name = "unit[]">
                    <option value=0>Select</option>

                    <?php foreach ($this->units as $unit) { ?>

                    <option value="<?php echo $unit['id']?>"><?php echo $unit['name_regional']?></option>

                    <?php } ?>


                </select>    
                </td>
<td><INPUT type="text" name = "quantity[]" id =  "quantity1" size = 10 maxlength="3" class="quantity required number produced"></td>
                <td><INPUT type="text" name = "marketed[]" id = "marketed1" size = 10 maxlength="5" min="1" class="marketed sold numeric1 number" ></td>
                <td><INPUT type="text" name = "price[]" id =  "price[]" size = 10 maxlength="6" min="1" class="numeric1 product number" ></td>
                <td><INPUT type="text" name = "realised[]" id = "realised[]" size = 10 maxlength="6" readonly class="realised "></td>
                <td><INPUT type="text" name = "date[]"  class="date" readonly></td>
                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
            </tr> 
        </table>

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>">
	<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->id ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
<?php //echo $this->errormsg; ?>
</div>
</BODY>
</html>
td><INPUT type="text" name = "price[]" id =  "price[]" size = 10 maxlength="6" min="1" class="numeric1 product number" ></td>
                <td><INPUT type="text" name = "realised[]" id = "realised[]" size = 10 maxlength="6" readonly class="realised "></td>
                <!--<td><INPUT type="text" name = "date[]"  class="date" readonly></td>-->
                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
            </tr> 
        </table>

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>">
	<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->id ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
<?php //echo $this->errormsg; ?>
</div>
</BODY>
</html>
