<html>
<script type='text/javascript' src="/IDF/public/js/jquery-1.3.2.js"></script>
<script type='text/javascript' src="/IDF/public/js/jquery.validate.js"></script>
<script type='text/javascript' src="/IDF/public/js/jquery.selectboxes.pack.js"></script>
<script type='text/javascript'>
$(document).ready(
  function() {
  $('input#tmpAddRow').click(
      function() {
      tableobj=$(this).parent();
        selectedval=[];
      rowindex=$('tr',tableobj).length;
      trobjec=$('tr',tableobj);
       $('tr',tableobj).each(function (index, domEle) {
           if(index!=rowindex && index!=0)
             {
              sval=$("#select"+index).selectedValues();
               selectedval.push(sval);}
        });
       var newRow = $('tr#tmp').clone(true).removeAttr('id');
                selectobj=newRow.find("select");
                newrowobj=$(this).children(':first');
                inputobj=newRow.find("input:text");
                inputobj.val("");
                newRow.find('span').remove();
        newRow.appendTo('.nonasset tbody');
        $(selectobj).attr('id', 'select'+rowindex);
             trobjec.each(function (index, domEle) {
                   if(index!=0 && index!=rowindex)
                     {
                      sval=$("#select"+index).selectedValues();
                    $("#select"+rowindex+" option[value='"+sval+"']").remove();
            
                }
       });
        
           $('tr#tmp').closest('table').find('input:text.date').each(function() {
           $(this).removeClass('hasDatepick').datepick({dateFormat: 'dd/mm/yyyy',maxDate : '+0D',});
        });

      }
    );

    $('.select').change(function(){
            if($(this).val() == 'Select'){
                    $(this).after('<span style="color: #FF0000">Choose proper Asset</span>');
            } else {
                    $(this).next('span').remove();
            }
    });





    $('tr input[type=text]').focus(
      function() {
        $(this).addClass('myFocused');
      }
    ).blur(
      function() {
        $(this).removeClass('myFocused');
      }
    );
        $(".date").datepick("option",{dateFormat: 'dd/mm/yyyy', maxDate : '+0D', });

    $('.delete-icon').click(function() {
        $(this).closest('tr').not('#tmp').remove();
    });
  });
$(document).ready(function() {
    $('#pluginForm').submit(function(e) {
        var isValid = true;
        $(this).find(':text.required').each(function() {
            if($(this).val().replace(/^\s+|\s+$/g,"") == "") {
                isValid = false;
                if($(this).next('span').length == 0 ) {
                    $(this).after('<span style="color: #FF0000">Field is required</span>');
                }
                e.preventDefault();
                return;
            } else {
                if($(this).next('span').length > 0 )
                    $(this).next('span').remove();
            }
        });

 $(this).find(':select.select').each(function() {
            if($(this).val() == 'Select'){
                        if($(this).next('span').length == 0 ) {
                    $(this).after('<span style="color: #FF0000">Field is required</span>');
                }
                e.preventDefault();
                return;            } else {
                        if($(this).next('span').length > 0 )
                    $(this).next('span').remove();            }
        });
        $(this).find(':text.numeric').each(function() {
            var regex = new RegExp(/^[1-9][0-9]*$/);
            if(!regex.test($(this).val()) && isValid) {
                isValid = false;
                if($(this).next('span').length == 0 ) {
                   $(this).after('<span style="color: #FF0000">Numeric Data allowed only.</span>');
                }
                e.preventDefault();
                return;
            } else {
                if($(this).next('span').length > 0  && isValid)
                    $(this).next('span').remove();
            }
        }); 
    });
});
</script>
<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }
em { font-weight: bold; padding-right: 1em; vertical-align: top; }
</style>
</head>
<body>
 <table id="hor-minimalist-b" border="1" bgcolor="#F8F8F8">
   <tr>
        <th><?php echo $this->translate("Family information"); ?></th>
        <th></th>
        <th></th>
        <th></th>
   </tr>
    <?php 
    $convertdate = new App_Model_dateConvertor();
    foreach($this->membername as $family_view){ ?>

<tr>
        <td ><?php echo $this->translate("Family ID:"); ?></td>
        <td ><?php echo $family_view['family_id']; ?></td>
        <td ><?php //echo $this->translate("Caste:"); ?></td>
        <td ><?php //echo $family_view['subcaste']; ?></td>    </tr>
    <tr>
        <td ><?php echo $this->translate("House No:"); ?></td>
        <td ><?php echo $family_view['house_no']; ?></td>
        <td ><?php echo $this->translate("Ration card:"); ?></td>
        <td ><?php echo $family_view['ration']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Street/Road/Lane:"); ?></td>
        <td ><?php echo $family_view['street']; ?></td>
        <td ><?php echo $this->translate("Health Insurance:"); ?></td>
        <td ><?php foreach($this->insurance as $insurance){ echo $insurance['insurancename']; echo "<br>";
        }?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Rev Village:"); ?></td>
        <td ><?php echo $family_view['villagename']; ?></td>
        <td ><?php echo $this->translate("NREGS Job Card No:"); ?></td>
        <td ><?php echo $family_view['nregs_jobno']; ?></td>    </tr>

    <tr>
        <td ><?php echo $this->translate("Colony/Habitation:"); ?></td>
        <td ><?php echo $family_view['names']; ?></td>
        <td ><?php echo $this->translate("Major source of income:"); ?></td>
        <td ><?php echo $family_view['income']; ?></td>
    </tr>
    <tr>
        <td ><?php echo $this->translate("Family type:"); ?></td>
        <td ><?php echo $family_view['familytype']; ?></td>
        <td ><?php echo $this->translate("Contact Phone:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>

    <tr>
        <td ><?php echo $this->translate("Category:"); ?></td>
        <td ><?php echo $family_view['caste']; ?></td>
        <td ><?php echo $this->translate("Mobile:"); ?></td>
        <td ><?php echo $family_view['mobile']; ?></td>
    </tr>   <?php } ?>
</table> 
<br/>
<form name="form1" id = "pluginForm" action="<?php echo $this->baseUrl();?>/nonlivingassets/index/editasset/id/<?php echo $this->memberid; ?>" method="POST">
<table id="hor-minimalist-b" class="nonasset">
<tr> 
    <th><?php echo $this->translate("Assets"); ?></th>
    <th><?php echo $this->translate("Quantity"); ?></th>
    <th><?php echo $this->translate("Asset value"); ?></th>
    <th><?php echo $this->translate("Date of value"); ?></th>

    <th>Action</th>
</tr>
 <?php $i = 0; ?>
            <?php foreach ($this->editAsset as $editAsset) { $i++;?>
             <?php if ($i == 1) { ?>
             <tr id='tmp'>
            <?php } else { ?>
            <tr>
            <?php } ?>
        <td><select name = "assettype[]" id="select1" class="select">
                    <OPTION value="<?php echo $editAsset["nonliveasset_id"]; ?>">
                    <?php echo $editAsset["name"]; ?>
                    </OPTION>
                    <option>Select</option>
                    <?php foreach ($this->nonliveasset_details as $assetdetails) { $dateconvert= new App_Model_dateConvertor();?>
                        <? if($editAsset["name"] != $assetdetails["name"] ) {?>
                           <option value="<?php echo $assetdetails['id']?>"><?php echo $assetdetails['name']?></option>
                    <?php } } ?>
                </select>  
                </td>
                <td><INPUT type="text" name = "number[]" size="6" class="required numeric" maxlength="6" value = "<?php echo $editAsset["number"];?>" class="required"></td>
                <td><INPUT type="text" name = "value[]" maxlength="6" value = "<?php echo $editAsset["value"];?>" ></td>
                <td><INPUT type="text" name = "date[]" class="date" value = "<?php if($editAsset['date_of_value'] != null) { echo $dateconvert->phpnormalformat($editAsset['date_of_value']); } else { echo "Null"; }  ?>"></td>

                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
            </tr> 
<input type="hidden" name="subid" value="<?php echo $this->submoduleid;?>">

       <?php } ?>
        </table>  

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" id="submit" name="Submit" value="<?php echo $this->translate("Update"); ?>">&nbsp;&nbsp;&nbsp;&nbsp;<a href="<? echo $this->baseUrl();?>/familycommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
