<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<div id="searchDiv">
<fieldset>
    <legend>Search</legend>
        <div class="search" style="margin-left:20px;">
            <form action="<?php echo $this->baseUrl();?>/category" method="POST">
                <table width="100%">
                        <tr>
                            <td class="label">Name:</td>
                                <td ><?php echo $this->form->name;?></td>
                                <td class="label">Description:</td>
                                <td ><?php echo $this->form->description;?></td>
                        </tr>
                </table><br>
                <div class="btnhouse">
                    <div class="ltbtns">
                        <input type = "Submit" name = "Search" id="Search" value = "Search"/>
                    </div>
                </div>	
            </form>	
        </div>
</fieldset> 
</div>  
<?php  if((count($this->paginator) ==0) && ($this->search == true))  { ?>
<font color='RED'><?php echo $this->translate('Record not found try again'); ?>.</font>
<?php } ?>
<?php if (count($this->paginator)): ?>
<table id="hor-minimalist-b">
    <tr>
        <th>Category Name</th>
        <th>Description</td>
        <th>Created Date</th>
       
    </tr>
<?php $dateconvertor = new App_Model_dateConvertor();?>
        <?php foreach ($this->paginator as $category ): ?>
    <tr>
        <td><a href="<?php echo $this->baseUrl()."/category/index/categoryview/id/".$category['id']; ?>">
                     <?php echo $this->escape($category['name']); ?></a></td>
    <td><?php echo $this->escape($category['description']);?></td>
    <td><?php echo $dateconvertor->normalformat($this->escape($category['created_date']));?></td>
    
                <?php endforeach; ?>
                <?php endif; ?>
    </tr>
    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                    '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>
</table>
