<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-latest.js"></script>
<script type="text/javascript">
function getstate(state,path) { 
	if(state) {
	 	targeturl=path+"/dropdown/index/district?state="+state;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}

function getacctype(acctype,path) { 
	if(acctype) {
	 	targeturl=path+"/dropdown/index/bank?acctype="+acctype;
		$.ajax({ url: targeturl, success: function(data){ $("#acctypediv").html(data) }});
	}
}

function getkoota(koota,path) { 
	if(koota) {
	 	targeturl=path+"/dropdown/index/promoter?koota="+koota;
		$.ajax({ url: targeturl, success: function(data){ $("#kootadiv").html(data) }});
	}
}

function getcbp(cbp,path) { 
	if(cbp) {
	 	targeturl=path+"/dropdown/index/promoter?cbp="+cbp;
		$.ajax({ url: targeturl, success: function(data){ $("#cbpdiv").html(data) }});
	}
}

function getdistrict(district,path) { 
	if(district) {
	 	targeturl=path+"/dropdown/index/taluk?district="+district;
		$.ajax({ url: targeturl, success: function(data){ $("#districtdiv").html(data) }});
	}
}

function gettaluk(taluk,path) { 
	if(taluk) {
	 	targeturl=path+"/dropdown/index/hobli?taluk="+taluk;
		$.ajax({ url: targeturl, success: function(data){ $("#talukdiv").html(data) }});
	}
}

function gethobli(hobli,path) { 
	if(hobli) {
	 	targeturl=path+"/dropdown/index/gillapanchayath?hobli="+hobli;
		$.ajax({ url: targeturl, success: function(data){ $("#hoblidiv").html(data) }});
	}
}

function getgillapanchayath(gillapanchayath,path) { 
	if(gillapanchayath) {
	 	targeturl=path+"/dropdown/index/village?gillapanchayath="+gillapanchayath;
		$.ajax({ url: targeturl, success: function(data){ $("#gillapanchayathdiv").html(data) }});
	}
} 

function getvillage(village,path) { 
	if(village) {
	 	targeturl=path+"/dropdown/index/gillapanchayath?village="+village;
		$.ajax({ url: targeturl, success: function(data){ $("#villagediv").html(data) }});
	}
} 
</script>

<form action="<?php echo $this->baseUrl();?>/dropdown/index/add/id/<?php echo $this->id; ?>/name/<?php  echo $this->tableName; ?>" method="POST">
 	<div id="container-1">
		<div class="profile_tab">

			<table class="fieldsets" id="hor-minimalist-b">	
				<th colspan="3">New <?php echo substr($this->tableName,15);?></th>
				<?php if($this->tableName == 'ourbank_master_districtlist') {?>
			<tr><td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD></tr>
				<?php }?>

				<?php if($this->tableName == 'ourbank_master_taluklist') {?>
			<tr><td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD></tr>

			<tr><td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD></tr>
				<?php }?>

				<?php if($this->tableName == 'ourbank_master_hoblilist') {?>
			<tr><td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD></tr>

			<tr><td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD></tr>

			<tr><td>Taluk</td>
                <TD colspan="2" id="districtdiv"><?php echo $this->form->taluk;?></TD></tr>
				<?php }?>

				<?php if($this->tableName == 'ourbank_master_gillapanchayath') {?>
			<tr><td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD></tr>

			<tr><td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD></tr>
			<tr><td>Taluk</td>
                <TD colspan="2" id="districtdiv"><?php echo $this->form->taluk;?></TD></tr>

			<tr><td>Hobli</td>
                <TD colspan="2"><div id="talukdiv"><?php echo $this->form->hobli;?></div></TD>
			</tr>
				<?php }?>

			<?php if($this->tableName == 'ourbank_master_villagelist') {?>
			<tr><td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD></tr>

			<tr><td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD></tr>

			<tr><td>Taluk</td>
                <TD colspan="2" id="districtdiv"><?php echo $this->form->taluk;?></TD></tr>

			<tr><td>Hobli</td>
                <TD colspan="2"><div id="talukdiv"><?php echo $this->form->hobli;?></TD></tr>

			<tr><td>Grama panchayath</td>
                <TD colspan="2" id="hoblidiv"><?php echo $this->form->gillapanchayath;?></div></TD></tr>
			<?php }?>

			<?php if($this->tableName == 'ourbank_master_habitation') {?>
				<tr><td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD></tr>

			<tr><td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD></tr>

			<tr><td>Taluk</td>
                <TD colspan="2" id="districtdiv"><?php echo $this->form->taluk;?></TD></tr>

			<tr><td>Hobli</td>
                <TD colspan="2"><div id="talukdiv"><?php echo $this->form->hobli;?></TD></tr>

			</tr><tr><td>Grama panchayath</td>
                <TD colspan="2" id="hoblidiv"><?php echo $this->form->gillapanchayath;?></TD></tr>

			<tr><td>Village</td>
                <TD colspan="2"><div id="gillapanchayathdiv"><?php echo $this->form->village;?></div></TD></tr>
				<?php }?>

			<?php if($this->tableName == 'ourbank_master_bank') {?>
			<tr><td>Grama panchayat</td>
				<TD colspan="2"><?php echo $this->form->gillapanchayath;?></TD></tr>
			<tr><td>Village</td>
				<TD colspan="2"><div id="gillapanchayathdiv"><?php echo $this->form->village;?></div></TD></tr>
			<tr><td>Account Type</td>
                <TD colspan="2"><?php echo $this->form->acctype;?></TD></tr>
				<?php }?>

			<?php if($this->tableName == 'ourbank_master_branch') {?>
			<tr><td>Bank</td>
                <TD colspan="2"><?php echo $this->form->bank;?></TD></tr>
				<?php }?>

			<?php if($this->tableName == 'ourbank_master_mastertables') {?>
			<tr><td>Description</td>
                <TD colspan="2"><?php echo $this->form->description;?></TD></tr>
				<?php }?>

			<?php if($this->tableName == 'ourbank_master_cbopromoter') {?>
			<tr><td>Koota List</td>
                <TD colspan="2"><div id="kootadiv"><?php echo $this->form->koota;?></div></TD></tr>
				<?php }?>

			<?php if($this->tableName == 'ourbank_master_cbos') {?>
			<tr><td>CBO Promoter</td>
                <TD colspan="2"><?php echo $this->form->cbp;?></div></TD></tr>
				<?php }?>

			<tr><TD> Add new <? echo substr($this->tableName,15); ?></TD>
                <TD colspan="2"><?php echo $this->form->commonname;?></TD></tr>
			<tr><td>Regional name</td><TD colspan="2"><?php echo $this->form->name_regional;?></TD></tr>

			<tr><TD><input type="submit" name="Save" id="Submit" value="Save"></TD>
				<td align="right"><a href="<?php echo $this->baseUrl(); ?>/dropdown">
                <input name="submit" type="submit" class="officebutton" value="Back"></a></td></tr>
 			</table>
   		</div>
	</div>
</form>
<form action="<?php echo $this->baseUrl();?>/dropdown/edit/id/<?php echo $this->id; ?>" method="POST">
