<div id="container-1">
	<div class="register">
		<div class="profile_tab">
            <TABLE id="hor-minimalist-b">
			
        <?php foreach($this->details as $details) {  ?>
    <th colspan="4"><? echo substr($this->tableName,15); ?> <a href="<?php echo $this->baseUrl();?>/dropdown/index/edit/id/<?php echo $this->id;?>/name/<?php echo $this->tableName ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" align="right" width="20" height="20"></a></th> 
<?php if($this->tableName == 'ourbank_master_habitation') {?>
	<tr><td align="center">State :</td><TD colspan="2"><?php echo $details['sname'];?></TD></tr>
	<tr><td align="center">District :</td><TD colspan="2"><?php echo $details['dname'];?></TD></tr>
	<tr><td align="center">Taluk :</td><TD colspan="2"><?php echo $details['tname'];?></TD></tr>
	<tr><td align="center">Hobli :</td><TD colspan="2"><?php echo $details['hbname'];?></TD></tr>
	<tr><td align="center">Grama panchayat :</td><TD colspan="2"><?php echo $details['gpname'];?></TD></tr>
	<tr><td align="center">Village :</td><TD colspan="2"><?php echo $details['vname'];?></TD></tr>
				<?php }?>

<?php if($this->tableName == 'ourbank_master_districtlist') {?>
	<tr><td align="center">State :</td><TD colspan="2"><?php echo $details['sname'];?></TD></tr>
				<?php }?>

<?php if($this->tableName == 'ourbank_master_taluklist') {?>
	<tr><td align="center">State :</td><TD colspan="2"><?php echo $details['sname'];?></TD></tr>
	<tr><td align="center">District :</td><TD colspan="2"><?php echo $details['dname'];?></TD></tr>
				<?php }?>
<?php if($this->tableName == 'ourbank_master_hoblilist') {?>
	<tr><td align="center">State :</td><TD colspan="2"><?php echo $details['sname'];?></TD></tr>
	<tr><td align="center">District :</td><TD colspan="2"><?php echo $details['dname'];?></TD></tr>
	<tr><td align="center">Taluk :</td><TD colspan="2"><?php echo $details['tname'];?></TD></tr>
				<?php }?>
<?php if($this->tableName == 'ourbank_master_gillapanchayath') {?>
	<tr><td align="center">State :</td><TD colspan="2"><?php echo $details['sname'];?></TD></tr>
	<tr><td align="center">District :</td><TD colspan="2"><?php echo $details['dname'];?></TD></tr>
	<tr><td align="center">Taluk :</td><TD colspan="2"><?php echo $details['tname'];?></TD></tr>
	<tr><td align="center">Hobli :</td><TD colspan="2"><?php echo $details['hbname'];?></TD></tr>
				<?php }?>

<?php if($this->tableName == 'ourbank_master_bank') {?>
	<tr><td align="center">Grama panchyat:</td><TD colspan="2"><?php echo $details['gpname'];?></TD></tr>
	<tr><td align="center">Village:</td><TD colspan="2"><?php echo $details['vname'];?></TD></tr>
	<tr><td align="center">Account Type:</td><TD colspan="2"><?php echo $details['accname'];?></TD></tr>
				<?php }?>

<?php if($this->tableName == 'ourbank_master_branch') {?>
	<tr><td align="center">Grama panchyat:</td><TD colspan="2"><?php echo $details['gpname'];?></TD></tr>
	<tr><td align="center">Village:</td><TD colspan="2"><?php echo $details['vname'];?></TD></tr>
	<tr><td align="center">Bank :</td><TD colspan="2"><?php echo $details['bankname'];?></TD></tr>
				<?php }?>

<?php if($this->tableName == 'ourbank_master_cbopromoter') {?>
	<tr><td align="center">Koota list :</td><TD colspan="2"><?php echo $details['oname'];?></TD></tr>
				<?php }?>

<?php if($this->tableName == 'ourbank_master_cbos') {?>
	<tr><td align="center">CBO promoter :</td><TD colspan="2"><?php echo $details['cbname'];?></TD></tr>
				<?php }?>

	<tr><td align="center"><? echo substr($this->tableName,15); ?> :</td><td><?php echo $details['habit'];?></td><TD></TD></tr>
	<tr><td align="center">Regional name :</td><TD colspan="2"><?php echo $details['name_regional'];?></TD></tr>

	  <TR><td colspan="2"></td>
			<td align="right"><a href="<?php echo $this->baseUrl(); ?>/dropdown"><input name="submit" type="submit" class="officebutton" value="Back"></a></td>
      </TR>
        </TABLE>
<?php } ?>
</div>
</div>
</div>
