<div id="container-1">
	<div class="register">
		<div class="profile_tab">
            <TABLE id="hor-minimalist-b">
			
        <?php foreach($this->details as $details) {  ?>
    <th colspan="4"><a href="<?php echo $this->baseUrl();?>/dropdown/index/edit/id/<?php echo $this->id;?>/name/<?php echo $this->tableName ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" align="right" width="20" height="20"></a></th> 
	<TR>	


            <TD align="center">Name :</TD>
            <TD><?php echo $details['habit'];?></TD><TD></TD>
     </TR>
	<tr><td align="center">Regional name :</td><TD colspan="2"><?php echo $details['name_regional'];?></TD></tr>

	  <TR><td colspan="2"></td>
			<td align="right"><a href="<?php echo $this->baseUrl(); ?>/dropdown"><input name="submit" type="submit" class="officebutton" value="Back"></a></td>
      </TR>
        </TABLE>
<?php } ?>
</div>
</div>
</div>
