<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-latest.js"></script>

<script type="text/javascript">
function getstate(state,path) { 
	if(state) {
	 	targeturl=path+"/dropdown/index/district?state="+state;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
</script>


<script type="text/javascript">
function getdistrict(district,path) { 
	if(district) {
	 	targeturl=path+"/dropdown/index/taluk?district="+district;
		$.ajax({ url: targeturl, success: function(data){ $("#districtdiv").html(data) }});
	}
}
</script>

<script type="text/javascript">
function gettaluk(taluk,path) { 
	if(taluk) {
	 	targeturl=path+"/dropdown/index/hobli?taluk="+taluk;
		$.ajax({ url: targeturl, success: function(data){ $("#talukdiv").html(data) }});
	}
}
</script>

<script type="text/javascript">
function gethobli(hobli,path) { 
	if(hobli) {
	 	targeturl=path+"/dropdown/index/gillapanchayath?hobli="+hobli;
		$.ajax({ url: targeturl, success: function(data){ $("#hoblidiv").html(data) }});
	}
}
</script>

<script type="text/javascript">
function getgillapanchayath(gillapanchayath,path) {
	if(gillapanchayath) {
	 	targeturl=path+"/dropdown/index/village?gillapanchayath="+gillapanchayath;
		$.ajax({ url: targeturl, success: function(data){ $("#gillapanchayathdiv").html(data) }});
	}
} 
</script>

<script type="text/javascript">
function getvillage(village,path) {
	if(village) {
	 	targeturl=path+"/dropdown/index/gillapanchayath?village="+village;
		$.ajax({ url: targeturl, success: function(data){ $("#villagediv").html(data) }});
	}
} 
</script>



<form action="<?php echo $this->baseUrl();?>/dropdown/index/edit/id/<?php echo $this->id; ?>/name/<?php  echo $this->ff; ?>" method="POST">
 	<div id="container-1">
		<div class="profile_tab">

			<table class="fieldsets" id="hor-minimalist-b">	
				<th colspan="2">Edit <? echo substr($this->tableName,15); ?><a href="<?php echo $this->baseUrl();?>/dropdown/index/delete/id/<?php echo $this->id ?>/name/<?php echo $this->tableName ?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" align="right" width="20" height="20"></a></th>

			<tr>

			<TR>
				<?php if($this->tableName == 'ourbank_master_districtlist') {?>
				<td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD>
			</tr>
				<?php }?>
				<?php if($this->tableName == 'ourbank_master_taluklist') {?>
				<td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD></tr>
			<tr>
				<td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD>
			</tr>
				<?php }?>
				<?php if($this->tableName == 'ourbank_master_hoblilist') {?>
				<td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD>
			</tr>
			<tr>
				<td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD>
			</tr>
			<tr>
				<td>Taluk</td>
                <TD colspan="2"><?php echo $this->form->taluk;?></TD>
			</tr>
			<tr>
				<?php }?>
				<?php if($this->tableName == 'ourbank_master_gillapanchayath') {?>
				<td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD>
			</tr>
			<tr>
				<td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD>
			</tr>
			<tr>
				<td>Taluk</td>
                <TD colspan="2"><?php echo $this->form->taluk;?></TD>
			</tr><tr>
				<td>Hobli</td>
                <TD colspan="2"><div id="talukdiv"><?php echo $this->form->hobli;?></div></TD>
			</tr>
				<?php }?>
				<?php if($this->tableName == 'ourbank_master_villagelist') {?>
				<td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD>
			</tr>
				<tr><td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD></tr>
			<tr>
				<td>Taluk</td>
                <TD colspan="2"><?php echo $this->form->taluk;?></TD>
			</tr>
<tr>
				<td>Hobli</td>
                <TD colspan="2"><div id="talukdiv"><?php echo $this->form->hobli;?></TD>
			</tr>

<tr>
				<td>Grama panchayath</td>
                <TD colspan="2" id="hoblidiv"><?php echo $this->form->gillapanchayath;?></div></TD>
			</tr>
			
				<?php }?>
<?php if($this->tableName == 'ourbank_master_habitation') {?>
				<td>State</td>
                <TD colspan="2"><?php echo $this->form->state;?></TD>
			</tr>
				<tr><td>District</td>
                <TD colspan="2"><div id="statediv"><?php echo $this->form->district;?></div></TD></tr>
			<tr>
				<td>Taluk</td>
                <TD colspan="2"><?php echo $this->form->taluk;?></TD>
			</tr>
<tr>
				<td>Hobli</td>
                <TD colspan="2"><div id="talukdiv"><?php echo $this->form->hobli;?></TD>
			</tr>

<tr>
				<td>Grama panchayath</td>
                <TD colspan="2" id="hoblidiv"><?php echo $this->form->gillapanchayath;?></TD>
			</tr>
			<tr>
				<td>Village</td>
                <TD colspan="2"><div id="gillapanchayathdiv"><?php echo $this->form->village;?></div></TD>
			</tr>
				<?php }?>
		<?php if($this->tableName == 'ourbank_master_branch') {?>
				<td>Bank</td>
                <TD colspan="2"><?php echo $this->form->bank;?></TD>
			</tr>
				
				<?php }?>
<?php if($this->tableName == 'ourbank_master_mastertables') {?>
<tr>
				
				<td>Description</td>
                <TD colspan="2"><?php echo $this->form->description;?></TD>

			</tr>
				<?php }?>

	
			<TR>
                    <TD><? echo substr($this->tableName,15); ?></TD>
                	<TD ><?php echo $this->form->commonname;?></TD>
            </TR>
			<tr><td>Regional name</td><TD><?php echo $this->form->name_regional;?></TD></tr>

 					<TR><TD><input type="submit" name="Update" id="Submit" value="Update"></TD>
					<TD align="right"><a href="<?php echo $this->baseUrl(); ?>/dropdown"> <input name="submit" type="submit" class="officebutton" value="Back"></a></TD></TR>
			</table>
			</div>
	</div>
</form>

