<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-latest.js"></script>

<script type="text/javascript">
function getnames(names,path) { 
	if(names) {
 targeturl=path+'/dropdown/index/name?names='+names; 
            $.ajax({ url: targeturl, success: function(data){ $('#namelist').html(data) }});
	}
}
</script>

<div id="namelist" style="float: right; clear: right; height:250px; ; overflow-y: auto; overflow-x: hidden;"></div>


<div style="float: left; clear: left;"> 
	<form action="<?php echo $this->baseUrl();?>/dropdown" method="POST">
		<TABLE id="hor-minimalist-s">
			<th colspan="2">Search</th>
			<tr><td></td>
				<td><div id="names"><?php echo $this->form;?></div></td>
			</tr>
		</table>
	</form>
</div>
