<script type='text/javascript' src="<?php  echo $this->baseUrl();?>/js/jquery-latest.js"></script>

<script type="text/javascript">
function getnames(names,path) { 
	if(names) {
 targeturl=path+'/dropdown/index/name?names='+names; 
            $.ajax({ url: targeturl, success: function(data){ $('#namelist').html(data) }});
	}
}
</script>

<div style="float: left; clear: left;"> 
	<form action="<?php echo $this->baseUrl();?>/dropdown" method="POST">
		<TABLE id="hor-minimalist-s">
			<th colspan="2">Search</th>
				<div id="names"><?php echo $this->form;?></div>
		</table>
	</form>
</div>


<div id="namelist" style="float: left; clear: left; "></div>

