<div id="container-1">
		<div class="profile_tab">
<form action="<?php echo $this->baseUrl();?>/dropdown/index/newtable" method="POST">

			<fieldset>
				<legend>New Master table</legend>
					<table class="fieldsets">	
<tr>
<th></th>
<th></th>
<th></th>


			<TR>
                <TD ><?php echo $this->form->name;?></TD>
			                <TD ><?php echo $this->form->description;?></TD>

							<td><input type="submit" name="Create" id="Submit" value="Create"></td>	

			</TR>

</form>
 					</table>
					
			</fieldset>
		</div>
	</div>
</form>
