<head>
<script type="text/javascript" language="JavaScript">
function display (yy)  {

    var div0=document.getElementById(1);
    var div1=document.getElementById(3);
    
    if(yy==100){
    div0.style.display='block';
    } 
    if(yy==2){
    document.getElementById("7").style.display = 'block';
    }
    if(yy!=2) {
    document.getElementById("7").style.display = 'none';
    }
    if(yy==300){
    document.getElementById("4").style.display = 'none';
    document.getElementById("5").style.display = 'none';
    document.getElementById("6").style.display = 'block';
    div1.style.display='block';
    }

}
</script> 
</head>
 <div class="register">
    <div class="profile_tab">   
	<div id =2 style="width:180px;float:left">


<?php if(count($this->result)) { ?>

<fieldset>
    <legend>Transaction Details</legend>
	<div class="cont-rgt-data">
         <form action="<?php echo $this->baseUrl();?>/altertransaction/alter" method="POST">
            <TABLE id="hor-minimalist-s" >
                <tr>

                <?php foreach($this->result  as $tran) : ?>
                <TR>
                    <TD align="right"><?php echo $this->translate("Voucher number"); ?></TD>
                    <TD ><input type = "text" name = "transaction_id"  value = "<?php echo $tran['vNum'];?>" size = 5 readonly="true" ></TD>
                </TR>
                <TR>
                   <TD align="right"><?php echo $this->translate("Transaction type"); ?></TD>
                    <TD ><input type = "text" name = "transaction_id"  value = "<?php echo $tran['tranType'];?>" size = 7 readonly="true" ></TD>

               </TR>
               <TR>
                    <TD align="right"><?php echo $this->translate("Account number"); ?></TD>
                    <TD ><input type = "text" name = "account_number"  value = "<?php echo $tran['accNum'];?>" size = 16  readonly="true" ></TD>
                </TR>


                <TR>
                    <input type ="hidden" name="created_by" value="<?php //echo $tran->created_by;?>" size=20 >
                    <td align="right"><?php echo $this->translate("Transaction date"); ?></td>
                    <TD ><input type = "text" name = "transaction_date"  value = "<?php echo $tran['date'];?>" size = 10 readonly="true" ></TD>
                </TR>

                <TR>
                    <TD align="right"><?php echo $this->translate("Transaction mode "); ?></TD>
                    <TD ><input type = "text" name = "paymenttype_description"  value = "<?php echo $tran['payName'];?>" size = 5 readonly="true" ></TD>

                </TR>
                <TR>
                    <TD align="right"><?php echo $this->translate("Amount"); ?></TD>
                    <TD ><input type = "text" name = "transaction_amount"  value = "<?php echo $tran['cR'];?>" size = 10 readonly="true" ></TD>
                </TR>
                <?php endforeach; ?>
				</table>
            </form>
      </div>
    <table>


    <?php if($this->result1['cFlag'] == 3) { ?>
	<TR>
            <td id="4" style="display:block;">
                <input name="button" type="button" class="officebutton" value="Edit" onclick="display(300);">
            </TD>
            </form>
	    <td id="5" style="display:block;">
                <input name="submit" type="submit" class="officebutton" value="Void Transaction" onclick = "display(100);">
            </td>
        </TR>
    <?php } ?>
    <?php if($this->result1['cFlag'] != 3) { ?>
        <th bgcolor="#EE9A4D">This Transation has Done</th>
    <?php } ?>
    
</table>


	<div id = "1" style="display:none;">
			<?php foreach($this->result  as $ledger) : ?>
				<form action = "<?php echo $this->baseUrl(); ?>/altertransaction/index/deletetransaction" method="POST">
   					 <table id = "hor-minimalist-b" class="fieldsets">
       					<tr><th colspan="4">Remarks</th></tr>
            				<input type = "hidden" name = "vNum" value = "<?php echo $ledger['vNum'];?>">
        				<TR>
            				<TD><label class="mand">Transaction Remarks</label><textarea value="" name="transaction_remarks"></textarea></td>
        				</TR>
        				<tr>
            				<TD><input name="submit" type="submit" class="officebutton" value="Save"></TD>
        				</tr>
   					</table>
				</form>
			<?php endforeach; ?>
	</div>
			<?php }  ?>
		</fieldset>
	</div>



<div id =3 style="width:340px;float:right;display:none">
<?php if(count($this->result)) { ?>
<table>
	<TABLE id="hor-minimalist-s">
    <th colspan="2">Transaction Details</th>
	<div class="cont-rgt-data">
         <form action="<?php echo $this->baseUrl();?>/altertransaction/index/alter" method="POST">

                <?php foreach($this->result  as $tran) : ?>
                <TR>
                    <TD align="right"><?php echo $this->translate("Voucher number"); ?></TD>
                    <TD ><input type = "text" name = "vochure_number" size = 6 readonly="true" value = "<?php echo $tran['vNum'];?>" ></TD>
                </TR>
                <input type = "hidden" name = "accID"  value = "<?php echo $tran['aID'];?>" >
                <input type = "hidden" name = "gl"  value = "<?php echo $tran['gl'];?>" >
                <input type = "hidden" name = "desc"  value = "<?php echo $tran['dsc'];?>" >

                <TR>
                   <TD align="right"><br><?php echo $this->translate("Transaction type"); ?></TD>
                   <TD ><?php echo $this->form->transactionType;?></TD>
					
               </TR>
               <TR>
                    <TD align="right"><br><?php echo $this->translate("Account number"); ?></TD>
                    <TD ><?php echo $this->form->account_id;?></TD>
					<input type="hidden" name="accNum" value="<?php echo $this->accountnumber;?>">
                </TR>


                <TR>
                    <input type ="hidden" name="created_by" value="<?php echo $tran['created_by'];?>" size=20 >
                    <td align="right"><br><?php echo $this->translate("date"); ?> </td>
                    <TD><?php echo $this->form->transaction_date;?></TD>
                </TR>

                <TR>
                    <TD align="right"><br><?php echo $this->translate("Transaction mode"); ?></TD>
                    <TD ><?php echo $this->form->transactionMode;?></TD>
               </TR>
                <tr>
					<TD></TD>
                    <TD id="7" style="display:none;"><input type="text" name="modeDetails" value = "" size= "20" class = "txt_put" ></TD>
                </tr>
                <TR>
                    <TD align="right"><br><?php echo $this->translate("Amount"); ?></TD>
                    <TD ><?php echo $this->form->transaction_amount;?></TD>

                </TR>
                <TR>
                    <TD align="right"><?php echo $this->translate("Transaction remarks"); ?></TD>
                    <TD ><?php echo $this->form->transaction_remarks;?></TD>
                </TR>

                <tr>
                     <TD class="label"><input type="submit" value="submit"></TD>
                     <td id="6" style="display:none;"><input name="submit" type="submit" class="officebutton" value="Void Transaction" onclick = "display(01);">
         			  </td>
                </tr>
                <?php endforeach; ?>

		</form>
    </div>
</table>

<?php }   ?>
</div>
</fieldset></div></div>
<?php if(!count($this->result)) { ?>
<fieldset>
    <legend>Search</legend>
    <form action="<?php echo $this->baseUrl();?>/altertransaction" method="POST">
        <table class="fieldsets">
            <tr>
                <td><label class="mand">Voucher number :</label></td>
                <td><input type="text" class="txt_put" value="" id="vNum" name="vNum"></td>
            </tr>
        </table>
        <div class="btnhouse">
            <div class="ltbtns">
                <input type="submit" value="Search" id="Search" name="Search">
            </div>
        </div>
    </form>
</fieldset>
<?php  }?>