<div id="container-1">
	<div class="register">
		<div class="profile_tab">
            <TABLE id="hor-minimalist-b">
<?php if(($this->holidaydetails)!=NULL) {
					foreach($this->holidaydetails as $edit_id) { ?>
<tr>
						<th class = "firsttd">Fee Details</th>
						<th class = "secondtd"></th>	
<th class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/holiday/index/holidayedit/id/<?php echo $edit_id['id'];?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th>
</tr>
<?php }}  ?>
        <?php foreach($this->details as $details) {  ?>
                <TR>
                    <TD>Name</TD>
                    <TD><?php echo $details['name'];?></TD>
<td></td>
<td></td>
                    <TD><a href="<?php echo $this->baseUrl();?>/settings/dropdown/edit/id/<?php echo $details['id'];?>/ff/<?php echo $this->tableName ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th></TD>
                   
                    
                </TR>

               

<td><a href="<?php echo $this->baseUrl(); ?>/settings/dropdown">
                                <input name="submit" type="submit" class="officebutton" value="Back"></a></td>

              </TR>
        </TABLE>
<?php } ?>
</div>
</div>
</div>
