<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div style="width:480px;float:left"> 





<fieldset>
	<legend>Confirm Delete</legend>
			<div class="cont-rgt-data">
				<form action="<?php echo $this->baseUrl();?>/settings/dropdown/delete/id/<?php echo $this->id; ?>/ff/<?php  echo $this->ff; ?>" method="POST" name="joe" id="signupForm" class="cmxform">
				<table id="hor-minimalist-b" summary="Employee Pay Sheet">
					<TR>
						<TD  width="35%" align="right" ><label>Remarks<span class="reqMark">*</span></label></TD>
						<TD  width="65%"  align="left" ><?php echo $this->form->remarks;?></TD>
									</table>
					</tr>
							<input type="submit" name="Delete" id="Submit" value="Delete">			

						<input name="submit" type="submit"  value="Cancel" ></a></TD>
					</TR>
				</form>
			
</fieldset>
</div>