<form action="<?php echo $this->baseUrl();?>/settings/dropdown/edit/id/<?php echo $this->id; ?>/ff/<?php  echo $this->ff; ?>" method="POST">
 	<div id="container-1">
		<div class="profile_tab">

			<fieldset>
				<legend>Edit</legend>
					<table class="fieldsets">	
<tr>
<th></th>
<th></th>
<th></th>

<th><a href="<?php echo $this->baseUrl();?>/settings/dropdown/delete/id/<?php echo $this->id ?>/ff/<?php echo $this->tableName ?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="20" height="20"></a></th></tr>
						<TR>
						<?php echo $this->form;?>
						</TR>


 					</table>
						<div class="btnhouse">
							<div class="ltbtns">
 								<input type="submit" name="Update" id="Submit" value="Update">                 
							</div>
								<div class="rtbtns">
 <TD><a href="<?php echo $this->baseUrl(); ?>/settings/dropdown">
                                <input name="submit" type="submit" class="officebutton" value="Back"></a></TD>								</div>
						</div>
			</fieldset>
		</div>
	</div>
</form>

<form action="<?php echo $this->baseUrl();?>/settings/dropdown/edit/id/<?php echo $this->id; ?>" method="POST">
